#!/bin/sh
# update expected outputs to match actual ones, if appropriate

agree () {
    while true ; do
	read -p "$1" response
	case "$response" in
	    [yY]*) return 0 ;;
	    [nN]*) return 1 ;;
	    *) echo "Please answer 'y' or 'n'." ;;
	esac
    done
}

for f in $(make test | awk '$2 == "..." && $3 != "PASS" {print $1}') ; do
    exp=$(echo "$f" | sed 's/\.frg/.exp/')
    out=$(echo "$f" | sed 's/\.frg/.out/')
    echo
    echo '======='
    echo $f:
    cat $f
    if [ -r "$exp" ] ; then
	echo '-------'
	echo 'Output changes:'
	dwdiff -c "$exp" "$out"
	echo
	if agree "Is the green version appropriate? " ; then
	    mv "$out" "$exp"
	    echo "Green version now expected"
	else
	    echo "OK, expected output not changed"
	fi
    else
	echo 'Output:'
	cat "$out"
	echo
	if agree "Is this this output appropriate? " ; then
	    mv "$out" "$exp"
	    echo "This output is now expected"
	else
	    echo "OK, expected output not established"
	fi
    fi
done