#!/bin/sh
# update expected outputs to match actual ones, if appropriate

agree () {
    while true ; do
	read -p "$1" response
	case "$response" in
	    [yY]*) return 0 ;;
	    [nN]*) return 1 ;;
	    *) echo "Please answer 'y' or 'n'." ;;
	esac
    done
}

make test
for f in test-cases/*.wybe ; do
    exp=$(echo "$f" | sed 's/\.wybe/.exp/')
    out=$(echo "$f" | sed 's/\.wybe/.out/')
    if [ -r "$exp" ] ; then
	if ! diff -q $exp $out > /dev/null ; then
	    echo
	    echo '======='
	    echo $f:
	    cat $f
	    echo '-------'
	    echo 'Output changes:'
	    dwdiff -c -d '()<>~!@:?.%#' "$exp" "$out"
	    echo
	    if agree "Is the green version of $out appropriate? " ; then
		mv "$out" "$exp"
		echo "Green version now expected"
	    else
		echo "OK, expected output not changed"
	    fi
	fi
    else
	echo "New test case $f"
	echo 'Output:'
	cat "$out"
	echo
	if agree "Is $out appropriate? " ; then
	    mv "$out" "$exp"
	    echo "This output is now expected"
	else
	    echo "OK, expected output not established"
	fi
    fi
done
