======================================================================
AFTER EVERYTHING:
 Module exp_simple
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : exp_simple.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: exp_simple.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#7##0:wybe.phantom) @exp_simple:nn:nn
    foreign c print_int(3:wybe.int, ~tmp#7##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @exp_simple:nn:nn
    foreign c print_float(3.5999999999999996:wybe.float, ~tmp#9##0:wybe.phantom, ?tmp#14##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#14##0:wybe.phantom, ?tmp#15##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('h':wybe.char, ~tmp#15##0:wybe.phantom, ?tmp#18##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#18##0:wybe.phantom, ?tmp#19##0:wybe.phantom) @exp_simple:nn:nn
    foreign lpvm store(~%tmp#19##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @exp_simple:nn:nn
    wybe.string.print<0>("hello":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5 @exp_simple:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#23##0:wybe.phantom) @exp_simple:nn:nn
    foreign c print_int(3:wybe.int, ~tmp#23##0:wybe.phantom, ?tmp#24##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#24##0:wybe.phantom, ?tmp#25##0:wybe.phantom) @exp_simple:nn:nn
    foreign c print_int(1001:wybe.int, ~tmp#25##0:wybe.phantom, ?tmp#29##0:wybe.phantom) @exp_simple:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#29##0:wybe.phantom, ?tmp#30##0:wybe.phantom) @exp_simple:nn:nn
    foreign c print_int(3:wybe.int, ~tmp#30##0:wybe.phantom, ?tmp#33##0:wybe.phantom) @exp_simple:nn:nn
    foreign lpvm store(~%tmp#33##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @exp_simple:nn:nn


proc foreign_add > {inline} (1 calls)
0: exp_simple.foreign_add<0>
foreign_add(?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(3:wybe.int, ?#result##0:wybe.int) @exp_simple:nn:nn

  LLVM code       :

; ModuleID = 'exp_simple'


 


@exp_simple.1 =    constant {i64, i64} { i64 5, i64 ptrtoint ([?? x i8]* @exp_simple.0 to i64) }


@exp_simple.0 =    constant [?? x i8] c"hello\00"


declare external ccc  void @print_int(i64)    


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external ccc  void @print_float(double)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"exp_simple.<0>"()    {
entry:
  tail call ccc  void  @print_int(i64  3)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  3.600000e0)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @putchar(i8  104)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @exp_simple.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  3)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  1001)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  3)  
  ret void 
}


define external fastcc  i64 @"exp_simple.foreign_add<0>"() alwaysinline   {
entry:
  ret i64 3 
}
