======================================================================
AFTER EVERYTHING:
 Module specials
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials.show_column<0>
                    specials.show_file<0>
                    specials.show_full_file<0>
                    specials.show_full_location<0>
                    specials.show_line<0>
                    specials.show_location<0>
  imports         : use wybe
  resources       : 
  procs           : 

proc show_column > public {inline} (0 calls)
0: specials.show_column<0>
show_column(%call_source_column_number##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_int(~call_source_column_number##0:wybe.int, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn


proc show_file > public {inline} (0 calls)
0: specials.show_file<0>
show_file(%call_source_file_name##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_string(~call_source_file_name##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn


proc show_full_file > public {inline} (0 calls)
0: specials.show_full_file<0>
show_full_file(%call_source_file_full_name##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_string(~call_source_file_full_name##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn


proc show_full_location > public {inline} (0 calls)
0: specials.show_full_location<0>
show_full_location(%call_source_full_location##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_string(~call_source_full_location##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn


proc show_line > public {inline} (0 calls)
0: specials.show_line<0>
show_line(%call_source_line_number##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_int(~call_source_line_number##0:wybe.int, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn


proc show_location > public {inline} (0 calls)
0: specials.show_location<0>
show_location(%call_source_location##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials:nn:nn
    foreign c print_string(~call_source_location##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials:nn:nn

  LLVM code       :

; ModuleID = 'specials'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"specials.show_column<0>"(i64  %"call_source_column_number##0") alwaysinline   {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_column_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials.show_file<0>"(i64  %"call_source_file_name##0") alwaysinline   {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_file_name##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials.show_full_file<0>"(i64  %"call_source_file_full_name##0") alwaysinline   {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_file_full_name##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials.show_full_location<0>"(i64  %"call_source_full_location##0") alwaysinline   {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_full_location##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials.show_line<0>"(i64  %"call_source_line_number##0") alwaysinline   {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_line_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials.show_location<0>"(i64  %"call_source_location##0") alwaysinline   {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_location##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module specials_use
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials_use.<0>
  imports         : use specials
                    use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: specials_use.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_string(c"specials_use":wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_string(c"!ROOT!/final-dump/specials_use.wybe":wybe.c_string, ~tmp#3##0:wybe.phantom, ?tmp#6##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_int(5:wybe.int, ~tmp#7##0:wybe.phantom, ?tmp#10##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#10##0:wybe.phantom, ?tmp#11##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_int(2:wybe.int, ~tmp#11##0:wybe.phantom, ?tmp#14##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#14##0:wybe.phantom, ?tmp#15##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_string(c"specials_use:7:2":wybe.c_string, ~tmp#15##0:wybe.phantom, ?tmp#18##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#18##0:wybe.phantom, ?tmp#19##0:wybe.phantom) @specials_use:nn:nn
    foreign c print_string(c"!ROOT!/final-dump/specials_use.wybe:8:2":wybe.c_string, ~tmp#19##0:wybe.phantom, ?tmp#22##0:wybe.phantom) @specials_use:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#22##0:wybe.phantom, ?tmp#23##0:wybe.phantom) @specials_use:nn:nn
    foreign lpvm store(~%tmp#23##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_use:nn:nn

  LLVM code       :

; ModuleID = 'specials_use'


 


@specials_use.1 =    constant [?? x i8] c"!ROOT!/final-dump/specials_use.wybe\00"


@specials_use.3 =    constant [?? x i8] c"!ROOT!/final-dump/specials_use.wybe:8:2\00"


@specials_use.0 =    constant [?? x i8] c"specials_use\00"


@specials_use.2 =    constant [?? x i8] c"specials_use:7:2\00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"specials_use.<0>"()    {
entry:
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.0, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  5)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.2, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.3, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
