<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Wybe</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.char.begin.wybe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.char.end.wybe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.wybe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.wybe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.quote.wybe</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wybe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}#</string>
			<key>name</key>
			<string>comment.block.wybe</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.wybe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.wybe</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.percentage.wybe</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>def</string>
			<key>name</key>
			<string>keyword.operator.definition.wybe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[!\?][a-z_][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.wybe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>constant.other.symbol.wybe</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wybe</string>
	<key>uuid</key>
	<string>C0E2ADB0-1706-4A28-8DB7-263BDC8B5C5C</string>
</dict>
</plist>
