======================================================================
AFTER EVERYTHING:
 Module alias_multifunc4
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_multifunc4.<0>
                    alias_multifunc4.replicate1<0>
                    alias_multifunc4.replicate21<0>
                    alias_multifunc4.replicate22<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#18:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 10:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 10:wybe.int)
    alias_multifunc4.replicate1<0>(tmp$0#0:position.position, ?p2#0:position.position, ?p3#0:position.position, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @alias_multifunc4:36:2
    foreign c print_string("--- After calling replicate1:":wybe.string, ~#wybe.io$io#1:wybe.phantom, ?tmp$8#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$8#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:78:28
    foreign c print_string("expect p1(10,10):":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~tmp$0#0:position.position, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @alias_multifunc4:40:2
    foreign c print_string("expect p2(99,10):":wybe.string, ~#wybe.io$io#4:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~p2#0:position.position, ~#wybe.io$io#5:wybe.phantom, ?#wybe.io$io#6:wybe.phantom) @alias_multifunc4:42:2
    foreign c print_string("expect p3(10,10):":wybe.string, ~#wybe.io$io#6:wybe.phantom, ?#wybe.io$io#7:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~p3#0:position.position, ~#wybe.io$io#7:wybe.phantom, ?#wybe.io$io#8:wybe.phantom) @alias_multifunc4:44:2
    alias_multifunc4.replicate21<0>(?p4#0:position.position, ~#wybe.io$io#8:wybe.phantom, ?#wybe.io$io#9:wybe.phantom) @alias_multifunc4:47:2
    foreign c print_string("--- After calling replicate21:":wybe.string, ~#wybe.io$io#9:wybe.phantom, ?tmp$17#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$17#0:wybe.phantom, ?#wybe.io$io#10:wybe.phantom) @wybe:78:28
    foreign c print_string("expect p4(99999,99999):":wybe.string, ~#wybe.io$io#10:wybe.phantom, ?#wybe.io$io#11:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~p4#0:position.position, ~#wybe.io$io#11:wybe.phantom, ?#wybe.io$io#12:wybe.phantom) @alias_multifunc4:50:2
    alias_multifunc4.replicate22<0>(?p6#0:position.position, ?p7#0:position.position, ~#wybe.io$io#12:wybe.phantom, ?#wybe.io$io#13:wybe.phantom) @alias_multifunc4:53:2
    foreign c print_string("--- After calling replicate22:":wybe.string, ~#wybe.io$io#13:wybe.phantom, ?tmp$22#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$22#0:wybe.phantom, ?#wybe.io$io#14:wybe.phantom) @wybe:78:28
    foreign c print_string("expect p6(99999,99999):":wybe.string, ~#wybe.io$io#14:wybe.phantom, ?#wybe.io$io#15:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~p6#0:position.position, ~#wybe.io$io#15:wybe.phantom, ?#wybe.io$io#16:wybe.phantom) @alias_multifunc4:56:2
    foreign c print_string("expect p7(1111111111,99999):":wybe.string, ~#wybe.io$io#16:wybe.phantom, ?#wybe.io$io#17:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~p7#0:position.position, ~#wybe.io$io#17:wybe.phantom, ?#wybe.io$io#18:wybe.phantom) @alias_multifunc4:58:2


replicate1 > public (1 calls)
0: replicate1(pa#0:position.position, ?pb#1:position.position, ?pc#0:position.position, wybe.io$io#0:wybe.phantom, [?wybe.io$io#0:wybe.phantom]): AliasPairs: [(pa#0,pc#0)]
    foreign llvm move(pa#0:position.position, ?pc#0:position.position)
    foreign lpvm alloc(16:wybe.int, ?tmp$6#0:position.position)
    foreign lpvm mutate(~tmp$6#0:position.position, ?tmp$7#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99:wybe.int)
    foreign lpvm mutate(~tmp$7#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99:wybe.int)
    foreign lpvm access(~tmp$0#0:position.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign lpvm mutate(~pa#0:position.position, ?%pb#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~tmp$1#0:wybe.int)


replicate21 > public (1 calls)
0: replicate21(?pb#0:position.position, wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign llvm move(tmp$0#0:position.position, ?pb#0:position.position)
    foreign lpvm mutate(~tmp$0#0:position.position, ?%pc#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 1111111111:wybe.int)
    foreign c print_string("--- Inside replicate21, expect pc(1111111111, 99999): ":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~pc#1:position.position, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @alias_multifunc4:20:6


replicate22 > public (1 calls)
0: replicate22(?pb#0:position.position, ?pc#1:position.position, wybe.io$io#0:wybe.phantom, ?wybe.io$io#4:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign llvm move(tmp$0#0:position.position, ?pb#0:position.position)
    foreign c print_string("--- Inside replicate22, expect pc(99999, 99999):":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:92:41
    position.printPosition<0>(tmp$0#0:position.position, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @alias_multifunc4:28:6
    foreign lpvm mutate(~tmp$0#0:position.position, ?%pc#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 1111111111:wybe.int)
    foreign c print_string("--- Inside replicate22, after calling x(!pc, 1111111111), expect pc(1111111111, 99999): ":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:92:41
    position.printPosition<0>(pc#1:position.position, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @alias_multifunc4:32:6
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,"pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:8
  resources       : 
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, wybe.io$io#0:wybe.phantom, ?wybe.io$io#5:wybe.phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:92:41
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:80:38
    foreign c print_string(",":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:92:41
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:80:38
    foreign c print_string(")":wybe.string, ~#wybe.io$io#4:wybe.phantom, ?tmp$14#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$14#0:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @wybe:78:28
  submodules      : position.position
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:position.position, in#0:position.position): AliasPairs: []
    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline (0 calls)
1: =(in#0:position.position, ?out#0:position.position): AliasPairs: []
    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline test (3 calls)
2: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:28:40
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:28:40



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
alias_multifunc4, position, position.position
======================================================================
AFTER LLVM IR:

; ModuleID = 'alias_multifunc4'
source_filename = "test-cases/alias_multifunc4.wybe"

@alias_multifunc4.21 = constant [29 x i8] c"expect p7(1111111111,99999):\00"
@alias_multifunc4.20 = constant [24 x i8] c"expect p6(99999,99999):\00"
@alias_multifunc4.19 = constant [31 x i8] c"--- After calling replicate22:\00"
@alias_multifunc4.15 = constant [24 x i8] c"expect p4(99999,99999):\00"
@alias_multifunc4.14 = constant [31 x i8] c"--- After calling replicate21:\00"
@alias_multifunc4.13 = constant [18 x i8] c"expect p3(10,10):\00"
@alias_multifunc4.12 = constant [18 x i8] c"expect p2(99,10):\00"
@alias_multifunc4.11 = constant [18 x i8] c"expect p1(10,10):\00"
@alias_multifunc4.10 = constant [30 x i8] c"--- After calling replicate1:\00"
@alias_multifunc4.52 = constant [55 x i8] c"--- Inside replicate21, expect pc(1111111111, 99999): \00"
@alias_multifunc4.66 = constant [89 x i8] c"--- Inside replicate22, after calling x(!pc, 1111111111), expect pc(1111111111, 99999): \00"
@alias_multifunc4.59 = constant [49 x i8] c"--- Inside replicate22, expect pc(99999, 99999):\00"

declare void @"position.printPosition<0>"(i64*) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

declare void @putchar(i8) local_unnamed_addr

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

define i32 @alias_multifunc4.main() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 10, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 10, i64* %3, align 4
  %4 = tail call { i64*, i64* } @"alias_multifunc4.replicate1<0>"(i64* %1)
  %5 = extractvalue { i64*, i64* } %4, 0
  %6 = extractvalue { i64*, i64* } %4, 1
  tail call void @print_string(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @alias_multifunc4.10, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.11, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %1)
  tail call void @print_string(i8* getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.12, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %5)
  tail call void @print_string(i8* getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.13, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %6)
  %"p4#0" = tail call i64* @"alias_multifunc4.replicate21<0>"()
  tail call void @print_string(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @alias_multifunc4.14, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @alias_multifunc4.15, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %"p4#0")
  %7 = tail call { i64*, i64* } @"alias_multifunc4.replicate22<0>"()
  %8 = extractvalue { i64*, i64* } %7, 0
  %9 = extractvalue { i64*, i64* } %7, 1
  tail call void @print_string(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @alias_multifunc4.19, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @alias_multifunc4.20, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %8)
  tail call void @print_string(i8* getelementptr inbounds ([29 x i8], [29 x i8]* @alias_multifunc4.21, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %9)
  ret i32 0
}

define { i64*, i64* } @"alias_multifunc4.replicate1<0>"(i64* %"pa#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 99, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 99, i64* %3, align 4
  %4 = tail call i8* @wybe_malloc(i32 16)
  %5 = bitcast i8* %4 to i64*
  %6 = bitcast i64* %"pa#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %4, i8* %6, i32 16, i1 false)
  store i64 99, i64* %5, align 4
  %7 = insertvalue { i64*, i64* } undef, i64* %5, 0
  %8 = insertvalue { i64*, i64* } %7, i64* %"pa#0", 1
  ret { i64*, i64* } %8
}

define i64* @"alias_multifunc4.replicate21<0>"() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 99999, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 99999, i64* %3, align 4
  %4 = tail call i8* @wybe_malloc(i32 16)
  %5 = bitcast i8* %4 to i64*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %4, i8* %0, i32 16, i1 false)
  store i64 1111111111, i64* %5, align 4
  tail call void @print_string(i8* getelementptr inbounds ([55 x i8], [55 x i8]* @alias_multifunc4.52, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %5)
  ret i64* %1
}

define { i64*, i64* } @"alias_multifunc4.replicate22<0>"() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 99999, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 99999, i64* %3, align 4
  tail call void @print_string(i8* getelementptr inbounds ([49 x i8], [49 x i8]* @alias_multifunc4.59, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %1)
  %4 = tail call i8* @wybe_malloc(i32 16)
  %5 = bitcast i8* %4 to i64*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %4, i8* %0, i32 16, i1 false)
  store i64 1111111111, i64* %5, align 4
  tail call void @print_string(i8* getelementptr inbounds ([89 x i8], [89 x i8]* @alias_multifunc4.66, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %5)
  %6 = insertvalue { i64*, i64* } undef, i64* %1, 0
  %7 = insertvalue { i64*, i64* } %6, i64* %5, 1
  ret { i64*, i64* } %7
}

--------------------------------------------------
; ModuleID = 'position'
source_filename = "test-cases/position.wybe"

@position.9 = constant [2 x i8] c")\00"
@position.5 = constant [2 x i8] c",\00"
@position.1 = constant [3 x i8] c" (\00"

declare void @putchar(i8) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

define void @"position.printPosition<0>"(i64* nocapture readonly) local_unnamed_addr {
entry:
  tail call void @print_string(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i64 0, i64 0))
  %1 = load i64, i64* %0, align 4
  tail call void @print_int(i64 %1)
  tail call void @print_string(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.5, i64 0, i64 0))
  %2 = getelementptr i64, i64* %0, i64 1
  %3 = load i64, i64* %2, align 4
  tail call void @print_int(i64 %3)
  tail call void @print_string(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.9, i64 0, i64 0))
  tail call void @putchar(i8 10)
  ret void
}

--------------------------------------------------
; ModuleID = 'position.position'
source_filename = "test-cases"

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position.position.=<2>"(i64* nocapture readonly, i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %2 = load i64, i64* %0, align 4
  %3 = load i64, i64* %1, align 4
  %"tmp$2#0" = icmp eq i64 %2, %3
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %4 = getelementptr i64, i64* %1, i64 1
  %5 = load i64, i64* %4, align 4
  %6 = getelementptr i64, i64* %0, i64 1
  %7 = load i64, i64* %6, align 4
  %"$$#0" = icmp eq i64 %7, %5
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position.position.position<1>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = load i64, i64* %0, align 4
  %2 = getelementptr i64, i64* %0, i64 1
  %3 = load i64, i64* %2, align 4
  %4 = insertvalue { i64, i64 } undef, i64 %1, 0
  %5 = insertvalue { i64, i64 } %4, i64 %3, 1
  ret { i64, i64 } %5
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.x<0>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position.position.x<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.y<0>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = getelementptr i64, i64* %0, i64 1
  %2 = load i64, i64* %1, align 4
  ret i64 %2
}

define i64* @"position.position.y<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  %3 = getelementptr i8, i8* %0, i64 8
  %4 = bitcast i8* %3 to i64*
  store i64 %"$field#0", i64* %4, align 4
  ret i64* %1
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

