======================================================================
AFTER EVERYTHING:
 Module alias_recursion1
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_recursion1.<0>
                    alias_recursion1.if_test<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:phantom, ?io#18:phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$7#0:position.position)
    foreign lpvm mutate(~tmp$7#0:position.position, ?tmp$8#0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 100:wybe.int)
    foreign lpvm mutate(~tmp$8#0:position.position, ?tmp$0#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 101:wybe.int)
    foreign lpvm alloc(16:wybe.int, ?tmp$13#0:position.position)
    foreign lpvm mutate(~tmp$13#0:position.position, ?tmp$14#0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, -200:wybe.int)
    foreign lpvm mutate(~tmp$14#0:position.position, ?tmp$1#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, -201:wybe.int)
    foreign c print_string("--- before proc call: ":wybe.string, ~#io#0:phantom, ?tmp$17#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$17#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    foreign c print_string("expect pa(100,101):":wybe.string, ~#io#1:phantom, ?#io#2:phantom) @wybe:nn:nn
    position.printPosition<0>(tmp$0#0:position.position, ~#io#2:phantom, ?#io#3:phantom) @alias_recursion1:20:2
    foreign c print_string("expect pb(-200,-201):":wybe.string, ~#io#3:phantom, ?#io#4:phantom) @wybe:nn:nn
    position.printPosition<0>(tmp$1#0:position.position, ~#io#4:phantom, ?#io#5:phantom) @alias_recursion1:22:2
    alias_recursion1.if_test<0>(tmp$0#0:position.position, tmp$1#0:position.position, ?r#0:position.position) @alias_recursion1:24:1
    foreign c print_string("--- after calling if_test, pa and pb should be the same: ":wybe.string, ~#io#5:phantom, ?tmp$24#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$24#0:phantom, ?#io#6:phantom) @wybe:nn:nn
    foreign c print_string("expect pa(100,101):":wybe.string, ~#io#6:phantom, ?#io#7:phantom) @wybe:nn:nn
    position.printPosition<0>(tmp$0#0:position.position, ~#io#7:phantom, ?#io#8:phantom) @alias_recursion1:28:2
    foreign c print_string("expect pb(-200,-201):":wybe.string, ~#io#8:phantom, ?#io#9:phantom) @wybe:nn:nn
    position.printPosition<0>(~tmp$1#0:position.position, ~#io#9:phantom, ?#io#10:phantom) @alias_recursion1:30:2
    foreign c print_string("--- expected result to be same as pb: ":wybe.string, ~#io#10:phantom, ?tmp$31#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$31#0:phantom, ?#io#11:phantom) @wybe:nn:nn
    foreign c print_string("expect r(-200,-201):":wybe.string, ~#io#11:phantom, ?#io#12:phantom) @wybe:nn:nn
    position.printPosition<0>(r#0:position.position, ~#io#12:phantom, ?#io#13:phantom) @alias_recursion1:34:2
    foreign c print_string("--- modify pa.x: ":wybe.string, ~#io#13:phantom, ?tmp$36#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$36#0:phantom, ?#io#14:phantom) @wybe:nn:nn
    foreign lpvm mutate noalias(~tmp$0#0:position.position, ?%pa#1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, -1000:wybe.int)
    foreign c print_string("expect pa(-1000,101):":wybe.string, ~#io#14:phantom, ?#io#15:phantom) @wybe:nn:nn
    position.printPosition<0>(~pa#1:position.position, ~#io#15:phantom, ?#io#16:phantom) @alias_recursion1:39:2
    foreign c print_string("expect r still (-200,-201):":wybe.string, ~#io#16:phantom, ?#io#17:phantom) @wybe:nn:nn
    position.printPosition<0>(~r#0:position.position, ~#io#17:phantom, ?#io#18:phantom) @alias_recursion1:42:2


if_test > public (2 calls)
0: if_test(a#0:position.position, b#0:position.position, ?r#0:position.position): AliasPairs: [(a#0,b#0),(a#0,r#0),(b#0,r#0)]
    foreign lpvm access(a#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(~tmp$0#0:wybe.int, 0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:nn:nn
    case ~tmp$1#0:wybe.bool of
    0:
        foreign llvm move(~a#0:position.position, ?r#0:position.position) @alias_recursion1:12:13

    1:
        alias_recursion1.if_test<0>(~b#0:position.position, ~a#0:position.position, ?r#0:position.position) @alias_recursion1:10:13


  LLVM code       :

; ModuleID = 'alias_recursion1'


 


declare external ccc  void @"position.printPosition<0>"(i64)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @putchar(i8)    


@alias_recursion1.45 =    constant [28 x i8] c"expect r still (-200,-201):\00"


@alias_recursion1.43 =    constant [22 x i8] c"expect pa(-1000,101):\00"


@alias_recursion1.33 =    constant [18 x i8] c"--- modify pa.x: \00"


@alias_recursion1.31 =    constant [21 x i8] c"expect r(-200,-201):\00"


@alias_recursion1.29 =    constant [39 x i8] c"--- expected result to be same as pb: \00"


@alias_recursion1.27 =    constant [22 x i8] c"expect pb(-200,-201):\00"


@alias_recursion1.25 =    constant [20 x i8] c"expect pa(100,101):\00"


@alias_recursion1.23 =    constant [58 x i8] c"--- after calling if_test, pa and pb should be the same: \00"


@alias_recursion1.21 =    constant [22 x i8] c"expect pb(-200,-201):\00"


@alias_recursion1.19 =    constant [20 x i8] c"expect pa(100,101):\00"


@alias_recursion1.17 =    constant [23 x i8] c"--- before proc call: \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_recursion1.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 100, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  store  i64 101, i64* %8 
  %9 = trunc i64 16 to i32  
  %10 = tail call ccc  i8*  @wybe_malloc(i32  %9)  
  %11 = ptrtoint i8* %10 to i64 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  store  i64 -200, i64* %13 
  %14 = add   i64 %11, 8 
  %15 = inttoptr i64 %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 -201, i64* %16 
  %18 = ptrtoint i8* getelementptr inbounds ([23 x i8], [23 x i8]* @alias_recursion1.17, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %18)  
  tail call ccc  void  @putchar(i8  10)  
  %20 = ptrtoint i8* getelementptr inbounds ([20 x i8], [20 x i8]* @alias_recursion1.19, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %20)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %3)  
  %22 = ptrtoint i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.21, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %22)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %11)  
  %"r#0" = tail call ccc  i64  @"alias_recursion1.if_test<0>"(i64  %3, i64  %11)  
  %24 = ptrtoint i8* getelementptr inbounds ([58 x i8], [58 x i8]* @alias_recursion1.23, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %24)  
  tail call ccc  void  @putchar(i8  10)  
  %26 = ptrtoint i8* getelementptr inbounds ([20 x i8], [20 x i8]* @alias_recursion1.25, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %26)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %3)  
  %28 = ptrtoint i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.27, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %28)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %11)  
  %30 = ptrtoint i8* getelementptr inbounds ([39 x i8], [39 x i8]* @alias_recursion1.29, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %30)  
  tail call ccc  void  @putchar(i8  10)  
  %32 = ptrtoint i8* getelementptr inbounds ([21 x i8], [21 x i8]* @alias_recursion1.31, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %32)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %"r#0")  
  %34 = ptrtoint i8* getelementptr inbounds ([18 x i8], [18 x i8]* @alias_recursion1.33, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %34)  
  tail call ccc  void  @putchar(i8  10)  
  %35 = trunc i64 16 to i32  
  %36 = tail call ccc  i8*  @wybe_malloc(i32  %35)  
  %37 = ptrtoint i8* %36 to i64 
  %38 = inttoptr i64 %37 to i8* 
  %39 = inttoptr i64 %3 to i8* 
  %40 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %38, i8*  %39, i32  %40, i32  8, i1  0)  
  %41 = inttoptr i64 %37 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  store  i64 -1000, i64* %42 
  %44 = ptrtoint i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.43, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %44)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %37)  
  %46 = ptrtoint i8* getelementptr inbounds ([28 x i8], [28 x i8]* @alias_recursion1.45, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %46)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %"r#0")  
  ret void 
}


define external ccc  i64 @"alias_recursion1.if_test<0>"(i64  %"a#0", i64  %"b#0")    {
entry:
  %47 = inttoptr i64 %"a#0" to i64* 
  %48 = getelementptr  i64, i64* %47, i64 0 
  %49 = load  i64, i64* %48 
  %"tmp$1#0" = icmp sgt i64 %49, 0 
  br i1 %"tmp$1#0", label %if.then, label %if.else 
if.then:
  %"r#0" = tail call ccc  i64  @"alias_recursion1.if_test<0>"(i64  %"b#0", i64  %"a#0")  
  ret i64 %"r#0" 
if.else:
  ret i64 %"a#0" 
}
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,Just "pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:5
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, io#0:phantom, ?io#5:phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string(",":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#3:phantom, ?#io#4:phantom) @wybe:nn:nn
    foreign c print_string(")":wybe.string, ~#io#4:phantom, ?tmp$14#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$14#0:phantom, ?#io#5:phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


@position.12 =    constant [2 x i8] c")\00"


@position.6 =    constant [2 x i8] c",\00"


@position.1 =    constant [3 x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"position.printPosition<0>"(i64  %"pos#0")    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  %3 = inttoptr i64 %"pos#0" to i64* 
  %4 = getelementptr  i64, i64* %3, i64 0 
  %5 = load  i64, i64* %4 
  tail call ccc  void  @print_int(i64  %5)  
  %7 = ptrtoint i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.6, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %7)  
  %8 = add   i64 %"pos#0", 8 
  %9 = inttoptr i64 %8 to i64* 
  %10 = getelementptr  i64, i64* %9, i64 0 
  %11 = load  i64, i64* %10 
  tail call ccc  void  @print_int(i64  %11)  
  %13 = ptrtoint i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.12, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %13)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:position.position, ?%$rec#1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:position.position, ?%$rec#1:position.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"position.position.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$2#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %7, %14 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64 @"position.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %15 = trunc i64 16 to i32  
  %16 = tail call ccc  i8*  @wybe_malloc(i32  %15)  
  %17 = ptrtoint i8* %16 to i64 
  %18 = inttoptr i64 %17 to i64* 
  %19 = getelementptr  i64, i64* %18, i64 0 
  store  i64 %"x#0", i64* %19 
  %20 = add   i64 %17, 8 
  %21 = inttoptr i64 %20 to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  store  i64 %"y#0", i64* %22 
  ret i64 %17 
}


define external ccc  {i64, i64} @"position.position.position<1>"(i64  %"$#0")    {
entry:
  %23 = inttoptr i64 %"$#0" to i64* 
  %24 = getelementptr  i64, i64* %23, i64 0 
  %25 = load  i64, i64* %24 
  %26 = add   i64 %"$#0", 8 
  %27 = inttoptr i64 %26 to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  %30 = insertvalue {i64, i64} undef, i64 %25, 0 
  %31 = insertvalue {i64, i64} %30, i64 %29, 1 
  ret {i64, i64} %31 
}


define external ccc  i64 @"position.position.x<0>"(i64  %"$rec#0")    {
entry:
  %32 = inttoptr i64 %"$rec#0" to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  %34 = load  i64, i64* %33 
  ret i64 %34 
}


define external ccc  i64 @"position.position.x<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %35 = trunc i64 16 to i32  
  %36 = tail call ccc  i8*  @wybe_malloc(i32  %35)  
  %37 = ptrtoint i8* %36 to i64 
  %38 = inttoptr i64 %37 to i8* 
  %39 = inttoptr i64 %"$rec#0" to i8* 
  %40 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %38, i8*  %39, i32  %40, i32  8, i1  0)  
  %41 = inttoptr i64 %37 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  store  i64 %"$field#0", i64* %42 
  ret i64 %37 
}


define external ccc  i64 @"position.position.y<0>"(i64  %"$rec#0")    {
entry:
  %43 = add   i64 %"$rec#0", 8 
  %44 = inttoptr i64 %43 to i64* 
  %45 = getelementptr  i64, i64* %44, i64 0 
  %46 = load  i64, i64* %45 
  ret i64 %46 
}


define external ccc  i64 @"position.position.y<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %47 = trunc i64 16 to i32  
  %48 = tail call ccc  i8*  @wybe_malloc(i32  %47)  
  %49 = ptrtoint i8* %48 to i64 
  %50 = inttoptr i64 %49 to i8* 
  %51 = inttoptr i64 %"$rec#0" to i8* 
  %52 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %50, i8*  %51, i32  %52, i32  8, i1  0)  
  %53 = add   i64 %49, 8 
  %54 = inttoptr i64 %53 to i64* 
  %55 = getelementptr  i64, i64* %54, i64 0 
  store  i64 %"$field#0", i64* %55 
  ret i64 %49 
}
