======================================================================
AFTER EVERYTHING:
 Module alias_recursion1
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_recursion1.<0>
                    alias_recursion1.if_test<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#18:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$7#0:position.position)
    foreign lpvm mutate(~tmp$7#0:position.position, ?tmp$8#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 100:wybe.int)
    foreign lpvm mutate(~tmp$8#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 101:wybe.int)
    foreign lpvm alloc(16:wybe.int, ?tmp$14#0:position.position)
    foreign lpvm mutate(~tmp$14#0:position.position, ?tmp$15#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, -200:wybe.int)
    foreign lpvm mutate(~tmp$15#0:position.position, ?tmp$1#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, -201:wybe.int)
    foreign c print_string("--- before proc call: ":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?tmp$19#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$19#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:78:28
    foreign c print_string("expect pa(100,101):":wybe.string, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:92:41
    position.printPosition<0>(tmp$0#0:position.position, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @alias_recursion1:19:2
    foreign c print_string("expect pb(-200,-201):":wybe.string, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:92:41
    position.printPosition<0>(tmp$1#0:position.position, ~#wybe.io$io#4:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @alias_recursion1:21:2
    alias_recursion1.if_test<0>(tmp$0#0:position.position, tmp$1#0:position.position, ?r#0:position.position) @alias_recursion1:23:1
    foreign c print_string("--- after calling if_test, pa and pb should be the same: ":wybe.string, ~#wybe.io$io#5:wybe.phantom, ?tmp$26#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$26#0:wybe.phantom, ?#wybe.io$io#6:wybe.phantom) @wybe:78:28
    foreign c print_string("expect pa(100,101):":wybe.string, ~#wybe.io$io#6:wybe.phantom, ?#wybe.io$io#7:wybe.phantom) @wybe:92:41
    position.printPosition<0>(tmp$0#0:position.position, ~#wybe.io$io#7:wybe.phantom, ?#wybe.io$io#8:wybe.phantom) @alias_recursion1:27:2
    foreign c print_string("expect pb(-200,-201):":wybe.string, ~#wybe.io$io#8:wybe.phantom, ?#wybe.io$io#9:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~tmp$1#0:position.position, ~#wybe.io$io#9:wybe.phantom, ?#wybe.io$io#10:wybe.phantom) @alias_recursion1:29:2
    foreign c print_string("--- expected result to be same as pb: ":wybe.string, ~#wybe.io$io#10:wybe.phantom, ?tmp$33#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$33#0:wybe.phantom, ?#wybe.io$io#11:wybe.phantom) @wybe:78:28
    foreign c print_string("expect r(-200,-201):":wybe.string, ~#wybe.io$io#11:wybe.phantom, ?#wybe.io$io#12:wybe.phantom) @wybe:92:41
    position.printPosition<0>(r#0:position.position, ~#wybe.io$io#12:wybe.phantom, ?#wybe.io$io#13:wybe.phantom) @alias_recursion1:33:2
    foreign c print_string("--- modify pa.x: ":wybe.string, ~#wybe.io$io#13:wybe.phantom, ?tmp$38#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$38#0:wybe.phantom, ?#wybe.io$io#14:wybe.phantom) @wybe:78:28
    foreign lpvm mutate(~tmp$0#0:position.position, ?%pa#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, -1000:wybe.int)
    foreign c print_string("expect pa(-1000,101):":wybe.string, ~#wybe.io$io#14:wybe.phantom, ?#wybe.io$io#15:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~pa#1:position.position, ~#wybe.io$io#15:wybe.phantom, ?#wybe.io$io#16:wybe.phantom) @alias_recursion1:38:2
    foreign c print_string("expect r still (-200,-201):":wybe.string, ~#wybe.io$io#16:wybe.phantom, ?#wybe.io$io#17:wybe.phantom) @wybe:92:41
    position.printPosition<0>(~r#0:position.position, ~#wybe.io$io#17:wybe.phantom, ?#wybe.io$io#18:wybe.phantom) @alias_recursion1:41:2


if_test > public (2 calls)
0: if_test(a#0:position.position, b#0:position.position, ?r#0:position.position): AliasPairs: [(a#0,b#0),(a#0,r#0),(b#0,r#0)]
    foreign lpvm access(a#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(~tmp$0#0:wybe.int, 0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:26:39
    case ~tmp$1#0:wybe.bool of
    0:
        foreign lpvm cast(1:wybe.bool, ?tmp$2#0:wybe.bool)
        case ~tmp$2#0:wybe.bool of
        0:

        1:
            foreign llvm move(~a#0:position.position, ?r#0:position.position)


    1:
        alias_recursion1.if_test<0>(~b#0:position.position, ~a#0:position.position, ?r#0:position.position) @alias_recursion1:10:7

--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,"pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:8
  resources       : 
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, wybe.io$io#0:wybe.phantom, ?wybe.io$io#5:wybe.phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:92:41
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:80:38
    foreign c print_string(",":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:92:41
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:80:38
    foreign c print_string(")":wybe.string, ~#wybe.io$io#4:wybe.phantom, ?tmp$14#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$14#0:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @wybe:78:28
  submodules      : position.position
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:position.position, in#0:position.position): AliasPairs: []
    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline (0 calls)
1: =(in#0:position.position, ?out#0:position.position): AliasPairs: []
    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline test (3 calls)
2: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:28:40
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:28:40



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
alias_recursion1, position, position.position
======================================================================
AFTER LLVM IR:

; ModuleID = 'alias_recursion1'
source_filename = "test-cases/alias_recursion1.wybe"

@alias_recursion1.29 = constant [28 x i8] c"expect r still (-200,-201):\00"
@alias_recursion1.28 = constant [22 x i8] c"expect pa(-1000,101):\00"
@alias_recursion1.21 = constant [18 x i8] c"--- modify pa.x: \00"
@alias_recursion1.20 = constant [21 x i8] c"expect r(-200,-201):\00"
@alias_recursion1.19 = constant [39 x i8] c"--- expected result to be same as pb: \00"
@alias_recursion1.18 = constant [22 x i8] c"expect pb(-200,-201):\00"
@alias_recursion1.17 = constant [20 x i8] c"expect pa(100,101):\00"
@alias_recursion1.16 = constant [58 x i8] c"--- after calling if_test, pa and pb should be the same: \00"
@alias_recursion1.15 = constant [22 x i8] c"expect pb(-200,-201):\00"
@alias_recursion1.14 = constant [20 x i8] c"expect pa(100,101):\00"
@alias_recursion1.13 = constant [23 x i8] c"--- before proc call: \00"

declare void @"position.printPosition<0>"(i64*) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

declare void @putchar(i8) local_unnamed_addr

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

define i32 @alias_recursion1.main() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 100, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 101, i64* %3, align 4
  %4 = tail call i8* @wybe_malloc(i32 16)
  %5 = bitcast i8* %4 to i64*
  store i64 -200, i64* %5, align 4
  %6 = getelementptr i8, i8* %4, i64 8
  %7 = bitcast i8* %6 to i64*
  store i64 -201, i64* %7, align 4
  tail call void @print_string(i8* getelementptr inbounds ([23 x i8], [23 x i8]* @alias_recursion1.13, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([20 x i8], [20 x i8]* @alias_recursion1.14, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %1)
  tail call void @print_string(i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.15, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %5)
  %"r#0" = tail call i64* @"alias_recursion1.if_test<0>"(i64* %1, i64* %5)
  tail call void @print_string(i8* getelementptr inbounds ([58 x i8], [58 x i8]* @alias_recursion1.16, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([20 x i8], [20 x i8]* @alias_recursion1.17, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %1)
  tail call void @print_string(i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.18, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %5)
  tail call void @print_string(i8* getelementptr inbounds ([39 x i8], [39 x i8]* @alias_recursion1.19, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_string(i8* getelementptr inbounds ([21 x i8], [21 x i8]* @alias_recursion1.20, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %"r#0")
  tail call void @print_string(i8* getelementptr inbounds ([18 x i8], [18 x i8]* @alias_recursion1.21, i64 0, i64 0))
  tail call void @putchar(i8 10)
  %8 = tail call i8* @wybe_malloc(i32 16)
  %9 = bitcast i8* %8 to i64*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %8, i8* %0, i32 16, i1 false)
  store i64 -1000, i64* %9, align 4
  tail call void @print_string(i8* getelementptr inbounds ([22 x i8], [22 x i8]* @alias_recursion1.28, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %9)
  tail call void @print_string(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @alias_recursion1.29, i64 0, i64 0))
  tail call void @"position.printPosition<0>"(i64* %"r#0")
  ret i32 0
}

; Function Attrs: nounwind readonly
define i64* @"alias_recursion1.if_test<0>"(i64* readonly, i64* %"b#0") local_unnamed_addr #0 {
entry:
  br label %tailrecurse

tailrecurse:                                      ; preds = %tailrecurse, %entry
  %.tr = phi i64* [ %0, %entry ], [ %"b#0.tr", %tailrecurse ]
  %"b#0.tr" = phi i64* [ %"b#0", %entry ], [ %.tr, %tailrecurse ]
  %1 = load i64, i64* %.tr, align 4
  %"tmp$1#0" = icmp sgt i64 %1, 0
  br i1 %"tmp$1#0", label %tailrecurse, label %if.then1

if.then1:                                         ; preds = %tailrecurse
  ret i64* %.tr
}

attributes #0 = { nounwind readonly }

--------------------------------------------------
; ModuleID = 'position'
source_filename = "test-cases/position.wybe"

@position.9 = constant [2 x i8] c")\00"
@position.5 = constant [2 x i8] c",\00"
@position.1 = constant [3 x i8] c" (\00"

declare void @putchar(i8) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

define void @"position.printPosition<0>"(i64* nocapture readonly) local_unnamed_addr {
entry:
  tail call void @print_string(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i64 0, i64 0))
  %1 = load i64, i64* %0, align 4
  tail call void @print_int(i64 %1)
  tail call void @print_string(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.5, i64 0, i64 0))
  %2 = getelementptr i64, i64* %0, i64 1
  %3 = load i64, i64* %2, align 4
  tail call void @print_int(i64 %3)
  tail call void @print_string(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.9, i64 0, i64 0))
  tail call void @putchar(i8 10)
  ret void
}

--------------------------------------------------
; ModuleID = 'position.position'
source_filename = "test-cases"

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position.position.=<2>"(i64* nocapture readonly, i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %2 = load i64, i64* %0, align 4
  %3 = load i64, i64* %1, align 4
  %"tmp$2#0" = icmp eq i64 %2, %3
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %4 = getelementptr i64, i64* %1, i64 1
  %5 = load i64, i64* %4, align 4
  %6 = getelementptr i64, i64* %0, i64 1
  %7 = load i64, i64* %6, align 4
  %"$$#0" = icmp eq i64 %7, %5
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position.position.position<1>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = load i64, i64* %0, align 4
  %2 = getelementptr i64, i64* %0, i64 1
  %3 = load i64, i64* %2, align 4
  %4 = insertvalue { i64, i64 } undef, i64 %1, 0
  %5 = insertvalue { i64, i64 } %4, i64 %3, 1
  ret { i64, i64 } %5
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.x<0>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position.position.x<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.y<0>"(i64* nocapture readonly) local_unnamed_addr #1 {
entry:
  %1 = getelementptr i64, i64* %0, i64 1
  %2 = load i64, i64* %1, align 4
  ret i64 %2
}

define i64* @"position.position.y<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  %3 = getelementptr i8, i8* %0, i64 8
  %4 = bitcast i8* %3 to i64*
  store i64 %"$field#0", i64* %4, align 4
  ret i64* %1
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

