======================================================================
AFTER EVERYTHING:
 Module alias_data
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_data.<0>
                    alias_data.backup<0>
                    alias_data.bar<0>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    alias_data.bar<0>(~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @alias_data:19:2


backup > public inline (1 calls)
0: backup(student1#0:student.student, ?student2#0:student.student, io#0:wybe.phantom, [?io#0:wybe.phantom]): AliasPairs: []
    foreign llvm move(~student1#0:student.student, ?student2#0:student.student) @alias_data:4:3


bar > public (1 calls)
0: bar(io#0:wybe.phantom, ?io#5:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:student.course)
    foreign lpvm mutate(~tmp$4#0:student.course, ?tmp$5#0:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 101:wybe.int)
    foreign lpvm mutate(~tmp$5#0:student.course, ?tmp$0#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, "intro to cs":wybe.string)
    foreign lpvm alloc(16:wybe.int, ?tmp$8#0:student.student)
    foreign lpvm mutate(~tmp$8#0:student.student, ?tmp$9#0:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 9401:wybe.int)
    foreign lpvm mutate(~tmp$9#0:student.student, ?tmp$1#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$0#0:student.course)
    foreign c print_string("student1":wybe.string, ~#io#0:wybe.phantom, ?tmp$13#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$13#0:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    student.printStudent<0>(tmp$1#0:student.student, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @alias_data:13:4
    foreign c print_string("student2":wybe.string, ~#io#3:wybe.phantom, ?tmp$16#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$16#0:wybe.phantom, ?#io#4:wybe.phantom) @wybe:nn:nn
    student.printStudent<0>(~tmp$1#0:student.student, ~#io#4:wybe.phantom, ?#io#5:wybe.phantom) @alias_data:16:4

  LLVM code       :

; ModuleID = 'alias_data'


 


declare external ccc  void @"student.printStudent<0>"(i64)    


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


@alias_data.21 =    constant [9 x i8] c"student2\00"


@alias_data.19 =    constant [9 x i8] c"student1\00"


@alias_data.9 =    constant [12 x i8] c"intro to cs\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_data.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  tail call ccc  void  @"alias_data.bar<0>"()  
  ret void 
}


define external ccc  i64 @"alias_data.backup<0>"(i64  %"student1#0")    {
entry:
  ret i64 %"student1#0" 
}


define external ccc  void @"alias_data.bar<0>"()    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 101, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %10 = ptrtoint i8* getelementptr inbounds ([12 x i8], [12 x i8]* @alias_data.9, i32 0, i32 0) to i64 
  store  i64 %10, i64* %8 
  %11 = trunc i64 16 to i32  
  %12 = tail call ccc  i8*  @wybe_malloc(i32  %11)  
  %13 = ptrtoint i8* %12 to i64 
  %14 = inttoptr i64 %13 to i64* 
  %15 = getelementptr  i64, i64* %14, i64 0 
  store  i64 9401, i64* %15 
  %16 = add   i64 %13, 8 
  %17 = inttoptr i64 %16 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 0 
  store  i64 %3, i64* %18 
  %20 = ptrtoint i8* getelementptr inbounds ([9 x i8], [9 x i8]* @alias_data.19, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %20)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @"student.printStudent<0>"(i64  %13)  
  %22 = ptrtoint i8* getelementptr inbounds ([9 x i8], [9 x i8]* @alias_data.21, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %22)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @"student.printStudent<0>"(i64  %13)  
  ret void 
}
--------------------------------------------------
 Module student
  public submods  : 
  public types    : course: (student.course,Just "address")
                    student: (student.student,Just "address")
  public resources: 
  public procs    : student.<0>
                    student.printStudent<0>
                    student.course.=<0>
                    student.course.code<0>
                    student.course.code<1>
                    student.course.course<0>
                    student.course.course<1>
                    student.course.name<0>
                    student.course.name<1>
                    student.student.=<0>
                    student.student.id<0>
                    student.student.id<1>
                    student.student.major<0>
                    student.student.major<1>
                    student.student.student<0>
                    student.student.student<1>
  imports         : public use student.course
                    public use student.student
                    use wybe
  types           : course/public  is address { course(code:int, name:string) @student:1:24  }  @student:1:5, student/public  is address { student(id:int, major:course) @student:2:24  }  @student:2:5
  resources       : 
  submodules      : student.course, student.student
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:student.course)
    foreign lpvm mutate(~tmp$4#0:student.course, ?tmp$5#0:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 90048:wybe.int)
    foreign lpvm mutate(~tmp$5#0:student.course, ?tmp$6#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, "Declarative Programming":wybe.string)
    foreign lpvm alloc(16:wybe.int, ?tmp$9#0:student.student)
    foreign lpvm mutate(~tmp$9#0:student.student, ?tmp$10#0:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 12345:wybe.int)
    foreign lpvm mutate(~tmp$10#0:student.student, ?tmp$11#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$6#0:student.course)
    student.printStudent<0>(~tmp$11#0:student.student, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @student:14:2


printStudent > public (1 calls)
0: printStudent(stu#0:student.student, io#0:wybe.phantom, ?io#6:wybe.phantom): AliasPairs: []
    foreign c print_string("student id: ":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(stu#0:student.student, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$9#0:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(~stu#0:student.student, 8:wybe.int, ?tmp$1#0:student.course)
    foreign c print_string("course code: ":wybe.string, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(tmp$1#0:student.course, 0:wybe.int, ?tmp$2#0:wybe.int)
    foreign c print_int(~tmp$2#0:wybe.int, ~#io#3:wybe.phantom, ?tmp$16#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$16#0:wybe.phantom, ?#io#4:wybe.phantom) @wybe:nn:nn
    foreign c print_string("course name: ":wybe.string, ~#io#4:wybe.phantom, ?#io#5:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(~tmp$1#0:student.course, 8:wybe.int, ?tmp$3#0:wybe.string)
    foreign c print_string(~tmp$3#0:wybe.string, ~#io#5:wybe.phantom, ?tmp$22#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$22#0:wybe.phantom, ?#io#6:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'student'


 


@student.9 =    constant [24 x i8] c"Declarative Programming\00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


@student.33 =    constant [14 x i8] c"course name: \00"


@student.28 =    constant [14 x i8] c"course code: \00"


@student.19 =    constant [13 x i8] c"student id: \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"student.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 90048, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %10 = ptrtoint i8* getelementptr inbounds ([24 x i8], [24 x i8]* @student.9, i32 0, i32 0) to i64 
  store  i64 %10, i64* %8 
  %11 = trunc i64 16 to i32  
  %12 = tail call ccc  i8*  @wybe_malloc(i32  %11)  
  %13 = ptrtoint i8* %12 to i64 
  %14 = inttoptr i64 %13 to i64* 
  %15 = getelementptr  i64, i64* %14, i64 0 
  store  i64 12345, i64* %15 
  %16 = add   i64 %13, 8 
  %17 = inttoptr i64 %16 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 0 
  store  i64 %3, i64* %18 
  tail call ccc  void  @"student.printStudent<0>"(i64  %13)  
  ret void 
}


define external ccc  void @"student.printStudent<0>"(i64  %"stu#0")    {
entry:
  %20 = ptrtoint i8* getelementptr inbounds ([13 x i8], [13 x i8]* @student.19, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %20)  
  %21 = inttoptr i64 %"stu#0" to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  tail call ccc  void  @print_int(i64  %23)  
  tail call ccc  void  @putchar(i8  10)  
  %24 = add   i64 %"stu#0", 8 
  %25 = inttoptr i64 %24 to i64* 
  %26 = getelementptr  i64, i64* %25, i64 0 
  %27 = load  i64, i64* %26 
  %29 = ptrtoint i8* getelementptr inbounds ([14 x i8], [14 x i8]* @student.28, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %29)  
  %30 = inttoptr i64 %27 to i64* 
  %31 = getelementptr  i64, i64* %30, i64 0 
  %32 = load  i64, i64* %31 
  tail call ccc  void  @print_int(i64  %32)  
  tail call ccc  void  @putchar(i8  10)  
  %34 = ptrtoint i8* getelementptr inbounds ([14 x i8], [14 x i8]* @student.33, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %34)  
  %35 = add   i64 %27, 8 
  %36 = inttoptr i64 %35 to i64* 
  %37 = getelementptr  i64, i64* %36, i64 0 
  %38 = load  i64, i64* %37 
  tail call ccc  void  @print_string(i64  %38)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module student.course
  public submods  : 
  public types    : 
  public resources: 
  public procs    : student.course.=<0>
                    student.course.code<0>
                    student.course.code<1>
                    student.course.course<0>
                    student.course.course<1>
                    student.course.name<0>
                    student.course.name<1>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:student.course, $right#0:student.course, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.course, 0:wybe.int, ?$left$code#0:wybe.int)
    foreign lpvm access(~$left#0:student.course, 8:wybe.int, ?$left$name#0:wybe.string)
    foreign lpvm access($right#0:student.course, 0:wybe.int, ?$right$code#0:wybe.int)
    foreign lpvm access(~$right#0:student.course, 8:wybe.int, ?$right$name#0:wybe.string)
    foreign llvm icmp eq(~$left$code#0:wybe.int, ~$right$code#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign c strcmp(~$left$name#0:wybe.string, ~$right$name#0:wybe.string, ?tmp$10#0:wybe.int) @wybe:nn:nn
        wybe.int.=<0>(~tmp$10#0:wybe.int, 0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



code > public inline (0 calls)
0: code($rec#0:student.course, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:student.course, 0:wybe.int, ?$#0:wybe.int)
code > public inline (0 calls)
1: code($rec#0:student.course, ?$rec#1:student.course, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:student.course, ?%$rec#1:student.course, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


course > public inline (0 calls)
0: course(code#0:wybe.int, name#0:wybe.string, ?$#0:student.course): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:student.course)
    foreign lpvm mutate(~%$rec#0:student.course, ?%$rec#1:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~code#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:student.course, ?%$#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~name#0:wybe.string)
course > public inline (4 calls)
1: course(?code#0:wybe.int, ?name#0:wybe.string, $#0:student.course): AliasPairs: []
    foreign lpvm access($#0:student.course, 0:wybe.int, ?code#0:wybe.int)
    foreign lpvm access(~$#0:student.course, 8:wybe.int, ?name#0:wybe.string)


name > public inline (0 calls)
0: name($rec#0:student.course, ?$#0:wybe.string): AliasPairs: []
    foreign lpvm access(~$rec#0:student.course, 8:wybe.int, ?$#0:wybe.string)
name > public inline (0 calls)
1: name($rec#0:student.course, ?$rec#1:student.course, $field#0:wybe.string): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:student.course, ?%$rec#1:student.course, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.string)

  LLVM code       :

; ModuleID = 'student.course'


 


declare external ccc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i64 @strcmp(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"student.course.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$2#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"tmp$10#0" = tail call ccc  i64  @strcmp(i64  %7, i64  %14)  
  %"$$#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %"tmp$10#0", i64  0)  
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64 @"student.course.code<0>"(i64  %"$rec#0")    {
entry:
  %15 = inttoptr i64 %"$rec#0" to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  %17 = load  i64, i64* %16 
  ret i64 %17 
}


define external ccc  i64 @"student.course.code<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %18 = trunc i64 16 to i32  
  %19 = tail call ccc  i8*  @wybe_malloc(i32  %18)  
  %20 = ptrtoint i8* %19 to i64 
  %21 = inttoptr i64 %20 to i8* 
  %22 = inttoptr i64 %"$rec#0" to i8* 
  %23 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %21, i8*  %22, i32  %23, i32  8, i1  0)  
  %24 = inttoptr i64 %20 to i64* 
  %25 = getelementptr  i64, i64* %24, i64 0 
  store  i64 %"$field#0", i64* %25 
  ret i64 %20 
}


define external ccc  i64 @"student.course.course<0>"(i64  %"code#0", i64  %"name#0")    {
entry:
  %26 = trunc i64 16 to i32  
  %27 = tail call ccc  i8*  @wybe_malloc(i32  %26)  
  %28 = ptrtoint i8* %27 to i64 
  %29 = inttoptr i64 %28 to i64* 
  %30 = getelementptr  i64, i64* %29, i64 0 
  store  i64 %"code#0", i64* %30 
  %31 = add   i64 %28, 8 
  %32 = inttoptr i64 %31 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  store  i64 %"name#0", i64* %33 
  ret i64 %28 
}


define external ccc  {i64, i64} @"student.course.course<1>"(i64  %"$#0")    {
entry:
  %34 = inttoptr i64 %"$#0" to i64* 
  %35 = getelementptr  i64, i64* %34, i64 0 
  %36 = load  i64, i64* %35 
  %37 = add   i64 %"$#0", 8 
  %38 = inttoptr i64 %37 to i64* 
  %39 = getelementptr  i64, i64* %38, i64 0 
  %40 = load  i64, i64* %39 
  %41 = insertvalue {i64, i64} undef, i64 %36, 0 
  %42 = insertvalue {i64, i64} %41, i64 %40, 1 
  ret {i64, i64} %42 
}


define external ccc  i64 @"student.course.name<0>"(i64  %"$rec#0")    {
entry:
  %43 = add   i64 %"$rec#0", 8 
  %44 = inttoptr i64 %43 to i64* 
  %45 = getelementptr  i64, i64* %44, i64 0 
  %46 = load  i64, i64* %45 
  ret i64 %46 
}


define external ccc  i64 @"student.course.name<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %47 = trunc i64 16 to i32  
  %48 = tail call ccc  i8*  @wybe_malloc(i32  %47)  
  %49 = ptrtoint i8* %48 to i64 
  %50 = inttoptr i64 %49 to i8* 
  %51 = inttoptr i64 %"$rec#0" to i8* 
  %52 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %50, i8*  %51, i32  %52, i32  8, i1  0)  
  %53 = add   i64 %49, 8 
  %54 = inttoptr i64 %53 to i64* 
  %55 = getelementptr  i64, i64* %54, i64 0 
  store  i64 %"$field#0", i64* %55 
  ret i64 %49 
}
--------------------------------------------------
 Module student.student
  public submods  : 
  public types    : 
  public resources: 
  public procs    : student.student.=<0>
                    student.student.id<0>
                    student.student.id<1>
                    student.student.major<0>
                    student.student.major<1>
                    student.student.student<0>
                    student.student.student<1>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:student.student, $right#0:student.student, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.student, 0:wybe.int, ?$left$id#0:wybe.int)
    foreign lpvm access(~$left#0:student.student, 8:wybe.int, ?$left$major#0:student.course)
    foreign lpvm access($right#0:student.student, 0:wybe.int, ?$right$id#0:wybe.int)
    foreign lpvm access(~$right#0:student.student, 8:wybe.int, ?$right$major#0:student.course)
    foreign llvm icmp eq(~$left$id#0:wybe.int, ~$right$id#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        student.course.course<1>(?tmp$12#0:wybe.int, ?tmp$13#0:wybe.string, ~$left$major#0:student.course)
        student.course.course<1>(?tmp$14#0:wybe.int, ?tmp$15#0:wybe.string, ~$right$major#0:student.course)
        wybe.int.=<0>(~tmp$12#0:wybe.int, ~tmp$14#0:wybe.int, ?tmp$16#0:wybe.bool)
        case ~tmp$16#0:wybe.bool of
        0:
            foreign llvm move(0:wybe.bool, ?tmp$3#0:wybe.bool)
            foreign llvm move(~tmp$3#0, ?$$#0:wybe.bool)

        1:
            wybe.string.=<0>(~tmp$13#0:wybe.string, ~tmp$15#0:wybe.string, ?tmp$3#0:wybe.bool)
            foreign llvm move(~tmp$3#0, ?$$#0:wybe.bool)




id > public inline (0 calls)
0: id($rec#0:student.student, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:student.student, 0:wybe.int, ?$#0:wybe.int)
id > public inline (0 calls)
1: id($rec#0:student.student, ?$rec#1:student.student, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:student.student, ?%$rec#1:student.student, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


major > public inline (0 calls)
0: major($rec#0:student.student, ?$#0:student.course): AliasPairs: []
    foreign lpvm access(~$rec#0:student.student, 8:wybe.int, ?$#0:student.course)
major > public inline (0 calls)
1: major($rec#0:student.student, ?$rec#1:student.student, $field#0:student.course): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:student.student, ?%$rec#1:student.student, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:student.course)


student > public inline (0 calls)
0: student(id#0:wybe.int, major#0:student.course, ?$#0:student.student): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:student.student)
    foreign lpvm mutate(~%$rec#0:student.student, ?%$rec#1:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~id#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:student.student, ?%$#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~major#0:student.course)
student > public inline (4 calls)
1: student(?id#0:wybe.int, ?major#0:student.course, $#0:student.student): AliasPairs: []
    foreign lpvm access($#0:student.student, 0:wybe.int, ?id#0:wybe.int)
    foreign lpvm access(~$#0:student.student, 8:wybe.int, ?major#0:student.course)

  LLVM code       :

; ModuleID = 'student.student'


 


declare external ccc  i1 @"wybe.string.=<0>"(i64, i64)    


declare external ccc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"student.student.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$2#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %15 = tail call ccc  {i64, i64}  @"student.course.course<1>"(i64  %7)  
  %16 = extractvalue {i64, i64} %15, 0 
  %17 = extractvalue {i64, i64} %15, 1 
  %18 = tail call ccc  {i64, i64}  @"student.course.course<1>"(i64  %14)  
  %19 = extractvalue {i64, i64} %18, 0 
  %20 = extractvalue {i64, i64} %18, 1 
  %"tmp$16#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %16, i64  %19)  
  br i1 %"tmp$16#0", label %if.then1, label %if.else1 
if.else:
  ret i1 0 
if.then1:
  %"tmp$3#0" = tail call ccc  i1  @"wybe.string.=<0>"(i64  %17, i64  %20)  
  ret i1 %"tmp$3#0" 
if.else1:
  ret i1 %"tmp$16#0" 
}


define external ccc  i64 @"student.student.id<0>"(i64  %"$rec#0")    {
entry:
  %21 = inttoptr i64 %"$rec#0" to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  ret i64 %23 
}


define external ccc  i64 @"student.student.id<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %24 = trunc i64 16 to i32  
  %25 = tail call ccc  i8*  @wybe_malloc(i32  %24)  
  %26 = ptrtoint i8* %25 to i64 
  %27 = inttoptr i64 %26 to i8* 
  %28 = inttoptr i64 %"$rec#0" to i8* 
  %29 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %27, i8*  %28, i32  %29, i32  8, i1  0)  
  %30 = inttoptr i64 %26 to i64* 
  %31 = getelementptr  i64, i64* %30, i64 0 
  store  i64 %"$field#0", i64* %31 
  ret i64 %26 
}


define external ccc  i64 @"student.student.major<0>"(i64  %"$rec#0")    {
entry:
  %32 = add   i64 %"$rec#0", 8 
  %33 = inttoptr i64 %32 to i64* 
  %34 = getelementptr  i64, i64* %33, i64 0 
  %35 = load  i64, i64* %34 
  ret i64 %35 
}


define external ccc  i64 @"student.student.major<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %36 = trunc i64 16 to i32  
  %37 = tail call ccc  i8*  @wybe_malloc(i32  %36)  
  %38 = ptrtoint i8* %37 to i64 
  %39 = inttoptr i64 %38 to i8* 
  %40 = inttoptr i64 %"$rec#0" to i8* 
  %41 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %39, i8*  %40, i32  %41, i32  8, i1  0)  
  %42 = add   i64 %38, 8 
  %43 = inttoptr i64 %42 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 0 
  store  i64 %"$field#0", i64* %44 
  ret i64 %38 
}


define external ccc  i64 @"student.student.student<0>"(i64  %"id#0", i64  %"major#0")    {
entry:
  %45 = trunc i64 16 to i32  
  %46 = tail call ccc  i8*  @wybe_malloc(i32  %45)  
  %47 = ptrtoint i8* %46 to i64 
  %48 = inttoptr i64 %47 to i64* 
  %49 = getelementptr  i64, i64* %48, i64 0 
  store  i64 %"id#0", i64* %49 
  %50 = add   i64 %47, 8 
  %51 = inttoptr i64 %50 to i64* 
  %52 = getelementptr  i64, i64* %51, i64 0 
  store  i64 %"major#0", i64* %52 
  ret i64 %47 
}


define external ccc  {i64, i64} @"student.student.student<1>"(i64  %"$#0")    {
entry:
  %53 = inttoptr i64 %"$#0" to i64* 
  %54 = getelementptr  i64, i64* %53, i64 0 
  %55 = load  i64, i64* %54 
  %56 = add   i64 %"$#0", 8 
  %57 = inttoptr i64 %56 to i64* 
  %58 = getelementptr  i64, i64* %57, i64 0 
  %59 = load  i64, i64* %58 
  %60 = insertvalue {i64, i64} undef, i64 %55, 0 
  %61 = insertvalue {i64, i64} %60, i64 %59, 1 
  ret {i64, i64} %61 
}
