======================================================================
AFTER EVERYTHING:
 Module alias_type4
  public submods  : 
  public types    : position: (alias_type4.position,Just address)
                    posrec: (alias_type4.posrec,Just address)
  public resources: 
  public procs    : alias_type4.<0>
                    alias_type4.foo<0>
                    alias_type4.position./=<0>
                    alias_type4.position.=<0>
                    alias_type4.position.position<0>
                    alias_type4.position.position<1>
                    alias_type4.position.x<0>
                    alias_type4.position.x<1>
                    alias_type4.position.y<0>
                    alias_type4.position.y<1>
                    alias_type4.posrec./=<0>
                    alias_type4.posrec.=<0>
                    alias_type4.posrec.a<0>
                    alias_type4.posrec.a<1>
                    alias_type4.posrec.p<0>
                    alias_type4.posrec.p<1>
                    alias_type4.posrec.posrec<0>
                    alias_type4.posrec.posrec<1>
  imports         : public use alias_type4.position
                    public use alias_type4.posrec
                    use wybe
  types           : position/public  is address { position(x:int, y:int) @alias_type4:2:25  }  @alias_type4:2:5, posrec/public  is address { posrec(p:position, a:int) @alias_type4:4:23  }  @alias_type4:4:5
  resources       : 
  submodules      : alias_type4.position, alias_type4.posrec
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:alias_type4.position)
    foreign lpvm mutate(~tmp$4#0:alias_type4.position, ?tmp$5#0:alias_type4.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 100:wybe.int)
    foreign lpvm mutate(~tmp$5#0:alias_type4.position, ?tmp$6#0:alias_type4.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 100:wybe.int)
    foreign lpvm alloc(16:wybe.int, ?tmp$9#0:alias_type4.posrec)
    foreign lpvm mutate(~tmp$9#0:alias_type4.posrec, ?tmp$10#0:alias_type4.posrec, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$6#0:alias_type4.position)
    foreign lpvm mutate(~tmp$10#0:alias_type4.posrec, ?tmp$11#0:alias_type4.posrec, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.int)
    alias_type4.foo<0>(~tmp$11#0:alias_type4.posrec, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @alias_type4:16:2


foo > public (1 calls)
0: foo(r1#0:alias_type4.posrec, io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    foreign lpvm access(~r1#0:alias_type4.posrec, 0:wybe.int, ?tmp$0#0:alias_type4.position)
    foreign lpvm mutate noalias(~tmp$0#0:alias_type4.position, ?%pos1#1:alias_type4.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, 1111:wybe.int)
    foreign lpvm access(~pos1#1:alias_type4.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#0:wybe.phantom, ?tmp$8#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$8#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'alias_type4'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_type4.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 100, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  store  i64 100, i64* %8 
  %9 = trunc i64 16 to i32  
  %10 = tail call ccc  i8*  @wybe_malloc(i32  %9)  
  %11 = ptrtoint i8* %10 to i64 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  store  i64 %3, i64* %13 
  %14 = add   i64 %11, 8 
  %15 = inttoptr i64 %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 1, i64* %16 
  tail call ccc  void  @"alias_type4.foo<0>"(i64  %11)  
  ret void 
}


define external ccc  void @"alias_type4.foo<0>"(i64  %"r1#0")    {
entry:
  %17 = inttoptr i64 %"r1#0" to i64* 
  %18 = getelementptr  i64, i64* %17, i64 0 
  %19 = load  i64, i64* %18 
  %20 = trunc i64 16 to i32  
  %21 = tail call ccc  i8*  @wybe_malloc(i32  %20)  
  %22 = ptrtoint i8* %21 to i64 
  %23 = inttoptr i64 %22 to i8* 
  %24 = inttoptr i64 %19 to i8* 
  %25 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %23, i8*  %24, i32  %25, i32  8, i1  0)  
  %26 = inttoptr i64 %22 to i64* 
  %27 = getelementptr  i64, i64* %26, i64 0 
  store  i64 1111, i64* %27 
  %28 = inttoptr i64 %22 to i64* 
  %29 = getelementptr  i64, i64* %28, i64 0 
  %30 = load  i64, i64* %29 
  tail call ccc  void  @print_int(i64  %30)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module alias_type4.position
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_type4.position./=<0>
                    alias_type4.position.=<0>
                    alias_type4.position.position<0>
                    alias_type4.position.position<1>
                    alias_type4.position.x<0>
                    alias_type4.position.x<1>
                    alias_type4.position.y<0>
                    alias_type4.position.y<1>
  imports         : use alias_type4
                    use wybe
  types           : 
  resources       : 
  procs           : 

/= > public inline test (0 calls)
0: /=($left#0:alias_type4.position, $right#0:alias_type4.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:alias_type4.position, 0:wybe.int, ?tmp$4#0:wybe.int)
    foreign lpvm access(~$left#0:alias_type4.position, 8:wybe.int, ?tmp$5#0:wybe.int)
    foreign lpvm access($right#0:alias_type4.position, 0:wybe.int, ?tmp$6#0:wybe.int)
    foreign lpvm access(~$right#0:alias_type4.position, 8:wybe.int, ?tmp$7#0:wybe.int)
    foreign llvm icmp eq(~tmp$4#0:wybe.int, ~tmp$6#0:wybe.int, ?tmp$8#0:wybe.bool) @wybe:nn:nn
    case ~tmp$8#0:wybe.bool of
    0:
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~tmp$5#0:wybe.int, ~tmp$7#0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:nn:nn
        case ~tmp$1#0:wybe.bool of
        0:
            foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)




= > public inline test (6 calls)
0: =($left#0:alias_type4.position, $right#0:alias_type4.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:alias_type4.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:alias_type4.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:alias_type4.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:alias_type4.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:alias_type4.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:!alias_type4.position)
    foreign lpvm mutate(~%$rec#0:alias_type4.position, ?%$rec#1:alias_type4.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:alias_type4.position, ?%$#0:alias_type4.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:alias_type4.position): AliasPairs: []
    foreign lpvm access($#0:alias_type4.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:alias_type4.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:alias_type4.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:alias_type4.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:alias_type4.position, ?$rec#1:alias_type4.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:alias_type4.position, ?%$rec#1:alias_type4.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:alias_type4.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:alias_type4.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:alias_type4.position, ?$rec#1:alias_type4.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:alias_type4.position, ?%$rec#1:alias_type4.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'alias_type4.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"alias_type4.position./=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$8#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$8#0", label %if.then, label %if.else 
if.then:
  %"tmp$1#0" = icmp eq i64 %7, %14 
  br i1 %"tmp$1#0", label %if.then1, label %if.else1 
if.else:
  ret i1 1 
if.then1:
  ret i1 0 
if.else1:
  ret i1 1 
}


define external ccc  i1 @"alias_type4.position.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %15 = inttoptr i64 %"$left#0" to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  %17 = load  i64, i64* %16 
  %18 = add   i64 %"$left#0", 8 
  %19 = inttoptr i64 %18 to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = inttoptr i64 %"$right#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 0 
  %24 = load  i64, i64* %23 
  %25 = add   i64 %"$right#0", 8 
  %26 = inttoptr i64 %25 to i64* 
  %27 = getelementptr  i64, i64* %26, i64 0 
  %28 = load  i64, i64* %27 
  %"tmp$2#0" = icmp eq i64 %17, %24 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %21, %28 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64 @"alias_type4.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %29 = trunc i64 16 to i32  
  %30 = tail call ccc  i8*  @wybe_malloc(i32  %29)  
  %31 = ptrtoint i8* %30 to i64 
  %32 = inttoptr i64 %31 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  store  i64 %"x#0", i64* %33 
  %34 = add   i64 %31, 8 
  %35 = inttoptr i64 %34 to i64* 
  %36 = getelementptr  i64, i64* %35, i64 0 
  store  i64 %"y#0", i64* %36 
  ret i64 %31 
}


define external ccc  {i64, i64} @"alias_type4.position.position<1>"(i64  %"$#0")    {
entry:
  %37 = inttoptr i64 %"$#0" to i64* 
  %38 = getelementptr  i64, i64* %37, i64 0 
  %39 = load  i64, i64* %38 
  %40 = add   i64 %"$#0", 8 
  %41 = inttoptr i64 %40 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  %43 = load  i64, i64* %42 
  %44 = insertvalue {i64, i64} undef, i64 %39, 0 
  %45 = insertvalue {i64, i64} %44, i64 %43, 1 
  ret {i64, i64} %45 
}


define external ccc  i64 @"alias_type4.position.x<0>"(i64  %"$rec#0")    {
entry:
  %46 = inttoptr i64 %"$rec#0" to i64* 
  %47 = getelementptr  i64, i64* %46, i64 0 
  %48 = load  i64, i64* %47 
  ret i64 %48 
}


define external ccc  i64 @"alias_type4.position.x<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %49 = trunc i64 16 to i32  
  %50 = tail call ccc  i8*  @wybe_malloc(i32  %49)  
  %51 = ptrtoint i8* %50 to i64 
  %52 = inttoptr i64 %51 to i8* 
  %53 = inttoptr i64 %"$rec#0" to i8* 
  %54 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %52, i8*  %53, i32  %54, i32  8, i1  0)  
  %55 = inttoptr i64 %51 to i64* 
  %56 = getelementptr  i64, i64* %55, i64 0 
  store  i64 %"$field#0", i64* %56 
  ret i64 %51 
}


define external ccc  i64 @"alias_type4.position.y<0>"(i64  %"$rec#0")    {
entry:
  %57 = add   i64 %"$rec#0", 8 
  %58 = inttoptr i64 %57 to i64* 
  %59 = getelementptr  i64, i64* %58, i64 0 
  %60 = load  i64, i64* %59 
  ret i64 %60 
}


define external ccc  i64 @"alias_type4.position.y<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %61 = trunc i64 16 to i32  
  %62 = tail call ccc  i8*  @wybe_malloc(i32  %61)  
  %63 = ptrtoint i8* %62 to i64 
  %64 = inttoptr i64 %63 to i8* 
  %65 = inttoptr i64 %"$rec#0" to i8* 
  %66 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %64, i8*  %65, i32  %66, i32  8, i1  0)  
  %67 = add   i64 %63, 8 
  %68 = inttoptr i64 %67 to i64* 
  %69 = getelementptr  i64, i64* %68, i64 0 
  store  i64 %"$field#0", i64* %69 
  ret i64 %63 
}
--------------------------------------------------
 Module alias_type4.posrec
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_type4.posrec./=<0>
                    alias_type4.posrec.=<0>
                    alias_type4.posrec.a<0>
                    alias_type4.posrec.a<1>
                    alias_type4.posrec.p<0>
                    alias_type4.posrec.p<1>
                    alias_type4.posrec.posrec<0>
                    alias_type4.posrec.posrec<1>
  imports         : use alias_type4
                    use wybe
  types           : 
  resources       : 
  procs           : 

/= > public inline test (0 calls)
0: /=($left#0:alias_type4.posrec, $right#0:alias_type4.posrec, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:alias_type4.posrec, 0:wybe.int, ?tmp$4#0:alias_type4.position)
    foreign lpvm access(~$left#0:alias_type4.posrec, 8:wybe.int, ?tmp$5#0:wybe.int)
    foreign lpvm access($right#0:alias_type4.posrec, 0:wybe.int, ?tmp$6#0:alias_type4.position)
    foreign lpvm access(~$right#0:alias_type4.posrec, 8:wybe.int, ?tmp$7#0:wybe.int)
    alias_type4.position.position<1>(?tmp$8#0:wybe.int, ?tmp$9#0:wybe.int, ~tmp$4#0:alias_type4.position)
    alias_type4.position.position<1>(?tmp$10#0:wybe.int, ?tmp$11#0:wybe.int, ~tmp$6#0:alias_type4.position)
    wybe.int.=<0>(~tmp$8#0:wybe.int, ~tmp$10#0:wybe.int, ?tmp$12#0:wybe.bool)
    case ~tmp$12#0:wybe.bool of
    0:
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

    1:
        wybe.int.=<0>(~tmp$9#0:wybe.int, ~tmp$11#0:wybe.int, ?tmp$13#0:wybe.bool)
        case ~tmp$13#0:wybe.bool of
        0:
            foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign llvm icmp eq(~tmp$5#0:wybe.int, ~tmp$7#0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:nn:nn
            case ~tmp$1#0:wybe.bool of
            0:
                foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

            1:
                foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)





= > public inline test (6 calls)
0: =($left#0:alias_type4.posrec, $right#0:alias_type4.posrec, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:alias_type4.posrec, 0:wybe.int, ?$left$p#0:alias_type4.position)
    foreign lpvm access(~$left#0:alias_type4.posrec, 8:wybe.int, ?$left$a#0:wybe.int)
    foreign lpvm access($right#0:alias_type4.posrec, 0:wybe.int, ?$right$p#0:alias_type4.position)
    foreign lpvm access(~$right#0:alias_type4.posrec, 8:wybe.int, ?$right$a#0:wybe.int)
    alias_type4.position.position<1>(?tmp$10#0:wybe.int, ?tmp$11#0:wybe.int, ~$left$p#0:alias_type4.position)
    alias_type4.position.position<1>(?tmp$12#0:wybe.int, ?tmp$13#0:wybe.int, ~$right$p#0:alias_type4.position)
    wybe.int.=<0>(~tmp$10#0:wybe.int, ~tmp$12#0:wybe.int, ?tmp$14#0:wybe.bool)
    case ~tmp$14#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        wybe.int.=<0>(~tmp$11#0:wybe.int, ~tmp$13#0:wybe.int, ?tmp$2#0:wybe.bool)
        case ~tmp$2#0:wybe.bool of
        0:
            foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign llvm icmp eq(~$left$a#0:wybe.int, ~$right$a#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn




a > public inline (0 calls)
0: a($rec#0:alias_type4.posrec, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:alias_type4.posrec, 8:wybe.int, ?$#0:wybe.int)
a > public inline (0 calls)
1: a($rec#0:alias_type4.posrec, ?$rec#1:alias_type4.posrec, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:alias_type4.posrec, ?%$rec#1:alias_type4.posrec, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


p > public inline (0 calls)
0: p($rec#0:alias_type4.posrec, ?$#0:alias_type4.position): AliasPairs: []
    foreign lpvm access(~$rec#0:alias_type4.posrec, 0:wybe.int, ?$#0:alias_type4.position)
p > public inline (0 calls)
1: p($rec#0:alias_type4.posrec, ?$rec#1:alias_type4.posrec, $field#0:alias_type4.position): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:alias_type4.posrec, ?%$rec#1:alias_type4.posrec, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:alias_type4.position)


posrec > public inline (0 calls)
0: posrec(p#0:alias_type4.position, a#0:wybe.int, ?$#0:alias_type4.posrec): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:!alias_type4.posrec)
    foreign lpvm mutate(~%$rec#0:alias_type4.posrec, ?%$rec#1:alias_type4.posrec, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~p#0:alias_type4.position)
    foreign lpvm mutate(~%$rec#1:alias_type4.posrec, ?%$#0:alias_type4.posrec, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~a#0:wybe.int)
posrec > public inline (4 calls)
1: posrec(?p#0:alias_type4.position, ?a#0:wybe.int, $#0:alias_type4.posrec): AliasPairs: []
    foreign lpvm access($#0:alias_type4.posrec, 0:wybe.int, ?p#0:alias_type4.position)
    foreign lpvm access(~$#0:alias_type4.posrec, 8:wybe.int, ?a#0:wybe.int)

  LLVM code       :

; ModuleID = 'alias_type4.posrec'


 


declare external ccc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"alias_type4.posrec./=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %15 = tail call ccc  {i64, i64}  @"alias_type4.position.position<1>"(i64  %3)  
  %16 = extractvalue {i64, i64} %15, 0 
  %17 = extractvalue {i64, i64} %15, 1 
  %18 = tail call ccc  {i64, i64}  @"alias_type4.position.position<1>"(i64  %10)  
  %19 = extractvalue {i64, i64} %18, 0 
  %20 = extractvalue {i64, i64} %18, 1 
  %"tmp$12#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %16, i64  %19)  
  br i1 %"tmp$12#0", label %if.then, label %if.else 
if.then:
  %"tmp$13#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %17, i64  %20)  
  br i1 %"tmp$13#0", label %if.then1, label %if.else1 
if.else:
  ret i1 1 
if.then1:
  %"tmp$1#0" = icmp eq i64 %7, %14 
  br i1 %"tmp$1#0", label %if.then2, label %if.else2 
if.else1:
  ret i1 1 
if.then2:
  ret i1 0 
if.else2:
  ret i1 1 
}


define external ccc  i1 @"alias_type4.posrec.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %21 = inttoptr i64 %"$left#0" to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  %24 = add   i64 %"$left#0", 8 
  %25 = inttoptr i64 %24 to i64* 
  %26 = getelementptr  i64, i64* %25, i64 0 
  %27 = load  i64, i64* %26 
  %28 = inttoptr i64 %"$right#0" to i64* 
  %29 = getelementptr  i64, i64* %28, i64 0 
  %30 = load  i64, i64* %29 
  %31 = add   i64 %"$right#0", 8 
  %32 = inttoptr i64 %31 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  %34 = load  i64, i64* %33 
  %35 = tail call ccc  {i64, i64}  @"alias_type4.position.position<1>"(i64  %23)  
  %36 = extractvalue {i64, i64} %35, 0 
  %37 = extractvalue {i64, i64} %35, 1 
  %38 = tail call ccc  {i64, i64}  @"alias_type4.position.position<1>"(i64  %30)  
  %39 = extractvalue {i64, i64} %38, 0 
  %40 = extractvalue {i64, i64} %38, 1 
  %"tmp$14#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %36, i64  %39)  
  br i1 %"tmp$14#0", label %if.then, label %if.else 
if.then:
  %"tmp$2#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %37, i64  %40)  
  br i1 %"tmp$2#0", label %if.then1, label %if.else1 
if.else:
  ret i1 0 
if.then1:
  %"$$#0" = icmp eq i64 %27, %34 
  ret i1 %"$$#0" 
if.else1:
  ret i1 0 
}


define external ccc  i64 @"alias_type4.posrec.a<0>"(i64  %"$rec#0")    {
entry:
  %41 = add   i64 %"$rec#0", 8 
  %42 = inttoptr i64 %41 to i64* 
  %43 = getelementptr  i64, i64* %42, i64 0 
  %44 = load  i64, i64* %43 
  ret i64 %44 
}


define external ccc  i64 @"alias_type4.posrec.a<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %45 = trunc i64 16 to i32  
  %46 = tail call ccc  i8*  @wybe_malloc(i32  %45)  
  %47 = ptrtoint i8* %46 to i64 
  %48 = inttoptr i64 %47 to i8* 
  %49 = inttoptr i64 %"$rec#0" to i8* 
  %50 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %48, i8*  %49, i32  %50, i32  8, i1  0)  
  %51 = add   i64 %47, 8 
  %52 = inttoptr i64 %51 to i64* 
  %53 = getelementptr  i64, i64* %52, i64 0 
  store  i64 %"$field#0", i64* %53 
  ret i64 %47 
}


define external ccc  i64 @"alias_type4.posrec.p<0>"(i64  %"$rec#0")    {
entry:
  %54 = inttoptr i64 %"$rec#0" to i64* 
  %55 = getelementptr  i64, i64* %54, i64 0 
  %56 = load  i64, i64* %55 
  ret i64 %56 
}


define external ccc  i64 @"alias_type4.posrec.p<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %57 = trunc i64 16 to i32  
  %58 = tail call ccc  i8*  @wybe_malloc(i32  %57)  
  %59 = ptrtoint i8* %58 to i64 
  %60 = inttoptr i64 %59 to i8* 
  %61 = inttoptr i64 %"$rec#0" to i8* 
  %62 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %60, i8*  %61, i32  %62, i32  8, i1  0)  
  %63 = inttoptr i64 %59 to i64* 
  %64 = getelementptr  i64, i64* %63, i64 0 
  store  i64 %"$field#0", i64* %64 
  ret i64 %59 
}


define external ccc  i64 @"alias_type4.posrec.posrec<0>"(i64  %"p#0", i64  %"a#0")    {
entry:
  %65 = trunc i64 16 to i32  
  %66 = tail call ccc  i8*  @wybe_malloc(i32  %65)  
  %67 = ptrtoint i8* %66 to i64 
  %68 = inttoptr i64 %67 to i64* 
  %69 = getelementptr  i64, i64* %68, i64 0 
  store  i64 %"p#0", i64* %69 
  %70 = add   i64 %67, 8 
  %71 = inttoptr i64 %70 to i64* 
  %72 = getelementptr  i64, i64* %71, i64 0 
  store  i64 %"a#0", i64* %72 
  ret i64 %67 
}


define external ccc  {i64, i64} @"alias_type4.posrec.posrec<1>"(i64  %"$#0")    {
entry:
  %73 = inttoptr i64 %"$#0" to i64* 
  %74 = getelementptr  i64, i64* %73, i64 0 
  %75 = load  i64, i64* %74 
  %76 = add   i64 %"$#0", 8 
  %77 = inttoptr i64 %76 to i64* 
  %78 = getelementptr  i64, i64* %77, i64 0 
  %79 = load  i64, i64* %78 
  %80 = insertvalue {i64, i64} undef, i64 %75, 0 
  %81 = insertvalue {i64, i64} %80, i64 %79, 1 
  ret {i64, i64} %81 
}
