======================================================================
AFTER EVERYTHING:
 Module alias_multifunc4
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_multifunc4.<0>
                    alias_multifunc4.replicate1<0>
                    alias_multifunc4.replicate21<0>
                    alias_multifunc4.replicate22<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:phantom, ?io#18:phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 10:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 10:wybe.int)
    alias_multifunc4.replicate1<0>(tmp$0#0:position.position, ?p2#0:position.position, ?p3#0:position.position, #io#0:phantom, ?_:phantom) @alias_multifunc4:36:2
    foreign c print_string("--- After calling replicate1:":wybe.string, ~#io#0:phantom, ?tmp$7#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$7#0:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string("expect p1(10,10):":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    position.printPosition<0>(~tmp$0#0:position.position, ~#io#3:phantom, ?#io#4:phantom) @alias_multifunc4:40:2
    foreign c print_string("expect p2(99,10):":wybe.string, ~#io#4:phantom, ?#io#5:phantom) @wybe:nn:nn
    position.printPosition<0>(~p2#0:position.position, ~#io#5:phantom, ?#io#6:phantom) @alias_multifunc4:42:2
    foreign c print_string("expect p3(10,10):":wybe.string, ~#io#6:phantom, ?#io#7:phantom) @wybe:nn:nn
    position.printPosition<0>(~p3#0:position.position, ~#io#7:phantom, ?#io#8:phantom) @alias_multifunc4:44:2
    alias_multifunc4.replicate21<0>(?p4#0:position.position, ~#io#8:phantom, ?#io#9:phantom) @alias_multifunc4:47:2
    foreign c print_string("--- After calling replicate21:":wybe.string, ~#io#9:phantom, ?tmp$16#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$16#0:phantom, ?#io#10:phantom) @wybe:nn:nn
    foreign c print_string("expect p4(99999,99999):":wybe.string, ~#io#10:phantom, ?#io#11:phantom) @wybe:nn:nn
    position.printPosition<0>(~p4#0:position.position, ~#io#11:phantom, ?#io#12:phantom) @alias_multifunc4:50:2
    alias_multifunc4.replicate22<0>(?p6#0:position.position, ?p7#0:position.position, ~#io#12:phantom, ?#io#13:phantom) @alias_multifunc4:53:2
    foreign c print_string("--- After calling replicate22:":wybe.string, ~#io#13:phantom, ?tmp$21#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$21#0:phantom, ?#io#14:phantom) @wybe:nn:nn
    foreign c print_string("expect p6(99999,99999):":wybe.string, ~#io#14:phantom, ?#io#15:phantom) @wybe:nn:nn
    position.printPosition<0>(~p6#0:position.position, ~#io#15:phantom, ?#io#16:phantom) @alias_multifunc4:56:2
    foreign c print_string("expect p7(1111111111,99999):":wybe.string, ~#io#16:phantom, ?#io#17:phantom) @wybe:nn:nn
    position.printPosition<0>(~p7#0:position.position, ~#io#17:phantom, ?#io#18:phantom) @alias_multifunc4:58:2


replicate1 > public (1 calls)
0: replicate1(pa#0:position.position, ?pb#1:position.position, ?pc#0:position.position, io#0:phantom, [?io#0:phantom]): AliasPairs: [(pa#0,pc#0)]
    foreign llvm move(pa#0:position.position, ?pc#0:position.position) @alias_multifunc4:8:5
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:position.position)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$5#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99:wybe.int)
    foreign lpvm mutate(~tmp$5#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99:wybe.int)
    foreign lpvm access(~tmp$0#0:position.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign lpvm mutate(~pa#0:position.position, ?%pb#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~tmp$1#0:wybe.int)


replicate21 > public (1 calls)
0: replicate21(?pb#0:position.position, io#0:phantom, ?io#2:phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign llvm move(tmp$0#0:position.position, ?pb#0:position.position) @alias_multifunc4:16:5
    foreign lpvm mutate(~tmp$0#0:position.position, ?%pc#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 1111111111:wybe.int)
    foreign c print_string("--- Inside replicate21, expect pc(1111111111,99999): ":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    position.printPosition<0>(~pc#1:position.position, ~#io#1:phantom, ?#io#2:phantom) @alias_multifunc4:20:6


replicate22 > public (1 calls)
0: replicate22(?pb#0:position.position, ?pc#1:position.position, io#0:phantom, ?io#4:phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 99999:wybe.int)
    foreign llvm move(tmp$0#0:position.position, ?pb#0:position.position) @alias_multifunc4:25:5
    foreign c print_string("--- Inside replicate22, expect pc(99999,99999):":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    position.printPosition<0>(tmp$0#0:position.position, ~#io#1:phantom, ?#io#2:phantom) @alias_multifunc4:28:6
    foreign lpvm mutate(~tmp$0#0:position.position, ?%pc#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 1111111111:wybe.int)
    foreign c print_string("--- Inside replicate22, after calling x(!pc,1111111111), expect pc(1111111111,99999): ":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    position.printPosition<0>(pc#1:position.position, ~#io#3:phantom, ?#io#4:phantom) @alias_multifunc4:32:6

  LLVM code       :

; ModuleID = 'alias_multifunc4'


 


declare external ccc  void @"position.printPosition<0>"(i64*)    


declare external ccc  void @print_string(i8*)    


declare external ccc  void @putchar(i8)    


@alias_multifunc4.21 =    constant [29 x i8] c"expect p7(1111111111,99999):\00"


@alias_multifunc4.20 =    constant [24 x i8] c"expect p6(99999,99999):\00"


@alias_multifunc4.19 =    constant [31 x i8] c"--- After calling replicate22:\00"


@alias_multifunc4.15 =    constant [24 x i8] c"expect p4(99999,99999):\00"


@alias_multifunc4.14 =    constant [31 x i8] c"--- After calling replicate21:\00"


@alias_multifunc4.13 =    constant [18 x i8] c"expect p3(10,10):\00"


@alias_multifunc4.12 =    constant [18 x i8] c"expect p2(99,10):\00"


@alias_multifunc4.11 =    constant [18 x i8] c"expect p1(10,10):\00"


@alias_multifunc4.10 =    constant [30 x i8] c"--- After calling replicate1:\00"


@alias_multifunc4.51 =    constant [54 x i8] c"--- Inside replicate21, expect pc(1111111111,99999): \00"


@alias_multifunc4.65 =    constant [87 x i8] c"--- Inside replicate22, after calling x(!pc,1111111111), expect pc(1111111111,99999): \00"


@alias_multifunc4.58 =    constant [48 x i8] c"--- Inside replicate22, expect pc(99999,99999):\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_multifunc4.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %2 = bitcast i8* %1 to i64* 
  %3 = bitcast i64* %2 to i64* 
  %4 = getelementptr  i64, i64* %3, i64 0 
  store  i64 10, i64* %4 
  %5 = bitcast i64* %2 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 1 
  store  i64 10, i64* %6 
  %7 = tail call ccc  {i64*, i64*}  @"alias_multifunc4.replicate1<0>"(i64*  %2)  
  %8 = extractvalue {i64*, i64*} %7, 0 
  %9 = extractvalue {i64*, i64*} %7, 1 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([30 x i8], [30 x i8]* @alias_multifunc4.10, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.11, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %2)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.12, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %8)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([18 x i8], [18 x i8]* @alias_multifunc4.13, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %9)  
  %"p4#0" = tail call ccc  i64*  @"alias_multifunc4.replicate21<0>"()  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([31 x i8], [31 x i8]* @alias_multifunc4.14, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([24 x i8], [24 x i8]* @alias_multifunc4.15, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %"p4#0")  
  %16 = tail call ccc  {i64*, i64*}  @"alias_multifunc4.replicate22<0>"()  
  %17 = extractvalue {i64*, i64*} %16, 0 
  %18 = extractvalue {i64*, i64*} %16, 1 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([31 x i8], [31 x i8]* @alias_multifunc4.19, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([24 x i8], [24 x i8]* @alias_multifunc4.20, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %17)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([29 x i8], [29 x i8]* @alias_multifunc4.21, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %18)  
  ret void 
}


define external ccc  {i64*, i64*} @"alias_multifunc4.replicate1<0>"(i64*  %"pa#0")    {
entry:
  %22 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %23 = bitcast i8* %22 to i64* 
  %24 = bitcast i64* %23 to i64* 
  %25 = getelementptr  i64, i64* %24, i64 0 
  store  i64 99, i64* %25 
  %26 = bitcast i64* %23 to i64* 
  %27 = getelementptr  i64, i64* %26, i64 1 
  store  i64 99, i64* %27 
  %28 = bitcast i64* %23 to i64* 
  %29 = getelementptr  i64, i64* %28, i64 0 
  %30 = load  i64, i64* %29 
  %31 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %32 = bitcast i8* %31 to i64* 
  %33 = bitcast i64* %32 to i8* 
  %34 = bitcast i64* %"pa#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %33, i8*  %34, i32  16, i32  8, i1  0)  
  %35 = bitcast i64* %32 to i64* 
  %36 = getelementptr  i64, i64* %35, i64 0 
  store  i64 %30, i64* %36 
  %37 = insertvalue {i64*, i64*} undef, i64* %32, 0 
  %38 = insertvalue {i64*, i64*} %37, i64* %"pa#0", 1 
  ret {i64*, i64*} %38 
}


define external ccc  i64* @"alias_multifunc4.replicate21<0>"()    {
entry:
  %39 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %40 = bitcast i8* %39 to i64* 
  %41 = bitcast i64* %40 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  store  i64 99999, i64* %42 
  %43 = bitcast i64* %40 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 1 
  store  i64 99999, i64* %44 
  %45 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %46 = bitcast i8* %45 to i64* 
  %47 = bitcast i64* %46 to i8* 
  %48 = bitcast i64* %40 to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %47, i8*  %48, i32  16, i32  8, i1  0)  
  %49 = bitcast i64* %46 to i64* 
  %50 = getelementptr  i64, i64* %49, i64 0 
  store  i64 1111111111, i64* %50 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([54 x i8], [54 x i8]* @alias_multifunc4.51, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %46)  
  ret i64* %40 
}


define external ccc  {i64*, i64*} @"alias_multifunc4.replicate22<0>"()    {
entry:
  %52 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %53 = bitcast i8* %52 to i64* 
  %54 = bitcast i64* %53 to i64* 
  %55 = getelementptr  i64, i64* %54, i64 0 
  store  i64 99999, i64* %55 
  %56 = bitcast i64* %53 to i64* 
  %57 = getelementptr  i64, i64* %56, i64 1 
  store  i64 99999, i64* %57 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([48 x i8], [48 x i8]* @alias_multifunc4.58, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %53)  
  %59 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %60 = bitcast i8* %59 to i64* 
  %61 = bitcast i64* %60 to i8* 
  %62 = bitcast i64* %53 to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %61, i8*  %62, i32  16, i32  8, i1  0)  
  %63 = bitcast i64* %60 to i64* 
  %64 = getelementptr  i64, i64* %63, i64 0 
  store  i64 1111111111, i64* %64 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([87 x i8], [87 x i8]* @alias_multifunc4.65, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %60)  
  %66 = insertvalue {i64*, i64*} undef, i64* %53, 0 
  %67 = insertvalue {i64*, i64*} %66, i64* %60, 1 
  ret {i64*, i64*} %67 
}
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,"pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:5
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, io#0:phantom, ?io#5:phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string(",":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#3:phantom, ?#io#4:phantom) @wybe:nn:nn
    foreign c print_string(")":wybe.string, ~#io#4:phantom, ?tmp$14#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$14#0:phantom, ?#io#5:phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i8*)    


declare external ccc  void @print_int(i64)    


@position.9 =    constant [2 x i8] c")\00"


@position.5 =    constant [2 x i8] c",\00"


@position.1 =    constant [3 x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"position.printPosition<0>"(i64*  %"pos#0")    {
entry:
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i32 0, i32 0))  
  %2 = bitcast i64* %"pos#0" to i64* 
  %3 = getelementptr  i64, i64* %2, i64 0 
  %4 = load  i64, i64* %3 
  tail call ccc  void  @print_int(i64  %4)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.5, i32 0, i32 0))  
  %6 = bitcast i64* %"pos#0" to i64* 
  %7 = getelementptr  i64, i64* %6, i64 1 
  %8 = load  i64, i64* %7 
  tail call ccc  void  @print_int(i64  %8)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.9, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"position.position.=<0>"(i64*  %"$left#0", i64*  %"$right#0")    {
entry:
  %1 = bitcast i64* %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = bitcast i64* %"$left#0" to i64* 
  %5 = getelementptr  i64, i64* %4, i64 1 
  %6 = load  i64, i64* %5 
  %7 = bitcast i64* %"$right#0" to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %9 = load  i64, i64* %8 
  %10 = bitcast i64* %"$right#0" to i64* 
  %11 = getelementptr  i64, i64* %10, i64 1 
  %12 = load  i64, i64* %11 
  %"tmp$2#0" = icmp eq i64 %3, %9 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %6, %12 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64* @"position.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %13 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %14 = bitcast i8* %13 to i64* 
  %15 = bitcast i64* %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 %"x#0", i64* %16 
  %17 = bitcast i64* %14 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 1 
  store  i64 %"y#0", i64* %18 
  ret i64* %14 
}


define external ccc  {i64, i64} @"position.position.position<1>"(i64*  %"$#0")    {
entry:
  %19 = bitcast i64* %"$#0" to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = bitcast i64* %"$#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 1 
  %24 = load  i64, i64* %23 
  %25 = insertvalue {i64, i64} undef, i64 %21, 0 
  %26 = insertvalue {i64, i64} %25, i64 %24, 1 
  ret {i64, i64} %26 
}


define external ccc  i64 @"position.position.x<0>"(i64*  %"$rec#0")    {
entry:
  %27 = bitcast i64* %"$rec#0" to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  ret i64 %29 
}


define external ccc  i64* @"position.position.x<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %30 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %31 = bitcast i8* %30 to i64* 
  %32 = bitcast i64* %31 to i8* 
  %33 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %32, i8*  %33, i32  16, i32  8, i1  0)  
  %34 = bitcast i64* %31 to i64* 
  %35 = getelementptr  i64, i64* %34, i64 0 
  store  i64 %"$field#0", i64* %35 
  ret i64* %31 
}


define external ccc  i64 @"position.position.y<0>"(i64*  %"$rec#0")    {
entry:
  %36 = bitcast i64* %"$rec#0" to i64* 
  %37 = getelementptr  i64, i64* %36, i64 1 
  %38 = load  i64, i64* %37 
  ret i64 %38 
}


define external ccc  i64* @"position.position.y<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %39 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %40 = bitcast i8* %39 to i64* 
  %41 = bitcast i64* %40 to i8* 
  %42 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %41, i8*  %42, i32  16, i32  8, i1  0)  
  %43 = bitcast i64* %40 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 1 
  store  i64 %"$field#0", i64* %44 
  ret i64* %40 
}
