======================================================================
AFTER EVERYTHING:
 Module alias_scc_proc
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_scc_proc.<0>
                    alias_scc_proc.bar<0>
                    alias_scc_proc.foo<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:phantom, ?io#8:phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 1:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 1:wybe.int)
    alias_scc_proc.foo<0>(tmp$0#0:position.position, ?p2#0:position.position, ?p3#0:position.position, ~#io#0:phantom, ?#io#1:phantom) @alias_scc_proc:29:2
    foreign c print_string("--- After calling foo: ":wybe.string, ~#io#1:phantom, ?tmp$7#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$7#0:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string("expect p1(2,2):":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    position.printPosition<0>(~tmp$0#0:position.position, ~#io#3:phantom, ?#io#4:phantom) @alias_scc_proc:33:2
    foreign c print_string("expect p2(2,2):":wybe.string, ~#io#4:phantom, ?#io#5:phantom) @wybe:nn:nn
    position.printPosition<0>(~p2#0:position.position, ~#io#5:phantom, ?#io#6:phantom) @alias_scc_proc:35:2
    foreign c print_string("expect p3(3,3):":wybe.string, ~#io#6:phantom, ?#io#7:phantom) @wybe:nn:nn
    position.printPosition<0>(~p3#0:position.position, ~#io#7:phantom, ?#io#8:phantom) @alias_scc_proc:37:2


bar > public (1 calls)
0: bar(p1#0:position.position, ?p3#0:position.position, io#0:phantom, ?io#1:phantom): AliasPairs: [(p1#0,p3#0)]
    foreign lpvm access(p1#0:position.position, 8:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.bool) @wybe:nn:nn
    case ~tmp$3#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$2#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate(~%p1#0:position.position, ?%p1#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~tmp$2#0:wybe.int)
        foreign llvm move(p1#1:position.position, ?p3#0:position.position) @alias_scc_proc:23:15
        alias_scc_proc.foo<0>(~p1#1:position.position, ?p2#0:position.position, ?p3#1:position.position, ~#io#0:phantom, ?#io#1:phantom) @alias_scc_proc:24:16

    1:
        foreign llvm move(~p1#0:position.position, ?p3#0:position.position) @alias_scc_proc:20:20
        foreign llvm move(~io#0:phantom, ?io#1:phantom)



foo > public (2 calls)
0: foo(p1#0:position.position, ?p2#0:position.position, ?p3#0:position.position, io#0:phantom, ?io#2:phantom): AliasPairs: [(p1#0,p2#0)]
    foreign lpvm access(p1#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$5#0:wybe.bool) @wybe:nn:nn
    case ~tmp$5#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate(~%p1#0:position.position, ?%p1#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~tmp$3#0:wybe.int)
        alias_scc_proc.bar<0>(~p1#1:position.position, ?p3#0:position.position, ~#io#0:phantom, ?#io#2:phantom) @alias_scc_proc:13:16
        foreign lpvm alloc(16:wybe.int, ?tmp$17#0:position.position)
        foreign lpvm mutate(~tmp$17#0:position.position, ?tmp$18#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 2:wybe.int)
        foreign lpvm mutate(~tmp$18#0:position.position, ?p2#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 2:wybe.int)

    1:
        foreign llvm move(~p1#0:position.position, ?p2#0:position.position) @alias_scc_proc:7:20
        foreign lpvm alloc(16:wybe.int, ?tmp$12#0:position.position)
        foreign lpvm mutate(~tmp$12#0:position.position, ?tmp$13#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 3:wybe.int)
        foreign lpvm mutate(~tmp$13#0:position.position, ?tmp$1#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 3:wybe.int)
        foreign llvm move(tmp$1#0:position.position, ?p3#0:position.position) @alias_scc_proc:8:21
        foreign c print_string("--- Inside foo: expect p3(3,3):":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
        position.printPosition<0>(~tmp$1#0:position.position, ~#io#1:phantom, ?#io#2:phantom) @alias_scc_proc:10:22


  LLVM code       :

; ModuleID = 'alias_scc_proc'


 


declare external ccc  void @"position.printPosition<0>"(i64*)    


declare external ccc  void @print_string(i8*)    


declare external ccc  void @putchar(i8)    


@alias_scc_proc.13 =    constant [16 x i8] c"expect p3(3,3):\00"


@alias_scc_proc.12 =    constant [16 x i8] c"expect p2(2,2):\00"


@alias_scc_proc.11 =    constant [16 x i8] c"expect p1(2,2):\00"


@alias_scc_proc.10 =    constant [24 x i8] c"--- After calling foo: \00"


@alias_scc_proc.35 =    constant [32 x i8] c"--- Inside foo: expect p3(3,3):\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_scc_proc.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %2 = bitcast i8* %1 to i64* 
  %3 = bitcast i64* %2 to i64* 
  %4 = getelementptr  i64, i64* %3, i64 0 
  store  i64 1, i64* %4 
  %5 = bitcast i64* %2 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 1 
  store  i64 1, i64* %6 
  %7 = tail call ccc  {i64*, i64*}  @"alias_scc_proc.foo<0>"(i64*  %2)  
  %8 = extractvalue {i64*, i64*} %7, 0 
  %9 = extractvalue {i64*, i64*} %7, 1 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([24 x i8], [24 x i8]* @alias_scc_proc.10, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.11, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %2)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.12, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %8)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.13, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %9)  
  ret void 
}


define external ccc  i64* @"alias_scc_proc.bar<0>"(i64*  %"p1#0")    {
entry:
  %14 = bitcast i64* %"p1#0" to i64* 
  %15 = getelementptr  i64, i64* %14, i64 1 
  %16 = load  i64, i64* %15 
  %"tmp$3#0" = icmp sgt i64 %16, 1 
  br i1 %"tmp$3#0", label %if.then, label %if.else 
if.then:
  ret i64* %"p1#0" 
if.else:
  %"tmp$2#0" = add   i64 %16, 1 
  %17 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %18 = bitcast i8* %17 to i64* 
  %19 = bitcast i64* %18 to i8* 
  %20 = bitcast i64* %"p1#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %19, i8*  %20, i32  16, i32  8, i1  0)  
  %21 = bitcast i64* %18 to i64* 
  %22 = getelementptr  i64, i64* %21, i64 1 
  store  i64 %"tmp$2#0", i64* %22 
  %23 = tail call ccc  {i64*, i64*}  @"alias_scc_proc.foo<0>"(i64*  %18)  
  %24 = extractvalue {i64*, i64*} %23, 0 
  %25 = extractvalue {i64*, i64*} %23, 1 
  ret i64* %25 
}


define external ccc  {i64*, i64*} @"alias_scc_proc.foo<0>"(i64*  %"p1#0")    {
entry:
  %26 = bitcast i64* %"p1#0" to i64* 
  %27 = getelementptr  i64, i64* %26, i64 0 
  %28 = load  i64, i64* %27 
  %"tmp$5#0" = icmp sgt i64 %28, 1 
  br i1 %"tmp$5#0", label %if.then, label %if.else 
if.then:
  %29 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %30 = bitcast i8* %29 to i64* 
  %31 = bitcast i64* %30 to i64* 
  %32 = getelementptr  i64, i64* %31, i64 0 
  store  i64 3, i64* %32 
  %33 = bitcast i64* %30 to i64* 
  %34 = getelementptr  i64, i64* %33, i64 1 
  store  i64 3, i64* %34 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([32 x i8], [32 x i8]* @alias_scc_proc.35, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %30)  
  %36 = insertvalue {i64*, i64*} undef, i64* %"p1#0", 0 
  %37 = insertvalue {i64*, i64*} %36, i64* %30, 1 
  %38 = insertvalue {i64*, i64*} undef, i64* %"p1#0", 0 
  %39 = insertvalue {i64*, i64*} %38, i64* %30, 1 
  ret {i64*, i64*} %39 
if.else:
  %"tmp$3#0" = add   i64 %28, 1 
  %40 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %41 = bitcast i8* %40 to i64* 
  %42 = bitcast i64* %41 to i8* 
  %43 = bitcast i64* %"p1#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %42, i8*  %43, i32  16, i32  8, i1  0)  
  %44 = bitcast i64* %41 to i64* 
  %45 = getelementptr  i64, i64* %44, i64 0 
  store  i64 %"tmp$3#0", i64* %45 
  %"p3#0" = tail call ccc  i64*  @"alias_scc_proc.bar<0>"(i64*  %41)  
  %46 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %47 = bitcast i8* %46 to i64* 
  %48 = bitcast i64* %47 to i64* 
  %49 = getelementptr  i64, i64* %48, i64 0 
  store  i64 2, i64* %49 
  %50 = bitcast i64* %47 to i64* 
  %51 = getelementptr  i64, i64* %50, i64 1 
  store  i64 2, i64* %51 
  %52 = insertvalue {i64*, i64*} undef, i64* %47, 0 
  %53 = insertvalue {i64*, i64*} %52, i64* %"p3#0", 1 
  ret i64* %47 
}
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,Just "pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:8
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, io#0:phantom, ?io#5:phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string(",":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#3:phantom, ?#io#4:phantom) @wybe:nn:nn
    foreign c print_string(")":wybe.string, ~#io#4:phantom, ?tmp$14#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$14#0:phantom, ?#io#5:phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i8*)    


declare external ccc  void @print_int(i64)    


@position.9 =    constant [2 x i8] c")\00"


@position.5 =    constant [2 x i8] c",\00"


@position.1 =    constant [3 x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"position.printPosition<0>"(i64*  %"pos#0")    {
entry:
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i32 0, i32 0))  
  %2 = bitcast i64* %"pos#0" to i64* 
  %3 = getelementptr  i64, i64* %2, i64 0 
  %4 = load  i64, i64* %3 
  tail call ccc  void  @print_int(i64  %4)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.5, i32 0, i32 0))  
  %6 = bitcast i64* %"pos#0" to i64* 
  %7 = getelementptr  i64, i64* %6, i64 1 
  %8 = load  i64, i64* %7 
  tail call ccc  void  @print_int(i64  %8)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.9, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"position.position.=<0>"(i64*  %"$left#0", i64*  %"$right#0")    {
entry:
  %1 = bitcast i64* %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = bitcast i64* %"$left#0" to i64* 
  %5 = getelementptr  i64, i64* %4, i64 1 
  %6 = load  i64, i64* %5 
  %7 = bitcast i64* %"$right#0" to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %9 = load  i64, i64* %8 
  %10 = bitcast i64* %"$right#0" to i64* 
  %11 = getelementptr  i64, i64* %10, i64 1 
  %12 = load  i64, i64* %11 
  %"tmp$2#0" = icmp eq i64 %3, %9 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %6, %12 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64* @"position.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %13 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %14 = bitcast i8* %13 to i64* 
  %15 = bitcast i64* %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 %"x#0", i64* %16 
  %17 = bitcast i64* %14 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 1 
  store  i64 %"y#0", i64* %18 
  ret i64* %14 
}


define external ccc  {i64, i64} @"position.position.position<1>"(i64*  %"$#0")    {
entry:
  %19 = bitcast i64* %"$#0" to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = bitcast i64* %"$#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 1 
  %24 = load  i64, i64* %23 
  %25 = insertvalue {i64, i64} undef, i64 %21, 0 
  %26 = insertvalue {i64, i64} %25, i64 %24, 1 
  ret {i64, i64} %26 
}


define external ccc  i64 @"position.position.x<0>"(i64*  %"$rec#0")    {
entry:
  %27 = bitcast i64* %"$rec#0" to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  ret i64 %29 
}


define external ccc  i64* @"position.position.x<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %30 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %31 = bitcast i8* %30 to i64* 
  %32 = bitcast i64* %31 to i8* 
  %33 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %32, i8*  %33, i32  16, i32  8, i1  0)  
  %34 = bitcast i64* %31 to i64* 
  %35 = getelementptr  i64, i64* %34, i64 0 
  store  i64 %"$field#0", i64* %35 
  ret i64* %31 
}


define external ccc  i64 @"position.position.y<0>"(i64*  %"$rec#0")    {
entry:
  %36 = bitcast i64* %"$rec#0" to i64* 
  %37 = getelementptr  i64, i64* %36, i64 1 
  %38 = load  i64, i64* %37 
  ret i64 %38 
}


define external ccc  i64* @"position.position.y<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %39 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %40 = bitcast i8* %39 to i64* 
  %41 = bitcast i64* %40 to i8* 
  %42 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %41, i8*  %42, i32  16, i32  8, i1  0)  
  %43 = bitcast i64* %40 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 1 
  store  i64 %"$field#0", i64* %44 
  ret i64* %40 
}
