======================================================================
AFTER EVERYTHING:
 Module alias_mbar
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_mbar.bar<0>
  imports         : use alias_mfoo
                    use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

bar > public (0 calls)
0: bar(p1#0:position.position, ?p3#0:position.position, io#0:phantom, ?io#1:phantom): AliasPairs: [(p1#0,p3#0)]
    foreign lpvm access(p1#0:position.position, 8:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.bool) @wybe:nn:nn
    case ~tmp$3#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$2#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate(~%p1#0:position.position, ?%p1#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~tmp$2#0:wybe.int)
        foreign llvm move(p1#1:position.position, ?p3#0:position.position) @alias_mbar:12:12
        alias_mfoo.foo<0>(~p1#1:position.position, ?p2#0:position.position, ?p3#1:position.position, ~#io#0:phantom, ?#io#1:phantom) @alias_mbar:13:13

    1:
        foreign llvm move(~p1#0:position.position, ?p3#0:position.position) @alias_mbar:8:22
        foreign llvm move(~io#0:phantom, ?io#1:phantom)


  LLVM code       :

; ModuleID = 'alias_mbar'


 


declare external ccc  {i64*, i64*} @"alias_mfoo.foo<0>"(i64*)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i64* @"alias_mbar.bar<0>"(i64*  %"p1#0")    {
entry:
  %1 = bitcast i64* %"p1#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 1 
  %3 = load  i64, i64* %2 
  %"tmp$3#0" = icmp sgt i64 %3, 1 
  br i1 %"tmp$3#0", label %if.then, label %if.else 
if.then:
  ret i64* %"p1#0" 
if.else:
  %"tmp$2#0" = add   i64 %3, 1 
  %4 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %5 = bitcast i8* %4 to i64* 
  %6 = bitcast i64* %5 to i8* 
  %7 = bitcast i64* %"p1#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %6, i8*  %7, i32  16, i32  8, i1  0)  
  %8 = bitcast i64* %5 to i64* 
  %9 = getelementptr  i64, i64* %8, i64 1 
  store  i64 %"tmp$2#0", i64* %9 
  %10 = tail call ccc  {i64*, i64*}  @"alias_mfoo.foo<0>"(i64*  %5)  
  %11 = extractvalue {i64*, i64*} %10, 0 
  %12 = extractvalue {i64*, i64*} %10, 1 
  ret i64* %12 
}
--------------------------------------------------
 Module alias_mfoo
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_mfoo.foo<0>
  imports         : use alias_mbar
                    use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

foo > public (0 calls)
0: foo(p1#0:position.position, ?p2#0:position.position, ?p3#0:position.position, io#0:phantom, ?io#2:phantom): AliasPairs: [(p1#0,p2#0)]
    foreign lpvm access(p1#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$5#0:wybe.bool) @wybe:nn:nn
    case ~tmp$5#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate(~%p1#0:position.position, ?%p1#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~tmp$3#0:wybe.int)
        alias_mbar.bar<0>(~p1#1:position.position, ?p3#0:position.position, ~#io#0:phantom, ?#io#2:phantom) @alias_mfoo:15:14
        foreign lpvm alloc(16:wybe.int, ?tmp$17#0:position.position)
        foreign lpvm mutate(~tmp$17#0:position.position, ?tmp$18#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 2:wybe.int)
        foreign lpvm mutate(~tmp$18#0:position.position, ?p2#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 2:wybe.int)

    1:
        foreign llvm move(~p1#0:position.position, ?p2#0:position.position) @alias_mfoo:9:13
        foreign lpvm alloc(16:wybe.int, ?tmp$12#0:position.position)
        foreign lpvm mutate(~tmp$12#0:position.position, ?tmp$13#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 3:wybe.int)
        foreign lpvm mutate(~tmp$13#0:position.position, ?tmp$1#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 3:wybe.int)
        foreign llvm move(tmp$1#0:position.position, ?p3#0:position.position) @alias_mfoo:10:13
        foreign c print_string("p3:":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
        position.printPosition<0>(~tmp$1#0:position.position, ~#io#1:phantom, ?#io#2:phantom) @alias_mfoo:12:14


  LLVM code       :

; ModuleID = 'alias_mfoo'


 


declare external ccc  i64* @"alias_mbar.bar<0>"(i64*)    


declare external ccc  void @"position.printPosition<0>"(i64*)    


declare external ccc  void @print_string(i8*)    


@alias_mfoo.10 =    constant [4 x i8] c"p3:\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  {i64*, i64*} @"alias_mfoo.foo<0>"(i64*  %"p1#0")    {
entry:
  %1 = bitcast i64* %"p1#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %"tmp$5#0" = icmp sgt i64 %3, 1 
  br i1 %"tmp$5#0", label %if.then, label %if.else 
if.then:
  %4 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %5 = bitcast i8* %4 to i64* 
  %6 = bitcast i64* %5 to i64* 
  %7 = getelementptr  i64, i64* %6, i64 0 
  store  i64 3, i64* %7 
  %8 = bitcast i64* %5 to i64* 
  %9 = getelementptr  i64, i64* %8, i64 1 
  store  i64 3, i64* %9 
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([4 x i8], [4 x i8]* @alias_mfoo.10, i32 0, i32 0))  
  tail call ccc  void  @"position.printPosition<0>"(i64*  %5)  
  %11 = insertvalue {i64*, i64*} undef, i64* %"p1#0", 0 
  %12 = insertvalue {i64*, i64*} %11, i64* %5, 1 
  %13 = insertvalue {i64*, i64*} undef, i64* %"p1#0", 0 
  %14 = insertvalue {i64*, i64*} %13, i64* %5, 1 
  ret {i64*, i64*} %14 
if.else:
  %"tmp$3#0" = add   i64 %3, 1 
  %15 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %16 = bitcast i8* %15 to i64* 
  %17 = bitcast i64* %16 to i8* 
  %18 = bitcast i64* %"p1#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %17, i8*  %18, i32  16, i32  8, i1  0)  
  %19 = bitcast i64* %16 to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  store  i64 %"tmp$3#0", i64* %20 
  %"p3#0" = tail call ccc  i64*  @"alias_mbar.bar<0>"(i64*  %16)  
  %21 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %22 = bitcast i8* %21 to i64* 
  %23 = bitcast i64* %22 to i64* 
  %24 = getelementptr  i64, i64* %23, i64 0 
  store  i64 2, i64* %24 
  %25 = bitcast i64* %22 to i64* 
  %26 = getelementptr  i64, i64* %25, i64 1 
  store  i64 2, i64* %26 
  %27 = insertvalue {i64*, i64*} undef, i64* %22, 0 
  %28 = insertvalue {i64*, i64*} %27, i64* %"p3#0", 1 
  ret i64* %22 
}
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,"pointer")
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:8
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, io#0:phantom, ?io#5:phantom): AliasPairs: []
    foreign c print_string(" (":wybe.string, ~#io#0:phantom, ?#io#1:phantom) @wybe:nn:nn
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:phantom, ?#io#2:phantom) @wybe:nn:nn
    foreign c print_string(",":wybe.string, ~#io#2:phantom, ?#io#3:phantom) @wybe:nn:nn
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#3:phantom, ?#io#4:phantom) @wybe:nn:nn
    foreign c print_string(")":wybe.string, ~#io#4:phantom, ?tmp$14#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$14#0:phantom, ?#io#5:phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i8*)    


declare external ccc  void @print_int(i64)    


@position.9 =    constant [2 x i8] c")\00"


@position.5 =    constant [2 x i8] c",\00"


@position.1 =    constant [3 x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"position.printPosition<0>"(i64*  %"pos#0")    {
entry:
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i32 0, i32 0))  
  %2 = bitcast i64* %"pos#0" to i64* 
  %3 = getelementptr  i64, i64* %2, i64 0 
  %4 = load  i64, i64* %3 
  tail call ccc  void  @print_int(i64  %4)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.5, i32 0, i32 0))  
  %6 = bitcast i64* %"pos#0" to i64* 
  %7 = getelementptr  i64, i64* %6, i64 1 
  %8 = load  i64, i64* %7 
  tail call ccc  void  @print_int(i64  %8)  
  tail call ccc  void  @print_string(i8*  getelementptr inbounds ([2 x i8], [2 x i8]* @position.9, i32 0, i32 0))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): AliasPairs: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"position.position.=<0>"(i64*  %"$left#0", i64*  %"$right#0")    {
entry:
  %1 = bitcast i64* %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = bitcast i64* %"$left#0" to i64* 
  %5 = getelementptr  i64, i64* %4, i64 1 
  %6 = load  i64, i64* %5 
  %7 = bitcast i64* %"$right#0" to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %9 = load  i64, i64* %8 
  %10 = bitcast i64* %"$right#0" to i64* 
  %11 = getelementptr  i64, i64* %10, i64 1 
  %12 = load  i64, i64* %11 
  %"tmp$2#0" = icmp eq i64 %3, %9 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %6, %12 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64* @"position.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %13 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %14 = bitcast i8* %13 to i64* 
  %15 = bitcast i64* %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 %"x#0", i64* %16 
  %17 = bitcast i64* %14 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 1 
  store  i64 %"y#0", i64* %18 
  ret i64* %14 
}


define external ccc  {i64, i64} @"position.position.position<1>"(i64*  %"$#0")    {
entry:
  %19 = bitcast i64* %"$#0" to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = bitcast i64* %"$#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 1 
  %24 = load  i64, i64* %23 
  %25 = insertvalue {i64, i64} undef, i64 %21, 0 
  %26 = insertvalue {i64, i64} %25, i64 %24, 1 
  ret {i64, i64} %26 
}


define external ccc  i64 @"position.position.x<0>"(i64*  %"$rec#0")    {
entry:
  %27 = bitcast i64* %"$rec#0" to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  ret i64 %29 
}


define external ccc  i64* @"position.position.x<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %30 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %31 = bitcast i8* %30 to i64* 
  %32 = bitcast i64* %31 to i8* 
  %33 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %32, i8*  %33, i32  16, i32  8, i1  0)  
  %34 = bitcast i64* %31 to i64* 
  %35 = getelementptr  i64, i64* %34, i64 0 
  store  i64 %"$field#0", i64* %35 
  ret i64* %31 
}


define external ccc  i64 @"position.position.y<0>"(i64*  %"$rec#0")    {
entry:
  %36 = bitcast i64* %"$rec#0" to i64* 
  %37 = getelementptr  i64, i64* %36, i64 1 
  %38 = load  i64, i64* %37 
  ret i64 %38 
}


define external ccc  i64* @"position.position.y<1>"(i64*  %"$rec#0", i64  %"$field#0")    {
entry:
  %39 = tail call ccc  i8*  @wybe_malloc(i32  16)  
  %40 = bitcast i8* %39 to i64* 
  %41 = bitcast i64* %40 to i8* 
  %42 = bitcast i64* %"$rec#0" to i8* 
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %41, i8*  %42, i32  16, i32  8, i1  0)  
  %43 = bitcast i64* %40 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 1 
  store  i64 %"$field#0", i64* %44 
  ret i64* %40 
}
