======================================================================
AFTER EVERYTHING:
 Module bbb
  public submods  : 
  public types    : 
  public resources: 
  public procs    : bbb.<0>
  imports         : use ddd
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:phantom, ?wybe.io$io#1:phantom):
    foreign c print_string("BBB: Init":wybe.string, ~#wybe.io$io#0:phantom, ?tmp$2#0:phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$2#0:phantom, ?#wybe.io$io#1:phantom) @wybe:78:28
--------------------------------------------------
 Module ddd
  public submods  : 
  public types    : 
  public resources: 
  public procs    : ddd.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:phantom, ?wybe.io$io#1:phantom):
    foreign c print_string("DDD: Init":wybe.string, ~#wybe.io$io#0:phantom, ?tmp$2#0:phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$2#0:phantom, ?#wybe.io$io#1:phantom) @wybe:78:28
bbb, ddd
======================================================================
AFTER LLVM IR:

; ModuleID = 'bbb'
source_filename = "test-cases/bbb.wybe"

@bbb.1 = constant [10 x i8] c"BBB: Init\00"

declare void @putchar(i8) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

define i32 @bbb.main() local_unnamed_addr {
entry:
  tail call void @print_string(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @bbb.1, i64 0, i64 0))
  tail call void @putchar(i8 10)
  ret i32 0
}

--------------------------------------------------
; ModuleID = 'ddd'
source_filename = "test-cases/ddd.wybe"

@ddd.1 = constant [10 x i8] c"DDD: Init\00"

declare void @putchar(i8) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

define i32 @ddd.main() local_unnamed_addr {
entry:
  tail call void @print_string(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @ddd.1, i64 0, i64 0))
  tail call void @putchar(i8 10)
  ret i32 0
}

