======================================================================
AFTER EVERYTHING:
 Module commonsubexpr
  public submods  : 
  public types    : 
  public resources: 
  public procs    : commonsubexpr.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:phantom, ?wybe.io$io#1:phantom):
    foreign c print_int(198:wybe.int, ~#wybe.io$io#0:phantom, ?tmp$6#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$6#0:phantom, ?tmp$7#0:phantom) @wybe:78:28
    foreign c print_int(198:wybe.int, ~tmp$7#0:phantom, ?tmp$8#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$8#0:phantom, ?tmp$9#0:phantom) @wybe:78:28
    foreign c print_int(11:wybe.int, ~tmp$9#0:phantom, ?tmp$10#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$10#0:phantom, ?#wybe.io$io#1:phantom) @wybe:78:28


common_subexpr > inline (1 calls)
0: common_subexpr(x#0:wybe.int, wybe.io$io#0:phantom, ?wybe.io$io#3:phantom):
    foreign llvm add(x#0:wybe.int, 1:wybe.int, ?tmp$2#0:wybe.int) @wybe:12:38
    foreign llvm sub(~x#0:wybe.int, 1:wybe.int, ?tmp$51#0:wybe.int) @wybe:15:38
    foreign llvm mul(tmp$2#0:wybe.int, ~tmp$51#0:wybe.int, ?tmp$41#0:wybe.int) @wybe:20:38
    foreign llvm add(~tmp$41#0:wybe.int, ~tmp$41#0:wybe.int, ?tmp$0#0:wybe.int) @wybe:12:38
    foreign c print_int(tmp$0#0:wybe.int, ~#wybe.io$io#0:phantom, ?tmp$31#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$31#0:phantom, ?#wybe.io$io#1:phantom) @wybe:78:28
    foreign c print_int(~tmp$0#0:wybe.int, ~#wybe.io$io#1:phantom, ?tmp$44#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$44#0:phantom, ?#wybe.io$io#2:phantom) @wybe:78:28
    foreign c print_int(~tmp$2#0:wybe.int, ~#wybe.io$io#2:phantom, ?tmp$54#0:phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$54#0:phantom, ?#wybe.io$io#3:phantom) @wybe:78:28
commonsubexpr
======================================================================
AFTER LLVM IR:

; ModuleID = 'commonsubexpr'
source_filename = "test-cases/commonsubexpr.wybe"

declare void @putchar(i8) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

define i32 @commonsubexpr.main() local_unnamed_addr {
entry:
  tail call void @print_int(i64 198)
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 198)
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 11)
  tail call void @putchar(i8 10)
  ret i32 0
}

define void @"commonsubexpr.common_subexpr<0>"(i64 %"x#0") local_unnamed_addr {
entry:
  %"tmp$2#0" = add i64 %"x#0", 1
  %"tmp$51#0" = shl i64 %"x#0", 1
  %"tmp$41#0" = add i64 %"tmp$51#0", -2
  %"tmp$0#0" = mul i64 %"tmp$41#0", %"tmp$2#0"
  tail call void @print_int(i64 %"tmp$0#0")
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 %"tmp$0#0")
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 %"tmp$2#0")
  tail call void @putchar(i8 10)
  ret void
}

