======================================================================
AFTER EVERYTHING:
 Module commonsubexpr
  public submods  : 
  public types    : 
  public resources: 
  public procs    : commonsubexpr.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_int(198:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?tmp$6#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$6#0:wybe.phantom, ?tmp$7#0:wybe.phantom) @wybe:74:28
    foreign c print_int(198:wybe.int, ~tmp$7#0:wybe.phantom, ?tmp$8#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$8#0:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:74:28
    foreign c print_int(11:wybe.int, ~tmp$9#0:wybe.phantom, ?tmp$10#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$10#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:74:28


common_subexpr > inline (1 calls)
0: common_subexpr(x#0:wybe.int, wybe.io$io#0:wybe.phantom, ?wybe.io$io#3:wybe.phantom):
    foreign llvm add(x#0:wybe.int, 1:wybe.int, ?tmp$20#0:wybe.int) @wybe:13:38
    foreign llvm sub(~x#0:wybe.int, 1:wybe.int, ?tmp$22#0:wybe.int) @wybe:16:38
    foreign llvm mul(tmp$20#0:wybe.int, ~tmp$22#0:wybe.int, ?tmp$25#0:wybe.int) @wybe:21:38
    foreign llvm add(~tmp$25#0:wybe.int, ~tmp$25#0:wybe.int, ?tmp$35#0:wybe.int) @wybe:13:38
    foreign c print_int(tmp$35#0:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?tmp$38#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$38#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:74:28
    foreign c print_int(~tmp$35#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?tmp$58#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$58#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:74:28
    foreign c print_int(~tmp$20#0:wybe.int, ~#wybe.io$io#2:wybe.phantom, ?tmp$73#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$73#0:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:74:28
commonsubexpr
======================================================================
AFTER LLVM IR:

; ModuleID = 'commonsubexpr'
source_filename = "test-cases/commonsubexpr.wybe"

declare void @putchar(i8) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

define i32 @commonsubexpr.main() local_unnamed_addr {
entry:
  tail call void @print_int(i64 198)
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 198)
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 11)
  tail call void @putchar(i8 10)
  ret i32 0
}

define void @"commonsubexpr.common_subexpr<0>"(i64 %"x#0") local_unnamed_addr {
entry:
  %"tmp$20#0" = add i64 %"x#0", 1
  %"tmp$22#0" = shl i64 %"x#0", 1
  %"tmp$25#0" = add i64 %"tmp$22#0", -2
  %"tmp$35#0" = mul i64 %"tmp$25#0", %"tmp$20#0"
  tail call void @print_int(i64 %"tmp$35#0")
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 %"tmp$35#0")
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 %"tmp$20#0")
  tail call void @putchar(i8 10)
  ret void
}

