======================================================================
AFTER EVERYTHING:
 Module compute
  public submods  : 
  public types    : 
  public resources: 
  public procs    : compute.<0>
  imports         : use math
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom):
    math.utils.factorial<0>(4:wybe.int, ?tmp$0#0:wybe.int) @compute:3:10
    foreign c print_int(~tmp$0#0:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?tmp$4#0:wybe.phantom) @wybe:80:38
    foreign c putchar('\n':wybe.char, ~tmp$4#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:78:28
    foreign c print_float(65.55555555555556:wybe.float, ~#wybe.io$io#1:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:84:40
    foreign c putchar('\n':wybe.char, ~tmp$9#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:78:28
  LLVM code       :

; ModuleID = 'compute'


declare external ccc void @putchar(i8)

declare external ccc void @print_float(double)

declare external ccc void @print_int(i64)

declare external ccc i64 @"math.utils.factorial<0>"(i64)

declare external ccc i8* @wybe_malloc(i32)

define external ccc i32 @compute.main(){
entry:
  %"tmp$0#0" = tail call ccc i64 @"math.utils.factorial<0>"(i64 4)
  tail call ccc void @print_int(i64 %"tmp$0#0")
  tail call ccc void @putchar(i8 10)
  tail call ccc void @print_float(double 6.555556e1)
  tail call ccc void @putchar(i8 10)
  %1 = alloca i32
  store i32 0, i32* %1
  ret i32 0
}
--------------------------------------------------
 Module math
  public submods  : 
  public types    : 
  public resources: 
  public procs    : math.temperature.toCelsius<0>
                    math.utils.<0>
                    math.utils.factorial<0>
  imports         : public use math.temperature
                    public use math.utils
  types           : 
  resources       : 
  procs           : 

  LLVM code       :

; ModuleID = 'math'


declare external ccc i8* @wybe_malloc(i32)
  submodules      : math.temperature, math.utils
--------------------------------------------------
 Module math.temperature
  public submods  : 
  public types    : 
  public resources: 
  public procs    : math.temperature.toCelsius<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

toCelsius > public inline (0 calls)
0: toCelsius(f#0:wybe.float, ?$#0:wybe.float):
    foreign llvm fsub(~f#0:wybe.float, 32.0:wybe.float, ?tmp$1#0:wybe.float) @wybe:40:44
    foreign llvm fdiv(~tmp$1#0:wybe.float, 1.8:wybe.float, ?$#0:wybe.float) @wybe:46:44
  LLVM code       :

; ModuleID = 'math.temperature'


declare external ccc i8* @wybe_malloc(i32)

define external ccc double @"math.temperature.toCelsius<0>"(double %"f#0"){
entry:
  %"tmp$1#0" = fsub double %"f#0", 3.200000e1
  %"$#0" = fdiv double %"tmp$1#0", 1.800000e0
  ret double %"$#0"
}
--------------------------------------------------
 Module math.utils
  public submods  : 
  public types    : 
  public resources: 
  public procs    : math.utils.<0>
                    math.utils.factorial<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_string("Utils has been initialised.":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?tmp$2#0:wybe.phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$2#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:78:28


factorial > public (1 calls)
0: factorial(n#0:wybe.int, ?$#0:wybe.int):
    foreign llvm icmp sle(n#0:wybe.int, 0:wybe.int, ?tmp$4#0:wybe.bool) @wybe:25:40
    case ~tmp$4#0:wybe.bool of
    0:
        foreign llvm sub(n#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.int) @wybe:16:38
        math.utils.factorial<0>(~tmp$3#0:wybe.int, ?tmp$2#0:wybe.int) @utils:2:34
        foreign llvm mul(~n#0:wybe.int, ~tmp$2#0:wybe.int, ?$#0:wybe.int) @wybe:21:38

    1:
        foreign llvm move(1:wybe.int, ?$#0:wybe.int) @utils:1:8

  LLVM code       :

; ModuleID = 'math.utils'


declare external ccc void @putchar(i8)

declare external ccc void @print_string(i8*)

@math.utils.1 = constant [28 x i8] c"Utils has been initialised.\00"

declare external ccc i8* @wybe_malloc(i32)

define external ccc i32 @math.utils.main(){
entry:
  tail call ccc void @print_string(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @math.utils.1, i32 0, i32 0))
  tail call ccc void @putchar(i8 10)
  %2 = alloca i32
  store i32 0, i32* %2
  ret i32 0
}

define external ccc i64 @"math.utils.factorial<0>"(i64 %"n#0"){
entry:
  %"tmp$4#0" = icmp sle i64 %"n#0", 0
  br i1 %"tmp$4#0", label %if.then, label %if.else
if.then:
  ret i64 1
if.else:
  %"tmp$3#0" = sub i64 %"n#0", 1
  %"tmp$2#0" = tail call ccc i64 @"math.utils.factorial<0>"(i64 %"tmp$3#0")
  %"$#0" = mul i64 %"n#0", %"tmp$2#0"
  ret i64 %"$#0"
}
