======================================================================
AFTER EVERYTHING:
 Module ddd
  public submods  : 
  public types    : 
  public resources: 
  public procs    : ddd.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (io#0:phantom, ?io#1:phantom):
    foreign c print_string("DDD: Init":wybe.string, ~#io#0:phantom, ?tmp$2#0:phantom) @wybe:92:41
    foreign c putchar('\n':wybe.char, ~tmp$2#0:phantom, ?#io#1:phantom) @wybe:78:28

  LLVM code       :

; ModuleID = 'ddd'


declare external ccc void @putchar(i8)

declare external ccc void @print_string(i8*)

@ddd.1 = constant [10 x i8] c"DDD: Init\00"

declare external ccc i8* @wybe_malloc(i32)

define external ccc i32 @ddd.main(){
entry:
  tail call ccc void @print_string(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @ddd.1, i32 0, i32 0))
  tail call ccc void @putchar(i8 10)
  %2 = alloca i32
  store i32 0, i32* %2
  ret i32 0
}
