======================================================================
AFTER EVERYTHING:
 Module escape
  public submods  : 
  public types    : 
  public resources: 
  public procs    : escape.<0>
                    escape.bar<0>
                    escape.baz<0>
                    escape.foo<0>
                    escape.replicate<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#8:wybe.phantom): Alias Pairs: []

    foreign c print_string("foo: ":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:88:41
    escape.foo<0>(~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @escape:45:2
    foreign c print_string("---":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:88:41
    foreign c print_string("bar: ":wybe.string, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:88:41
    escape.bar<0>(~#wybe.io$io#4:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @escape:48:2
    foreign c print_string("---":wybe.string, ~#wybe.io$io#5:wybe.phantom, ?#wybe.io$io#6:wybe.phantom) @wybe:88:41
    foreign c print_string("baz: ":wybe.string, ~#wybe.io$io#6:wybe.phantom, ?#wybe.io$io#7:wybe.phantom) @wybe:88:41
    escape.baz<0>(~#wybe.io$io#7:wybe.phantom, ?#wybe.io$io#8:wybe.phantom) @escape:51:2


bar > public (1 calls)
0: bar(wybe.io$io#0:wybe.phantom, ?wybe.io$io#3:wybe.phantom): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?tmp$5#0:position.position)
    foreign lpvm mutate(~tmp$5#0:position.position, ?tmp$6#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 101:wybe.int)
    foreign lpvm mutate(~tmp$6#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 102:wybe.int)
    escape.replicate<0>(tmp$0#0:position.position, ?p2#0:position.position, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @escape:24:4
    foreign lpvm mutate(~tmp$0#0:position.position, ?%p1#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 555:wybe.int)
    foreign lpvm access(~p1#1:position.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?tmp$13#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$13#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:74:28
    foreign lpvm access(~p2#0:position.position, 0:wybe.int, ?tmp$2#0:wybe.int)
    foreign c print_int(~tmp$2#0:wybe.int, ~#wybe.io$io#2:wybe.phantom, ?tmp$17#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$17#0:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:74:28


baz > public (1 calls)
0: baz(wybe.io$io#0:wybe.phantom, ?wybe.io$io#4:wybe.phantom): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?tmp$8#0:position.position)
    foreign lpvm mutate(~tmp$8#0:position.position, ?tmp$9#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 101:wybe.int)
    foreign lpvm mutate(~tmp$9#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 102:wybe.int)
    escape.replicate<0>(tmp$0#0:position.position, ?p2#0:position.position, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @escape:33:4
    foreign lpvm access(p2#0:position.position, 8:wybe.int, ?tmp$2#0:wybe.int)
    foreign lpvm alloc(16:wybe.int, ?tmp$14#0:position.position)
    foreign lpvm mutate(~tmp$14#0:position.position, ?tmp$15#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 33333333:wybe.int)
    foreign lpvm mutate(~tmp$15#0:position.position, ?tmp$1#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~tmp$2#0:wybe.int)
    foreign lpvm mutate(~tmp$0#0:position.position, ?%p1#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 555:wybe.int)
    foreign lpvm access(~p1#1:position.position, 0:wybe.int, ?tmp$3#0:wybe.int)
    foreign c print_int(~tmp$3#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?tmp$22#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$22#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:74:28
    foreign lpvm access(~p2#0:position.position, 0:wybe.int, ?tmp$4#0:wybe.int)
    foreign c print_int(~tmp$4#0:wybe.int, ~#wybe.io$io#2:wybe.phantom, ?tmp$26#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$26#0:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:74:28
    foreign lpvm access(~tmp$1#0:position.position, 0:wybe.int, ?tmp$5#0:wybe.int)
    foreign c print_int(~tmp$5#0:wybe.int, ~#wybe.io$io#3:wybe.phantom, ?tmp$30#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$30#0:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:74:28


foo > public (1 calls)
0: foo(wybe.io$io#0:wybe.phantom, ?wybe.io$io#5:wybe.phantom): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?tmp$7#0:position.position)
    foreign lpvm mutate(~tmp$7#0:position.position, ?tmp$8#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 101:wybe.int)
    foreign lpvm mutate(~tmp$8#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 102:wybe.int)
    escape.replicate<0>(tmp$0#0:position.position, ?tmp$24#0:position.position, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @escape:11:4
    foreign lpvm access(tmp$0#0:position.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?tmp$13#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$13#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:74:28
    foreign lpvm access(~tmp$24#0:position.position, 0:wybe.int, ?tmp$2#0:wybe.int)
    foreign c print_int(tmp$2#0:wybe.int, ~#wybe.io$io#2:wybe.phantom, ?tmp$17#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$17#0:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:74:28
    foreign lpvm mutate(~tmp$0#0:position.position, ?%p1#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, 555:wybe.int)
    foreign lpvm access(~p1#1:position.position, 0:wybe.int, ?tmp$3#0:wybe.int)
    foreign c print_int(~tmp$3#0:wybe.int, ~#wybe.io$io#3:wybe.phantom, ?tmp$23#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$23#0:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:74:28
    foreign c print_int(~tmp$2#0:wybe.int, ~#wybe.io$io#4:wybe.phantom, ?tmp$27#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$27#0:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @wybe:74:28


replicate > public (3 calls)
0: replicate(p1#0:position.position, ?p2#0:position.position, wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom): Alias Pairs: [(0,1)]

    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:position.position)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$5#0:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 0:wybe.int)
    foreign lpvm mutate(~tmp$5#0:position.position, ?tmp$0#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 0:wybe.int)
    foreign c print_string("random print":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:88:41
    foreign lpvm access(~tmp$0#0:position.position, 0:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?tmp$12#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$12#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:74:28
    foreign llvm move(~p1#0:position.position, ?p2#0:position.position)
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,"pointer")
  public resources: 
  public procs    : position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/0 (pointer)  @position:1:8
  resources       : 
  procs           : 

  submodules      : position.position
--------------------------------------------------
 Module position.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.=<1>
                    position.position.=<2>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:position.position, in#0:position.position): Alias Pairs: []

    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline (0 calls)
1: =(in#0:position.position, ?out#0:position.position): Alias Pairs: []

    foreign llvm move(~in#0:position.position, ?out#0:position.position)
= > public inline test (3 calls)
2: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool): Alias Pairs: []

    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:28:40
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:28:40



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?$rec#0:position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position): Alias Pairs: []

    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
escape, position, position.position
======================================================================
AFTER LLVM IR:

; ModuleID = 'escape'
source_filename = "test-cases/escape.wybe"

@escape.5 = constant [6 x i8] c"baz: \00"
@escape.4 = constant [4 x i8] c"---\00"
@escape.3 = constant [6 x i8] c"bar: \00"
@escape.2 = constant [4 x i8] c"---\00"
@escape.1 = constant [6 x i8] c"foo: \00"
@escape.54 = constant [13 x i8] c"random print\00"

declare void @print_string(i8*) local_unnamed_addr

declare void @putchar(i8) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

declare i8* @wybe_malloc(i32) local_unnamed_addr

define i32 @escape.main() local_unnamed_addr {
entry:
  tail call void @print_string(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @escape.1, i64 0, i64 0))
  tail call void @"escape.foo<0>"()
  tail call void @print_string(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @escape.2, i64 0, i64 0))
  tail call void @print_string(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @escape.3, i64 0, i64 0))
  tail call void @"escape.bar<0>"()
  tail call void @print_string(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @escape.4, i64 0, i64 0))
  tail call void @print_string(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @escape.5, i64 0, i64 0))
  tail call void @"escape.baz<0>"()
  ret i32 0
}

define void @"escape.bar<0>"() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 101, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 102, i64* %3, align 4
  %"p2#0" = tail call i64* @"escape.replicate<0>"(i64* %1)
  %4 = tail call i8* @wybe_malloc(i32 16)
  store i64 555, i64* %1, align 4
  tail call void @print_int(i64 555)
  tail call void @putchar(i8 10)
  %5 = load i64, i64* %"p2#0", align 4
  tail call void @print_int(i64 %5)
  tail call void @putchar(i8 10)
  ret void
}

define void @"escape.baz<0>"() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 101, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 102, i64* %3, align 4
  %"p2#0" = tail call i64* @"escape.replicate<0>"(i64* %1)
  %4 = getelementptr i64, i64* %"p2#0", i64 1
  %5 = load i64, i64* %4, align 4
  %6 = tail call i8* @wybe_malloc(i32 16)
  %7 = bitcast i8* %6 to i64*
  store i64 33333333, i64* %7, align 4
  %8 = getelementptr i8, i8* %6, i64 8
  %9 = bitcast i8* %8 to i64*
  store i64 %5, i64* %9, align 4
  %10 = tail call i8* @wybe_malloc(i32 16)
  store i64 555, i64* %1, align 4
  tail call void @print_int(i64 555)
  tail call void @putchar(i8 10)
  %11 = load i64, i64* %"p2#0", align 4
  tail call void @print_int(i64 %11)
  tail call void @putchar(i8 10)
  %12 = load i64, i64* %7, align 4
  tail call void @print_int(i64 %12)
  tail call void @putchar(i8 10)
  ret void
}

define void @"escape.foo<0>"() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 101, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 102, i64* %3, align 4
  %"tmp$24#0" = tail call i64* @"escape.replicate<0>"(i64* %1)
  %4 = load i64, i64* %1, align 4
  tail call void @print_int(i64 %4)
  tail call void @putchar(i8 10)
  %5 = load i64, i64* %"tmp$24#0", align 4
  tail call void @print_int(i64 %5)
  tail call void @putchar(i8 10)
  %6 = tail call i8* @wybe_malloc(i32 16)
  store i64 555, i64* %1, align 4
  tail call void @print_int(i64 555)
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 %5)
  tail call void @putchar(i8 10)
  ret void
}

define i64* @"escape.replicate<0>"(i64* readnone returned %"p1#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  call void @llvm.memset.p0i8.i64(i8* %0, i8 0, i64 16, i32 4, i1 false)
  tail call void @print_string(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @escape.54, i64 0, i64 0))
  %2 = load i64, i64* %1, align 4
  tail call void @print_int(i64 %2)
  tail call void @putchar(i8 10)
  ret i64* %"p1#0"
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i32, i1) #0

attributes #0 = { argmemonly nounwind }

--------------------------------------------------
; ModuleID = 'position'
source_filename = "test-cases/position.wybe"

--------------------------------------------------
; ModuleID = 'position.position'
source_filename = "test-cases"

declare i8* @wybe_malloc(i32) local_unnamed_addr

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position.position.=<2>"(i64* nocapture readonly %"$left#0", i64* nocapture readonly %"$right#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$left#0", align 4
  %1 = load i64, i64* %"$right#0", align 4
  %"tmp$2#0" = icmp eq i64 %0, %1
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = getelementptr i64, i64* %"$right#0", i64 1
  %3 = load i64, i64* %2, align 4
  %4 = getelementptr i64, i64* %"$left#0", i64 1
  %5 = load i64, i64* %4, align 4
  %"$$#0" = icmp eq i64 %5, %3
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position.position.position<1>"(i64* nocapture readonly %"$#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$#0", align 4
  %1 = getelementptr i64, i64* %"$#0", i64 1
  %2 = load i64, i64* %1, align 4
  %3 = insertvalue { i64, i64 } undef, i64 %0, 0
  %4 = insertvalue { i64, i64 } %3, i64 %2, 1
  ret { i64, i64 } %4
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.x<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$rec#0", align 4
  ret i64 %0
}

define i64* @"position.position.x<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  store i64 %"$field#0", i64* %"$rec#0", align 4
  ret i64* %"$rec#0"
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position.position.y<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = getelementptr i64, i64* %"$rec#0", i64 1
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position.position.y<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = getelementptr i64, i64* %"$rec#0", i64 1
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %"$rec#0"
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

