======================================================================
AFTER EVERYTHING:
 Module func_let
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_let.<0>
                    func_let.quad<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls) (inline)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_int(40:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:104:38


quad > public (1 calls) (inline)
0: quad(x#0:wybe.int, ?$#0:wybe.int):
    foreign llvm add(~x#0:wybe.int, ~x#0:wybe.int, ?tmp$4#0:wybe.int) @wybe:4:38
    foreign llvm add(~tmp$4#0:wybe.int, ~tmp$4#0:wybe.int, ?tmp$8#0:wybe.int) @wybe:4:38
    foreign llvm move(~tmp$8#0:wybe.int, ?$#0:wybe.int)
func_let
======================================================================
AFTER LLVM IR:

; ModuleID = 'func_let'

declare void @print_int(i32)

define i32 @func_let.main() {
entry:
  tail call void @print_int(i32 40)
  %0 = alloca i32
  store i32 0, i32* %0
  ret i32 0
}

define i32 @func_let.quad(i32 %"x#0") {
entry:
  %"tmp$4#0" = add i32 %"x#0", %"x#0"
  %"tmp$8#0" = add i32 %"tmp$4#0", %"tmp$4#0"
  ret i32 %"tmp$8#0"
}

