======================================================================
AFTER EVERYTHING:
 Module func_where
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_where.quad<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

quad > public (0 calls) (inline)
0: quad(x#0:wybe.int, ?$#0:wybe.int):
    foreign llvm add(~x#0:wybe.int, ~x#0:wybe.int, ?tmp$4#0:wybe.int) @wybe:4:38
    foreign llvm add(~tmp$4#0:wybe.int, ~tmp$4#0:wybe.int, ?tmp$8#0:wybe.int) @wybe:4:38
    foreign llvm move(~tmp$8#0:wybe.int, ?$#0:wybe.int)
