======================================================================
AFTER EVERYTHING:
 Module func_typed
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_typed.plus<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

plus > public inline (0 calls)
0: plus(a#0:wybe.int, b#0:wybe.int, ?$#0:wybe.int) aliases []:
    foreign llvm add(~a#0:wybe.int, ~b#0:wybe.int, ?$#0:wybe.int) @wybe:13:38
func_typed
======================================================================
AFTER LLVM IR:

; ModuleID = 'func_typed'
source_filename = "test-cases/func_typed.wybe"

; Function Attrs: norecurse nounwind readnone
define i64 @"func_typed.plus<0>"(i64 %"a#0", i64 %"b#0") local_unnamed_addr #0 {
entry:
  %"$#0" = add i64 %"b#0", %"a#0"
  ret i64 %"$#0"
}

attributes #0 = { norecurse nounwind readnone }

