Public func plus(a:int,b:int):int {func-typed:1:8} = +(a {func-typed:1:40}, b {func-typed:1:42}) {func-typed:1:40}

 Module func-typed
  public submods  : 
  public types    : 
  public resources: 
  public procs    : plus(a:int, b:int, ?$:int) <0> {func-typed:1:8}
  imports         : 
  types           : 
  resources       : 
  procs           : plus:
proc plus(a:int, b:int, ?$:int) (id 0):  {func-typed:1:8}
    +(a:0, b:0, ?$tmp0:0) {func-typed:1:40}
    =(?$:0, $tmp0:0) {?}

Submodules of func-typed:

