Public func double(a:int):int {func-quadruple:1:8} = +(a {func-quadruple:1:35}, a {func-quadruple:1:37}) {func-quadruple:1:35}
Public func quadruple(a:int):int {func-quadruple:3:8} = double(double(a {func-quadruple:3:52}) {func-quadruple:3:45}) {func-quadruple:3:38}

 Module func-quadruple
  imports         : 
  public submods  : 
  public types    : 
  public resources: 
  public procs    : double, quadruple
  types           : 
  resources       : 
  procs           : double: [
proc double(a:int, ?$:int) (id 1):  {func-quadruple:1:8}
    +(a, a, ?$tmp0) {func-quadruple:1:35}
    =(?$, $tmp0) {?}]
                    quadruple: [
proc quadruple(a:int, ?$:int) (id 2):  {func-quadruple:3:8}
    double(a, ?$tmp1) {func-quadruple:3:45}
    double($tmp1, ?$tmp2) {func-quadruple:3:38}
    =(?$, $tmp2) {?}]

Submodules of func-quadruple:

