Public func quad(x:int):int {func-where:1:8} = +(d {func-where:1:31}, d {func-where:1:33}) {func-where:1:31} where [=(?d {func-where:1:42}, +(x {func-where:1:44}, x {func-where:1:46}) {func-where:1:44}) {func-where:1:42}] {func-where:1:31}

 Module func-where
  imports         : 
  public submods  : 
  public types    : 
  public resources: 
  public procs    : quad
  types           : 
  resources       : 
  procs           : quad: [
proc quad(x:int, ?$:int) (id 1):  {func-where:1:8}
    +(x, x, ?$tmp0) {func-where:1:44}
    =(?d, $tmp0) {func-where:1:42}
    +(d, d, ?$tmp1) {func-where:1:31}
    =(?$, $tmp1) {?}]

Submodules of func-where:

