[Public func times(a:?,b:?):? {func-no-types:1:8} = *(a {func-no-types:1:26}, b {func-no-types:1:28}) {func-no-types:1:26}]
Module
  imports         : 
  public types    : 
  public resources: 
  public procs    : times
  types:          : 
  resources       : 
  procs           : times: [proc 1: times(a:?, b:?, ?$:?) {func-no-types:1:8}
    *(a {func-no-types:1:26}, b {func-no-types:1:28}, ?$tmp0 {?}) {func-no-types:1:26}
    =(?$ {?}, $tmp0 {?}) {?}]

