======================================================================
AFTER EVERYTHING:
 Module func_where
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_where.quad<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

quad > public inline (0 calls)
0: quad(x#0:wybe.int, ?$#0:wybe.int):
    foreign llvm add(~x#0:wybe.int, ~x#0:wybe.int, ?tmp$4#0:wybe.int) @wybe:13:38
    foreign llvm add(~tmp$4#0:wybe.int, ~tmp$4#0:wybe.int, ?tmp$8#0:wybe.int) @wybe:13:38
    foreign llvm move(~tmp$8#0:wybe.int, ?$#0:wybe.int) @func_where:1:8
func_where
======================================================================
AFTER LLVM IR:

; ModuleID = 'func_where'

; Function Attrs: nounwind readnone
define i64 @"func_where.quad<0>"(i64 %"x#0") #0 {
entry:
  %"tmp$8#0" = shl i64 %"x#0", 2
  ret i64 %"tmp$8#0"
}

attributes #0 = { nounwind readnone }

