 Module func_factorial
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_factorial.factorial<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : factorial:
public proc factorial(n:0:int, ?~tmp$0:0:int)<0>  @func_factorial:1:8 (0 calls)
    func_factorial.gen$1<0>(n:0:int, ?n:1:int, ?tmp$0:0:int) @func_factorial:2:8
    wybe.int.=<0>(?~$:0:int, ~tmp$0:0:int)
                    gen$1:
proc gen$1(n:0:int, ?n:0:int, ?tmp$0:0:int)<0>  (0 calls)
    wybe.int.<=<0>(n:0:int, 0:int, ?~tmp$1:0:bool) @func_factorial:2:11
    case tmp$1:0 of
    0:
        wybe.int.-<0>(n:0:int, 1:int, ?~tmp$4:0:int) @func_factorial:2:44
        func_factorial.factorial<0>(~tmp$4:0:int, ?~tmp$3:0:int) @func_factorial:2:34
        wybe.int.*<0>(n:0:int, ~tmp$3:0:int, ?~tmp$2:0:int) @func_factorial:2:30
        wybe.int.=<0>(?~tmp$0:0:int, ~tmp$2:0:int)

    1:
        wybe.int.=<0>(?~tmp$0:0:int, 1:int)

