 Module func_where
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_where.quad<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : quad:
public proc quad(x:0:int, ?~tmp$1:0:int)<0>  @func_where:1:8 (0 calls)
    wybe.int.+<0>(x:0:int, x:0:int, ?~tmp$0:0:int) @func_where:1:44
    wybe.int.+<0>(~tmp$0:0:int, ~tmp$0:0:int, ?~tmp$1:0:int) @func_where:1:31
    wybe.int.=<0>(?~$:0:int, ~tmp$1:0:int)
