Public func quad(x:int):int {func-let:1:8} = +(d {func-let:1:47}, d {func-let:1:49}) {func-let:1:47} where [=(?d {func-let:1:35}, +(x {func-let:1:40}, x {func-let:1:42}) {func-let:1:40}) {func-let:1:35}] {func-let:1:31}

 Module func-let
  imports         : 
  public submods  : 
  public types    : 
  public resources: 
  public procs    : quad
  types           : 
  resources       : 
  procs           : quad: [
proc quad(x:int, ?$:int) (id 1):  {func-let:1:8}
    +(x, x, ?$tmp0) {func-let:1:40}
    =(?d, $tmp0) {func-let:1:35}
    +(d, d, ?$tmp1) {func-let:1:47}
    =(?$, $tmp1) {?}]

Submodules of func-let:

