======================================================================
AFTER EVERYTHING:
 Module func_let
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_let.<0>
                    func_let.quad<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign llvm move(~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @func_let:3:1


quad > public inline (1 calls)
0: quad(x#0:wybe.int, ?$#0:wybe.int):
    foreign llvm add(~x#0:wybe.int, ~x#0:wybe.int, ?tmp$4#0:int) @wybe:12:38
    foreign llvm add(~tmp$4#0:int, ~tmp$4#0:int, ?tmp$8#0:int) @wybe:12:38
    foreign llvm move(~tmp$8#0:int, ?$#0:wybe.int) @func_let:1:8
func_let
======================================================================
AFTER LLVM IR:

; ModuleID = 'func_let'

; Function Attrs: nounwind readnone
define i32 @func_let.main() #0 {
entry:
  ret i32 0
}

; Function Attrs: nounwind readnone
define i64 @"func_let.quad<0>"(i64 %"x#0") #0 {
entry:
  %"tmp$8#0" = shl i64 %"x#0", 2
  ret i64 %"tmp$8#0"
}

attributes #0 = { nounwind readnone }

