Public func times(a:?,b:?):? {func-no-types:1:8} = *(a {func-no-types:1:26}, b {func-no-types:1:28}) {func-no-types:1:26}
Module
  imports         : 
  public types    : 
  public resources: 
  public procs    : times
  types           : 
  resources       : 
  procs           : times: [
proc times(a:?, b:?, ?$:?) (id 1):  {func-no-types:1:8}
    *(a, b, ?$tmp0) {func-no-types:1:26}
    =(?$, $tmp0) {?}]

