Private import position {import:1:1}
  
Public func distance(p1:position,p2:position):? {import:3:8} = sqrt(+(^(-(x(p2 {import:4:11}) {import:4:11}, x(p1 {import:4:16}) {import:4:16}) {import:4:10}, 2 {import:4:23}) {import:4:10}, ^(-(y(p2 {import:4:27}) {import:4:27}, y(p1 {import:4:32}) {import:4:32}) {import:4:26}, 2 {import:4:39}) {import:4:26}) {import:4:10}) {import:4:5}
Public type position is {position:1:8}
  Public ctor position(x:int,y:int) {position:2:12}
end


 Module position
  public submods  : position {position:1:8}
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of position:
position: 
 Module position.position([])
  public submods  : 
  public types    : position/0 {position:1:8}
  public resources: 
  public procs    : position(x:0:int, y:0:int, ?$:-1:position) <0> {?}
                    x($rec:0:position, ?$rec:-1:position, $field:0:int) <1> {?}
                    x($rec:0:position, ?$:-1:int) <0> {?}
                    y($rec:0:position, ?$rec:-1:position, $field:0:int) <1> {?}
                    y($rec:0:position, ?$:-1:int) <0> {?}
  imports         : 
  types           : position/0 {position:1:8}
  resources       : 
  procs           : position:
proc position(x:0:int, y:0:int, ?$:-1:position) (id 0):  {?}
    foreign  alloc("position", "position", ?$rec:0) {?}
    foreign  mutate("position", "position", "x", $rec:0, ?$rec:1, x:0) {?}
    foreign  mutate("position", "position", "y", $rec:1, ?$rec:2, y:0) {?}
    =(?$:0, $rec:2) {?}
                    x:
proc x($rec:0:position, ?$:-1:int) (id 0):  {?}
    foreign  access("position", "position", "x", $rec:0, ?$tmp0:0) {?}
    =(?$:0, $tmp0:0) {?}
proc x($rec:0:position, ?$rec:-1:position, $field:0:int) (id 1):  {?}
    foreign  mutate("position", "position", "x", $rec:0, ?$rec:1, $field:0) {?}
                    y:
proc y($rec:0:position, ?$:-1:int) (id 0):  {?}
    foreign  access("position", "position", "y", $rec:0, ?$tmp0:0) {?}
    =(?$:0, $tmp0:0) {?}
proc y($rec:0:position, ?$rec:-1:position, $field:0:int) (id 1):  {?}
    foreign  mutate("position", "position", "y", $rec:0, ?$rec:1, $field:0) {?}

Submodules of position.position:


 Module import
  public submods  : 
  public types    : 
  public resources: 
  public procs    : distance(p1:0:position, p2:0:position, ?$:-1:?) <0> {import:3:8}
  imports         : import position 
  types           : 
  resources       : 
  procs           : distance:
proc distance(p1:0:position, p2:0:position, ?$:-1:?) (id 0):  {import:3:8}
    x(p2:0, ?$tmp5:0) {import:4:11}
    x(p1:0, ?$tmp4:0) {import:4:16}
    -($tmp5:0, $tmp4:0, ?$tmp6:0) {import:4:10}
    ^($tmp6:0, 2, ?$tmp7:0) {import:4:10}
    y(p2:0, ?$tmp1:0) {import:4:27}
    y(p1:0, ?$tmp0:0) {import:4:32}
    -($tmp1:0, $tmp0:0, ?$tmp2:0) {import:4:26}
    ^($tmp2:0, 2, ?$tmp3:0) {import:4:26}
    +($tmp7:0, $tmp3:0, ?$tmp8:0) {import:4:10}
    sqrt($tmp8:0, ?$tmp9:0) {import:4:5}
    =(?$:0, $tmp9:0) {?}

Submodules of import:

uninitialised variable $tmp0
uninitialised variable $tmp0