
 Module mod1
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod1:


 Module mod2
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod2:


 Module mod3
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod3:


 Module mod4
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod4:


 Module mod5
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod5:


 Module mod6
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod6:


 Module mod7
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod7:


 Module mod8
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : 
  types           : 
  resources       : 
  procs           : 

Submodules of mod8:


 Module imports
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : import mod1 
                    use mod2 
                    from mod3 import fn1
                    from mod4 use fn2
                    public import mod5 
                    public use mod6 
                    public from mod7 import fn3
                    public from mod8 use fn4
  types           : 
  resources       : 
  procs           : 

Submodules of imports:

