======================================================================
AFTER EVERYTHING:
 Module imports
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use mod1
                    use mod2
                    from mod3 use fn1
                    from mod4 use fn2
                    public use mod5
                    public use mod6
                    public from mod7 use fn3
                    public from mod8 use fn4
                    use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod1
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod2
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod3
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod4
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod5
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod6
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod7
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

--------------------------------------------------
 Module mod8
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

imports, mod1, mod2, mod3, mod4, mod5, mod6, mod7, mod8
======================================================================
AFTER LLVM IR:

; ModuleID = 'imports'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod1'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod2'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod3'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod4'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod5'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod6'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod7'

declare i8* @wybe_malloc(i32)

--------------------------------------------------
; ModuleID = 'mod8'

declare i8* @wybe_malloc(i32)

