======================================================================
AFTER EVERYTHING:
 Module mainless
  public submods  : 
  public types    : 
  public resources: 
  public procs    : mainless.nothing_interesting<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

nothing_interesting > public inline (0 calls)
0: nothing_interesting(?$#0:wybe.int):
    foreign llvm move(7:wybe.int, ?$#0:wybe.int) @mainless:4:8
mainless
======================================================================
AFTER LLVM IR:

; ModuleID = 'mainless'

; Function Attrs: nounwind readnone
define i64 @"mainless.nothing_interesting<0>"() #0 {
entry:
  ret i64 7
}

attributes #0 = { nounwind readnone }

