======================================================================
AFTER EVERYTHING:
 Module main_hello2
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
(0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom):
    foreign c print_string("hello, ":wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:122:41
    foreign c print_string("world!":wybe.string, ~%wybe.io$io#1:wybe.phantom, ?%tmp$0#0:wybe.phantom) @wybe:122:41
    foreign c putc('\n':wybe.char, ~%tmp$0#0:wybe.phantom, ?%wybe.io$io#2:wybe.phantom) @wybe:108:28
