======================================================================
AFTER EVERYTHING:
 Module main_hello
  public submods  : 
  public types    : 
  public resources: 
  public procs    : main_hello.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_string("hello, world!":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?tmp$2#0:wybe.phantom) @wybe:93:41
    foreign c putchar('\n':wybe.char, ~tmp$2#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:79:28
  LLVM code       :

; ModuleID = 'main_hello'


declare external ccc void @putchar(i8)

declare external ccc void @print_string(i8*)

@main_hello.1 = constant [14 x i8] c"hello, world!\00"

declare external ccc i8* @wybe_malloc(i32)

define external ccc i32 @main_hello.main(){
entry:
  tail call ccc void @print_string(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @main_hello.1, i32 0, i32 0))
  tail call ccc void @putchar(i8 10)
  %2 = alloca i32
  store i32 0, i32* %2
  ret i32 0
}
