======================================================================
AFTER EVERYTHING:
 Module mod3
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

mod3
======================================================================
AFTER LLVM IR:

; ModuleID = 'mod3'
source_filename = "test-cases/mod3.wybe"

