======================================================================
AFTER EVERYTHING:
 Module mod5
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 


  LLVM code       :

; ModuleID = 'mod5'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    
