======================================================================
AFTER EVERYTHING:
 Module mod5
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

mod5
======================================================================
AFTER LLVM IR:

; ModuleID = 'mod5'
source_filename = "test-cases/mod5.wybe"

