======================================================================
AFTER EVERYTHING:
 Module mod6
  public submods  : 
  public types    : 
  public resources: 
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

mod6
======================================================================
AFTER LLVM IR:

; ModuleID = 'mod6'

declare i8* @wybe_malloc(i32)

