======================================================================
AFTER EVERYTHING:
 Module person1
  public submods  : 
  public types    : person: (person1.person,Just "address")
  public resources: 
  public procs    : person1.<0>
                    person1.person.=<0>
                    person1.person.firstname<0>
                    person1.person.firstname<1>
                    person1.person.lastname<0>
                    person1.person.lastname<1>
                    person1.person.person<0>
                    person1.person.person<1>
  imports         : public use person1.person
                    use wybe
  types           : person/public  is address { person(firstname:string, lastname:string) @person1:1:23  }  @person1:1:5
  resources       : 
  submodules      : person1.person
  procs           : 

*main* > public inline (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    foreign c print_string("Wang":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'person1'


 


declare external ccc  void @print_string(i64)    


@person1.1 =    constant [5 x i8] c"Wang\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"person1.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([5 x i8], [5 x i8]* @person1.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  ret void 
}
--------------------------------------------------
 Module person1.person
  public submods  : 
  public types    : 
  public resources: 
  public procs    : person1.person.=<0>
                    person1.person.firstname<0>
                    person1.person.firstname<1>
                    person1.person.lastname<0>
                    person1.person.lastname<1>
                    person1.person.person<0>
                    person1.person.person<1>
  imports         : use person1
                    use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline test (3 calls)
0: =($left#0:person1.person, $right#0:person1.person, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:person1.person, 0:wybe.int, ?$left$firstname#0:wybe.string)
    foreign lpvm access(~$left#0:person1.person, 8:wybe.int, ?$left$lastname#0:wybe.string)
    foreign lpvm access($right#0:person1.person, 0:wybe.int, ?$right$firstname#0:wybe.string)
    foreign lpvm access(~$right#0:person1.person, 8:wybe.int, ?$right$lastname#0:wybe.string)
    foreign c strcmp(~$left$firstname#0:wybe.string, ~$right$firstname#0:wybe.string, ?tmp$8#0:wybe.int) @wybe:nn:nn
    wybe.int.=<0>(~tmp$8#0:wybe.int, 0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign c strcmp(~$left$lastname#0:wybe.string, ~$right$lastname#0:wybe.string, ?tmp$11#0:wybe.int) @wybe:nn:nn
        wybe.int.=<0>(~tmp$11#0:wybe.int, 0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



firstname > public inline (0 calls)
0: firstname($rec#0:person1.person, ?$#0:wybe.string): AliasPairs: []
    foreign lpvm access(~$rec#0:person1.person, 0:wybe.int, ?$#0:wybe.string)
firstname > public inline (0 calls)
1: firstname($rec#0:person1.person, ?$rec#1:person1.person, $field#0:wybe.string): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:person1.person, ?%$rec#1:person1.person, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.string)


lastname > public inline (0 calls)
0: lastname($rec#0:person1.person, ?$#0:wybe.string): AliasPairs: []
    foreign lpvm access(~$rec#0:person1.person, 8:wybe.int, ?$#0:wybe.string)
lastname > public inline (0 calls)
1: lastname($rec#0:person1.person, ?$rec#1:person1.person, $field#0:wybe.string): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:person1.person, ?%$rec#1:person1.person, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.string)


person > public inline (0 calls)
0: person(firstname#0:wybe.string, lastname#0:wybe.string, ?$#0:person1.person): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:person1.person)
    foreign lpvm mutate(~%$rec#0:person1.person, ?%$rec#1:person1.person, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~firstname#0:wybe.string)
    foreign lpvm mutate(~%$rec#1:person1.person, ?%$#0:person1.person, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~lastname#0:wybe.string)
person > public inline (4 calls)
1: person(?firstname#0:wybe.string, ?lastname#0:wybe.string, $#0:person1.person): AliasPairs: []
    foreign lpvm access($#0:person1.person, 0:wybe.int, ?firstname#0:wybe.string)
    foreign lpvm access(~$#0:person1.person, 8:wybe.int, ?lastname#0:wybe.string)

  LLVM code       :

; ModuleID = 'person1.person'


 


declare external ccc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i64 @strcmp(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"person1.person.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$8#0" = tail call ccc  i64  @strcmp(i64  %3, i64  %10)  
  %"tmp$2#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %"tmp$8#0", i64  0)  
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"tmp$11#0" = tail call ccc  i64  @strcmp(i64  %7, i64  %14)  
  %"$$#0" = tail call ccc  i1  @"wybe.int.=<0>"(i64  %"tmp$11#0", i64  0)  
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64 @"person1.person.firstname<0>"(i64  %"$rec#0")    {
entry:
  %15 = inttoptr i64 %"$rec#0" to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  %17 = load  i64, i64* %16 
  ret i64 %17 
}


define external ccc  i64 @"person1.person.firstname<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %18 = trunc i64 16 to i32  
  %19 = tail call ccc  i8*  @wybe_malloc(i32  %18)  
  %20 = ptrtoint i8* %19 to i64 
  %21 = inttoptr i64 %20 to i8* 
  %22 = inttoptr i64 %"$rec#0" to i8* 
  %23 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %21, i8*  %22, i32  %23, i32  8, i1  0)  
  %24 = inttoptr i64 %20 to i64* 
  %25 = getelementptr  i64, i64* %24, i64 0 
  store  i64 %"$field#0", i64* %25 
  ret i64 %20 
}


define external ccc  i64 @"person1.person.lastname<0>"(i64  %"$rec#0")    {
entry:
  %26 = add   i64 %"$rec#0", 8 
  %27 = inttoptr i64 %26 to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  ret i64 %29 
}


define external ccc  i64 @"person1.person.lastname<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %30 = trunc i64 16 to i32  
  %31 = tail call ccc  i8*  @wybe_malloc(i32  %30)  
  %32 = ptrtoint i8* %31 to i64 
  %33 = inttoptr i64 %32 to i8* 
  %34 = inttoptr i64 %"$rec#0" to i8* 
  %35 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %33, i8*  %34, i32  %35, i32  8, i1  0)  
  %36 = add   i64 %32, 8 
  %37 = inttoptr i64 %36 to i64* 
  %38 = getelementptr  i64, i64* %37, i64 0 
  store  i64 %"$field#0", i64* %38 
  ret i64 %32 
}


define external ccc  i64 @"person1.person.person<0>"(i64  %"firstname#0", i64  %"lastname#0")    {
entry:
  %39 = trunc i64 16 to i32  
  %40 = tail call ccc  i8*  @wybe_malloc(i32  %39)  
  %41 = ptrtoint i8* %40 to i64 
  %42 = inttoptr i64 %41 to i64* 
  %43 = getelementptr  i64, i64* %42, i64 0 
  store  i64 %"firstname#0", i64* %43 
  %44 = add   i64 %41, 8 
  %45 = inttoptr i64 %44 to i64* 
  %46 = getelementptr  i64, i64* %45, i64 0 
  store  i64 %"lastname#0", i64* %46 
  ret i64 %41 
}


define external ccc  {i64, i64} @"person1.person.person<1>"(i64  %"$#0")    {
entry:
  %47 = inttoptr i64 %"$#0" to i64* 
  %48 = getelementptr  i64, i64* %47, i64 0 
  %49 = load  i64, i64* %48 
  %50 = add   i64 %"$#0", 8 
  %51 = inttoptr i64 %50 to i64* 
  %52 = getelementptr  i64, i64* %51, i64 0 
  %53 = load  i64, i64* %52 
  %54 = insertvalue {i64, i64} undef, i64 %49, 0 
  %55 = insertvalue {i64, i64} %54, i64 %53, 1 
  ret {i64, i64} %55 
}
