======================================================================
AFTER EVERYTHING:
 Module position2
  public submods  : 
  public types    : position: (position2.position,"pointer")
  public resources: 
  public procs    : position2.<0>
                    position2.position.=<0>
                    position2.position.=<1>
                    position2.position.=<2>
                    position2.position.position<0>
                    position2.position.position<1>
                    position2.position.x<0>
                    position2.position.x<1>
                    position2.position.y<0>
                    position2.position.y<1>
  imports         : public use position2.position
                    use wybe
  types           : position/0 (pointer)  @position2:1:8
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#6:wybe.phantom): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?tmp$8#0:position2.position)
    foreign lpvm mutate(~tmp$8#0:position2.position, ?tmp$9#0:position2.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 111:wybe.int)
    foreign lpvm mutate(~tmp$9#0:position2.position, ?tmp$0#0:position2.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 222:wybe.int)
    foreign lpvm access(tmp$0#0:position2.position, 8:wybe.int, ?tmp$2#0:wybe.int)
    foreign lpvm alloc(16:wybe.int, ?tmp$14#0:position2.position)
    foreign lpvm mutate(~tmp$14#0:position2.position, ?tmp$15#0:position2.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 333:wybe.int)
    foreign lpvm mutate(~tmp$15#0:position2.position, ?tmp$1#0:position2.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, tmp$2#0:wybe.int)
    foreign c print_string("posA y field":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?tmp$19#0:wybe.phantom) @wybe:88:41
    foreign c putchar('\n':wybe.char, ~tmp$19#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:74:28
    foreign c print_int(~tmp$2#0:wybe.int, ~#wybe.io$io#1:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:76:38
    foreign lpvm mutate(~tmp$0#0:position2.position, ?%posA#1:position2.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 20000:wybe.int)
    foreign c print_string("posA new y field":wybe.string, ~#wybe.io$io#2:wybe.phantom, ?tmp$27#0:wybe.phantom) @wybe:88:41
    foreign c putchar('\n':wybe.char, ~tmp$27#0:wybe.phantom, ?#wybe.io$io#3:wybe.phantom) @wybe:74:28
    foreign lpvm access(~posA#1:position2.position, 8:wybe.int, ?tmp$4#0:wybe.int)
    foreign c print_int(~tmp$4#0:wybe.int, ~#wybe.io$io#3:wybe.phantom, ?#wybe.io$io#4:wybe.phantom) @wybe:76:38
    foreign c print_string("posB y field":wybe.string, ~#wybe.io$io#4:wybe.phantom, ?tmp$33#0:wybe.phantom) @wybe:88:41
    foreign c putchar('\n':wybe.char, ~tmp$33#0:wybe.phantom, ?#wybe.io$io#5:wybe.phantom) @wybe:74:28
    foreign lpvm access(~tmp$1#0:position2.position, 8:wybe.int, ?tmp$5#0:wybe.int)
    foreign c print_int(~tmp$5#0:wybe.int, ~#wybe.io$io#5:wybe.phantom, ?#wybe.io$io#6:wybe.phantom) @wybe:76:38
  submodules      : position2.position
--------------------------------------------------
 Module position2.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position2.position.=<0>
                    position2.position.=<1>
                    position2.position.=<2>
                    position2.position.position<0>
                    position2.position.position<1>
                    position2.position.x<0>
                    position2.position.x<1>
                    position2.position.y<0>
                    position2.position.y<1>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:position2.position, in#0:position2.position): Alias Pairs: []

    foreign llvm move(~in#0:position2.position, ?out#0:position2.position)
= > public inline (0 calls)
1: =(in#0:position2.position, ?out#0:position2.position): Alias Pairs: []

    foreign llvm move(~in#0:position2.position, ?out#0:position2.position)
= > public inline test (3 calls)
2: =($left#0:position2.position, $right#0:position2.position, ?$$#0:wybe.bool): Alias Pairs: []

    foreign lpvm access($left#0:position2.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position2.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position2.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position2.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:28:40
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:28:40



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position2.position): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?$rec#0:position2.position)
    foreign lpvm mutate(~%$rec#0:position2.position, ?%$rec#1:position2.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position2.position, ?%$#0:position2.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position2.position): Alias Pairs: []

    foreign lpvm access($#0:position2.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position2.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position2.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position2.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position2.position, ?$rec#1:position2.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position2.position, ?%$rec#1:position2.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position2.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position2.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position2.position, ?$rec#1:position2.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position2.position, ?%$rec#1:position2.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
position2, position2.position
======================================================================
AFTER LLVM IR:

; ModuleID = 'position2'
source_filename = "test-cases/position2.wybe"

@position2.16 = constant [13 x i8] c"posB y field\00"
@position2.13 = constant [17 x i8] c"posA new y field\00"
@position2.11 = constant [13 x i8] c"posA y field\00"

declare void @print_int(i64) local_unnamed_addr

declare void @putchar(i8) local_unnamed_addr

declare void @print_string(i8*) local_unnamed_addr

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

define i32 @position2.main() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 111, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 222, i64* %3, align 4
  %4 = tail call i8* @wybe_malloc(i32 16)
  %5 = bitcast i8* %4 to i64*
  store i64 333, i64* %5, align 4
  %6 = getelementptr i8, i8* %4, i64 8
  %7 = bitcast i8* %6 to i64*
  store i64 222, i64* %7, align 4
  tail call void @print_string(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @position2.11, i64 0, i64 0))
  tail call void @putchar(i8 10)
  tail call void @print_int(i64 222)
  store i64 20000, i64* %3, align 4
  tail call void @print_string(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @position2.13, i64 0, i64 0))
  tail call void @putchar(i8 10)
  %8 = load i64, i64* %3, align 4
  tail call void @print_int(i64 %8)
  tail call void @print_string(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @position2.16, i64 0, i64 0))
  tail call void @putchar(i8 10)
  %9 = load i64, i64* %7, align 4
  tail call void @print_int(i64 %9)
  ret i32 0
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position2.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position2.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position2.position.=<2>"(i64* nocapture readonly %"$left#0", i64* nocapture readonly %"$right#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$left#0", align 4
  %1 = load i64, i64* %"$right#0", align 4
  %"tmp$2#0" = icmp eq i64 %0, %1
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = getelementptr i64, i64* %"$right#0", i64 1
  %3 = load i64, i64* %2, align 4
  %4 = getelementptr i64, i64* %"$left#0", i64 1
  %5 = load i64, i64* %4, align 4
  %"$$#0" = icmp eq i64 %5, %3
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position2.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position2.position.position<1>"(i64* nocapture readonly %"$#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$#0", align 4
  %1 = getelementptr i64, i64* %"$#0", i64 1
  %2 = load i64, i64* %1, align 4
  %3 = insertvalue { i64, i64 } undef, i64 %0, 0
  %4 = insertvalue { i64, i64 } %3, i64 %2, 1
  ret { i64, i64 } %4
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position2.position.x<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$rec#0", align 4
  ret i64 %0
}

define i64* @"position2.position.x<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position2.position.y<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = getelementptr i64, i64* %"$rec#0", i64 1
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position2.position.y<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  %3 = getelementptr i8, i8* %0, i64 8
  %4 = bitcast i8* %3 to i64*
  store i64 %"$field#0", i64* %4, align 4
  ret i64* %1
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

--------------------------------------------------
; ModuleID = 'position2.position'
source_filename = "test-cases"

declare i8* @wybe_malloc(i32) local_unnamed_addr

declare void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)

; Function Attrs: norecurse nounwind readnone
define i64* @"position2.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position2.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position2.position.=<2>"(i64* nocapture readonly %"$left#0", i64* nocapture readonly %"$right#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$left#0", align 4
  %1 = load i64, i64* %"$right#0", align 4
  %"tmp$2#0" = icmp eq i64 %0, %1
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = getelementptr i64, i64* %"$right#0", i64 1
  %3 = load i64, i64* %2, align 4
  %4 = getelementptr i64, i64* %"$left#0", i64 1
  %5 = load i64, i64* %4, align 4
  %"$$#0" = icmp eq i64 %5, %3
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position2.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position2.position.position<1>"(i64* nocapture readonly %"$#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$#0", align 4
  %1 = getelementptr i64, i64* %"$#0", i64 1
  %2 = load i64, i64* %1, align 4
  %3 = insertvalue { i64, i64 } undef, i64 %0, 0
  %4 = insertvalue { i64, i64 } %3, i64 %2, 1
  ret { i64, i64 } %4
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position2.position.x<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$rec#0", align 4
  ret i64 %0
}

define i64* @"position2.position.x<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position2.position.y<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = getelementptr i64, i64* %"$rec#0", i64 1
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position2.position.y<1>"(i64* %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  %2 = bitcast i64* %"$rec#0" to i8*
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* %0, i8* %2, i32 16, i1 false)
  %3 = getelementptr i8, i8* %0, i64 8
  %4 = bitcast i8* %3 to i64*
  store i64 %"$field#0", i64* %4, align 4
  ret i64* %1
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

