======================================================================
AFTER EVERYTHING:
 Module position1
  public submods  : 
  public types    : position: (position1.position,"pointer")
  public resources: 
  public procs    : position1.<0>
                    position1.position.=<0>
                    position1.position.=<1>
                    position1.position.=<2>
                    position1.position.position<0>
                    position1.position.position<1>
                    position1.position.x<0>
                    position1.position.x<1>
                    position1.position.y<0>
                    position1.position.y<1>
  imports         : public use position1.position
                    use wybe
  types           : position/0 (pointer)  @position1:1:8
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?tmp$5#0:position1.position)
    foreign lpvm mutate(~tmp$5#0:position1.position, ?tmp$6#0:position1.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, 111:wybe.int)
    foreign lpvm mutate(~tmp$6#0:position1.position, ?tmp$0#0:position1.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 222:wybe.int)
    foreign lpvm mutate(~tmp$0#0:position1.position, ?%posA#1:position1.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, 112:wybe.int)
    foreign lpvm access(~posA#1:position1.position, 8:wybe.int, ?tmp$2#0:wybe.int)
    foreign c print_int(~tmp$2#0:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?tmp$18#0:wybe.phantom) @wybe:76:38
    foreign c putchar('\n':wybe.char, ~tmp$18#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:74:28
  submodules      : position1.position
--------------------------------------------------
 Module position1.position([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position1.position.=<0>
                    position1.position.=<1>
                    position1.position.=<2>
                    position1.position.position<0>
                    position1.position.position<1>
                    position1.position.x<0>
                    position1.position.x<1>
                    position1.position.y<0>
                    position1.position.y<1>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:position1.position, in#0:position1.position): Alias Pairs: []

    foreign llvm move(~in#0:position1.position, ?out#0:position1.position)
= > public inline (0 calls)
1: =(in#0:position1.position, ?out#0:position1.position): Alias Pairs: []

    foreign llvm move(~in#0:position1.position, ?out#0:position1.position)
= > public inline test (3 calls)
2: =($left#0:position1.position, $right#0:position1.position, ?$$#0:wybe.bool): Alias Pairs: []

    foreign lpvm access($left#0:position1.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position1.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position1.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position1.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:28:40
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:28:40



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position1.position): Alias Pairs: []

    foreign lpvm alloc(16:wybe.int, ?$rec#0:position1.position)
    foreign lpvm mutate(~%$rec#0:position1.position, ?%$rec#1:position1.position, 16:wybe.int, 0:wybe.int, 1:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position1.position, ?%$#0:position1.position, 16:wybe.int, 8:wybe.int, 1:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position1.position): Alias Pairs: []

    foreign lpvm access($#0:position1.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position1.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position1.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position1.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position1.position, ?$rec#1:position1.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position1.position, ?%$rec#1:position1.position, 16:wybe.int, 0:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position1.position, ?$#0:wybe.int): Alias Pairs: []

    foreign lpvm access(~$rec#0:position1.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position1.position, ?$rec#1:position1.position, $field#0:wybe.int): Alias Pairs: []

    foreign lpvm mutate(~%$rec#0:position1.position, ?%$rec#1:position1.position, 16:wybe.int, 8:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
position1, position1.position
======================================================================
AFTER LLVM IR:

; ModuleID = 'position1'
source_filename = "test-cases/position1.wybe"

declare void @putchar(i8) local_unnamed_addr

declare void @print_int(i64) local_unnamed_addr

declare i8* @wybe_malloc(i32) local_unnamed_addr

define i32 @position1.main() local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 111, i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 112, i64* %3, align 4
  tail call void @print_int(i64 112)
  tail call void @putchar(i8 10)
  ret i32 0
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position1.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position1.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position1.position.=<2>"(i64* nocapture readonly %"$left#0", i64* nocapture readonly %"$right#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$left#0", align 4
  %1 = load i64, i64* %"$right#0", align 4
  %"tmp$2#0" = icmp eq i64 %0, %1
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = getelementptr i64, i64* %"$right#0", i64 1
  %3 = load i64, i64* %2, align 4
  %4 = getelementptr i64, i64* %"$left#0", i64 1
  %5 = load i64, i64* %4, align 4
  %"$$#0" = icmp eq i64 %5, %3
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position1.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position1.position.position<1>"(i64* nocapture readonly %"$#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$#0", align 4
  %1 = getelementptr i64, i64* %"$#0", i64 1
  %2 = load i64, i64* %1, align 4
  %3 = insertvalue { i64, i64 } undef, i64 %0, 0
  %4 = insertvalue { i64, i64 } %3, i64 %2, 1
  ret { i64, i64 } %4
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position1.position.x<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$rec#0", align 4
  ret i64 %0
}

define i64* @"position1.position.x<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  store i64 %"$field#0", i64* %"$rec#0", align 4
  ret i64* %"$rec#0"
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position1.position.y<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = getelementptr i64, i64* %"$rec#0", i64 1
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position1.position.y<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = getelementptr i64, i64* %"$rec#0", i64 1
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %"$rec#0"
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

--------------------------------------------------
; ModuleID = 'position1.position'
source_filename = "test-cases"

declare i8* @wybe_malloc(i32) local_unnamed_addr

; Function Attrs: norecurse nounwind readnone
define i64* @"position1.position.=<0>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readnone
define i64* @"position1.position.=<1>"(i64* readnone returned %"in#0") local_unnamed_addr #0 {
entry:
  ret i64* %"in#0"
}

; Function Attrs: norecurse nounwind readonly
define i1 @"position1.position.=<2>"(i64* nocapture readonly %"$left#0", i64* nocapture readonly %"$right#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$left#0", align 4
  %1 = load i64, i64* %"$right#0", align 4
  %"tmp$2#0" = icmp eq i64 %0, %1
  br i1 %"tmp$2#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = getelementptr i64, i64* %"$right#0", i64 1
  %3 = load i64, i64* %2, align 4
  %4 = getelementptr i64, i64* %"$left#0", i64 1
  %5 = load i64, i64* %4, align 4
  %"$$#0" = icmp eq i64 %5, %3
  ret i1 %"$$#0"

if.else:                                          ; preds = %entry
  ret i1 false
}

define i64* @"position1.position.position<0>"(i64 %"x#0", i64 %"y#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = bitcast i8* %0 to i64*
  store i64 %"x#0", i64* %1, align 4
  %2 = getelementptr i8, i8* %0, i64 8
  %3 = bitcast i8* %2 to i64*
  store i64 %"y#0", i64* %3, align 4
  ret i64* %1
}

; Function Attrs: norecurse nounwind readonly
define { i64, i64 } @"position1.position.position<1>"(i64* nocapture readonly %"$#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$#0", align 4
  %1 = getelementptr i64, i64* %"$#0", i64 1
  %2 = load i64, i64* %1, align 4
  %3 = insertvalue { i64, i64 } undef, i64 %0, 0
  %4 = insertvalue { i64, i64 } %3, i64 %2, 1
  ret { i64, i64 } %4
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position1.position.x<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = load i64, i64* %"$rec#0", align 4
  ret i64 %0
}

define i64* @"position1.position.x<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  store i64 %"$field#0", i64* %"$rec#0", align 4
  ret i64* %"$rec#0"
}

; Function Attrs: norecurse nounwind readonly
define i64 @"position1.position.y<0>"(i64* nocapture readonly %"$rec#0") local_unnamed_addr #1 {
entry:
  %0 = getelementptr i64, i64* %"$rec#0", i64 1
  %1 = load i64, i64* %0, align 4
  ret i64 %1
}

define i64* @"position1.position.y<1>"(i64* returned %"$rec#0", i64 %"$field#0") local_unnamed_addr {
entry:
  %0 = tail call i8* @wybe_malloc(i32 16)
  %1 = getelementptr i64, i64* %"$rec#0", i64 1
  store i64 %"$field#0", i64* %1, align 4
  ret i64* %"$rec#0"
}

attributes #0 = { norecurse nounwind readnone }
attributes #1 = { norecurse nounwind readonly }

