======================================================================
AFTER EVERYTHING:
 Module proc_beer
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_beer.beer99<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

beer99 > public (0 calls) (inline)
0: beer99(wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    proc_beer.gen$1<0>(99:wybe.int, ~wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom) @proc_beer:5:5


gen$1 > (2 calls)
0: gen$1(count#0:wybe.int, wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp sge(count#0:wybe.int, 0:wybe.int, ?tmp$4#0:wybe.bool) @wybe:18:40
    case ~tmp$4#0:wybe.bool of
    0:
        foreign llvm move(~wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom)

    1:
        foreign c print_int(count#0:wybe.int, ~wybe.io$io#0:wybe.phantom, ?tmp$8#0:wybe.phantom) @wybe:104:38
        foreign c print_string(" bottles of beer on the wall":wybe.string, ~tmp$8#0:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:116:41
        foreign c putchar('\n':wybe.char, ~tmp$9#0:wybe.phantom, ?tmp$10#0:wybe.phantom) @wybe:102:28
        foreign llvm sub(~count#0:wybe.int, 1:wybe.int, ?tmp$11#0:wybe.int) @wybe:7:38
        proc_beer.gen$1<0>(~tmp$11#0:wybe.int, ~tmp$10#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom) @proc_beer:5:5



gen$4 > (1 calls) (inline)
0: gen$4([count#0:wybe.int], [tmp$0#0:wybe.bool], wybe.io$io#0:wybe.phantom, [?wybe.io$io#0:wybe.phantom]):


gen$6 > (1 calls) (inline)
0: gen$6(count#0:wybe.int, [tmp$0#0:wybe.bool], wybe.io$io#0:wybe.phantom, ?wybe.io$io#3:wybe.phantom):
    foreign c print_int(count#0:wybe.int, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:104:38
    foreign c print_string(" bottles of beer on the wall":wybe.string, ~#wybe.io$io#1:wybe.phantom, ?tmp$6#0:wybe.phantom) @wybe:116:41
    foreign c putchar('\n':wybe.char, ~tmp$6#0:wybe.phantom, ?#wybe.io$io#2:wybe.phantom) @wybe:102:28
    foreign llvm sub(~count#0:wybe.int, 1:wybe.int, ?tmp$9#0:wybe.int) @wybe:7:38
    proc_beer.gen$1<0>(~tmp$9#0:wybe.int, ~wybe.io$io#2:wybe.phantom, ?wybe.io$io#3:wybe.phantom) @proc_beer:5:5
proc_beer
======================================================================
AFTER LLVM IR:

; ModuleID = 'proc_beer'

@0 = constant [29 x i8] c" bottles of beer on the wall\00"

declare void @putchar(i8)

declare void @print_string(i8*)

declare void @print_int(i64)

declare i8* @wybe_malloc(i32)

define void @"proc_beer.beer99<0>"() {
entry:
  tail call void @"proc_beer.gen$1<0>"(i64 99)
  ret void
}

define void @"proc_beer.gen$1<0>"(i64 %"count#0") {
entry:
  %"tmp$4#0" = icmp sge i64 %"count#0", 0
  br i1 %"tmp$4#0", label %if.then, label %if.else

if.then:                                          ; preds = %entry
  tail call void @print_int(i64 %"count#0")
  tail call void @print_string(i8* getelementptr inbounds ([29 x i8]* @0, i32 0, i32 0))
  tail call void @putchar(i8 10)
  %"tmp$11#0" = sub i64 %"count#0", 1
  tail call void @"proc_beer.gen$1<0>"(i64 %"tmp$11#0")
  ret void

if.else:                                          ; preds = %entry
  ret void
}

define void @"proc_beer.gen$6<0>"(i64 %"count#0") {
entry:
  tail call void @print_int(i64 %"count#0")
  tail call void @print_string(i8* getelementptr inbounds ([29 x i8]* @0, i32 0, i32 0))
  tail call void @putchar(i8 10)
  %"tmp$9#0" = sub i64 %"count#0", 1
  tail call void @"proc_beer.gen$1<0>"(i64 %"tmp$9#0")
  ret void
}

