Public proc yorn(prompt:string, ?result:bool) {proc-yorn:1:8}[do print(prompt {proc-yorn:2:18}) {proc-yorn:2:12} {proc-yorn:2:12}print(" (y/n) " {proc-yorn:3:18}) {proc-yorn:3:12} {proc-yorn:3:12}read_char(?response {proc-yorn:4:22}) {proc-yorn:4:12} {proc-yorn:4:12}=(?result {proc-yorn:5:12}, is_yes(response {proc-yorn:5:29}) {proc-yorn:5:22}) {proc-yorn:5:12} {proc-yorn:5:12}unless is_yes_or_no(response {proc-yorn:6:32}) {proc-yorn:6:19} {proc-yorn:6:12}println("Please answer 'yes' or 'no'." {proc-yorn:7:20}) {proc-yorn:7:12} {proc-yorn:7:12}until is_yes_or_no(response {proc-yorn:8:31}) {proc-yorn:8:18} {proc-yorn:8:12} end {proc-yorn:2:8}]

 Module proc-yorn
  public submods  : 
  public types    : 
  public resources: 
  public procs    : yorn(prompt:string, ?result:bool) <1> {proc-yorn:1:8}
  imports         : 
  types           : 
  resources       : 
  procs           : yorn: [
proc yorn(prompt:string, ?result:bool) (id 1):  {proc-yorn:1:8}
    do  {proc-yorn:2:8}
        print(prompt) {proc-yorn:2:12}
        print(" (y/n) ") {proc-yorn:3:12}
        read_char(?response) {proc-yorn:4:12}
        is_yes(response, ?$tmp4) {proc-yorn:5:22}
        =(?result, $tmp4) {proc-yorn:5:12}
        is_yes_or_no(response, ?$tmp2) {proc-yorn:6:19}
        =(?$tmp3, $tmp2) {?}
        unless $tmp3 {proc-yorn:6:12}
        println("Please answer 'yes' or 'no'.") {proc-yorn:7:12}
        is_yes_or_no(response, ?$tmp0) {proc-yorn:8:18}
        =(?$tmp1, $tmp0) {?}
        until $tmp1 {proc-yorn:8:12}
    end]

Submodules of proc-yorn:

