Public proc print2(x:int, y:int) {proc-beer:1:8}[do for count from 99 {proc-beer:2:29} by -1 {?} to ("<",0 {proc-beer:2:38}) {proc-beer:2:12}println("$count bottles of beer on the wall" {proc-beer:3:20}) {proc-beer:3:12} {proc-beer:3:12} end {proc-beer:2:8}]

 Module proc-beer
  public submods  : 
  public types    : 
  public resources: 
  public procs    : print2(x:0:int, y:0:int) <0> {proc-beer:1:8}
  imports         : 
  types           : 
  resources       : 
  procs           : print2:
proc print2(x:0:int, y:0:int) (id 0):  {proc-beer:1:8}
    =(?count:0, 99) {?}
    do  {proc-beer:2:8}
        <(count:0, 0, ?$tmp0:0) {?}
        until $tmp0:0 {?}
        println("$count bottles of beer on the wall") {proc-beer:3:12}
        -(count:0, 1, ?count:0) {?}
    end

Submodules of proc-beer:

