Public proc print2(x:int, y:int) {proc-beer:1:8}[do for count from 99 {proc-beer:2:29} by -1 {?} to ("<",0 {proc-beer:2:38}) {proc-beer:2:12}println("$count bottles of beer on the wall" {proc-beer:3:20}) {proc-beer:3:12} {proc-beer:3:12} end {proc-beer:2:8}]

 Module proc-beer
  imports         : 
  public submods  : 
  public types    : 
  public resources: 
  public procs    : print2
  types           : 
  resources       : 
  procs           : print2: [
proc print2(x:int, y:int) (id 1):  {proc-beer:1:8}
    =(?count, 99) {?}
    do  {proc-beer:2:8}
        <(count, 0, ?$tmp0) {?}
        until $tmp0 {?}
        println("$count bottles of beer on the wall") {proc-beer:3:12}
        -(count, 1, ?count) {?}
    end]

Submodules of proc-beer:

