 Module proc_allin
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_allin.nada<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : nada:
public proc nada(x:0:int, y:0:int)<0>  @proc_allin:1:8 (0 calls)
    foreign llvm add(32:int, x:0:int, y:0:int, ?~tmp$0:0:int) @wybe:4:38
    wybe.int.=<0>(?~$:0:int, ~tmp$0:0:int)
