======================================================================
AFTER EVERYTHING:
 Module proc_allin
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_allin.nada<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

nada > public (0 calls) (inline)
0: nada([x#0:wybe.int], [y#0:wybe.int]):
proc_allin
======================================================================
AFTER LLVM IR:

; ModuleID = 'proc_allin'

declare i8* @wybe_malloc(i32)

