======================================================================
AFTER EVERYTHING:
 Module proc_hello
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_hello.print2<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
public (0 calls) (inline)
0: print2([x#0:wybe.int], [y#0:wybe.int], wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_string("hello, world":wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$0#0:wybe.phantom) @wybe:122:41
    foreign c putc('\n':wybe.char, ~%tmp$0#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:108:28
