 Module proc_yorn2
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_yorn2.yorn<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
(0 calls) (inline)
0: gen$1(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, tmp$1#0:wybe.bool, tmp$2#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#0:wybe.string, ?response#0:wybe.char, ?result#0:wybe.bool, ?tmp$0#0:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#0:wybe.phantom):

(0 calls)
0: gen$2(prompt#0:wybe.string, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#4:wybe.phantom):
    foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:122:41
    foreign c print_string(" (y/n) ":wybe.string, ~%wybe.io$io#1:wybe.phantom, ?%wybe.io$io#2:wybe.phantom) @wybe:122:41
    foreign c read_char(?response#0:wybe.char, ~%wybe.io$io#2:wybe.phantom, ?%wybe.io$io#3:wybe.phantom) @wybe:120:39
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'Y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$0#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    proc_yorn2.gen$3<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~tmp$0#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#3:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#4:wybe.phantom) @proc_yorn2:6:9

(0 calls)
0: gen$3(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#1:wybe.bool, ?tmp$2#1:wybe.bool, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'N':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$2#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm or(result#0:wybe.bool, tmp$2#0:wybe.bool, ?tmp$1#0:wybe.bool) @wybe:54:43
    case tmp$1#0 of
    0:
        proc_yorn2.gen$4<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~result#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom)
        foreign wybe move(?tmp$1#1, ~tmp$1#0)
        foreign wybe move(?tmp$2#1, ~tmp$2#0)

    1:


(0 calls) (inline)
0: gen$4(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#2:wybe.phantom):
    foreign c print_string("Please answer 'yes' or 'no'.":wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$3#0:wybe.phantom) @wybe:122:41
    foreign c putc('\n':wybe.char, ~%tmp$3#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:108:28
    proc_yorn2.gen$2<0>(~prompt#0:wybe.string, ~wybe.io$io#1:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#2:wybe.phantom) @proc_yorn2:2:5

public (0 calls)
0: yorn(prompt#0:wybe.string, ?result#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    proc_yorn2.gen$2<0>(~prompt#0:wybe.string, ~wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#0:wybe.char, ?result#0:wybe.bool, ?tmp$0#0:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn2:2:5
