Public proc nada(x:int, y:int) {proc-allin:1:8}[=(?z {proc-allin:1:33}, +(x {proc-allin:1:35}, y {proc-allin:1:37}) {proc-allin:1:35}) {proc-allin:1:33}]
Module
  imports         : 
  public types    : 
  public resources: 
  public procs    : nada
  types:          : 
  resources       : 
  procs           : nada: [proc 1: nada(x:int, y:int) {proc-allin:1:8}
    +(x, y, ?$tmp0) {proc-allin:1:35}
    =(?z, $tmp0) {proc-allin:1:33}]

