public proc yorn(prompt:string, ?result:bool) @proc-yorn:1:8
    do
        print(prompt @proc-yorn:2:18)
        print(" (y/n) " @proc-yorn:3:18)
        read_char(?response @proc-yorn:4:22)
        =(?result @proc-yorn:5:12, is_yes(response @proc-yorn:5:29) @proc-yorn:5:22)
        if:
            is_yes_or_no(response @proc-yorn:6:32)
        then:
            nop
        else:
            next
        end
        println("Please answer 'yes' or 'no'." @proc-yorn:7:20)
        if:
            is_yes_or_no(response @proc-yorn:8:31)
        then:
            break
        else:
            nop
        end
     end


 Module proc-yorn
  public submods  : 
  public types    : 
  public resources: 
  public procs    : yorn(prompt:0:string, ?result:0:bool) <0> @proc-yorn:1:8
  imports         : 
  types           : 
  resources       : 
  procs           : gen$1:
proc gen$1(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:0:?, ?response:0:?, ?result:0:?, ?tmp$0:0:?) (id 0): 
                    gen$2:
proc gen$2(prompt:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    print(prompt:0) @proc-yorn:2:12
    print(" (y/n) ") @proc-yorn:3:12
    read_char(?response:0) @proc-yorn:4:12
    is_yes(response:0, ?tmp$0:0) @proc-yorn:5:22
    =(?result:0, tmp$0:0) @proc-yorn:5:12
    gen$3(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc-yorn:6:12
                    gen$3:
proc gen$3(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    begin guard 1
        is_yes_or_no(response:0) @proc-yorn:6:19
    end guard 
    gen$6(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)

    begin guard 0
        is_yes_or_no(response:0) @proc-yorn:6:19
    end guard 
    gen$2(prompt:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc-yorn:2:8
                    gen$4:
proc gen$4(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    begin guard 1
        is_yes_or_no(response:0) @proc-yorn:8:18
    end guard 
    gen$1(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)

    begin guard 0
        is_yes_or_no(response:0) @proc-yorn:8:18
    end guard 
    gen$5(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)
                    gen$5:
proc gen$5(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    gen$2(prompt:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc-yorn:2:8
                    gen$6:
proc gen$6(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    println("Please answer 'yes' or 'no'.") @proc-yorn:7:12
    gen$4(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc-yorn:8:12
                    yorn:
proc yorn(prompt:0:string, ?result:0:bool) (id 0):  @proc-yorn:1:8
    gen$2(prompt:0, ?prompt:1, ?response:0, ?result:0, ?tmp$0:0) @proc-yorn:2:8

Submodules of proc-yorn:

