Public proc print2(x:int, y:int) {proc-print2:1:8}[print(x {proc-print2:2:14}) {proc-print2:2:8},print(y {proc-print2:3:14}) {proc-print2:3:8}]
Module
  imports         : 
  public types    : 
  public resources: 
  public procs    : print2
  types           : 
  resources       : 
  procs           : print2: [
proc print2(x:int, y:int) (id 1):  {proc-print2:1:8}
    print(x) {proc-print2:2:8}
    print(y) {proc-print2:3:8}]

