======================================================================
AFTER EVERYTHING:
 Module proc_yorn
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_yorn.yorn<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
(0 calls) (inline)
0: gen$1(tmp$2#0:wybe.bool, wybe.io$io#0:wybe.phantom, [?tmp$2#0:wybe.bool], [?wybe.io$io#0:wybe.phantom]):

(0 calls) (inline)
0: gen$2(prompt#0:wybe.string, wybe.io$io#0:wybe.phantom, ?tmp$2#0:wybe.bool, ?wybe.io$io#4:wybe.phantom):
    foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:122:41
    foreign c print_string(" (y/n) ":wybe.string, ~%wybe.io$io#1:wybe.phantom, ?%wybe.io$io#2:wybe.phantom) @wybe:122:41
    foreign c read_char(?response#0:wybe.char, ~%wybe.io$io#2:wybe.phantom, ?%wybe.io$io#3:wybe.phantom) @wybe:120:39
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$4#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'Y':wybe.char, ?tmp$5#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$6#0:wybe.bool, ~tmp$5#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$4#0:wybe.bool, ~tmp$6#0:wybe.bool, ?tmp$0#0:wybe.bool) @wybe:54:43
    proc_yorn.gen$3<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~tmp$0#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#3:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?wybe.io$io#4:wybe.phantom) @proc_yorn:6:12

(4 calls)
0: gen$3(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$4#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'Y':wybe.char, ?tmp$5#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$6#0:wybe.bool, ~tmp$5#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$4#0:wybe.bool, ~tmp$6#0:wybe.bool, ?tmp$7#0:wybe.bool) @wybe:54:43
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'n':wybe.char, ?tmp$8#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$9#0:wybe.bool, ~tmp$8#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'N':wybe.char, ?tmp$10#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$11#0:wybe.bool, ~tmp$10#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$9#0:wybe.bool, ~tmp$11#0:wybe.bool, ?tmp$12#0:wybe.bool) @wybe:54:43
    foreign llvm or(~tmp$7#0:wybe.bool, ~tmp$12#0:wybe.bool, ?tmp$1#0:wybe.bool) @wybe:54:43
    case ~tmp$1#0 of
    0:
        foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$13#0:wybe.phantom) @wybe:122:41
        foreign c print_string(" (y/n) ":wybe.string, ~%tmp$13#0:wybe.phantom, ?%tmp$14#0:wybe.phantom) @wybe:122:41
        foreign c read_char(?tmp$15#0:wybe.char, ~%tmp$14#0:wybe.phantom, ?%tmp$16#0:wybe.phantom) @wybe:120:39
        foreign llvm icmp eq(32:wybe.int, tmp$15#0:wybe.char, 'y':wybe.char, ?tmp$17#0:wybe.bool) @wybe:70:42
        wybe.bool.=<0>(?tmp$18#0:wybe.bool, ~tmp$17#0:wybe.bool) @wybe:70:12
        foreign llvm icmp eq(32:wybe.int, tmp$15#0:wybe.char, 'Y':wybe.char, ?tmp$19#0:wybe.bool) @wybe:70:42
        wybe.bool.=<0>(?tmp$20#0:wybe.bool, ~tmp$19#0:wybe.bool) @wybe:70:12
        foreign llvm or(~tmp$18#0:wybe.bool, ~tmp$20#0:wybe.bool, ?tmp$21#0:wybe.bool) @wybe:54:43
        proc_yorn.gen$3<0>(prompt#0:wybe.string, ~tmp$15#0:wybe.char, ~tmp$21#0:wybe.bool, ~tmp$21#0:wybe.bool, ~tmp$16#0:wybe.phantom, ?tmp$22#0:wybe.string, ?tmp$23#0:wybe.char, ?tmp$24#0:wybe.bool, ?tmp$25#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn:6:12
        foreign wybe move(~prompt#0, ?prompt#1)
        foreign wybe move(~response#0, ?response#1)
        foreign wybe move(~result#0, ?result#1)
        foreign wybe move(~tmp$0#0, ?tmp$0#1)

    1:
        proc_yorn.gen$6<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~result#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?wybe.io$io#1:wybe.phantom)


(1 calls)(subproc of proc_yorn.gen$6<0>)
0: gen$4(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$4#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'Y':wybe.char, ?tmp$5#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$6#0:wybe.bool, ~tmp$5#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$4#0:wybe.bool, ~tmp$6#0:wybe.bool, ?tmp$7#0:wybe.bool) @wybe:54:43
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'n':wybe.char, ?tmp$8#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$9#0:wybe.bool, ~tmp$8#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'N':wybe.char, ?tmp$10#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$11#0:wybe.bool, ~tmp$10#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$9#0:wybe.bool, ~tmp$11#0:wybe.bool, ?tmp$12#0:wybe.bool) @wybe:54:43
    foreign llvm or(~tmp$7#0:wybe.bool, ~tmp$12#0:wybe.bool, ?tmp$2#0:wybe.bool) @wybe:54:43
    case tmp$2#0 of
    0:
        proc_yorn.gen$5<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~result#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom)

    1:
        NOP
        foreign wybe move(~prompt#0, ?prompt#1)
        foreign wybe move(~response#0, ?response#1)
        foreign wybe move(~result#0, ?result#1)
        foreign wybe move(~tmp$0#0, ?tmp$0#1)
        foreign wybe move(~wybe.io$io#0, ?wybe.io$io#1)


(1 calls) (inline)(subproc of proc_yorn.gen$4<0>)
0: gen$5(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, [?prompt#0:wybe.string], [?response#0:wybe.char], [?result#0:wybe.bool], [?tmp$0#0:wybe.bool], ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom):
    foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$3#0:wybe.phantom) @wybe:122:41
    foreign c print_string(" (y/n) ":wybe.string, ~%tmp$3#0:wybe.phantom, ?%tmp$4#0:wybe.phantom) @wybe:122:41
    foreign c read_char(?tmp$5#0:wybe.char, ~%tmp$4#0:wybe.phantom, ?%tmp$6#0:wybe.phantom) @wybe:120:39
    foreign llvm icmp eq(32:wybe.int, tmp$5#0:wybe.char, 'y':wybe.char, ?tmp$7#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$8#0:wybe.bool, ~tmp$7#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, tmp$5#0:wybe.char, 'Y':wybe.char, ?tmp$9#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$10#0:wybe.bool, ~tmp$9#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$8#0:wybe.bool, ~tmp$10#0:wybe.bool, ?tmp$11#0:wybe.bool) @wybe:54:43
    proc_yorn.gen$3<0>(prompt#0:wybe.string, ~tmp$5#0:wybe.char, ~tmp$11#0:wybe.bool, ~tmp$11#0:wybe.bool, ~tmp$6#0:wybe.phantom, ?tmp$12#0:wybe.string, ?tmp$13#0:wybe.char, ?tmp$14#0:wybe.bool, ?tmp$15#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn:6:12

(1 calls) (inline)(subproc of proc_yorn.gen$3<0>)
0: gen$6(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?wybe.io$io#2:wybe.phantom):
    foreign c print_string("Please answer 'yes' or 'no'.":wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$3#0:wybe.phantom) @wybe:122:41
    foreign c putc('\n':wybe.char, ~%tmp$3#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:108:28
    proc_yorn.gen$4<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~result#0:wybe.bool, ~tmp$0#0:wybe.bool, ~wybe.io$io#1:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#2:wybe.phantom) @proc_yorn:8:12

(0 calls) (inline)
0: is_yes(ch#0:wybe.char, ?tmp$0#0:wybe.bool):
    foreign llvm icmp eq(32:wybe.int, ch#0:wybe.char, 'y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$1#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, ~ch#0:wybe.char, 'Y':wybe.char, ?tmp$4#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$2#0:wybe.bool, ~tmp$4#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$1#0:wybe.bool, ~tmp$2#0:wybe.bool, ?tmp$0#0:wybe.bool) @wybe:54:43

(0 calls) (inline)
0: is_yes_or_no(ch#0:wybe.char, ?tmp$0#0:wybe.bool):
    foreign llvm icmp eq(32:wybe.int, ch#0:wybe.char, 'y':wybe.char, ?tmp$5#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$6#0:wybe.bool, ~tmp$5#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, ch#0:wybe.char, 'Y':wybe.char, ?tmp$7#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$8#0:wybe.bool, ~tmp$7#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$6#0:wybe.bool, ~tmp$8#0:wybe.bool, ?tmp$1#0:wybe.bool) @wybe:54:43
    foreign llvm icmp eq(32:wybe.int, ch#0:wybe.char, 'n':wybe.char, ?tmp$9#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$3#0:wybe.bool, ~tmp$9#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, ~ch#0:wybe.char, 'N':wybe.char, ?tmp$10#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$4#0:wybe.bool, ~tmp$10#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$3#0:wybe.bool, ~tmp$4#0:wybe.bool, ?tmp$2#0:wybe.bool) @wybe:54:43
    foreign llvm or(~tmp$1#0:wybe.bool, ~tmp$2#0:wybe.bool, ?tmp$0#0:wybe.bool) @wybe:54:43

public (0 calls)
0: yorn(prompt#0:wybe.string, ?result#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$3#0:wybe.phantom) @wybe:122:41
    foreign c print_string(" (y/n) ":wybe.string, ~%tmp$3#0:wybe.phantom, ?%tmp$4#0:wybe.phantom) @wybe:122:41
    foreign c read_char(?tmp$5#0:wybe.char, ~%tmp$4#0:wybe.phantom, ?%tmp$6#0:wybe.phantom) @wybe:120:39
    foreign llvm icmp eq(32:wybe.int, tmp$5#0:wybe.char, 'y':wybe.char, ?tmp$7#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$8#0:wybe.bool, ~tmp$7#0:wybe.bool) @wybe:70:12
    foreign llvm icmp eq(32:wybe.int, tmp$5#0:wybe.char, 'Y':wybe.char, ?tmp$9#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$10#0:wybe.bool, ~tmp$9#0:wybe.bool) @wybe:70:12
    foreign llvm or(~tmp$8#0:wybe.bool, ~tmp$10#0:wybe.bool, ?tmp$11#0:wybe.bool) @wybe:54:43
    proc_yorn.gen$3<0>(~prompt#0:wybe.string, ~tmp$5#0:wybe.char, ~tmp$11#0:wybe.bool, ~tmp$11#0:wybe.bool, ~tmp$6#0:wybe.phantom, ?tmp$12#0:wybe.string, ?tmp$13#0:wybe.char, ?tmp$14#0:wybe.bool, ?tmp$15#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn:6:12
