
 Module proc_yorn
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_yorn.yorn<0>
  imports         : 
  types           : 
  resources       : 
  procs           : gen$1:
proc gen$1(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:0:?, ?response:0:?, ?result:0:?, ?tmp$0:0:?) (id 0): 
                    gen$2:
proc gen$2(prompt:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    print(prompt:0) @proc_yorn:2:12
    print(" (y/n) ") @proc_yorn:3:12
    read_char(?response:0) @proc_yorn:4:12
    is_yes(response:0, ?tmp$0:0) @proc_yorn:5:22
    proc_yorn.gen$3(prompt:0, response:0, tmp$0:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc_yorn:6:12
                    gen$3:
proc gen$3(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    begin guard 1
        is_yes_or_no(response:0) @proc_yorn:6:19
    end guard 
    proc_yorn.gen$6(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)

    begin guard 0
        is_yes_or_no(response:0) @proc_yorn:6:19
    end guard 
    proc_yorn.gen$2(prompt:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc_yorn:2:8
                    gen$4:
proc gen$4(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    begin guard 1
        is_yes_or_no(response:0) @proc_yorn:8:18
    end guard 
    proc_yorn.gen$1(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)

    begin guard 0
        is_yes_or_no(response:0) @proc_yorn:8:18
    end guard 
    proc_yorn.gen$5(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1)
                    gen$5:
proc gen$5(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    proc_yorn.gen$2(prompt:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc_yorn:2:8
                    gen$6:
proc gen$6(prompt:0:?, response:0:?, result:0:?, tmp$0:0:?, ?prompt:1:?, ?response:1:?, ?result:1:?, ?tmp$0:1:?) (id 0): 
    println("Please answer 'yes' or 'no'.") @proc_yorn:7:12
    proc_yorn.gen$4(prompt:0, response:0, result:0, tmp$0:0, ?prompt:1, ?response:1, ?result:1, ?tmp$0:1) @proc_yorn:8:12
                    yorn:
public proc yorn(prompt:0:string, ?result:0:bool) (id 0):  @proc_yorn:1:8
    proc_yorn.gen$2(prompt:0, ?prompt:1, ?response:0, ?result:0, ?tmp$0:0) @proc_yorn:2:8

