======================================================================
AFTER EVERYTHING:
 Module proc_hello
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_hello.print2<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

print2 > public inline (0 calls)
0: print2([x#0:wybe.int], [y#0:wybe.int], io#0:phantom, ?io#1:phantom):
    foreign c print_string("hello, world":wybe.string, ~#io#0:phantom, ?tmp$2#0:phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$2#0:phantom, ?#io#1:phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'proc_hello'


declare external ccc void @putchar(i8)

declare external ccc void @print_string(i8*)

@proc_hello.1 = constant [13 x i8] c"hello, world\00"

declare external ccc i8* @wybe_malloc(i32)

define external ccc void @"proc_hello.print2<0>"(){
entry:
  tail call ccc void @print_string(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @proc_hello.1, i32 0, i32 0))
  tail call ccc void @putchar(i8 10)
  ret void
}
