======================================================================
AFTER EVERYTHING:
 Module proc_yorn2
  public submods  : 
  public types    : 
  public resources: 
  public procs    : proc_yorn2.yorn<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
(0 calls) (inline)
0: gen$1(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, tmp$1#0:wybe.bool, tmp$2#0:wybe.bool, wybe.io$io#0:wybe.phantom, [?prompt#0:wybe.string], [?response#0:wybe.char], [?result#0:wybe.bool], [?tmp$0#0:wybe.bool], [?tmp$1#0:wybe.bool], [?tmp$2#0:wybe.bool], [?wybe.io$io#0:wybe.phantom]):

(2 calls)
0: gen$2(prompt#0:wybe.string, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#4:wybe.phantom):
    foreign c print_string(prompt#0:wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:122:41
    foreign c print_string(" (y/n) ":wybe.string, ~%wybe.io$io#1:wybe.phantom, ?%wybe.io$io#2:wybe.phantom) @wybe:122:41
    foreign c read_char(?response#0:wybe.char, ~%wybe.io$io#2:wybe.phantom, ?%wybe.io$io#3:wybe.phantom) @wybe:120:39
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'Y':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.char.=<2>(response#0:wybe.char, 'N':wybe.char, ?tmp$2#0:wybe.bool) @proc_yorn2:6:26
    wybe.bool.or<0>(tmp$3#0:wybe.bool, tmp$2#0:wybe.bool, ?tmp$1#0:wybe.bool) @proc_yorn2:6:15
    case tmp$1#0 of
    0:
        proc_yorn2.gen$4<0>(~prompt#0:wybe.string, ~response#0:wybe.char, ~tmp$3#0:wybe.bool, ~tmp$3#0:wybe.bool, ~wybe.io$io#3:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#4:wybe.phantom)

    1:
        foreign wybe move(~prompt#0:wybe.string, ?prompt#1:wybe.string)
        foreign wybe move(~response#0:wybe.char, ?response#1:wybe.char)
        foreign wybe move(tmp$3#0:wybe.bool, ?result#1:wybe.bool)
        foreign wybe move(~tmp$3#0:wybe.bool, ?tmp$0#1:wybe.bool)
        foreign wybe move(~wybe.io$io#3:wybe.phantom, ?wybe.io$io#4:wybe.phantom)


(1 calls)
0: gen$3(prompt#0:wybe.string, response#0:wybe.char, result#0:wybe.bool, tmp$0#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp eq(32:wybe.int, response#0:wybe.char, 'N':wybe.char, ?tmp$3#0:wybe.bool) @wybe:70:42
    wybe.bool.=<0>(?tmp$2#0:wybe.bool, ~tmp$3#0:wybe.bool) @wybe:70:12
    foreign llvm or(result#0:wybe.bool, tmp$2#0:wybe.bool, ?tmp$4#0:wybe.bool) @wybe:54:43
    foreign llvm move(tmp$4#0:wybe.bool, ?tmp$1#0:wybe.bool)
    case ~tmp$4#0 of
    0:
        wybe.io.println<3>("Please answer 'yes' or 'no'.":wybe.string, ~#wybe.io$io#0:wybe.phantom, ?#tmp$5#0:wybe.phantom) @proc_yorn2:7:9
        proc_yorn2.gen$2<0>(~prompt#0:wybe.string, ~tmp$5#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$4#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn2:2:5

    1:
        foreign wybe move(~prompt#0, ?prompt#1)
        foreign wybe move(~response#0, ?response#1)
        foreign wybe move(~result#0, ?result#1)
        foreign wybe move(~tmp$0#0, ?tmp$0#1)
        foreign wybe move(~wybe.io$io#0, ?wybe.io$io#1)


(1 calls) (inline)
0: gen$4(prompt#0:wybe.string, [response#0:wybe.char], [result#0:wybe.bool], [tmp$0#0:wybe.bool], wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#2:wybe.phantom):
    foreign c print_string("Please answer 'yes' or 'no'.":wybe.string, ~%wybe.io$io#0:wybe.phantom, ?%tmp$3#0:wybe.phantom) @wybe:122:41
    foreign c putc('\n':wybe.char, ~%tmp$3#0:wybe.phantom, ?%wybe.io$io#1:wybe.phantom) @wybe:108:28
    proc_yorn2.gen$2<0>(~prompt#0:wybe.string, ~wybe.io$io#1:wybe.phantom, ?prompt#1:wybe.string, ?response#1:wybe.char, ?result#1:wybe.bool, ?tmp$0#1:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#2:wybe.phantom) @proc_yorn2:2:5

public (0 calls)
0: yorn(prompt#0:wybe.string, ?result#0:wybe.bool, wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    proc_yorn2.gen$2<0>(~prompt#0:wybe.string, ~wybe.io$io#0:wybe.phantom, ?prompt#1:wybe.string, ?response#0:wybe.char, ?result#0:wybe.bool, ?tmp$0#0:wybe.bool, ?tmp$1#0:wybe.bool, ?tmp$2#0:wybe.bool, ?wybe.io$io#1:wybe.phantom) @proc_yorn2:2:5
