======================================================================
AFTER EVERYTHING:
 Module res_decl
  public submods  : 
  public types    : 
  public resources: count: res_decl.count
  public procs    : 
  imports         : use wybe
  types           : 
  resources       : count: fromList [(res_decl.count,Just wybe.int @res_decl:1:8)] @res_decl:1:8
  procs           : 


  LLVM code       :

; ModuleID = 'res_decl'


declare external ccc i8* @wybe_malloc(i32)
