======================================================================
AFTER EVERYTHING:
 Module simple_loop
  public submods  : 
  public types    : 
  public resources: 
  public procs    : simple_loop.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    simple_loop.gen$1<0>(~wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom) @simple_loop:1:1


gen$1 > (2 calls)
0: gen$1(wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom):
    foreign c read_char(?c#0:wybe.char, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:85:39
    foreign llvm icmp ne(c#0:wybe.char, 'a':wybe.char, ?tmp$4#0:wybe.bool) @wybe:67:42
    case ~tmp$4#0:wybe.bool of
    0:
        foreign llvm move(~wybe.io$io#1:wybe.phantom, ?wybe.io$io#2:wybe.phantom)

    1:
        foreign c putchar(~c#0:wybe.char, ~wybe.io$io#1:wybe.phantom, ?tmp$8#0:wybe.phantom) @wybe:83:39
        simple_loop.gen$1<0>(~tmp$8#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom) @simple_loop:1:1



gen$3 > inline (1 calls)
0: gen$3([c#0:wybe.char], [tmp$0#0:wybe.bool], wybe.io$io#0:wybe.phantom, [?wybe.io$io#0:wybe.phantom]):


gen$4 > inline (1 calls)
0: gen$4(c#0:wybe.char, [tmp$0#0:wybe.bool], wybe.io$io#0:wybe.phantom, ?wybe.io$io#2:wybe.phantom):
    foreign c putchar(~c#0:wybe.char, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:83:39
    simple_loop.gen$1<0>(~wybe.io$io#1:wybe.phantom, ?wybe.io$io#2:wybe.phantom) @simple_loop:1:1
simple_loop
======================================================================
AFTER LLVM IR:

; ModuleID = 'simple_loop'

; Function Attrs: nounwind
declare void @putchar(i8) #0

declare i8 @read_char()

define i32 @simple_loop.main() {
entry:
  tail call void @"simple_loop.gen$1<0>"()
  ret i32 0
}

define void @"simple_loop.gen$1<0>"() {
entry:
  %"c#01" = tail call i8 @read_char()
  %"tmp$4#02" = icmp eq i8 %"c#01", 97
  br i1 %"tmp$4#02", label %if.else, label %if.then.preheader

if.then.preheader:                                ; preds = %entry
  br label %if.then

if.then:                                          ; preds = %if.then.preheader, %if.then
  %"c#03" = phi i8 [ %"c#0", %if.then ], [ %"c#01", %if.then.preheader ]
  tail call void @putchar(i8 %"c#03")
  %"c#0" = tail call i8 @read_char()
  %"tmp$4#0" = icmp eq i8 %"c#0", 97
  br i1 %"tmp$4#0", label %if.else.loopexit, label %if.then

if.else.loopexit:                                 ; preds = %if.then
  br label %if.else

if.else:                                          ; preds = %if.else.loopexit, %entry
  ret void
}

define void @"simple_loop.gen$4<0>"(i8 %"c#0") {
entry:
  tail call void @putchar(i8 %"c#0")
  tail call void @"simple_loop.gen$1<0>"()
  ret void
}

attributes #0 = { nounwind }

