======================================================================
AFTER EVERYTHING:
 Module simple_loop
  public submods  : 
  public types    : 
  public resources: 
  public procs    : simple_loop.<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
public (0 calls) (inline)
0: (wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom):
    foreign c read_char(?tmp$3#0:wybe.char, ~wybe.io$io#0:wybe.phantom, ?tmp$4#0:wybe.phantom) @wybe:120:39
    simple_loop.gen$3<0>(~tmp$3#0:wybe.char, ~tmp$4#0:wybe.phantom, ?c#0:wybe.char, ?wybe.io$io#1:wybe.phantom) @simple_loop:2:4

(0 calls) (inline)
0: gen$1(c#0:wybe.char, tmp$0#0:wybe.bool, tmp$1#0:wybe.char, wybe.io$io#0:wybe.phantom, [?c#0:wybe.char], [?tmp$0#0:wybe.bool], [?tmp$1#0:wybe.char], [?wybe.io$io#0:wybe.phantom]):

(2 calls) (inline)
0: gen$2(wybe.io$io#0:wybe.phantom, ?c#1:wybe.char, ?tmp$0#0:wybe.bool, ?tmp$1#0:wybe.char, ?wybe.io$io#2:wybe.phantom):
    foreign c read_char(?c#0:wybe.char, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:120:39
    simple_loop.gen$3<0>(~c#0:wybe.char, ~wybe.io$io#1:wybe.phantom, ?c#1:wybe.char, ?wybe.io$io#2:wybe.phantom) @simple_loop:2:4

(1 calls)
0: gen$3(c#0:wybe.char, wybe.io$io#0:wybe.phantom, ?c#1:wybe.char, ?wybe.io$io#1:wybe.phantom):
    foreign llvm icmp ne(c#0:wybe.char, '.':wybe.char, ?tmp$4#0:wybe.bool) @wybe:71:42
    case ~tmp$4#0 of
    0:
        foreign llvm move(~c#0:wybe.char, ?c#1:wybe.char)
        foreign llvm move(~wybe.io$io#0:wybe.phantom, ?wybe.io$io#1:wybe.phantom)

    1:
        foreign c putchar(~c#0:wybe.char, ~wybe.io$io#0:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:118:39
        foreign c read_char(?tmp$10#0:wybe.char, ~tmp$9#0:wybe.phantom, ?tmp$11#0:wybe.phantom) @wybe:120:39
        simple_loop.gen$3<0>(~tmp$10#0:wybe.char, ~tmp$11#0:wybe.phantom, ?c#1:wybe.char, ?wybe.io$io#1:wybe.phantom) @simple_loop:2:4


(1 calls) (inline)
0: gen$4(c#0:wybe.char, wybe.io$io#0:wybe.phantom, ?c#1:wybe.char, ?wybe.io$io#2:wybe.phantom):
    foreign c putchar(~c#0:wybe.char, ~#wybe.io$io#0:wybe.phantom, ?#wybe.io$io#1:wybe.phantom) @wybe:118:39
    foreign c read_char(?tmp$5#0:wybe.char, ~wybe.io$io#1:wybe.phantom, ?tmp$6#0:wybe.phantom) @wybe:120:39
    simple_loop.gen$3<0>(~tmp$5#0:wybe.char, ~tmp$6#0:wybe.phantom, ?c#1:wybe.char, ?wybe.io$io#2:wybe.phantom) @simple_loop:2:4
