
 Module submodule
  public submods  : publictest @submodule:6:8
  public types    : 
  public resources: 
  public procs    : submodule.publictest.visible<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : 

Submodules of submodule:
 Module submodule.privatetest
  public submods  : 
  public types    : 
  public resources: 
  public procs    : submodule.privatetest.semi_hidden<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : hidden:
proc hidden() (id 0):  @submodule:2:5
    print("private proc in a private module") @submodule:2:17
                    semi_hidden:
public proc semi_hidden() (id 0):  @submodule:3:12
    print("public proc in a private module") @submodule:3:29

 Module submodule.publictest
  public submods  : 
  public types    : 
  public resources: 
  public procs    : submodule.publictest.visible<0>
  imports         : import wybe 
  types           : 
  resources       : 
  procs           : semi_visible:
proc semi_visible() (id 0):  @submodule:7:5
    print("private proc in a public module") @submodule:7:23
                    visible:
public proc visible() (id 0):  @submodule:8:12
    print("public proc in a public module") @submodule:8:25

