======================================================================
AFTER EVERYTHING:
 Module type_list
  public submods  : 
  public types    : intlist: type_list.intlist
  public resources: 
  public procs    : type_list.++<0>
                    type_list.intlist.=<0>
                    type_list.intlist.=<1>
                    type_list.intlist.=<2>
                    type_list.intlist.[]<0>
                    type_list.intlist.[|]<0>
                    type_list.intlist.head<0>
                    type_list.intlist.head<1>
                    type_list.intlist.tail<0>
                    type_list.intlist.tail<1>
  imports         : public use type_list.intlist
                    use wybe
  types           : intlist/0 @type_list:1:8
  resources       : 
  procs           : 
public (1 calls)
0: ++(x#0:type_list.intlist, y#0:type_list.intlist, ?$#0:type_list.intlist):
    type_list.gen$1<0>(~x#0:type_list.intlist, ~y#0:type_list.intlist, ?tmp$0#0:type_list.intlist, ?x#1:type_list.intlist, ?y#1:type_list.intlist) @type_list:8:5
    foreign llvm move(~tmp$0#0:type_list.intlist, ?$#0:type_list.intlist)

(1 calls)
0: gen$1(x#0:type_list.intlist, y#0:type_list.intlist, ?tmp$0#0:type_list.intlist, [?x#0:type_list.intlist], [?y#0:type_list.intlist]):
    foreign $ alloc("bool":wybe.string, "false":wybe.string, ?tmp$8#0:wybe.bool)
    case ~tmp$8#0 of
    0:
        foreign $ access("intlist":wybe.string, "[|]":wybe.string, "head":wybe.string, x#0:type_list.intlist, ?tmp$9#0:wybe.int)
        foreign $ access("intlist":wybe.string, "[|]":wybe.string, "tail":wybe.string, x#0:type_list.intlist, ?tmp$10#0:type_list.intlist)
        type_list.++<0>(~tmp$10#0:type_list.intlist, y#0:type_list.intlist, ?tmp$5#0:type_list.intlist) @type_list:10:18
        foreign $ alloc("intlist":wybe.string, "[|]":wybe.string, ?tmp$11#0:type_list.intlist)
        foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "head":wybe.string, ~%tmp$11#0:type_list.intlist, ?%tmp$12#0:type_list.intlist, ~tmp$9#0:wybe.int)
        foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "tail":wybe.string, ~%tmp$12#0:type_list.intlist, ?%tmp$13#0:type_list.intlist, ~tmp$5#0:type_list.intlist)
        foreign llvm move(~tmp$13#0:type_list.intlist, ?tmp$0#0:type_list.intlist)

    1:
        foreign llvm move(y#0:type_list.intlist, ?tmp$0#0:type_list.intlist)

--------------------------------------------------
 Module type_list.intlist([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : type_list.intlist.=<0>
                    type_list.intlist.=<1>
                    type_list.intlist.=<2>
                    type_list.intlist.[]<0>
                    type_list.intlist.[|]<0>
                    type_list.intlist.head<0>
                    type_list.intlist.head<1>
                    type_list.intlist.tail<0>
                    type_list.intlist.tail<1>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 
public (5 calls) (inline)
0: =(?x#0:type_list.intlist, y#0:type_list.intlist):
    foreign llvm move(~y#0:type_list.intlist, ?x#0:type_list.intlist)public (0 calls) (inline)
1: =(y#0:type_list.intlist, ?x#0:type_list.intlist):
    foreign llvm move(~y#0:type_list.intlist, ?x#0:type_list.intlist)public (0 calls) (inline)
2: =([x#0:type_list.intlist], [y#0:type_list.intlist], ?$#0:wybe.bool):
    foreign $ alloc("bool":wybe.string, "false":wybe.string, ?tmp$1#0:wybe.bool)
    foreign llvm move(~tmp$1#0:wybe.bool, ?$#0:wybe.bool)

public (0 calls) (inline)
0: [](?$#0:type_list.intlist):
    foreign $ alloc("intlist":wybe.string, "[]":wybe.string, ?$rec#0:type_list.intlist)
    foreign llvm move(~$rec#0:type_list.intlist, ?$#0:type_list.intlist)

public (0 calls) (inline)
0: [|](head#0:wybe.int, tail#0:type_list.intlist, ?$#0:type_list.intlist):
    foreign $ alloc("intlist":wybe.string, "[|]":wybe.string, ?$rec#0:type_list.intlist)
    foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "head":wybe.string, ~%$rec#0:type_list.intlist, ?%$rec#1:type_list.intlist, ~head#0:wybe.int)
    foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "tail":wybe.string, ~%$rec#1:type_list.intlist, ?%$rec#2:type_list.intlist, ~tail#0:type_list.intlist)
    foreign llvm move(~$rec#2:type_list.intlist, ?$#0:type_list.intlist)

public (0 calls) (inline)
0: head($rec#0:type_list.intlist, ?$#0:wybe.int):
    foreign $ access("intlist":wybe.string, "[|]":wybe.string, "head":wybe.string, ~$rec#0:type_list.intlist, ?tmp$0#0:wybe.int)
    foreign llvm move(~tmp$0#0:wybe.int, ?$#0:wybe.int)public (0 calls) (inline)
1: head($rec#0:type_list.intlist, ?$rec#1:type_list.intlist, $field#0:wybe.int):
    foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "head":wybe.string, ~%$rec#0:type_list.intlist, ?%$rec#1:type_list.intlist, ~$field#0:wybe.int)

public (0 calls) (inline)
0: tail($rec#0:type_list.intlist, ?$#0:type_list.intlist):
    foreign $ access("intlist":wybe.string, "[|]":wybe.string, "tail":wybe.string, ~$rec#0:type_list.intlist, ?tmp$0#0:type_list.intlist)
    foreign llvm move(~tmp$0#0:type_list.intlist, ?$#0:type_list.intlist)public (0 calls) (inline)
1: tail($rec#0:type_list.intlist, ?$rec#1:type_list.intlist, $field#0:type_list.intlist):
    foreign $ mutate("intlist":wybe.string, "[|]":wybe.string, "tail":wybe.string, ~%$rec#0:type_list.intlist, ?%$rec#1:type_list.intlist, ~$field#0:type_list.intlist)
