======================================================================
AFTER EVERYTHING:
 Module type_enum
  public submods  : 
  public types    : season: (type_enum.season,"i2")
  public resources: 
  public procs    : type_enum.season.=<0>
                    type_enum.season.=<1>
                    type_enum.season.=<2>
                    type_enum.season.autumn<0>
                    type_enum.season.spring<0>
                    type_enum.season.summer<0>
                    type_enum.season.winter<0>
  imports         : public use type_enum.season
                    use wybe
  types           : season/0 (i2)  @type_enum:1:8
  resources       : 
  procs           : 

  submodules      : type_enum.season
--------------------------------------------------
 Module type_enum.season([])
  public submods  : 
  public types    : 
  public resources: 
  public procs    : type_enum.season.=<0>
                    type_enum.season.=<1>
                    type_enum.season.=<2>
                    type_enum.season.autumn<0>
                    type_enum.season.spring<0>
                    type_enum.season.summer<0>
                    type_enum.season.winter<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

= > public inline (0 calls)
0: =(?out#0:type_enum.season, in#0:type_enum.season):
    foreign llvm move(~in#0:type_enum.season, ?out#0:type_enum.season)
= > public inline (0 calls)
1: =(in#0:type_enum.season, ?out#0:type_enum.season):
    foreign llvm move(~in#0:type_enum.season, ?out#0:type_enum.season)
= > public inline test (0 calls)
2: =($left#0:type_enum.season, $right#0:type_enum.season, ?$$#0:wybe.bool):
    foreign llvm icmp eq(~$left#0:wybe.int, ~$right#0:wybe.int, ?tmp$0#0:wybe.bool)
    foreign llvm move(~tmp$0#0, ?$$#0:wybe.bool)


autumn > public inline (0 calls)
0: autumn(?$#0:type_enum.season):
    foreign lpvm cast(3:type_enum.season, ?$#0:type_enum.season)


spring > public inline (0 calls)
0: spring(?$#0:type_enum.season):
    foreign lpvm cast(1:type_enum.season, ?$#0:type_enum.season)


summer > public inline (0 calls)
0: summer(?$#0:type_enum.season):
    foreign lpvm cast(2:type_enum.season, ?$#0:type_enum.season)


winter > public inline (0 calls)
0: winter(?$#0:type_enum.season):
    foreign lpvm cast(0:type_enum.season, ?$#0:type_enum.season)
type_enum, type_enum.season
======================================================================
AFTER LLVM IR:

; ModuleID = 'type_enum'

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.=<0>"(i2 %"in#0") #0 {
entry:
  ret i2 %"in#0"
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.=<1>"(i2 %"in#0") #0 {
entry:
  ret i2 %"in#0"
}

; Function Attrs: nounwind readnone
define i1 @"type_enum.season.=<1>1"(i2 %"$left#0", i2 %"$right#0") #0 {
entry:
  %"tmp$0#0" = icmp eq i2 %"$left#0", %"$right#0"
  ret i1 %"tmp$0#0"
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.autumn<0>"() #0 {
entry:
  ret i2 -1
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.spring<0>"() #0 {
entry:
  ret i2 1
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.summer<0>"() #0 {
entry:
  ret i2 -2
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.winter<0>"() #0 {
entry:
  ret i2 0
}

attributes #0 = { nounwind readnone }

--------------------------------------------------
; ModuleID = 'type_enum.season'

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.=<0>"(i2 %"in#0") #0 {
entry:
  ret i2 %"in#0"
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.=<1>"(i2 %"in#0") #0 {
entry:
  ret i2 %"in#0"
}

; Function Attrs: nounwind readnone
define i1 @"type_enum.season.=<1>1"(i2 %"$left#0", i2 %"$right#0") #0 {
entry:
  %"tmp$0#0" = icmp eq i2 %"$left#0", %"$right#0"
  ret i1 %"tmp$0#0"
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.autumn<0>"() #0 {
entry:
  ret i2 -1
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.spring<0>"() #0 {
entry:
  ret i2 1
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.summer<0>"() #0 {
entry:
  ret i2 -2
}

; Function Attrs: nounwind readnone
define i2 @"type_enum.season.winter<0>"() #0 {
entry:
  ret i2 0
}

attributes #0 = { nounwind readnone }

