 Module update
  public submods  : 
  public types    : 
  public resources: 
  public procs    : update.inc2<0>
                    update.inc2<1>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : inc2:
public proc inc2(x:0:int, ?tmp$0:0:int)<0>  @update:1:8 (0 calls) (inline)
    foreign llvm add(32:int, ~x:0:int, 1:int, ?tmp$1:0:int) @wybe:4:38
    foreign llvm add(32:int, ~tmp$1:0:int, 1:int, ?tmp$0:0:int) @wybe:4:38
public proc inc2([%x:0:int], ?%x:1:int, y:0:int)<1>  @update:3:8 (0 calls) (inline)
    foreign llvm sub(32:int, ~y:0:int, 1:int, ?tmp$1:1:int) @wybe:5:44
    foreign llvm sub(32:int, ~tmp$1:1:int, 1:int, ?x:1:int) @wybe:5:44
