======================================================================
AFTER EVERYTHING:
 Module alias_scc_proc
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_scc_proc.<0>
                    alias_scc_proc.bar<0>
                    alias_scc_proc.foo<0>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#8:wybe.phantom):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm alloc(16:wybe.int, ?tmp$3#0:position.position)
    foreign lpvm mutate(~tmp$3#0:position.position, ?tmp$4#0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.int)
    foreign lpvm mutate(~tmp$4#0:position.position, ?tmp$0#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.int)
    alias_scc_proc.foo<0>(tmp$0#0:position.position, ?p2#0:position.position, ?p3#0:position.position, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @alias_scc_proc:29:2
    foreign c print_string("--- After calling foo: ":wybe.string, ~#io#1:wybe.phantom, ?tmp$7#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$7#0:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    foreign c print_string("expect p1(2,2):":wybe.string, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @wybe:nn:nn
    position.printPosition<0>(~tmp$0#0:position.position, ~#io#3:wybe.phantom, ?#io#4:wybe.phantom) @alias_scc_proc:33:2
    foreign c print_string("expect p2(2,2):":wybe.string, ~#io#4:wybe.phantom, ?#io#5:wybe.phantom) @wybe:nn:nn
    position.printPosition<0>(~p2#0:position.position, ~#io#5:wybe.phantom, ?#io#6:wybe.phantom) @alias_scc_proc:35:2
    foreign c print_string("expect p3(3,3):":wybe.string, ~#io#6:wybe.phantom, ?#io#7:wybe.phantom) @wybe:nn:nn
    position.printPosition<0>(~p3#0:position.position, ~#io#7:wybe.phantom, ?#io#8:wybe.phantom) @alias_scc_proc:37:2


bar > public (1 calls)
0: bar(p1#0:position.position, ?p3#1:position.position, io#0:wybe.phantom, ?io#1:wybe.phantom):
 AliasPairs: [(p1#0,p3#1)]
 AliasMultiSpeczInfo: [p1#0]
    foreign lpvm access(p1#0:position.position, 8:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.bool) @wybe:nn:nn
    case ~tmp$3#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$2#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate noalias(~%p1#0:position.position, ?%p1#1:position.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$2#0:wybe.int)
        alias_scc_proc.foo<0>(~p1#1:position.position, ?p2#0:position.position, ?p3#1:position.position, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @alias_scc_proc:24:19

    1:
        foreign llvm move(~p1#0:position.position, ?p3#1:position.position)
        foreign llvm move(~io#0:wybe.phantom, ?io#1:wybe.phantom)



foo > public (2 calls)
0: foo(p1#0:position.position, ?p2#0:position.position, ?p3#0:position.position, io#0:wybe.phantom, ?io#2:wybe.phantom):
 AliasPairs: [(p1#0,p2#0)]
 AliasMultiSpeczInfo: [p1#0]
    foreign lpvm access(p1#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign llvm icmp sgt(tmp$0#0:wybe.int, 1:wybe.int, ?tmp$5#0:wybe.bool) @wybe:nn:nn
    case ~tmp$5#0:wybe.bool of
    0:
        foreign llvm add(~tmp$0#0:wybe.int, 1:wybe.int, ?tmp$3#0:wybe.int) @wybe:nn:nn
        foreign lpvm mutate noalias(~%p1#0:position.position, ?%p1#1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$3#0:wybe.int)
        alias_scc_proc.bar<0>(~p1#1:position.position, ?p3#0:position.position, ~#io#0:wybe.phantom, ?#io#2:wybe.phantom) @alias_scc_proc:13:16
        foreign lpvm alloc(16:wybe.int, ?tmp$16#0:position.position)
        foreign lpvm mutate(~tmp$16#0:position.position, ?tmp$17#0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2:wybe.int)
        foreign lpvm mutate(~tmp$17#0:position.position, ?p2#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2:wybe.int)

    1:
        foreign llvm move(~p1#0:position.position, ?p2#0:position.position) @alias_scc_proc:7:21
        foreign lpvm alloc(16:wybe.int, ?tmp$11#0:position.position)
        foreign lpvm mutate(~tmp$11#0:position.position, ?tmp$12#0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 3:wybe.int)
        foreign lpvm mutate(~tmp$12#0:position.position, ?tmp$1#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 3:wybe.int)
        foreign llvm move(tmp$1#0:position.position, ?p3#0:position.position) @alias_scc_proc:8:21
        foreign c print_string("--- Inside foo: expect p3(3,3):":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn
        position.printPosition<0>(~tmp$1#0:position.position, ~#io#1:wybe.phantom, ?#io#2:wybe.phantom) @alias_scc_proc:10:22


  LLVM code       :

; ModuleID = 'alias_scc_proc'


 


declare external ccc  void @"position.printPosition<0>"(i64)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @putchar(i8)    


@alias_scc_proc.18 =    constant [16 x i8] c"expect p3(3,3):\00"


@alias_scc_proc.16 =    constant [16 x i8] c"expect p2(2,2):\00"


@alias_scc_proc.14 =    constant [16 x i8] c"expect p1(2,2):\00"


@alias_scc_proc.12 =    constant [24 x i8] c"--- After calling foo: \00"


@alias_scc_proc.47 =    constant [32 x i8] c"--- Inside foo: expect p3(3,3):\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"alias_scc_proc.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 1, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  store  i64 1, i64* %8 
  %9 = tail call ccc  {i64, i64}  @"alias_scc_proc.foo<0>"(i64  %3)  
  %10 = extractvalue {i64, i64} %9, 0 
  %11 = extractvalue {i64, i64} %9, 1 
  %13 = ptrtoint i8* getelementptr inbounds ([24 x i8], [24 x i8]* @alias_scc_proc.12, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %13)  
  tail call ccc  void  @putchar(i8  10)  
  %15 = ptrtoint i8* getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.14, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %15)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %3)  
  %17 = ptrtoint i8* getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.16, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %17)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %10)  
  %19 = ptrtoint i8* getelementptr inbounds ([16 x i8], [16 x i8]* @alias_scc_proc.18, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %19)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %11)  
  ret void 
}


define external ccc  i64 @"alias_scc_proc.bar<0>"(i64  %"p1#0")    {
entry:
  %20 = add   i64 %"p1#0", 8 
  %21 = inttoptr i64 %20 to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  %"tmp$3#0" = icmp sgt i64 %23, 1 
  br i1 %"tmp$3#0", label %if.then, label %if.else 
if.then:
  ret i64 %"p1#0" 
if.else:
  %"tmp$2#0" = add   i64 %23, 1 
  %24 = trunc i64 16 to i32  
  %25 = tail call ccc  i8*  @wybe_malloc(i32  %24)  
  %26 = ptrtoint i8* %25 to i64 
  %27 = inttoptr i64 %26 to i8* 
  %28 = inttoptr i64 %"p1#0" to i8* 
  %29 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %27, i8*  %28, i32  %29, i32  8, i1  0)  
  %30 = add   i64 %26, 8 
  %31 = inttoptr i64 %30 to i64* 
  %32 = getelementptr  i64, i64* %31, i64 0 
  store  i64 %"tmp$2#0", i64* %32 
  %33 = tail call ccc  {i64, i64}  @"alias_scc_proc.foo<0>"(i64  %26)  
  %34 = extractvalue {i64, i64} %33, 0 
  %35 = extractvalue {i64, i64} %33, 1 
  ret i64 %35 
}


define external ccc  {i64, i64} @"alias_scc_proc.foo<0>"(i64  %"p1#0")    {
entry:
  %36 = inttoptr i64 %"p1#0" to i64* 
  %37 = getelementptr  i64, i64* %36, i64 0 
  %38 = load  i64, i64* %37 
  %"tmp$5#0" = icmp sgt i64 %38, 1 
  br i1 %"tmp$5#0", label %if.then, label %if.else 
if.then:
  %39 = trunc i64 16 to i32  
  %40 = tail call ccc  i8*  @wybe_malloc(i32  %39)  
  %41 = ptrtoint i8* %40 to i64 
  %42 = inttoptr i64 %41 to i64* 
  %43 = getelementptr  i64, i64* %42, i64 0 
  store  i64 3, i64* %43 
  %44 = add   i64 %41, 8 
  %45 = inttoptr i64 %44 to i64* 
  %46 = getelementptr  i64, i64* %45, i64 0 
  store  i64 3, i64* %46 
  %48 = ptrtoint i8* getelementptr inbounds ([32 x i8], [32 x i8]* @alias_scc_proc.47, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %48)  
  tail call ccc  void  @"position.printPosition<0>"(i64  %41)  
  %49 = insertvalue {i64, i64} undef, i64 %"p1#0", 0 
  %50 = insertvalue {i64, i64} %49, i64 %41, 1 
  ret {i64, i64} %50 
if.else:
  %"tmp$3#0" = add   i64 %38, 1 
  %51 = trunc i64 16 to i32  
  %52 = tail call ccc  i8*  @wybe_malloc(i32  %51)  
  %53 = ptrtoint i8* %52 to i64 
  %54 = inttoptr i64 %53 to i8* 
  %55 = inttoptr i64 %"p1#0" to i8* 
  %56 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %54, i8*  %55, i32  %56, i32  8, i1  0)  
  %57 = inttoptr i64 %53 to i64* 
  %58 = getelementptr  i64, i64* %57, i64 0 
  store  i64 %"tmp$3#0", i64* %58 
  %"p3#0" = tail call ccc  i64  @"alias_scc_proc.bar<0>"(i64  %53)  
  %59 = trunc i64 16 to i32  
  %60 = tail call ccc  i8*  @wybe_malloc(i32  %59)  
  %61 = ptrtoint i8* %60 to i64 
  %62 = inttoptr i64 %61 to i64* 
  %63 = getelementptr  i64, i64* %62, i64 0 
  store  i64 2, i64* %63 
  %64 = add   i64 %61, 8 
  %65 = inttoptr i64 %64 to i64* 
  %66 = getelementptr  i64, i64* %65, i64 0 
  store  i64 2, i64* %66 
  %67 = insertvalue {i64, i64} undef, i64 %61, 0 
  %68 = insertvalue {i64, i64} %67, i64 %"p3#0", 1 
  ret {i64, i64} %68 
}
--------------------------------------------------
 Module position
  public submods  : 
  public types    : position: (position.position,Just address)
  public resources: 
  public procs    : position.printPosition<0>
                    position.position./=<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : public use position.position
                    use wybe
  types           : position/public  is address { position(x:int, y:int) @position:1:25  }  @position:1:5
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: printPosition(pos#0:position.position, io#0:wybe.phantom, ?io#5:wybe.phantom):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign c print_string(" (":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(pos#0:position.position, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    foreign c print_string(",":wybe.string, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(~pos#0:position.position, 8:wybe.int, ?tmp$1#0:wybe.int)
    foreign c print_int(~tmp$1#0:wybe.int, ~#io#3:wybe.phantom, ?#io#4:wybe.phantom) @wybe:nn:nn
    foreign c print_string(")":wybe.string, ~#io#4:wybe.phantom, ?tmp$14#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$14#0:wybe.phantom, ?#io#5:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


@position.12 =    constant [2 x i8] c")\00"


@position.6 =    constant [2 x i8] c",\00"


@position.1 =    constant [3 x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  void @"position.printPosition<0>"(i64  %"pos#0")    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([3 x i8], [3 x i8]* @position.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  %3 = inttoptr i64 %"pos#0" to i64* 
  %4 = getelementptr  i64, i64* %3, i64 0 
  %5 = load  i64, i64* %4 
  tail call ccc  void  @print_int(i64  %5)  
  %7 = ptrtoint i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.6, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %7)  
  %8 = add   i64 %"pos#0", 8 
  %9 = inttoptr i64 %8 to i64* 
  %10 = getelementptr  i64, i64* %9, i64 0 
  %11 = load  i64, i64* %10 
  tail call ccc  void  @print_int(i64  %11)  
  %13 = ptrtoint i8* getelementptr inbounds ([2 x i8], [2 x i8]* @position.12, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %13)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position
  public submods  : 
  public types    : 
  public resources: 
  public procs    : position.position./=<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
  imports         : use position
                    use wybe
  types           : 
  resources       : 
  procs           : 

/= > public inline test (0 calls)
0: /=($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?tmp$4#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?tmp$5#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?tmp$6#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?tmp$7#0:wybe.int)
    foreign llvm icmp eq(~tmp$4#0:wybe.int, ~tmp$6#0:wybe.int, ?tmp$8#0:wybe.bool) @wybe:nn:nn
    case ~tmp$8#0:wybe.bool of
    0:
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~tmp$5#0:wybe.int, ~tmp$7#0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:nn:nn
        case ~tmp$1#0:wybe.bool of
        0:
            foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)




= > public inline test (6 calls)
0: =($left#0:position.position, $right#0:position.position, ?$$#0:wybe.bool):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm access($left#0:position.position, 0:wybe.int, ?$left$x#0:wybe.int)
    foreign lpvm access(~$left#0:position.position, 8:wybe.int, ?$left$y#0:wybe.int)
    foreign lpvm access($right#0:position.position, 0:wybe.int, ?$right$x#0:wybe.int)
    foreign lpvm access(~$right#0:position.position, 8:wybe.int, ?$right$y#0:wybe.int)
    foreign llvm icmp eq(~$left$x#0:wybe.int, ~$right$x#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign llvm icmp eq(~$left$y#0:wybe.int, ~$right$y#0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



position > public inline (0 calls)
0: position(x#0:wybe.int, y#0:wybe.int, ?$#0:position.position):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:!position.position)
    foreign lpvm mutate(~%$rec#0:position.position, ?%$rec#1:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:position.position, ?%$#0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~y#0:wybe.int)
position > public inline (4 calls)
1: position(?x#0:wybe.int, ?y#0:wybe.int, $#0:position.position):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm access($#0:position.position, 0:wybe.int, ?x#0:wybe.int)
    foreign lpvm access(~$#0:position.position, 8:wybe.int, ?y#0:wybe.int)


x > public inline (0 calls)
0: x($rec#0:position.position, ?$#0:wybe.int):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm access(~$rec#0:position.position, 0:wybe.int, ?$#0:wybe.int)
x > public inline (0 calls)
1: x($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm mutate noalias(~%$rec#0:position.position, ?%$rec#1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


y > public inline (0 calls)
0: y($rec#0:position.position, ?$#0:wybe.int):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm access(~$rec#0:position.position, 8:wybe.int, ?$#0:wybe.int)
y > public inline (0 calls)
1: y($rec#0:position.position, ?$rec#1:position.position, $field#0:wybe.int):
 AliasPairs: []
 AliasMultiSpeczInfo: []
    foreign lpvm mutate noalias(~%$rec#0:position.position, ?%$rec#1:position.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)

  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external ccc  i1 @"position.position./=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$8#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$8#0", label %if.then, label %if.else 
if.then:
  %"tmp$1#0" = icmp eq i64 %7, %14 
  br i1 %"tmp$1#0", label %if.then1, label %if.else1 
if.else:
  ret i1 1 
if.then1:
  ret i1 0 
if.else1:
  ret i1 1 
}


define external ccc  i1 @"position.position.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %15 = inttoptr i64 %"$left#0" to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  %17 = load  i64, i64* %16 
  %18 = add   i64 %"$left#0", 8 
  %19 = inttoptr i64 %18 to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = inttoptr i64 %"$right#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 0 
  %24 = load  i64, i64* %23 
  %25 = add   i64 %"$right#0", 8 
  %26 = inttoptr i64 %25 to i64* 
  %27 = getelementptr  i64, i64* %26, i64 0 
  %28 = load  i64, i64* %27 
  %"tmp$2#0" = icmp eq i64 %17, %24 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"$$#0" = icmp eq i64 %21, %28 
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external ccc  i64 @"position.position.position<0>"(i64  %"x#0", i64  %"y#0")    {
entry:
  %29 = trunc i64 16 to i32  
  %30 = tail call ccc  i8*  @wybe_malloc(i32  %29)  
  %31 = ptrtoint i8* %30 to i64 
  %32 = inttoptr i64 %31 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  store  i64 %"x#0", i64* %33 
  %34 = add   i64 %31, 8 
  %35 = inttoptr i64 %34 to i64* 
  %36 = getelementptr  i64, i64* %35, i64 0 
  store  i64 %"y#0", i64* %36 
  ret i64 %31 
}


define external ccc  {i64, i64} @"position.position.position<1>"(i64  %"$#0")    {
entry:
  %37 = inttoptr i64 %"$#0" to i64* 
  %38 = getelementptr  i64, i64* %37, i64 0 
  %39 = load  i64, i64* %38 
  %40 = add   i64 %"$#0", 8 
  %41 = inttoptr i64 %40 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  %43 = load  i64, i64* %42 
  %44 = insertvalue {i64, i64} undef, i64 %39, 0 
  %45 = insertvalue {i64, i64} %44, i64 %43, 1 
  ret {i64, i64} %45 
}


define external ccc  i64 @"position.position.x<0>"(i64  %"$rec#0")    {
entry:
  %46 = inttoptr i64 %"$rec#0" to i64* 
  %47 = getelementptr  i64, i64* %46, i64 0 
  %48 = load  i64, i64* %47 
  ret i64 %48 
}


define external ccc  i64 @"position.position.x<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %49 = trunc i64 16 to i32  
  %50 = tail call ccc  i8*  @wybe_malloc(i32  %49)  
  %51 = ptrtoint i8* %50 to i64 
  %52 = inttoptr i64 %51 to i8* 
  %53 = inttoptr i64 %"$rec#0" to i8* 
  %54 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %52, i8*  %53, i32  %54, i32  8, i1  0)  
  %55 = inttoptr i64 %51 to i64* 
  %56 = getelementptr  i64, i64* %55, i64 0 
  store  i64 %"$field#0", i64* %56 
  ret i64 %51 
}


define external ccc  i64 @"position.position.y<0>"(i64  %"$rec#0")    {
entry:
  %57 = add   i64 %"$rec#0", 8 
  %58 = inttoptr i64 %57 to i64* 
  %59 = getelementptr  i64, i64* %58, i64 0 
  %60 = load  i64, i64* %59 
  ret i64 %60 
}


define external ccc  i64 @"position.position.y<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %61 = trunc i64 16 to i32  
  %62 = tail call ccc  i8*  @wybe_malloc(i32  %61)  
  %63 = ptrtoint i8* %62 to i64 
  %64 = inttoptr i64 %63 to i8* 
  %65 = inttoptr i64 %"$rec#0" to i8* 
  %66 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %64, i8*  %65, i32  %66, i32  8, i1  0)  
  %67 = add   i64 %63, 8 
  %68 = inttoptr i64 %67 to i64* 
  %69 = getelementptr  i64, i64* %68, i64 0 
  store  i64 %"$field#0", i64* %69 
  ret i64 %63 
}
