======================================================================
AFTER EVERYTHING:
 Module alias_data
  public submods  : 
  public types    : 
  public resources: 
  public procs    : alias_data.<0>
                    alias_data.backup<0>
                    alias_data.bar<0>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

*main* > public inline (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    alias_data.bar<0>(~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @alias_data:19:2


backup > public inline (1 calls)
0: backup(student1#0:student.student, ?student2#0:student.student, io#0:wybe.phantom, [?io#0:wybe.phantom]): AliasPairs: []
    foreign llvm move(~student1#0:student.student, ?student2#0:student.student) @alias_data:4:3


bar > public (1 calls)
0: bar(io#0:wybe.phantom, ?io#5:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:student.course)
    foreign lpvm mutate(~tmp$4#0:student.course, ?tmp$5#0:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 101:wybe.int)
    foreign lpvm mutate(~tmp$5#0:student.course, ?tmp$0#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, "intro to cs":wybe.string)
    foreign lpvm alloc(16:wybe.int, ?tmp$8#0:student.student)
    foreign lpvm mutate(~tmp$8#0:student.student, ?tmp$9#0:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 9401:wybe.int)
    foreign lpvm mutate(~tmp$9#0:student.student, ?tmp$1#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$0#0:student.course)
    foreign c print_string("student1":wybe.string, ~#io#0:wybe.phantom, ?tmp$13#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$13#0:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    student.printStudent<0>(tmp$1#0:student.student, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @alias_data:13:4
    foreign c print_string("student2":wybe.string, ~#io#3:wybe.phantom, ?tmp$16#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$16#0:wybe.phantom, ?#io#4:wybe.phantom) @wybe:nn:nn
    student.printStudent<0>(~tmp$1#0:student.student, ~#io#4:wybe.phantom, ?#io#5:wybe.phantom) @alias_data:16:4

  LLVM code       :

; ModuleID = 'alias_data'


 


declare external fastcc  void @"student.printStudent<0>"(i64)    


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


@alias_data.21 =    constant [9 x i8] c"student2\00"


@alias_data.19 =    constant [9 x i8] c"student1\00"


@alias_data.9 =    constant [12 x i8] c"intro to cs\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"alias_data.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  tail call fastcc  void  @"alias_data.bar<0>"()  
  ret void 
}


define external fastcc  i64 @"alias_data.backup<0>"(i64  %"student1#0")    {
entry:
  ret i64 %"student1#0" 
}


define external fastcc  void @"alias_data.bar<0>"()    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 101, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %10 = ptrtoint i8* getelementptr inbounds ([12 x i8], [12 x i8]* @alias_data.9, i32 0, i32 0) to i64 
  store  i64 %10, i64* %8 
  %11 = trunc i64 16 to i32  
  %12 = tail call ccc  i8*  @wybe_malloc(i32  %11)  
  %13 = ptrtoint i8* %12 to i64 
  %14 = inttoptr i64 %13 to i64* 
  %15 = getelementptr  i64, i64* %14, i64 0 
  store  i64 9401, i64* %15 
  %16 = add   i64 %13, 8 
  %17 = inttoptr i64 %16 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 0 
  store  i64 %3, i64* %18 
  %20 = ptrtoint i8* getelementptr inbounds ([9 x i8], [9 x i8]* @alias_data.19, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %20)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"student.printStudent<0>"(i64  %13)  
  %22 = ptrtoint i8* getelementptr inbounds ([9 x i8], [9 x i8]* @alias_data.21, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %22)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"student.printStudent<0>"(i64  %13)  
  ret void 
}
--------------------------------------------------
 Module student
  public submods  : 
  public types    : course: (student.course,Just address)
                    student: (student.student,Just address)
  public resources: 
  public procs    : student.<0>
                    student.printStudent<0>
                    student.course./=<0>
                    student.course.=<0>
                    student.course.code<0>
                    student.course.code<1>
                    student.course.course<0>
                    student.course.course<1>
                    student.course.name<0>
                    student.course.name<1>
                    student.student./=<0>
                    student.student.=<0>
                    student.student.id<0>
                    student.student.id<1>
                    student.student.major<0>
                    student.student.major<1>
                    student.student.student<0>
                    student.student.student<1>
  imports         : public use student.course
                    public use student.student
                    use wybe
  types           : course/public  is address { course(code:int, name:string) @student:1:24  }  @student:1:5, student/public  is address { student(id:int, major:course) @student:2:24  }  @student:2:5
  resources       : 
  submodules      : student.course, student.student
  procs           : 

*main* > public (0 calls)
0: (argc#0:wybe.int, [?argc#0:wybe.int], argv#0:wybe.int, [?argv#0:wybe.int], exit_code#0:wybe.int, [?exit_code#0:wybe.int], io#0:wybe.phantom, ?io#1:wybe.phantom): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?tmp$4#0:student.course)
    foreign lpvm mutate(~tmp$4#0:student.course, ?tmp$5#0:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 90048:wybe.int)
    foreign lpvm mutate(~tmp$5#0:student.course, ?tmp$6#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, "Declarative Programming":wybe.string)
    foreign lpvm alloc(16:wybe.int, ?tmp$9#0:student.student)
    foreign lpvm mutate(~tmp$9#0:student.student, ?tmp$10#0:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 12345:wybe.int)
    foreign lpvm mutate(~tmp$10#0:student.student, ?tmp$11#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp$6#0:student.course)
    student.printStudent<0>(~tmp$11#0:student.student, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @student:14:2


printStudent > public (1 calls)
0: printStudent(stu#0:student.student, io#0:wybe.phantom, ?io#6:wybe.phantom): AliasPairs: []
    foreign c print_string("student id: ":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(stu#0:student.student, 0:wybe.int, ?tmp$0#0:wybe.int)
    foreign c print_int(~tmp$0#0:wybe.int, ~#io#1:wybe.phantom, ?tmp$9#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$9#0:wybe.phantom, ?#io#2:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(~stu#0:student.student, 8:wybe.int, ?tmp$1#0:student.course)
    foreign c print_string("course code: ":wybe.string, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(tmp$1#0:student.course, 0:wybe.int, ?tmp$2#0:wybe.int)
    foreign c print_int(~tmp$2#0:wybe.int, ~#io#3:wybe.phantom, ?tmp$16#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$16#0:wybe.phantom, ?#io#4:wybe.phantom) @wybe:nn:nn
    foreign c print_string("course name: ":wybe.string, ~#io#4:wybe.phantom, ?#io#5:wybe.phantom) @wybe:nn:nn
    foreign lpvm access(~tmp$1#0:student.course, 8:wybe.int, ?tmp$3#0:wybe.string)
    foreign c print_string(~tmp$3#0:wybe.string, ~#io#5:wybe.phantom, ?tmp$22#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$22#0:wybe.phantom, ?#io#6:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'student'


 


@student.9 =    constant [24 x i8] c"Declarative Programming\00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


@student.33 =    constant [14 x i8] c"course name: \00"


@student.28 =    constant [14 x i8] c"course code: \00"


@student.19 =    constant [13 x i8] c"student id: \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"student.<0>"(i64  %"argc#0", i64  %"argv#0", i64  %"exit_code#0")    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 90048, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  %10 = ptrtoint i8* getelementptr inbounds ([24 x i8], [24 x i8]* @student.9, i32 0, i32 0) to i64 
  store  i64 %10, i64* %8 
  %11 = trunc i64 16 to i32  
  %12 = tail call ccc  i8*  @wybe_malloc(i32  %11)  
  %13 = ptrtoint i8* %12 to i64 
  %14 = inttoptr i64 %13 to i64* 
  %15 = getelementptr  i64, i64* %14, i64 0 
  store  i64 12345, i64* %15 
  %16 = add   i64 %13, 8 
  %17 = inttoptr i64 %16 to i64* 
  %18 = getelementptr  i64, i64* %17, i64 0 
  store  i64 %3, i64* %18 
  tail call fastcc  void  @"student.printStudent<0>"(i64  %13)  
  ret void 
}


define external fastcc  void @"student.printStudent<0>"(i64  %"stu#0")    {
entry:
  %20 = ptrtoint i8* getelementptr inbounds ([13 x i8], [13 x i8]* @student.19, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %20)  
  %21 = inttoptr i64 %"stu#0" to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  tail call ccc  void  @print_int(i64  %23)  
  tail call ccc  void  @putchar(i8  10)  
  %24 = add   i64 %"stu#0", 8 
  %25 = inttoptr i64 %24 to i64* 
  %26 = getelementptr  i64, i64* %25, i64 0 
  %27 = load  i64, i64* %26 
  %29 = ptrtoint i8* getelementptr inbounds ([14 x i8], [14 x i8]* @student.28, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %29)  
  %30 = inttoptr i64 %27 to i64* 
  %31 = getelementptr  i64, i64* %30, i64 0 
  %32 = load  i64, i64* %31 
  tail call ccc  void  @print_int(i64  %32)  
  tail call ccc  void  @putchar(i8  10)  
  %34 = ptrtoint i8* getelementptr inbounds ([14 x i8], [14 x i8]* @student.33, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %34)  
  %35 = add   i64 %27, 8 
  %36 = inttoptr i64 %35 to i64* 
  %37 = getelementptr  i64, i64* %36, i64 0 
  %38 = load  i64, i64* %37 
  tail call ccc  void  @print_string(i64  %38)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module student.course
  public submods  : 
  public types    : 
  public resources: 
  public procs    : student.course./=<0>
                    student.course.=<0>
                    student.course.code<0>
                    student.course.code<1>
                    student.course.course<0>
                    student.course.course<1>
                    student.course.name<0>
                    student.course.name<1>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

/= > public inline test (0 calls)
0: /=($left#0:student.course, $right#0:student.course, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.course, 0:wybe.int, ?tmp$4#0:wybe.int)
    foreign lpvm access(~$left#0:student.course, 8:wybe.int, ?tmp$5#0:wybe.string)
    foreign lpvm access($right#0:student.course, 0:wybe.int, ?tmp$6#0:wybe.int)
    foreign lpvm access(~$right#0:student.course, 8:wybe.int, ?tmp$7#0:wybe.string)
    foreign llvm icmp eq(~tmp$4#0:wybe.int, ~tmp$6#0:wybe.int, ?tmp$8#0:wybe.bool) @wybe:nn:nn
    case ~tmp$8#0:wybe.bool of
    0:
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign c strcmp(~tmp$5#0:wybe.string, ~tmp$7#0:wybe.string, ?tmp$9#0:wybe.int) @wybe:nn:nn
        wybe.int.=<0>(~tmp$9#0:wybe.int, 0:wybe.int, ?tmp$1#0:wybe.bool) @wybe:nn:nn
        case ~tmp$1#0:wybe.bool of
        0:
            foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)




= > public inline test (6 calls)
0: =($left#0:student.course, $right#0:student.course, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.course, 0:wybe.int, ?$left$code#0:wybe.int)
    foreign lpvm access(~$left#0:student.course, 8:wybe.int, ?$left$name#0:wybe.string)
    foreign lpvm access($right#0:student.course, 0:wybe.int, ?$right$code#0:wybe.int)
    foreign lpvm access(~$right#0:student.course, 8:wybe.int, ?$right$name#0:wybe.string)
    foreign llvm icmp eq(~$left$code#0:wybe.int, ~$right$code#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        foreign c strcmp(~$left$name#0:wybe.string, ~$right$name#0:wybe.string, ?tmp$10#0:wybe.int) @wybe:nn:nn
        wybe.int.=<0>(~tmp$10#0:wybe.int, 0:wybe.int, ?$$#0:wybe.bool) @wybe:nn:nn



code > public inline (0 calls)
0: code($rec#0:student.course, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:student.course, 0:wybe.int, ?$#0:wybe.int)
code > public inline (0 calls)
1: code($rec#0:student.course, ?$rec#1:student.course, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:student.course, ?%$rec#1:student.course, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


course > public inline (0 calls)
0: course(code#0:wybe.int, name#0:wybe.string, ?$#0:student.course): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:!student.course)
    foreign lpvm mutate(~%$rec#0:student.course, ?%$rec#1:student.course, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~code#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:student.course, ?%$#0:student.course, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~name#0:wybe.string)
course > public inline (4 calls)
1: course(?code#0:wybe.int, ?name#0:wybe.string, $#0:student.course): AliasPairs: []
    foreign lpvm access($#0:student.course, 0:wybe.int, ?code#0:wybe.int)
    foreign lpvm access(~$#0:student.course, 8:wybe.int, ?name#0:wybe.string)


name > public inline (0 calls)
0: name($rec#0:student.course, ?$#0:wybe.string): AliasPairs: []
    foreign lpvm access(~$rec#0:student.course, 8:wybe.int, ?$#0:wybe.string)
name > public inline (0 calls)
1: name($rec#0:student.course, ?$rec#1:student.course, $field#0:wybe.string): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:student.course, ?%$rec#1:student.course, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.string)

  LLVM code       :

; ModuleID = 'student.course'


 


declare external fastcc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i64 @strcmp(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  i1 @"student.course./=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$8#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$8#0", label %if.then, label %if.else 
if.then:
  %"tmp$9#0" = tail call ccc  i64  @strcmp(i64  %7, i64  %14)  
  %"tmp$1#0" = tail call fastcc  i1  @"wybe.int.=<0>"(i64  %"tmp$9#0", i64  0)  
  br i1 %"tmp$1#0", label %if.then1, label %if.else1 
if.else:
  ret i1 1 
if.then1:
  ret i1 0 
if.else1:
  ret i1 1 
}


define external fastcc  i1 @"student.course.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %15 = inttoptr i64 %"$left#0" to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  %17 = load  i64, i64* %16 
  %18 = add   i64 %"$left#0", 8 
  %19 = inttoptr i64 %18 to i64* 
  %20 = getelementptr  i64, i64* %19, i64 0 
  %21 = load  i64, i64* %20 
  %22 = inttoptr i64 %"$right#0" to i64* 
  %23 = getelementptr  i64, i64* %22, i64 0 
  %24 = load  i64, i64* %23 
  %25 = add   i64 %"$right#0", 8 
  %26 = inttoptr i64 %25 to i64* 
  %27 = getelementptr  i64, i64* %26, i64 0 
  %28 = load  i64, i64* %27 
  %"tmp$2#0" = icmp eq i64 %17, %24 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %"tmp$10#0" = tail call ccc  i64  @strcmp(i64  %21, i64  %28)  
  %"$$#0" = tail call fastcc  i1  @"wybe.int.=<0>"(i64  %"tmp$10#0", i64  0)  
  ret i1 %"$$#0" 
if.else:
  ret i1 0 
}


define external fastcc  i64 @"student.course.code<0>"(i64  %"$rec#0")    {
entry:
  %29 = inttoptr i64 %"$rec#0" to i64* 
  %30 = getelementptr  i64, i64* %29, i64 0 
  %31 = load  i64, i64* %30 
  ret i64 %31 
}


define external fastcc  i64 @"student.course.code<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %32 = trunc i64 16 to i32  
  %33 = tail call ccc  i8*  @wybe_malloc(i32  %32)  
  %34 = ptrtoint i8* %33 to i64 
  %35 = inttoptr i64 %34 to i8* 
  %36 = inttoptr i64 %"$rec#0" to i8* 
  %37 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %35, i8*  %36, i32  %37, i32  8, i1  0)  
  %38 = inttoptr i64 %34 to i64* 
  %39 = getelementptr  i64, i64* %38, i64 0 
  store  i64 %"$field#0", i64* %39 
  ret i64 %34 
}


define external fastcc  i64 @"student.course.course<0>"(i64  %"code#0", i64  %"name#0")    {
entry:
  %40 = trunc i64 16 to i32  
  %41 = tail call ccc  i8*  @wybe_malloc(i32  %40)  
  %42 = ptrtoint i8* %41 to i64 
  %43 = inttoptr i64 %42 to i64* 
  %44 = getelementptr  i64, i64* %43, i64 0 
  store  i64 %"code#0", i64* %44 
  %45 = add   i64 %42, 8 
  %46 = inttoptr i64 %45 to i64* 
  %47 = getelementptr  i64, i64* %46, i64 0 
  store  i64 %"name#0", i64* %47 
  ret i64 %42 
}


define external fastcc  {i64, i64} @"student.course.course<1>"(i64  %"$#0")    {
entry:
  %48 = inttoptr i64 %"$#0" to i64* 
  %49 = getelementptr  i64, i64* %48, i64 0 
  %50 = load  i64, i64* %49 
  %51 = add   i64 %"$#0", 8 
  %52 = inttoptr i64 %51 to i64* 
  %53 = getelementptr  i64, i64* %52, i64 0 
  %54 = load  i64, i64* %53 
  %55 = insertvalue {i64, i64} undef, i64 %50, 0 
  %56 = insertvalue {i64, i64} %55, i64 %54, 1 
  ret {i64, i64} %56 
}


define external fastcc  i64 @"student.course.name<0>"(i64  %"$rec#0")    {
entry:
  %57 = add   i64 %"$rec#0", 8 
  %58 = inttoptr i64 %57 to i64* 
  %59 = getelementptr  i64, i64* %58, i64 0 
  %60 = load  i64, i64* %59 
  ret i64 %60 
}


define external fastcc  i64 @"student.course.name<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %61 = trunc i64 16 to i32  
  %62 = tail call ccc  i8*  @wybe_malloc(i32  %61)  
  %63 = ptrtoint i8* %62 to i64 
  %64 = inttoptr i64 %63 to i8* 
  %65 = inttoptr i64 %"$rec#0" to i8* 
  %66 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %64, i8*  %65, i32  %66, i32  8, i1  0)  
  %67 = add   i64 %63, 8 
  %68 = inttoptr i64 %67 to i64* 
  %69 = getelementptr  i64, i64* %68, i64 0 
  store  i64 %"$field#0", i64* %69 
  ret i64 %63 
}
--------------------------------------------------
 Module student.student
  public submods  : 
  public types    : 
  public resources: 
  public procs    : student.student./=<0>
                    student.student.=<0>
                    student.student.id<0>
                    student.student.id<1>
                    student.student.major<0>
                    student.student.major<1>
                    student.student.student<0>
                    student.student.student<1>
  imports         : use student
                    use wybe
  types           : 
  resources       : 
  procs           : 

/= > public inline test (0 calls)
0: /=($left#0:student.student, $right#0:student.student, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.student, 0:wybe.int, ?tmp$4#0:wybe.int)
    foreign lpvm access(~$left#0:student.student, 8:wybe.int, ?tmp$5#0:student.course)
    foreign lpvm access($right#0:student.student, 0:wybe.int, ?tmp$6#0:wybe.int)
    foreign lpvm access(~$right#0:student.student, 8:wybe.int, ?tmp$7#0:student.course)
    foreign llvm icmp eq(~tmp$4#0:wybe.int, ~tmp$6#0:wybe.int, ?tmp$8#0:wybe.bool) @wybe:nn:nn
    case ~tmp$8#0:wybe.bool of
    0:
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

    1:
        student.course.course<1>(?tmp$9#0:wybe.int, ?tmp$10#0:wybe.string, ~tmp$5#0:student.course)
        student.course.course<1>(?tmp$11#0:wybe.int, ?tmp$12#0:wybe.string, ~tmp$7#0:student.course)
        wybe.int.=<0>(~tmp$9#0:wybe.int, ~tmp$11#0:wybe.int, ?tmp$13#0:wybe.bool)
        case ~tmp$13#0:wybe.bool of
        0:
            foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

        1:
            wybe.string.=<0>(~tmp$10#0:wybe.string, ~tmp$12#0:wybe.string, ?tmp$1#0:wybe.bool)
            case ~tmp$1#0:wybe.bool of
            0:
                foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

            1:
                foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)





= > public inline test (6 calls)
0: =($left#0:student.student, $right#0:student.student, ?$$#0:wybe.bool): AliasPairs: []
    foreign lpvm access($left#0:student.student, 0:wybe.int, ?$left$id#0:wybe.int)
    foreign lpvm access(~$left#0:student.student, 8:wybe.int, ?$left$major#0:student.course)
    foreign lpvm access($right#0:student.student, 0:wybe.int, ?$right$id#0:wybe.int)
    foreign lpvm access(~$right#0:student.student, 8:wybe.int, ?$right$major#0:student.course)
    foreign llvm icmp eq(~$left$id#0:wybe.int, ~$right$id#0:wybe.int, ?tmp$2#0:wybe.bool) @wybe:nn:nn
    case ~tmp$2#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

    1:
        student.course.course<1>(?tmp$12#0:wybe.int, ?tmp$13#0:wybe.string, ~$left$major#0:student.course)
        student.course.course<1>(?tmp$14#0:wybe.int, ?tmp$15#0:wybe.string, ~$right$major#0:student.course)
        wybe.int.=<0>(~tmp$12#0:wybe.int, ~tmp$14#0:wybe.int, ?tmp$16#0:wybe.bool)
        case ~tmp$16#0:wybe.bool of
        0:
            foreign llvm move(0:wybe.bool, ?tmp$3#0:wybe.bool)
            foreign llvm move(~tmp$3#0:!wybe.bool, ?$$#0:wybe.bool)

        1:
            wybe.string.=<0>(~tmp$13#0:wybe.string, ~tmp$15#0:wybe.string, ?tmp$3#0:wybe.bool)
            foreign llvm move(~tmp$3#0:!wybe.bool, ?$$#0:wybe.bool)




id > public inline (0 calls)
0: id($rec#0:student.student, ?$#0:wybe.int): AliasPairs: []
    foreign lpvm access(~$rec#0:student.student, 0:wybe.int, ?$#0:wybe.int)
id > public inline (0 calls)
1: id($rec#0:student.student, ?$rec#1:student.student, $field#0:wybe.int): AliasPairs: []
    foreign lpvm mutate(~%$rec#0:student.student, ?%$rec#1:student.student, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)


major > public inline (0 calls)
0: major($rec#0:student.student, ?$#0:student.course): AliasPairs: []
    foreign lpvm access(~$rec#0:student.student, 8:wybe.int, ?$#0:student.course)
major > public inline (0 calls)
1: major($rec#0:student.student, ?$rec#1:student.student, $field#0:student.course): AliasPairs: []
    foreign lpvm mutate noalias(~%$rec#0:student.student, ?%$rec#1:student.student, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:student.course)


student > public inline (0 calls)
0: student(id#0:wybe.int, major#0:student.course, ?$#0:student.student): AliasPairs: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:!student.student)
    foreign lpvm mutate(~%$rec#0:student.student, ?%$rec#1:student.student, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~id#0:wybe.int)
    foreign lpvm mutate(~%$rec#1:student.student, ?%$#0:student.student, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~major#0:student.course)
student > public inline (4 calls)
1: student(?id#0:wybe.int, ?major#0:student.course, $#0:student.student): AliasPairs: []
    foreign lpvm access($#0:student.student, 0:wybe.int, ?id#0:wybe.int)
    foreign lpvm access(~$#0:student.student, 8:wybe.int, ?major#0:student.course)

  LLVM code       :

; ModuleID = 'student.student'


 


declare external fastcc  i1 @"wybe.string.=<0>"(i64, i64)    


declare external fastcc  i1 @"wybe.int.=<0>"(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  i1 @"student.student./=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"tmp$8#0" = icmp eq i64 %3, %10 
  br i1 %"tmp$8#0", label %if.then, label %if.else 
if.then:
  %15 = tail call fastcc  {i64, i64}  @"student.course.course<1>"(i64  %7)  
  %16 = extractvalue {i64, i64} %15, 0 
  %17 = extractvalue {i64, i64} %15, 1 
  %18 = tail call fastcc  {i64, i64}  @"student.course.course<1>"(i64  %14)  
  %19 = extractvalue {i64, i64} %18, 0 
  %20 = extractvalue {i64, i64} %18, 1 
  %"tmp$13#0" = tail call fastcc  i1  @"wybe.int.=<0>"(i64  %16, i64  %19)  
  br i1 %"tmp$13#0", label %if.then1, label %if.else1 
if.else:
  ret i1 1 
if.then1:
  %"tmp$1#0" = tail call fastcc  i1  @"wybe.string.=<0>"(i64  %17, i64  %20)  
  br i1 %"tmp$1#0", label %if.then2, label %if.else2 
if.else1:
  ret i1 1 
if.then2:
  ret i1 0 
if.else2:
  ret i1 1 
}


define external fastcc  i1 @"student.student.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %21 = inttoptr i64 %"$left#0" to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  %23 = load  i64, i64* %22 
  %24 = add   i64 %"$left#0", 8 
  %25 = inttoptr i64 %24 to i64* 
  %26 = getelementptr  i64, i64* %25, i64 0 
  %27 = load  i64, i64* %26 
  %28 = inttoptr i64 %"$right#0" to i64* 
  %29 = getelementptr  i64, i64* %28, i64 0 
  %30 = load  i64, i64* %29 
  %31 = add   i64 %"$right#0", 8 
  %32 = inttoptr i64 %31 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  %34 = load  i64, i64* %33 
  %"tmp$2#0" = icmp eq i64 %23, %30 
  br i1 %"tmp$2#0", label %if.then, label %if.else 
if.then:
  %35 = tail call fastcc  {i64, i64}  @"student.course.course<1>"(i64  %27)  
  %36 = extractvalue {i64, i64} %35, 0 
  %37 = extractvalue {i64, i64} %35, 1 
  %38 = tail call fastcc  {i64, i64}  @"student.course.course<1>"(i64  %34)  
  %39 = extractvalue {i64, i64} %38, 0 
  %40 = extractvalue {i64, i64} %38, 1 
  %"tmp$16#0" = tail call fastcc  i1  @"wybe.int.=<0>"(i64  %36, i64  %39)  
  br i1 %"tmp$16#0", label %if.then1, label %if.else1 
if.else:
  ret i1 0 
if.then1:
  %"tmp$3#0" = tail call fastcc  i1  @"wybe.string.=<0>"(i64  %37, i64  %40)  
  ret i1 %"tmp$3#0" 
if.else1:
  ret i1 0 
}


define external fastcc  i64 @"student.student.id<0>"(i64  %"$rec#0")    {
entry:
  %41 = inttoptr i64 %"$rec#0" to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  %43 = load  i64, i64* %42 
  ret i64 %43 
}


define external fastcc  i64 @"student.student.id<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %44 = trunc i64 16 to i32  
  %45 = tail call ccc  i8*  @wybe_malloc(i32  %44)  
  %46 = ptrtoint i8* %45 to i64 
  %47 = inttoptr i64 %46 to i8* 
  %48 = inttoptr i64 %"$rec#0" to i8* 
  %49 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %47, i8*  %48, i32  %49, i32  8, i1  0)  
  %50 = inttoptr i64 %46 to i64* 
  %51 = getelementptr  i64, i64* %50, i64 0 
  store  i64 %"$field#0", i64* %51 
  ret i64 %46 
}


define external fastcc  i64 @"student.student.major<0>"(i64  %"$rec#0")    {
entry:
  %52 = add   i64 %"$rec#0", 8 
  %53 = inttoptr i64 %52 to i64* 
  %54 = getelementptr  i64, i64* %53, i64 0 
  %55 = load  i64, i64* %54 
  ret i64 %55 
}


define external fastcc  i64 @"student.student.major<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %56 = trunc i64 16 to i32  
  %57 = tail call ccc  i8*  @wybe_malloc(i32  %56)  
  %58 = ptrtoint i8* %57 to i64 
  %59 = inttoptr i64 %58 to i8* 
  %60 = inttoptr i64 %"$rec#0" to i8* 
  %61 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %59, i8*  %60, i32  %61, i32  8, i1  0)  
  %62 = add   i64 %58, 8 
  %63 = inttoptr i64 %62 to i64* 
  %64 = getelementptr  i64, i64* %63, i64 0 
  store  i64 %"$field#0", i64* %64 
  ret i64 %58 
}


define external fastcc  i64 @"student.student.student<0>"(i64  %"id#0", i64  %"major#0")    {
entry:
  %65 = trunc i64 16 to i32  
  %66 = tail call ccc  i8*  @wybe_malloc(i32  %65)  
  %67 = ptrtoint i8* %66 to i64 
  %68 = inttoptr i64 %67 to i64* 
  %69 = getelementptr  i64, i64* %68, i64 0 
  store  i64 %"id#0", i64* %69 
  %70 = add   i64 %67, 8 
  %71 = inttoptr i64 %70 to i64* 
  %72 = getelementptr  i64, i64* %71, i64 0 
  store  i64 %"major#0", i64* %72 
  ret i64 %67 
}


define external fastcc  {i64, i64} @"student.student.student<1>"(i64  %"$#0")    {
entry:
  %73 = inttoptr i64 %"$#0" to i64* 
  %74 = getelementptr  i64, i64* %73, i64 0 
  %75 = load  i64, i64* %74 
  %76 = add   i64 %"$#0", 8 
  %77 = inttoptr i64 %76 to i64* 
  %78 = getelementptr  i64, i64* %77, i64 0 
  %79 = load  i64, i64* %78 
  %80 = insertvalue {i64, i64} undef, i64 %75, 0 
  %81 = insertvalue {i64, i64} %80, i64 %79, 1 
  ret {i64, i64} %81 
}
