======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module alias_fork2
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : alias_fork2.<0>
                    alias_fork2.simpleMerge<0>
  imports         : use mytree
                    use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: alias_fork2.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(12,(mytree.printTree1<0>,fromList [NonAliasedParamCond 1 []])),(13,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(15,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    foreign lpvm alloc(24:wybe.int, ?tmp#9##0:mytree.tree) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#9##0:mytree.tree, ?tmp#10##0:mytree.tree, 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 0:mytree.tree) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#10##0:mytree.tree, ?tmp#11##0:mytree.tree, 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 1:wybe.int) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#11##0:mytree.tree, ?tmp#0##0:mytree.tree, 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 0:mytree.tree) @alias_fork2:nn:nn
    alias_fork2.simpleMerge<0>(tmp#0##0:mytree.tree, ?tmp#3##0:mytree.tree) #3 @alias_fork2:nn:nn
    wybe.string.print<0>("expect t -  1 200:":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #11 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#13##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#13##0:wybe.phantom, ?tmp#14##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#14##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn
    mytree.printTree1<0>[6dacb8fd25](tmp#3##0:mytree.tree, 1519:wybe.string, ?tmp#16##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #12 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](1527:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #13 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #15 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#19##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#19##0:wybe.phantom, ?tmp#20##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#20##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn
    foreign llvm icmp_ne(tmp#0##0:wybe.int, 0:wybe.int, ?tmp#22##0:wybe.bool) @alias_fork2:nn:nn
    case ~tmp#22##0:wybe.bool of
    0:
        alias_fork2.#cont#1<0>(~tmp#3##0:mytree.tree, 0:mytree.tree)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #10

    1:
        foreign lpvm access(~tmp#0##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?l##0:mytree.tree) @alias_fork2:nn:nn
        foreign lpvm alloc(24:wybe.int, ?tmp#26##0:mytree.tree) @alias_fork2:nn:nn
        foreign lpvm mutate(~tmp#26##0:mytree.tree, ?tmp#27##0:mytree.tree, 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~l##0:mytree.tree) @alias_fork2:nn:nn
        foreign lpvm mutate(~tmp#27##0:mytree.tree, ?tmp#28##0:mytree.tree, 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 1000:wybe.int) @alias_fork2:nn:nn
        foreign lpvm mutate(~tmp#28##0:mytree.tree, ?tmp#4##0:mytree.tree, 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 0:mytree.tree) @alias_fork2:nn:nn
        alias_fork2.#cont#1<0>(~tmp#3##0:mytree.tree, ~tmp#4##0:mytree.tree)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #9



proc #cont#1 > {semipure} (2 calls)
0: alias_fork2.#cont#1<0>
#cont#1(t##0:mytree.tree, t1##0:mytree.tree)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(7,(mytree.printTree1<0>,fromList [NonAliasedParamCond 1 []])),(8,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(10,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(12,(mytree.printTree1<0>,fromList [NonAliasedParamCond 1 []])),(13,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(15,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.string.print<0>("expect t1 - 1000:":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn
    mytree.printTree1<0>[6dacb8fd25](~t1##0:mytree.tree, 1519:wybe.string, ?tmp#9##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #7 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](1527:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #8 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #10 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#12##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#12##0:wybe.phantom, ?tmp#13##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#13##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn
    wybe.string.print<0>("expect t1 - 1 200:":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #11 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#15##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#15##0:wybe.phantom, ?tmp#16##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#16##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn
    mytree.printTree1<0>[6dacb8fd25](~t##0:mytree.tree, 1519:wybe.string, ?tmp#18##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #12 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](1527:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #13 @alias_fork2:nn:nn
    wybe.string.print<0>[410bae77d3](0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #15 @alias_fork2:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#21##0:wybe.phantom) @alias_fork2:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#21##0:wybe.phantom, ?tmp#22##0:wybe.phantom) @alias_fork2:nn:nn
    foreign lpvm store(~%tmp#22##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_fork2:nn:nn


proc simpleMerge > public (3 calls)
0: alias_fork2.simpleMerge<0>
simpleMerge(tl##0:mytree.tree, ?#result##0:mytree.tree)<{}; {}; {}>:
  AliasPairs: [(#result##0,tl##0)]
  InterestingCallProperties: []
    foreign lpvm alloc(24:wybe.int, ?tmp#5##0:mytree.tree) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#5##0:mytree.tree, ?tmp#6##0:mytree.tree, 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~tl##0:mytree.tree) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#6##0:mytree.tree, ?tmp#7##0:mytree.tree, 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 200:wybe.int) @alias_fork2:nn:nn
    foreign lpvm mutate(~tmp#7##0:mytree.tree, ?#result##0:mytree.tree, 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, 0:mytree.tree) @alias_fork2:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'alias_fork2'

source_filename = "!ROOT!/final-dump/alias_fork2.wybe"
target triple    ????

@"cstring#0" = private unnamed_addr constant [ ?? x i8 ] c"expect t -  1 200:\00", align 8
@"cstring#1" = private unnamed_addr constant [ ?? x i8 ] c"expect t1 - 1 200:\00", align 8
@"cstring#2" = private unnamed_addr constant [ ?? x i8 ] c"expect t1 - 1000:\00", align 8
@"string#3" = private unnamed_addr constant {i64, i64} { i64 18, i64 ptrtoint( ptr @"cstring#0" to i64 ) }, align 8
@"string#4" = private unnamed_addr constant {i64, i64} { i64 18, i64 ptrtoint( ptr @"cstring#1" to i64 ) }, align 8
@"string#5" = private unnamed_addr constant {i64, i64} { i64 17, i64 ptrtoint( ptr @"cstring#2" to i64 ) }, align 8

declare external fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64, i64)
declare external fastcc void @"wybe.string.print<0>"(i64)
declare external fastcc void @"wybe.string.print<0>[410bae77d3]"(i64)
declare external ccc void @putchar(i8)
declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"alias_fork2.<0>"() {
  %"tmp#29##0" = call ccc ptr @wybe_malloc(i32 24)
  %"tmp#9##0" = ptrtoint ptr %"tmp#29##0" to i64
  %"tmp#30##0" = inttoptr i64 %"tmp#9##0" to ptr
  store i64 0, ptr %"tmp#30##0"
  %"tmp#31##0" = add i64 %"tmp#9##0", 8
  %"tmp#32##0" = inttoptr i64 %"tmp#31##0" to ptr
  store i64 1, ptr %"tmp#32##0"
  %"tmp#33##0" = add i64 %"tmp#9##0", 16
  %"tmp#34##0" = inttoptr i64 %"tmp#33##0" to ptr
  store i64 0, ptr %"tmp#34##0"
  %"tmp#3##0" = tail call fastcc i64 @"alias_fork2.simpleMerge<0>"(i64 %"tmp#9##0")
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#3" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#16##0" = tail call fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64 %"tmp#3##0", i64 1519)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 1527)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 0)
  call ccc void @putchar(i8 10)
  %"tmp#22##0" = icmp ne i64 %"tmp#9##0", 0
  br i1 %"tmp#22##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#35##0" = inttoptr i64 %"tmp#9##0" to ptr
  %"l##0" = load i64, ptr %"tmp#35##0"
  %"tmp#36##0" = call ccc ptr @wybe_malloc(i32 24)
  %"tmp#26##0" = ptrtoint ptr %"tmp#36##0" to i64
  %"tmp#37##0" = inttoptr i64 %"tmp#26##0" to ptr
  store i64 %"l##0", ptr %"tmp#37##0"
  %"tmp#38##0" = add i64 %"tmp#26##0", 8
  %"tmp#39##0" = inttoptr i64 %"tmp#38##0" to ptr
  store i64 1000, ptr %"tmp#39##0"
  %"tmp#40##0" = add i64 %"tmp#26##0", 16
  %"tmp#41##0" = inttoptr i64 %"tmp#40##0" to ptr
  store i64 0, ptr %"tmp#41##0"
  tail call fastcc void @"alias_fork2.#cont#1<0>"(i64 %"tmp#3##0", i64 %"tmp#26##0")
  ret void
if.else.0:
  tail call fastcc void @"alias_fork2.#cont#1<0>"(i64 %"tmp#3##0", i64 0)
  ret void
}

define external fastcc void @"alias_fork2.#cont#1<0>"(i64 %"t##0", i64 %"t1##0") {
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#5" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#9##0" = tail call fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64 %"t1##0", i64 1519)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 1527)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 0)
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#4" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#18##0" = tail call fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64 %"t##0", i64 1519)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 1527)
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 0)
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc i64 @"alias_fork2.simpleMerge<0>"(i64 %"tl##0") {
  %"tmp#8##0" = call ccc ptr @wybe_malloc(i32 24)
  %"tmp#5##0" = ptrtoint ptr %"tmp#8##0" to i64
  %"tmp#9##0" = inttoptr i64 %"tmp#5##0" to ptr
  store i64 %"tl##0", ptr %"tmp#9##0"
  %"tmp#10##0" = add i64 %"tmp#5##0", 8
  %"tmp#11##0" = inttoptr i64 %"tmp#10##0" to ptr
  store i64 200, ptr %"tmp#11##0"
  %"tmp#12##0" = add i64 %"tmp#5##0", 16
  %"tmp#13##0" = inttoptr i64 %"tmp#12##0" to ptr
  store i64 0, ptr %"tmp#13##0"
  ret i64 %"tmp#5##0"
}

--------------------------------------------------
 Module mytree
  representation  : (not a type)
  public submods  : tree -> mytree.tree
  public resources: 
  public procs    : mytree.printTree<0>
                    mytree.printTree1<0>
                    mytree.tree.=<0>
                    mytree.tree.empty<0>
                    mytree.tree.key<0>
                    mytree.tree.key<1>
                    mytree.tree.left<0>
                    mytree.tree.left<1>
                    mytree.tree.node<0>
                    mytree.tree.node<1>
                    mytree.tree.right<0>
                    mytree.tree.right<1>
                    mytree.tree.~=<0>
  imports         : public use mytree.tree
                    use wybe
  resources       : 
  submodules      : mytree.tree
  procs           : 

proc printTree > public {inline} (0 calls)
0: mytree.printTree<0>
printTree(t##0:mytree.tree)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    mytree.printTree1<0>(~t##0:mytree.tree, 1519:wybe.string, ?prefix##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #0 @mytree:nn:nn
    wybe.string.print<0>(1527:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @mytree:nn:nn


proc printTree1 > public (3 calls)
0: mytree.printTree1<0>[6dacb8fd25]
printTree1(t##0:mytree.tree, prefix##0:wybe.string, ?prefix##3:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: [(prefix##0,prefix##3)]
  InterestingCallProperties: [InterestingUnaliased 1]
  MultiSpeczDepInfo: [(1,(mytree.printTree1<0>,fromList [NonAliasedParamCond 1 [1]])),(2,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 [1]]))]
    foreign llvm icmp_ne(t##0:wybe.int, 0:wybe.int, ?tmp#2##0:wybe.bool) @mytree:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign llvm move(~prefix##0:wybe.string, ?prefix##3:wybe.string)

    1:
        foreign lpvm access(t##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?l##0:mytree.tree) @mytree:nn:nn
        foreign lpvm access(t##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?k##0:wybe.int) @mytree:nn:nn
        foreign lpvm access(~t##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?r##0:mytree.tree) @mytree:nn:nn
        mytree.printTree1<0>(~l##0:mytree.tree, ~prefix##0:wybe.string, ?prefix##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @mytree:nn:nn
        wybe.string.print<0>(~prefix##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @mytree:nn:nn
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#4##0:wybe.phantom) @mytree:nn:nn
        foreign c print_int(~k##0:wybe.int, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @mytree:nn:nn
        foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @mytree:nn:nn
        mytree.printTree1<0>(~r##0:mytree.tree, ", ":wybe.string, ?prefix##3:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #4 @mytree:nn:nn

 [6dacb8fd25] [NonAliasedParam 1] :
    foreign llvm icmp_ne(t##0:wybe.int, 0:wybe.int, ?tmp#2##0:wybe.bool) @mytree:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign llvm move(~prefix##0:wybe.string, ?prefix##3:wybe.string)

    1:
        foreign lpvm access(t##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?l##0:mytree.tree) @mytree:nn:nn
        foreign lpvm access(t##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?k##0:wybe.int) @mytree:nn:nn
        foreign lpvm access(~t##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?r##0:mytree.tree) @mytree:nn:nn
        mytree.printTree1<0>[6dacb8fd25](~l##0:mytree.tree, ~prefix##0:wybe.string, ?prefix##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @mytree:nn:nn
        wybe.string.print<0>[410bae77d3](~prefix##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @mytree:nn:nn
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#4##0:wybe.phantom) @mytree:nn:nn
        foreign c print_int(~k##0:wybe.int, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @mytree:nn:nn
        foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @mytree:nn:nn
        mytree.printTree1<0>(~r##0:mytree.tree, ", ":wybe.string, ?prefix##3:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #4 @mytree:nn:nn


  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'mytree'

source_filename = "!ROOT!/final-dump/mytree.wybe"
target triple    ????

@"cstring#0" = private unnamed_addr constant [ ?? x i8 ] c", \00", align 8
@"string#1" = private unnamed_addr constant {i64, i64} { i64 2, i64 ptrtoint( ptr @"cstring#0" to i64 ) }, align 8

declare external fastcc void @"wybe.string.print<0>"(i64)
declare external fastcc void @"wybe.string.print<0>[410bae77d3]"(i64)
declare external ccc void @print_int(i64)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"mytree.printTree<0>"(i64 %"t##0") {
  %"prefix##1" = tail call fastcc i64 @"mytree.printTree1<0>"(i64 %"t##0", i64 1519)
  tail call fastcc void @"wybe.string.print<0>"(i64 1527)
  ret void
}

define external fastcc i64 @"mytree.printTree1<0>"(i64 %"t##0", i64 %"prefix##0") {
  %"tmp#2##0" = icmp ne i64 %"t##0", 0
  br i1 %"tmp#2##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#6##0" = inttoptr i64 %"t##0" to ptr
  %"l##0" = load i64, ptr %"tmp#6##0"
  %"tmp#7##0" = add i64 %"t##0", 8
  %"tmp#8##0" = inttoptr i64 %"tmp#7##0" to ptr
  %"k##0" = load i64, ptr %"tmp#8##0"
  %"tmp#9##0" = add i64 %"t##0", 16
  %"tmp#10##0" = inttoptr i64 %"tmp#9##0" to ptr
  %"r##0" = load i64, ptr %"tmp#10##0"
  %"prefix##1" = tail call fastcc i64 @"mytree.printTree1<0>"(i64 %"l##0", i64 %"prefix##0")
  tail call fastcc void @"wybe.string.print<0>"(i64 %"prefix##1")
  call ccc void @print_int(i64 %"k##0")
  %"tmp#11##0" = tail call fastcc i64 @"mytree.printTree1<0>"(i64 %"r##0", i64 ptrtoint( ptr @"string#1" to i64 ))
  ret i64 %"tmp#11##0"
if.else.0:
  ret i64 %"prefix##0"
}

define external fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64 %"t##0", i64 %"prefix##0") {
  %"tmp#2##0" = icmp ne i64 %"t##0", 0
  br i1 %"tmp#2##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#6##0" = inttoptr i64 %"t##0" to ptr
  %"l##0" = load i64, ptr %"tmp#6##0"
  %"tmp#7##0" = add i64 %"t##0", 8
  %"tmp#8##0" = inttoptr i64 %"tmp#7##0" to ptr
  %"k##0" = load i64, ptr %"tmp#8##0"
  %"tmp#9##0" = add i64 %"t##0", 16
  %"tmp#10##0" = inttoptr i64 %"tmp#9##0" to ptr
  %"r##0" = load i64, ptr %"tmp#10##0"
  %"prefix##1" = tail call fastcc i64 @"mytree.printTree1<0>[6dacb8fd25]"(i64 %"l##0", i64 %"prefix##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"prefix##1")
  call ccc void @print_int(i64 %"k##0")
  %"tmp#11##0" = tail call fastcc i64 @"mytree.printTree1<0>"(i64 %"r##0", i64 ptrtoint( ptr @"string#1" to i64 ))
  ret i64 %"tmp#11##0"
if.else.0:
  ret i64 %"prefix##0"
}

--------------------------------------------------
 Module mytree.tree
  representation  : pointer
  public submods  : 
  public resources: 
  public procs    : mytree.tree.=<0>
                    mytree.tree.empty<0>
                    mytree.tree.key<0>
                    mytree.tree.key<1>
                    mytree.tree.left<0>
                    mytree.tree.left<1>
                    mytree.tree.node<0>
                    mytree.tree.node<1>
                    mytree.tree.right<0>
                    mytree.tree.right<1>
                    mytree.tree.~=<0>
  imports         : use mytree
                    use wybe
  resources       : 
  procs           : 

proc = > public (7 calls)
0: mytree.tree.=<0>
=(#left##0:mytree.tree, #right##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#left##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm icmp_eq(~#right##0:mytree.tree, 0:mytree.tree, ?#success##0:wybe.bool)

    1:
        foreign lpvm access(#left##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?#left#left##0:mytree.tree) @mytree:nn:nn
        foreign lpvm access(#left##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?#left#key##0:wybe.int) @mytree:nn:nn
        foreign lpvm access(~#left##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?#left#right##0:mytree.tree) @mytree:nn:nn
        foreign llvm icmp_ne(#right##0:wybe.int, 0:wybe.int, ?tmp#10##0:wybe.bool)
        case ~tmp#10##0:wybe.bool of
        0:
            foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

        1:
            foreign lpvm access(#right##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?#right#left##0:mytree.tree) @mytree:nn:nn
            foreign lpvm access(#right##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?#right#key##0:wybe.int) @mytree:nn:nn
            foreign lpvm access(~#right##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?#right#right##0:mytree.tree) @mytree:nn:nn
            mytree.tree.=<0>(~#left#left##0:mytree.tree, ~#right#left##0:mytree.tree, ?tmp#4##0:wybe.bool) #2
            case ~tmp#4##0:wybe.bool of
            0:
                foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

            1:
                foreign llvm icmp_eq(~#left#key##0:wybe.int, ~#right#key##0:wybe.int, ?tmp#5##0:wybe.bool) @int:nn:nn
                case ~tmp#5##0:wybe.bool of
                0:
                    foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

                1:
                    mytree.tree.=<0>(~#left#right##0:mytree.tree, ~#right#right##0:mytree.tree, ?#success##0:wybe.bool) #4






proc empty > public {inline} (0 calls)
0: mytree.tree.empty<0>
empty(?#result##0:mytree.tree)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(0:mytree.tree, ?#result##0:mytree.tree)


proc key > public {inline} (0 calls)
0: mytree.tree.key<0>
key(#rec##0:mytree.tree, ?#result##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:wybe.int, ?#result##0:wybe.int)

    1:
        foreign lpvm access(~#rec##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:wybe.int) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

proc key > public {inline} (0 calls)
1: mytree.tree.key<1>
key(#rec##0:mytree.tree, ?#rec##1:mytree.tree, #field##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(0:mytree.tree, ?#rec##1:mytree.tree)

    1:
        foreign lpvm mutate(~#rec##0:mytree.tree, ?#rec##1:mytree.tree, 8:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:wybe.int) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)



proc left > public {inline} (0 calls)
0: mytree.tree.left<0>
left(#rec##0:mytree.tree, ?#result##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:mytree.tree, ?#result##0:mytree.tree)

    1:
        foreign lpvm access(~#rec##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:mytree.tree) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

proc left > public {inline} (0 calls)
1: mytree.tree.left<1>
left(#rec##0:mytree.tree, ?#rec##1:mytree.tree, #field##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(0:mytree.tree, ?#rec##1:mytree.tree)

    1:
        foreign lpvm mutate(~#rec##0:mytree.tree, ?#rec##1:mytree.tree, 0:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:mytree.tree) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)



proc node > public {inline} (0 calls)
0: mytree.tree.node<0>
node(left##0:mytree.tree, key##0:wybe.int, right##0:mytree.tree, ?#result##0:mytree.tree)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(24:wybe.int, ?#rec##0:mytree.tree) @mytree:nn:nn
    foreign lpvm mutate(~#rec##0:mytree.tree, ?#rec##1:mytree.tree, 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~left##0:mytree.tree) @mytree:nn:nn
    foreign lpvm mutate(~#rec##1:mytree.tree, ?#rec##2:mytree.tree, 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~key##0:wybe.int) @mytree:nn:nn
    foreign lpvm mutate(~#rec##2:mytree.tree, ?#result##0:mytree.tree, 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~right##0:mytree.tree) @mytree:nn:nn
proc node > public {inline} (16 calls)
1: mytree.tree.node<1>
node(?left##0:mytree.tree, ?key##0:wybe.int, ?right##0:mytree.tree, #result##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#result##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:mytree.tree, ?left##0:mytree.tree)
        foreign llvm move(undef:wybe.int, ?key##0:wybe.int)
        foreign llvm move(undef:mytree.tree, ?right##0:mytree.tree)

    1:
        foreign lpvm access(#result##0:mytree.tree, 0:wybe.int, 24:wybe.int, 0:wybe.int, ?left##0:mytree.tree) @mytree:nn:nn
        foreign lpvm access(#result##0:mytree.tree, 8:wybe.int, 24:wybe.int, 0:wybe.int, ?key##0:wybe.int) @mytree:nn:nn
        foreign lpvm access(~#result##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?right##0:mytree.tree) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)



proc right > public {inline} (0 calls)
0: mytree.tree.right<0>
right(#rec##0:mytree.tree, ?#result##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:mytree.tree, ?#result##0:mytree.tree)

    1:
        foreign lpvm access(~#rec##0:mytree.tree, 16:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:mytree.tree) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

proc right > public {inline} (0 calls)
1: mytree.tree.right<1>
right(#rec##0:mytree.tree, ?#rec##1:mytree.tree, #field##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(#rec##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool)
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(0:mytree.tree, ?#rec##1:mytree.tree)

    1:
        foreign lpvm mutate(~#rec##0:mytree.tree, ?#rec##1:mytree.tree, 16:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:mytree.tree) @mytree:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)



proc ~= > public {inline} (0 calls)
0: mytree.tree.~=<0>
~=(#left##0:mytree.tree, #right##0:mytree.tree, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    mytree.tree.=<0>(~#left##0:mytree.tree, ~#right##0:mytree.tree, ?tmp#0##0:wybe.bool) #0
    foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'mytree.tree'

source_filename = "!ROOT!/final-dump/mytree.wybe"
target triple    ????


declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc i1 @"mytree.tree.=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#0##0" = icmp ne i64 %"#left##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#13##0" = inttoptr i64 %"#left##0" to ptr
  %"#left#left##0" = load i64, ptr %"tmp#13##0"
  %"tmp#14##0" = add i64 %"#left##0", 8
  %"tmp#15##0" = inttoptr i64 %"tmp#14##0" to ptr
  %"#left#key##0" = load i64, ptr %"tmp#15##0"
  %"tmp#16##0" = add i64 %"#left##0", 16
  %"tmp#17##0" = inttoptr i64 %"tmp#16##0" to ptr
  %"#left#right##0" = load i64, ptr %"tmp#17##0"
  %"tmp#10##0" = icmp ne i64 %"#right##0", 0
  br i1 %"tmp#10##0", label %if.then.1, label %if.else.1
if.then.1:
  %"tmp#18##0" = inttoptr i64 %"#right##0" to ptr
  %"#right#left##0" = load i64, ptr %"tmp#18##0"
  %"tmp#19##0" = add i64 %"#right##0", 8
  %"tmp#20##0" = inttoptr i64 %"tmp#19##0" to ptr
  %"#right#key##0" = load i64, ptr %"tmp#20##0"
  %"tmp#21##0" = add i64 %"#right##0", 16
  %"tmp#22##0" = inttoptr i64 %"tmp#21##0" to ptr
  %"#right#right##0" = load i64, ptr %"tmp#22##0"
  %"tmp#4##0" = tail call fastcc i1 @"mytree.tree.=<0>"(i64 %"#left#left##0", i64 %"#right#left##0")
  br i1 %"tmp#4##0", label %if.then.2, label %if.else.2
if.then.2:
  %"tmp#5##0" = icmp eq i64 %"#left#key##0", %"#right#key##0"
  br i1 %"tmp#5##0", label %if.then.3, label %if.else.3
if.then.3:
  %"tmp#23##0" = tail call fastcc i1 @"mytree.tree.=<0>"(i64 %"#left#right##0", i64 %"#right#right##0")
  ret i1 %"tmp#23##0"
if.else.3:
  ret i1 0
if.else.2:
  ret i1 0
if.else.1:
  ret i1 0
if.else.0:
  %"tmp#24##0" = icmp eq i64 %"#right##0", 0
  ret i1 %"tmp#24##0"
}

define external fastcc i64 @"mytree.tree.empty<0>"() {
  ret i64 0
}

define external fastcc {i64, i1} @"mytree.tree.key<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = add i64 %"#rec##0", 8
  %"tmp#2##0" = inttoptr i64 %"tmp#1##0" to ptr
  %"tmp#3##0" = load i64, ptr %"tmp#2##0"
  %"tmp#4##0" = insertvalue {i64, i1} undef, i64 %"tmp#3##0", 0
  %"tmp#5##0" = insertvalue {i64, i1} %"tmp#4##0", i1 1, 1
  ret {i64, i1} %"tmp#5##0"
if.else.0:
  %"tmp#6##0" = insertvalue {i64, i1} undef, i64 undef, 0
  %"tmp#7##0" = insertvalue {i64, i1} %"tmp#6##0", i1 0, 1
  ret {i64, i1} %"tmp#7##0"
}

define external fastcc {i64, i1} @"mytree.tree.key<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#2##0" = call ccc ptr @wybe_malloc(i32 24)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#2##0", ptr %"tmp#1##0", i64 24, i1 0)
  %"tmp#3##0" = ptrtoint ptr %"tmp#2##0" to i64
  %"tmp#4##0" = add i64 %"tmp#3##0", 8
  %"tmp#5##0" = inttoptr i64 %"tmp#4##0" to ptr
  store i64 %"#field##0", ptr %"tmp#5##0"
  %"tmp#6##0" = insertvalue {i64, i1} undef, i64 %"tmp#3##0", 0
  %"tmp#7##0" = insertvalue {i64, i1} %"tmp#6##0", i1 1, 1
  ret {i64, i1} %"tmp#7##0"
if.else.0:
  %"tmp#8##0" = insertvalue {i64, i1} undef, i64 0, 0
  %"tmp#9##0" = insertvalue {i64, i1} %"tmp#8##0", i1 0, 1
  ret {i64, i1} %"tmp#9##0"
}

define external fastcc {i64, i1} @"mytree.tree.left<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#2##0" = load i64, ptr %"tmp#1##0"
  %"tmp#3##0" = insertvalue {i64, i1} undef, i64 %"tmp#2##0", 0
  %"tmp#4##0" = insertvalue {i64, i1} %"tmp#3##0", i1 1, 1
  ret {i64, i1} %"tmp#4##0"
if.else.0:
  %"tmp#5##0" = insertvalue {i64, i1} undef, i64 undef, 0
  %"tmp#6##0" = insertvalue {i64, i1} %"tmp#5##0", i1 0, 1
  ret {i64, i1} %"tmp#6##0"
}

define external fastcc {i64, i1} @"mytree.tree.left<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#2##0" = call ccc ptr @wybe_malloc(i32 24)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#2##0", ptr %"tmp#1##0", i64 24, i1 0)
  %"tmp#3##0" = ptrtoint ptr %"tmp#2##0" to i64
  %"tmp#4##0" = inttoptr i64 %"tmp#3##0" to ptr
  store i64 %"#field##0", ptr %"tmp#4##0"
  %"tmp#5##0" = insertvalue {i64, i1} undef, i64 %"tmp#3##0", 0
  %"tmp#6##0" = insertvalue {i64, i1} %"tmp#5##0", i1 1, 1
  ret {i64, i1} %"tmp#6##0"
if.else.0:
  %"tmp#7##0" = insertvalue {i64, i1} undef, i64 0, 0
  %"tmp#8##0" = insertvalue {i64, i1} %"tmp#7##0", i1 0, 1
  ret {i64, i1} %"tmp#8##0"
}

define external fastcc i64 @"mytree.tree.node<0>"(i64 %"left##0", i64 %"key##0", i64 %"right##0") {
  %"tmp#0##0" = call ccc ptr @wybe_malloc(i32 24)
  %"#rec##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  store i64 %"left##0", ptr %"tmp#1##0"
  %"tmp#2##0" = add i64 %"#rec##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  store i64 %"key##0", ptr %"tmp#3##0"
  %"tmp#4##0" = add i64 %"#rec##0", 16
  %"tmp#5##0" = inttoptr i64 %"tmp#4##0" to ptr
  store i64 %"right##0", ptr %"tmp#5##0"
  ret i64 %"#rec##0"
}

define external fastcc {i64, i64, i64, i1} @"mytree.tree.node<1>"(i64 %"#result##0") {
  %"tmp#0##0" = icmp ne i64 %"#result##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = inttoptr i64 %"#result##0" to ptr
  %"tmp#2##0" = load i64, ptr %"tmp#1##0"
  %"tmp#3##0" = add i64 %"#result##0", 8
  %"tmp#4##0" = inttoptr i64 %"tmp#3##0" to ptr
  %"tmp#5##0" = load i64, ptr %"tmp#4##0"
  %"tmp#6##0" = add i64 %"#result##0", 16
  %"tmp#7##0" = inttoptr i64 %"tmp#6##0" to ptr
  %"tmp#8##0" = load i64, ptr %"tmp#7##0"
  %"tmp#9##0" = insertvalue {i64, i64, i64, i1} undef, i64 %"tmp#2##0", 0
  %"tmp#10##0" = insertvalue {i64, i64, i64, i1} %"tmp#9##0", i64 %"tmp#5##0", 1
  %"tmp#11##0" = insertvalue {i64, i64, i64, i1} %"tmp#10##0", i64 %"tmp#8##0", 2
  %"tmp#12##0" = insertvalue {i64, i64, i64, i1} %"tmp#11##0", i1 1, 3
  ret {i64, i64, i64, i1} %"tmp#12##0"
if.else.0:
  %"tmp#13##0" = insertvalue {i64, i64, i64, i1} undef, i64 undef, 0
  %"tmp#14##0" = insertvalue {i64, i64, i64, i1} %"tmp#13##0", i64 undef, 1
  %"tmp#15##0" = insertvalue {i64, i64, i64, i1} %"tmp#14##0", i64 undef, 2
  %"tmp#16##0" = insertvalue {i64, i64, i64, i1} %"tmp#15##0", i1 0, 3
  ret {i64, i64, i64, i1} %"tmp#16##0"
}

define external fastcc {i64, i1} @"mytree.tree.right<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = add i64 %"#rec##0", 16
  %"tmp#2##0" = inttoptr i64 %"tmp#1##0" to ptr
  %"tmp#3##0" = load i64, ptr %"tmp#2##0"
  %"tmp#4##0" = insertvalue {i64, i1} undef, i64 %"tmp#3##0", 0
  %"tmp#5##0" = insertvalue {i64, i1} %"tmp#4##0", i1 1, 1
  ret {i64, i1} %"tmp#5##0"
if.else.0:
  %"tmp#6##0" = insertvalue {i64, i1} undef, i64 undef, 0
  %"tmp#7##0" = insertvalue {i64, i1} %"tmp#6##0", i1 0, 1
  ret {i64, i1} %"tmp#7##0"
}

define external fastcc {i64, i1} @"mytree.tree.right<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = icmp ne i64 %"#rec##0", 0
  br i1 %"tmp#0##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#2##0" = call ccc ptr @wybe_malloc(i32 24)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#2##0", ptr %"tmp#1##0", i64 24, i1 0)
  %"tmp#3##0" = ptrtoint ptr %"tmp#2##0" to i64
  %"tmp#4##0" = add i64 %"tmp#3##0", 16
  %"tmp#5##0" = inttoptr i64 %"tmp#4##0" to ptr
  store i64 %"#field##0", ptr %"tmp#5##0"
  %"tmp#6##0" = insertvalue {i64, i1} undef, i64 %"tmp#3##0", 0
  %"tmp#7##0" = insertvalue {i64, i1} %"tmp#6##0", i1 1, 1
  ret {i64, i1} %"tmp#7##0"
if.else.0:
  %"tmp#8##0" = insertvalue {i64, i1} undef, i64 0, 0
  %"tmp#9##0" = insertvalue {i64, i1} %"tmp#8##0", i1 0, 1
  ret {i64, i1} %"tmp#9##0"
}

define external fastcc i1 @"mytree.tree.~=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#0##0" = tail call fastcc i1 @"mytree.tree.=<0>"(i64 %"#left##0", i64 %"#right##0")
  %"tmp#1##0" = xor i1 %"tmp#0##0", 1
  ret i1 %"tmp#1##0"
}
