======================================================================
AFTER EVERYTHING:
 Module alias_multifunc1
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : alias_multifunc1.<0>
                    alias_multifunc1.replicate1<0>
                    alias_multifunc1.replicate2<0>
  imports         : use position
                    use wybe
  resources       : 
  procs           : 

*main* > public {impure} (0 calls)
0: alias_multifunc1.<0>
(%io##0:wybe.phantom, %?io##16:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?tmp#3##0:position.position)
    foreign lpvm mutate(~tmp#3##0:position.position, ?tmp#4##0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 10:wybe.int)
    foreign lpvm mutate(~tmp#4##0:position.position, ?tmp#0##0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 10:wybe.int)
    alias_multifunc1.replicate1<0>(tmp#0##0:position.position, ?p2##0:position.position, ?p3##0:position.position, ~%io##0:wybe.phantom, ?%io##1:wybe.phantom) #1 @alias_multifunc1:19:2
    wybe.string.print_string<0>("--- After calling replicate1: ":wybe.string, ~%io##1:wybe.phantom, ?%tmp#7##0:wybe.phantom) #19 @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#7##0:wybe.phantom, ?%io##2:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>("expect p1(10,10):":wybe.string, ~%io##2:wybe.phantom, ?%io##3:wybe.phantom) #20 @io:nn:nn
    position.printPosition<0>(tmp#0##0:position.position, ~%io##3:wybe.phantom, ?%io##4:wybe.phantom) #4 @alias_multifunc1:23:2
    wybe.string.print_string<0>("expect p2(22,10):":wybe.string, ~%io##4:wybe.phantom, ?%io##5:wybe.phantom) #21 @io:nn:nn
    position.printPosition<0>(p2##0:position.position, ~%io##5:wybe.phantom, ?%io##6:wybe.phantom) #6 @alias_multifunc1:25:2
    wybe.string.print_string<0>("expect p3(10,10):":wybe.string, ~%io##6:wybe.phantom, ?%io##7:wybe.phantom) #22 @io:nn:nn
    position.printPosition<0>(p3##0:position.position, ~%io##7:wybe.phantom, ?%io##8:wybe.phantom) #8 @alias_multifunc1:27:2
    foreign lpvm {noalias} mutate(~p2##0:position.position, ?p2##1:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2222222:wybe.int)
    wybe.string.print_string<0>("--- After calling x(!p2, 2222222): ":wybe.string, ~%io##8:wybe.phantom, ?%tmp#18##0:wybe.phantom) #23 @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#18##0:wybe.phantom, ?%io##9:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>("expect p2(2222222,10):":wybe.string, ~%io##9:wybe.phantom, ?%io##10:wybe.phantom) #24 @io:nn:nn
    position.printPosition<0>(~p2##1:position.position, ~%io##10:wybe.phantom, ?%io##11:wybe.phantom) #12 @alias_multifunc1:33:2
    foreign lpvm {noalias} mutate(~tmp#0##0:position.position, ?p1##1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, 11:wybe.int)
    wybe.string.print_string<0>("--- After calling x(!p1, 11): ":wybe.string, ~%io##11:wybe.phantom, ?%tmp#25##0:wybe.phantom) #25 @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#25##0:wybe.phantom, ?%io##12:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>("expect p1(11,10):":wybe.string, ~%io##12:wybe.phantom, ?%io##13:wybe.phantom) #26 @io:nn:nn
    position.printPosition<0>(~p1##1:position.position, ~%io##13:wybe.phantom, ?%io##14:wybe.phantom) #16 @alias_multifunc1:45:2
    wybe.string.print_string<0>("expect p3(10,10):":wybe.string, ~%io##14:wybe.phantom, ?%io##15:wybe.phantom) #27 @io:nn:nn
    position.printPosition<0>(~p3##0:position.position, ~%io##15:wybe.phantom, ?%io##16:wybe.phantom) #18 @alias_multifunc1:47:2


replicate1 > public (1 calls)
0: alias_multifunc1.replicate1<0>
replicate1(p1##0:position.position, ?p2##1:position.position, ?p3##0:position.position, %io##0:wybe.phantom, %?io##2:wybe.phantom):
 AliasPairs: [(p1##0,p3##0)]
 InterestingCallProperties: []
    alias_multifunc1.replicate2<0>(~p1##0:position.position, ?p2##0:position.position, ~%io##0:wybe.phantom, ?%io##1:wybe.phantom) #0 @alias_multifunc1:13:6
    alias_multifunc1.replicate2<0>(p2##0:position.position, ?p3##0:position.position, ~%io##1:wybe.phantom, ?%io##2:wybe.phantom) #1 @alias_multifunc1:14:6
    foreign lpvm {noalias} mutate(~p2##0:position.position, ?p2##1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, 22:wybe.int)


replicate2 > public (2 calls)
0: alias_multifunc1.replicate2<0>
replicate2(p1##0:position.position, ?p2##0:position.position, %io##0:wybe.phantom, %?io##2:wybe.phantom):
 AliasPairs: [(p1##0,p2##0)]
 InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?tmp#4##0:position.position)
    foreign lpvm mutate(~tmp#4##0:position.position, ?tmp#5##0:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:wybe.int)
    foreign lpvm mutate(~tmp#5##0:position.position, ?tmp#0##0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:wybe.int)
    wybe.string.print_string<0>("some noise...":wybe.string, ~%io##0:wybe.phantom, ?%io##1:wybe.phantom) #4 @io:nn:nn
    foreign lpvm access(~tmp#0##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.int)
    foreign c print_int(~tmp#1##0:wybe.int, ~%io##1:wybe.phantom, ?%tmp#11##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#11##0:wybe.phantom, ?%io##2:wybe.phantom) @io:nn:nn
    foreign llvm move(~p1##0:position.position, ?p2##0:position.position) @alias_multifunc1:8:6

  LLVM code       :

; ModuleID = 'alias_multifunc1'


 


declare external fastcc  void @"position.printPosition<0>"(i64)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


declare external ccc  void @putchar(i8)    


@"constant#alias_multifunc1.39" =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.38" to i64) }


@"constant#alias_multifunc1.38" =    constant [?? x i8] c"expect p3(10,10):\00"


@"constant#alias_multifunc1.37" =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.36" to i64) }


@"constant#alias_multifunc1.36" =    constant [?? x i8] c"expect p1(11,10):\00"


@"constant#alias_multifunc1.35" =    constant {i64, i64} { i64 30, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.34" to i64) }


@"constant#alias_multifunc1.34" =    constant [?? x i8] c"--- After calling x(!p1, 11): \00"


@"constant#alias_multifunc1.25" =    constant {i64, i64} { i64 22, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.24" to i64) }


@"constant#alias_multifunc1.24" =    constant [?? x i8] c"expect p2(2222222,10):\00"


@"constant#alias_multifunc1.23" =    constant {i64, i64} { i64 35, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.22" to i64) }


@"constant#alias_multifunc1.22" =    constant [?? x i8] c"--- After calling x(!p2, 2222222): \00"


@"constant#alias_multifunc1.19" =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.18" to i64) }


@"constant#alias_multifunc1.18" =    constant [?? x i8] c"expect p3(10,10):\00"


@"constant#alias_multifunc1.17" =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.16" to i64) }


@"constant#alias_multifunc1.16" =    constant [?? x i8] c"expect p2(22,10):\00"


@"constant#alias_multifunc1.15" =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.14" to i64) }


@"constant#alias_multifunc1.14" =    constant [?? x i8] c"expect p1(10,10):\00"


@"constant#alias_multifunc1.13" =    constant {i64, i64} { i64 30, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.12" to i64) }


@"constant#alias_multifunc1.12" =    constant [?? x i8] c"--- After calling replicate1: \00"


declare external ccc  void @print_int(i64)    


@"constant#alias_multifunc1.59" =    constant {i64, i64} { i64 13, i64 ptrtoint ([?? x i8]* @"constant#alias_multifunc1.58" to i64) }


@"constant#alias_multifunc1.58" =    constant [?? x i8] c"some noise...\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"alias_multifunc1.<0>"()    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 10, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  store  i64 10, i64* %8 
  %9 = tail call fastcc  {i64, i64}  @"alias_multifunc1.replicate1<0>"(i64  %3)  
  %10 = extractvalue {i64, i64} %9, 0 
  %11 = extractvalue {i64, i64} %9, 1 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.13", i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.15", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %3)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.17", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %10)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.19", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %11)  
  %20 = inttoptr i64 %10 to i64* 
  %21 = getelementptr  i64, i64* %20, i64 0 
  store  i64 2222222, i64* %21 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.23", i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.25", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %10)  
  %26 = trunc i64 16 to i32  
  %27 = tail call ccc  i8*  @wybe_malloc(i32  %26)  
  %28 = ptrtoint i8* %27 to i64 
  %29 = inttoptr i64 %28 to i8* 
  %30 = inttoptr i64 %3 to i8* 
  %31 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %29, i8*  %30, i32  %31, i32  8, i1  0)  
  %32 = inttoptr i64 %28 to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  store  i64 11, i64* %33 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.35", i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.37", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %28)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.39", i32 0, i32 0) to i64))  
  tail call fastcc  void  @"position.printPosition<0>"(i64  %11)  
  ret void 
}


define external fastcc  {i64, i64} @"alias_multifunc1.replicate1<0>"(i64  %"p1##0")    {
entry:
  %"1#p2##0" = tail call fastcc  i64  @"alias_multifunc1.replicate2<0>"(i64  %"p1##0")  
  %"1#p3##0" = tail call fastcc  i64  @"alias_multifunc1.replicate2<0>"(i64  %"1#p2##0")  
  %40 = trunc i64 16 to i32  
  %41 = tail call ccc  i8*  @wybe_malloc(i32  %40)  
  %42 = ptrtoint i8* %41 to i64 
  %43 = inttoptr i64 %42 to i8* 
  %44 = inttoptr i64 %"1#p2##0" to i8* 
  %45 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %43, i8*  %44, i32  %45, i32  8, i1  0)  
  %46 = inttoptr i64 %42 to i64* 
  %47 = getelementptr  i64, i64* %46, i64 0 
  store  i64 22, i64* %47 
  %48 = insertvalue {i64, i64} undef, i64 %42, 0 
  %49 = insertvalue {i64, i64} %48, i64 %"1#p3##0", 1 
  ret {i64, i64} %49 
}


define external fastcc  i64 @"alias_multifunc1.replicate2<0>"(i64  %"p1##0")    {
entry:
  %50 = trunc i64 16 to i32  
  %51 = tail call ccc  i8*  @wybe_malloc(i32  %50)  
  %52 = ptrtoint i8* %51 to i64 
  %53 = inttoptr i64 %52 to i64* 
  %54 = getelementptr  i64, i64* %53, i64 0 
  store  i64 0, i64* %54 
  %55 = add   i64 %52, 8 
  %56 = inttoptr i64 %55 to i64* 
  %57 = getelementptr  i64, i64* %56, i64 0 
  store  i64 0, i64* %57 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#alias_multifunc1.59", i32 0, i32 0) to i64))  
  %60 = inttoptr i64 %52 to i64* 
  %61 = getelementptr  i64, i64* %60, i64 0 
  %62 = load  i64, i64* %61 
  tail call ccc  void  @print_int(i64  %62)  
  tail call ccc  void  @putchar(i8  10)  
  ret i64 %"p1##0" 
}
--------------------------------------------------
 Module position
  representation  : (not a type)
  public submods  : position -> position.position
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
                    position.position.~=<0>
  imports         : public use position.position
                    use wybe
  resources       : 
  submodules      : position.position
  procs           : 

printPosition > public (0 calls)
0: position.printPosition<0>
printPosition(pos##0:position.position, %io##0:wybe.phantom, %?io##5:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.string.print_string<0>(" (":wybe.string, ~%io##0:wybe.phantom, ?%io##1:wybe.phantom) #7 @io:nn:nn
    foreign lpvm access(pos##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.int)
    foreign c print_int(~tmp#0##0:wybe.int, ~%io##1:wybe.phantom, ?%io##2:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>(",":wybe.string, ~%io##2:wybe.phantom, ?%io##3:wybe.phantom) #8 @io:nn:nn
    foreign lpvm access(~pos##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.int)
    foreign c print_int(~tmp#1##0:wybe.int, ~%io##3:wybe.phantom, ?%io##4:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>(")":wybe.string, ~%io##4:wybe.phantom, ?%tmp#14##0:wybe.phantom) #9 @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#14##0:wybe.phantom, ?%io##5:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'position'


 


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


declare external ccc  void @print_int(i64)    


@"constant#position.13" =    constant {i64, i64} { i64 1, i64 ptrtoint ([?? x i8]* @"constant#position.12" to i64) }


@"constant#position.12" =    constant [?? x i8] c")\00"


@"constant#position.7" =    constant {i64, i64} { i64 1, i64 ptrtoint ([?? x i8]* @"constant#position.6" to i64) }


@"constant#position.6" =    constant [?? x i8] c",\00"


@"constant#position.2" =    constant {i64, i64} { i64 2, i64 ptrtoint ([?? x i8]* @"constant#position.1" to i64) }


@"constant#position.1" =    constant [?? x i8] c" (\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"position.printPosition<0>"(i64  %"pos##0")    {
entry:
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#position.2", i32 0, i32 0) to i64))  
  %3 = inttoptr i64 %"pos##0" to i64* 
  %4 = getelementptr  i64, i64* %3, i64 0 
  %5 = load  i64, i64* %4 
  tail call ccc  void  @print_int(i64  %5)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#position.7", i32 0, i32 0) to i64))  
  %8 = add   i64 %"pos##0", 8 
  %9 = inttoptr i64 %8 to i64* 
  %10 = getelementptr  i64, i64* %9, i64 0 
  %11 = load  i64, i64* %10 
  tail call ccc  void  @print_int(i64  %11)  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @"constant#position.13", i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module position.position
  representation  : address
  public submods  : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
                    position.position.~=<0>
  imports         : use position
                    use wybe
  resources       : 
  procs           : 

= > public {inline} (1 calls)
0: position.position.=<0>
=(#left##0:position.position, #right##0:position.position, ?#success##0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm access(#left##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#x##0:wybe.int)
    foreign lpvm access(~#left##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#y##0:wybe.int)
    foreign lpvm access(#right##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#x##0:wybe.int)
    foreign lpvm access(~#right##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#y##0:wybe.int)
    foreign llvm icmp_eq(~#left#x##0:wybe.int, ~#right#x##0:wybe.int, ?tmp#1##0:wybe.bool) @int:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~#left#y##0:wybe.int, ~#right#y##0:wybe.int, ?#success##0:wybe.bool) @int:nn:nn



position > public {inline} (0 calls)
0: position.position.position<0>
position(x##0:wybe.int, y##0:wybe.int, ?#result##0:position.position):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?#rec##0:position.position)
    foreign lpvm mutate(~#rec##0:position.position, ?#rec##1:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x##0:wybe.int)
    foreign lpvm mutate(~#rec##1:position.position, ?#result##0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~y##0:wybe.int)
position > public {inline} (6 calls)
1: position.position.position<1>
position(?x##0:wybe.int, ?y##0:wybe.int, #result##0:position.position):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm access(#result##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?x##0:wybe.int)
    foreign lpvm access(~#result##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?y##0:wybe.int)


x > public {inline} (0 calls)
0: position.position.x<0>
x(#rec##0:position.position, ?#result##0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm access(~#rec##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int)
x > public {inline} (0 calls)
1: position.position.x<1>
x(#rec##0:position.position, ?#rec##1:position.position, #field##0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:position.position, ?#rec##1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int)


y > public {inline} (0 calls)
0: position.position.y<0>
y(#rec##0:position.position, ?#result##0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm access(~#rec##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int)
y > public {inline} (0 calls)
1: position.position.y<1>
y(#rec##0:position.position, ?#rec##1:position.position, #field##0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:position.position, ?#rec##1:position.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int)


~= > public {inline} (0 calls)
0: position.position.~=<0>
~=(#left##0:position.position, #right##0:position.position, ?#success##0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm access(#left##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#3##0:wybe.int)
    foreign lpvm access(~#left##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#4##0:wybe.int)
    foreign lpvm access(#right##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#5##0:wybe.int)
    foreign lpvm access(~#right##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#6##0:wybe.int)
    foreign llvm icmp_eq(~tmp#3##0:wybe.int, ~tmp#5##0:wybe.int, ?tmp#7##0:wybe.bool) @int:nn:nn
    case ~tmp#7##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?tmp#0##0:wybe.bool)
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~tmp#4##0:wybe.int, ~tmp#6##0:wybe.int, ?tmp#0##0:wybe.bool) @int:nn:nn
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)


  LLVM code       :

; ModuleID = 'position.position'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  i1 @"position.position.=<0>"(i64  %"#left##0", i64  %"#right##0")    {
entry:
  %1 = inttoptr i64 %"#left##0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"#left##0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %8 = inttoptr i64 %"#right##0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"#right##0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"1#tmp#1##0" = icmp eq i64 %3, %10 
  br i1 %"1#tmp#1##0", label %if.then, label %if.else 
if.then:
  %"2##success##0" = icmp eq i64 %7, %14 
  ret i1 %"2##success##0" 
if.else:
  ret i1 0 
}


define external fastcc  i64 @"position.position.position<0>"(i64  %"x##0", i64  %"y##0")    {
entry:
  %15 = trunc i64 16 to i32  
  %16 = tail call ccc  i8*  @wybe_malloc(i32  %15)  
  %17 = ptrtoint i8* %16 to i64 
  %18 = inttoptr i64 %17 to i64* 
  %19 = getelementptr  i64, i64* %18, i64 0 
  store  i64 %"x##0", i64* %19 
  %20 = add   i64 %17, 8 
  %21 = inttoptr i64 %20 to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  store  i64 %"y##0", i64* %22 
  ret i64 %17 
}


define external fastcc  {i64, i64} @"position.position.position<1>"(i64  %"#result##0")    {
entry:
  %23 = inttoptr i64 %"#result##0" to i64* 
  %24 = getelementptr  i64, i64* %23, i64 0 
  %25 = load  i64, i64* %24 
  %26 = add   i64 %"#result##0", 8 
  %27 = inttoptr i64 %26 to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  %30 = insertvalue {i64, i64} undef, i64 %25, 0 
  %31 = insertvalue {i64, i64} %30, i64 %29, 1 
  ret {i64, i64} %31 
}


define external fastcc  i64 @"position.position.x<0>"(i64  %"#rec##0")    {
entry:
  %32 = inttoptr i64 %"#rec##0" to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  %34 = load  i64, i64* %33 
  ret i64 %34 
}


define external fastcc  i64 @"position.position.x<1>"(i64  %"#rec##0", i64  %"#field##0")    {
entry:
  %35 = trunc i64 16 to i32  
  %36 = tail call ccc  i8*  @wybe_malloc(i32  %35)  
  %37 = ptrtoint i8* %36 to i64 
  %38 = inttoptr i64 %37 to i8* 
  %39 = inttoptr i64 %"#rec##0" to i8* 
  %40 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %38, i8*  %39, i32  %40, i32  8, i1  0)  
  %41 = inttoptr i64 %37 to i64* 
  %42 = getelementptr  i64, i64* %41, i64 0 
  store  i64 %"#field##0", i64* %42 
  ret i64 %37 
}


define external fastcc  i64 @"position.position.y<0>"(i64  %"#rec##0")    {
entry:
  %43 = add   i64 %"#rec##0", 8 
  %44 = inttoptr i64 %43 to i64* 
  %45 = getelementptr  i64, i64* %44, i64 0 
  %46 = load  i64, i64* %45 
  ret i64 %46 
}


define external fastcc  i64 @"position.position.y<1>"(i64  %"#rec##0", i64  %"#field##0")    {
entry:
  %47 = trunc i64 16 to i32  
  %48 = tail call ccc  i8*  @wybe_malloc(i32  %47)  
  %49 = ptrtoint i8* %48 to i64 
  %50 = inttoptr i64 %49 to i8* 
  %51 = inttoptr i64 %"#rec##0" to i8* 
  %52 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %50, i8*  %51, i32  %52, i32  8, i1  0)  
  %53 = add   i64 %49, 8 
  %54 = inttoptr i64 %53 to i64* 
  %55 = getelementptr  i64, i64* %54, i64 0 
  store  i64 %"#field##0", i64* %55 
  ret i64 %49 
}


define external fastcc  i1 @"position.position.~=<0>"(i64  %"#left##0", i64  %"#right##0")    {
entry:
  %56 = inttoptr i64 %"#left##0" to i64* 
  %57 = getelementptr  i64, i64* %56, i64 0 
  %58 = load  i64, i64* %57 
  %59 = add   i64 %"#left##0", 8 
  %60 = inttoptr i64 %59 to i64* 
  %61 = getelementptr  i64, i64* %60, i64 0 
  %62 = load  i64, i64* %61 
  %63 = inttoptr i64 %"#right##0" to i64* 
  %64 = getelementptr  i64, i64* %63, i64 0 
  %65 = load  i64, i64* %64 
  %66 = add   i64 %"#right##0", 8 
  %67 = inttoptr i64 %66 to i64* 
  %68 = getelementptr  i64, i64* %67, i64 0 
  %69 = load  i64, i64* %68 
  %"1#tmp#7##0" = icmp eq i64 %58, %65 
  br i1 %"1#tmp#7##0", label %if.then, label %if.else 
if.then:
  %"2#tmp#0##0" = icmp eq i64 %62, %69 
  %"2##success##0" = xor i1 %"2#tmp#0##0", 1 
  ret i1 %"2##success##0" 
if.else:
  %"3##success##0" = xor i1 0, 1 
  ret i1 %"3##success##0" 
}
