======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module alias_recursion1
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : alias_recursion1.<0>
                    alias_recursion1.if_test<0>
  constants       : 0:: CStringInfo {cstringChars = "--- before proc call: "}
                    1:: CStringInfo {cstringChars = "expect pa(100,101):"}
                    2:: CStringInfo {cstringChars = "expect pb(-200,-201):"}
                    3:: CStringInfo {cstringChars = "--- after calling if_test, pa and pb should be the same: "}
                    4:: CStringInfo {cstringChars = "--- expected result to be same as pb: "}
                    5:: CStringInfo {cstringChars = "expect r(-200,-201):"}
                    6:: CStringInfo {cstringChars = "--- modify pa^x: "}
                    7:: CStringInfo {cstringChars = "expect pa(-1000,101):"}
                    8:: CStringInfo {cstringChars = "expect r still (-200,-201):"}
                    9:: StructInfo {structSize = 16, structData = [IntStructMember 100 8,IntStructMember 101 8]}
                    10:: StructInfo {structSize = 16, structData = [IntStructMember (-200) 8,IntStructMember (-201) 8]}
                    11:: StructInfo {structSize = 16, structData = [IntStructMember 22 8,PointerStructMember c"--- before proc call: "]}
                    12:: StructInfo {structSize = 16, structData = [IntStructMember 19 8,PointerStructMember c"expect pa(100,101):"]}
                    13:: StructInfo {structSize = 16, structData = [IntStructMember 21 8,PointerStructMember c"expect pb(-200,-201):"]}
                    14:: StructInfo {structSize = 16, structData = [IntStructMember 57 8,PointerStructMember c"--- after calling if_test, pa and pb should be the same: "]}
                    15:: StructInfo {structSize = 16, structData = [IntStructMember 38 8,PointerStructMember c"--- expected result to be same as pb: "]}
                    16:: StructInfo {structSize = 16, structData = [IntStructMember 20 8,PointerStructMember c"expect r(-200,-201):"]}
                    17:: StructInfo {structSize = 16, structData = [IntStructMember 17 8,PointerStructMember c"--- modify pa^x: "]}
                    18:: StructInfo {structSize = 16, structData = [IntStructMember 21 8,PointerStructMember c"expect pa(-1000,101):"]}
                    19:: StructInfo {structSize = 16, structData = [IntStructMember 27 8,PointerStructMember c"expect r still (-200,-201):"]}
  imports         : use position
                    use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: alias_recursion1.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.print<0>("--- before proc call: ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #33 @alias_recursion1:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#26##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#26##0:wybe.phantom, ?tmp#27##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign lpvm store(~%tmp#27##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_recursion1:nn:nn
    wybe.string.print<0>("expect pa(100,101):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5 @alias_recursion1:nn:nn
    position.printPosition<0>(alias_recursion1#constant#9:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6 @alias_recursion1:nn:nn
    wybe.string.print<0>("expect pb(-200,-201):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #8 @alias_recursion1:nn:nn
    position.printPosition<0>(alias_recursion1#constant#10:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #9 @alias_recursion1:nn:nn
    alias_recursion1.if_test<0>(alias_recursion1#constant#9:position.position, alias_recursion1#constant#10:position.position, ?r##0:position.position) #10 @alias_recursion1:nn:nn
    wybe.string.print<0>("--- after calling if_test, pa and pb should be the same: ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #34 @alias_recursion1:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#41##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#41##0:wybe.phantom, ?tmp#42##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign lpvm store(~%tmp#42##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_recursion1:nn:nn
    wybe.string.print<0>("expect pa(100,101):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #14 @alias_recursion1:nn:nn
    position.printPosition<0>(alias_recursion1#constant#9:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #15 @alias_recursion1:nn:nn
    wybe.string.print<0>("expect pb(-200,-201):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #17 @alias_recursion1:nn:nn
    position.printPosition<0>(alias_recursion1#constant#10:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #18 @alias_recursion1:nn:nn
    wybe.string.print<0>("--- expected result to be same as pb: ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #35 @alias_recursion1:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#56##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#56##0:wybe.phantom, ?tmp#57##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign lpvm store(~%tmp#57##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_recursion1:nn:nn
    wybe.string.print<0>("expect r(-200,-201):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #22 @alias_recursion1:nn:nn
    position.printPosition<0>(r##0:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #23 @alias_recursion1:nn:nn
    wybe.string.print<0>("--- modify pa^x: ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #36 @alias_recursion1:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#67##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#67##0:wybe.phantom, ?tmp#68##0:wybe.phantom) @alias_recursion1:nn:nn
    foreign lpvm store(~%tmp#68##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @alias_recursion1:nn:nn
    foreign lpvm {noalias} mutate(alias_recursion1#constant#9:position.position, ?pa##1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, -1000:wybe.int) @alias_recursion1:nn:nn
    wybe.string.print<0>("expect pa(-1000,101):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #28 @alias_recursion1:nn:nn
    position.printPosition<0>(~pa##1:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #29 @alias_recursion1:nn:nn
    wybe.string.print<0>("expect r still (-200,-201):":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #31 @alias_recursion1:nn:nn
    position.printPosition<0>(~r##0:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #32 @alias_recursion1:nn:nn


proc if_test > public (2 calls)
0: alias_recursion1.if_test<0>
if_test(a##0:position.position, b##0:position.position, ?r##0:position.position)<{}; {}; {}>:
  AliasPairs: [(a##0,b##0),(a##0,r##0),(b##0,r##0)]
  InterestingCallProperties: []
    foreign lpvm access(a##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.int) @alias_recursion1:nn:nn
    foreign llvm icmp_sgt(~tmp#0##0:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.bool) @alias_recursion1:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign llvm move(~a##0:position.position, ?r##0:position.position) @alias_recursion1:nn:nn

    1:
        alias_recursion1.if_test<0>(~b##0:position.position, ~a##0:position.position, ?r##0:position.position) #2 @alias_recursion1:nn:nn


  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'alias_recursion1'

source_filename = "!ROOT!/final-dump/alias_recursion1.wybe"
target triple    ????

@"alias_recursion1#constant#0" = private unnamed_addr constant [ ?? x i8 ] c"--- before proc call: \00", align 8
@"alias_recursion1#constant#1" = private unnamed_addr constant [ ?? x i8 ] c"expect pa(100,101):\00", align 8
@"alias_recursion1#constant#2" = private unnamed_addr constant [ ?? x i8 ] c"expect pb(-200,-201):\00", align 8
@"alias_recursion1#constant#3" = private unnamed_addr constant [ ?? x i8 ] c"--- after calling if_test, pa and pb should be the same: \00", align 8
@"alias_recursion1#constant#4" = private unnamed_addr constant [ ?? x i8 ] c"--- expected result to be same as pb: \00", align 8
@"alias_recursion1#constant#5" = private unnamed_addr constant [ ?? x i8 ] c"expect r(-200,-201):\00", align 8
@"alias_recursion1#constant#6" = private unnamed_addr constant [ ?? x i8 ] c"--- modify pa^x: \00", align 8
@"alias_recursion1#constant#7" = private unnamed_addr constant [ ?? x i8 ] c"expect pa(-1000,101):\00", align 8
@"alias_recursion1#constant#8" = private unnamed_addr constant [ ?? x i8 ] c"expect r still (-200,-201):\00", align 8
@"alias_recursion1#constant#9" = private unnamed_addr constant {i64, i64} { i64 100, i64 101 }, align 8
@"alias_recursion1#constant#10" = private unnamed_addr constant {i64, i64} { i64 -200, i64 -201 }, align 8
@"alias_recursion1#constant#11" = private unnamed_addr constant {i64, ptr} { i64 22, ptr @"alias_recursion1#constant#0" }, align 8
@"alias_recursion1#constant#12" = private unnamed_addr constant {i64, ptr} { i64 19, ptr @"alias_recursion1#constant#1" }, align 8
@"alias_recursion1#constant#13" = private unnamed_addr constant {i64, ptr} { i64 21, ptr @"alias_recursion1#constant#2" }, align 8
@"alias_recursion1#constant#14" = private unnamed_addr constant {i64, ptr} { i64 57, ptr @"alias_recursion1#constant#3" }, align 8
@"alias_recursion1#constant#15" = private unnamed_addr constant {i64, ptr} { i64 38, ptr @"alias_recursion1#constant#4" }, align 8
@"alias_recursion1#constant#16" = private unnamed_addr constant {i64, ptr} { i64 20, ptr @"alias_recursion1#constant#5" }, align 8
@"alias_recursion1#constant#17" = private unnamed_addr constant {i64, ptr} { i64 17, ptr @"alias_recursion1#constant#6" }, align 8
@"alias_recursion1#constant#18" = private unnamed_addr constant {i64, ptr} { i64 21, ptr @"alias_recursion1#constant#7" }, align 8
@"alias_recursion1#constant#19" = private unnamed_addr constant {i64, ptr} { i64 27, ptr @"alias_recursion1#constant#8" }, align 8

declare external fastcc void @"position.printPosition<0>"(i64)
declare external fastcc void @"wybe.string.print<0>"(i64)
declare external ccc void @putchar(i8)
declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"alias_recursion1.<0>"() {
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#11" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#12" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#9" to i64 ))
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#13" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#10" to i64 ))
  %"r##0" = tail call fastcc i64 @"alias_recursion1.if_test<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#9" to i64 ), i64 ptrtoint( ptr @"alias_recursion1#constant#10" to i64 ))
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#14" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#12" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#9" to i64 ))
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#13" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#10" to i64 ))
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#15" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#16" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 %"r##0")
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#17" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#80##0" = call ccc ptr @wybe_malloc(i32 16)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#80##0", ptr @"alias_recursion1#constant#9", i64 16, i1 0)
  %"tmp#81##0" = ptrtoint ptr %"tmp#80##0" to i64
  %"tmp#82##0" = inttoptr i64 %"tmp#81##0" to ptr
  store i64 -1000, ptr %"tmp#82##0"
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#18" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 %"tmp#81##0")
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"alias_recursion1#constant#19" to i64 ))
  tail call fastcc void @"position.printPosition<0>"(i64 %"r##0")
  ret void
}

define external fastcc i64 @"alias_recursion1.if_test<0>"(i64 %"a##0", i64 %"b##0") {
  %"tmp#5##0" = inttoptr i64 %"a##0" to ptr
  %"tmp#0##0" = load i64, ptr %"tmp#5##0"
  %"tmp#1##0" = icmp sgt i64 %"tmp#0##0", 0
  br i1 %"tmp#1##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#6##0" = tail call fastcc i64 @"alias_recursion1.if_test<0>"(i64 %"b##0", i64 %"a##0")
  ret i64 %"tmp#6##0"
if.else.0:
  ret i64 %"a##0"
}

--------------------------------------------------
 Module position
  representation  : (not a type)
  public submods  : position -> position.position
  public resources: 
  public procs    : position.printPosition<0>
                    position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
                    position.position.~=<0>
  constants       : 0:: CStringInfo {cstringChars = " ("}
                    1:: StructInfo {structSize = 16, structData = [IntStructMember 2 8,PointerStructMember c" ("]}
  imports         : public use position.position
                    use wybe
  resources       : 
  submodules      : position.position
  procs           : 

proc printPosition > public (0 calls)
0: position.printPosition<0>
printPosition(pos##0:position.position)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(5,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(10,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.string.print<0>(" (":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @position:nn:nn
    foreign lpvm access(pos##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.int) @position:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#11##0:wybe.phantom) @position:nn:nn
    foreign c print_int(~tmp#1##0:wybe.int, ~tmp#11##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @position:nn:nn
    foreign lpvm store(~%tmp#12##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @position:nn:nn
    wybe.string.print<0>[410bae77d3](1203:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5 @position:nn:nn
    foreign lpvm access(~pos##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#3##0:wybe.int) @position:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#19##0:wybe.phantom) @position:nn:nn
    foreign c print_int(~tmp#3##0:wybe.int, ~tmp#19##0:wybe.phantom, ?tmp#20##0:wybe.phantom) @position:nn:nn
    foreign lpvm store(~%tmp#20##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @position:nn:nn
    wybe.string.print<0>[410bae77d3](1191:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #10 @position:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#26##0:wybe.phantom) @position:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#26##0:wybe.phantom, ?tmp#27##0:wybe.phantom) @position:nn:nn
    foreign lpvm store(~%tmp#27##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @position:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'position'

source_filename = "!ROOT!/final-dump/position.wybe"
target triple    ????

@"position#constant#0" = private unnamed_addr constant [ ?? x i8 ] c" (\00", align 8
@"position#constant#1" = private unnamed_addr constant {i64, ptr} { i64 2, ptr @"position#constant#0" }, align 8

declare external fastcc void @"wybe.string.print<0>"(i64)
declare external fastcc void @"wybe.string.print<0>[410bae77d3]"(i64)
declare external ccc void @print_int(i64)
declare external ccc void @putchar(i8)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"position.printPosition<0>"(i64 %"pos##0") {
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"position#constant#1" to i64 ))
  %"tmp#28##0" = inttoptr i64 %"pos##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#28##0"
  call ccc void @print_int(i64 %"tmp#1##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 1203)
  %"tmp#29##0" = add i64 %"pos##0", 8
  %"tmp#30##0" = inttoptr i64 %"tmp#29##0" to ptr
  %"tmp#3##0" = load i64, ptr %"tmp#30##0"
  call ccc void @print_int(i64 %"tmp#3##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 1191)
  call ccc void @putchar(i8 10)
  ret void
}

--------------------------------------------------
 Module position.position
  representation  : pointer
  public submods  : 
  public resources: 
  public procs    : position.position.=<0>
                    position.position.position<0>
                    position.position.position<1>
                    position.position.x<0>
                    position.position.x<1>
                    position.position.y<0>
                    position.position.y<1>
                    position.position.~=<0>
  constants       : 
  imports         : use position
                    use wybe
  resources       : 
  procs           : 

proc = > public {inline} (1 calls)
0: position.position.=<0>
=(#left##0:position.position, #right##0:position.position, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#left##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#x##0:wybe.int) @position:nn:nn
    foreign lpvm access(~#left##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#y##0:wybe.int) @position:nn:nn
    foreign lpvm access(#right##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#x##0:wybe.int) @position:nn:nn
    foreign lpvm access(~#right##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#y##0:wybe.int) @position:nn:nn
    foreign llvm icmp_eq(~#left#x##0:wybe.int, ~#right#x##0:wybe.int, ?tmp#1##0:wybe.bool) @int:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~#left#y##0:wybe.int, ~#right#y##0:wybe.int, ?#success##0:wybe.bool) @int:nn:nn



proc position > public {inline} (0 calls)
0: position.position.position<0>
position(x##0:wybe.int, y##0:wybe.int, ?#result##0:position.position)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?#rec##0:position.position) @position:nn:nn
    foreign lpvm mutate(~#rec##0:position.position, ?#rec##1:position.position, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x##0:wybe.int) @position:nn:nn
    foreign lpvm mutate(~#rec##1:position.position, ?#result##0:position.position, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~y##0:wybe.int) @position:nn:nn
proc position > public {inline} (6 calls)
1: position.position.position<1>
position(?x##0:wybe.int, ?y##0:wybe.int, #result##0:position.position)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#result##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?x##0:wybe.int) @position:nn:nn
    foreign lpvm access(~#result##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?y##0:wybe.int) @position:nn:nn


proc x > public {inline} (0 calls)
0: position.position.x<0>
x(#rec##0:position.position, ?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int) @position:nn:nn
proc x > public {inline} (0 calls)
1: position.position.x<1>
x(#rec##0:position.position, ?#rec##1:position.position, #field##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:position.position, ?#rec##1:position.position, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int) @position:nn:nn


proc y > public {inline} (0 calls)
0: position.position.y<0>
y(#rec##0:position.position, ?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int) @position:nn:nn
proc y > public {inline} (0 calls)
1: position.position.y<1>
y(#rec##0:position.position, ?#rec##1:position.position, #field##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:position.position, ?#rec##1:position.position, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int) @position:nn:nn


proc ~= > public {inline} (0 calls)
0: position.position.~=<0>
~=(#left##0:position.position, #right##0:position.position, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#left##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#3##0:wybe.int) @position:nn:nn
    foreign lpvm access(~#left##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#4##0:wybe.int) @position:nn:nn
    foreign lpvm access(#right##0:position.position, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#5##0:wybe.int) @position:nn:nn
    foreign lpvm access(~#right##0:position.position, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#6##0:wybe.int) @position:nn:nn
    foreign llvm icmp_eq(~tmp#3##0:wybe.int, ~tmp#5##0:wybe.int, ?tmp#7##0:wybe.bool) @int:nn:nn
    case ~tmp#7##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?tmp#0##0:wybe.bool)
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~tmp#4##0:wybe.int, ~tmp#6##0:wybe.int, ?tmp#0##0:wybe.bool) @int:nn:nn
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)


  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'position.position'

source_filename = "!ROOT!/final-dump/position.wybe"
target triple    ????


declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc i1 @"position.position.=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#9##0" = inttoptr i64 %"#left##0" to ptr
  %"#left#x##0" = load i64, ptr %"tmp#9##0"
  %"tmp#10##0" = add i64 %"#left##0", 8
  %"tmp#11##0" = inttoptr i64 %"tmp#10##0" to ptr
  %"#left#y##0" = load i64, ptr %"tmp#11##0"
  %"tmp#12##0" = inttoptr i64 %"#right##0" to ptr
  %"#right#x##0" = load i64, ptr %"tmp#12##0"
  %"tmp#13##0" = add i64 %"#right##0", 8
  %"tmp#14##0" = inttoptr i64 %"tmp#13##0" to ptr
  %"#right#y##0" = load i64, ptr %"tmp#14##0"
  %"tmp#1##0" = icmp eq i64 %"#left#x##0", %"#right#x##0"
  br i1 %"tmp#1##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#15##0" = icmp eq i64 %"#left#y##0", %"#right#y##0"
  ret i1 %"tmp#15##0"
if.else.0:
  ret i1 0
}

define external fastcc i64 @"position.position.position<0>"(i64 %"x##0", i64 %"y##0") {
  %"tmp#0##0" = call ccc ptr @wybe_malloc(i32 16)
  %"#rec##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  store i64 %"x##0", ptr %"tmp#1##0"
  %"tmp#2##0" = add i64 %"#rec##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  store i64 %"y##0", ptr %"tmp#3##0"
  ret i64 %"#rec##0"
}

define external fastcc {i64, i64} @"position.position.position<1>"(i64 %"#result##0") {
  %"tmp#0##0" = inttoptr i64 %"#result##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#0##0"
  %"tmp#2##0" = add i64 %"#result##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  %"tmp#4##0" = load i64, ptr %"tmp#3##0"
  %"tmp#5##0" = insertvalue {i64, i64} undef, i64 %"tmp#1##0", 0
  %"tmp#6##0" = insertvalue {i64, i64} %"tmp#5##0", i64 %"tmp#4##0", 1
  ret {i64, i64} %"tmp#6##0"
}

define external fastcc i64 @"position.position.x<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#0##0"
  ret i64 %"tmp#1##0"
}

define external fastcc i64 @"position.position.x<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#1##0" = call ccc ptr @wybe_malloc(i32 16)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#1##0", ptr %"tmp#0##0", i64 16, i1 0)
  %"tmp#2##0" = ptrtoint ptr %"tmp#1##0" to i64
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  store i64 %"#field##0", ptr %"tmp#3##0"
  ret i64 %"tmp#2##0"
}

define external fastcc i64 @"position.position.y<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = add i64 %"#rec##0", 8
  %"tmp#1##0" = inttoptr i64 %"tmp#0##0" to ptr
  %"tmp#2##0" = load i64, ptr %"tmp#1##0"
  ret i64 %"tmp#2##0"
}

define external fastcc i64 @"position.position.y<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#1##0" = call ccc ptr @wybe_malloc(i32 16)
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#1##0", ptr %"tmp#0##0", i64 16, i1 0)
  %"tmp#2##0" = ptrtoint ptr %"tmp#1##0" to i64
  %"tmp#3##0" = add i64 %"tmp#2##0", 8
  %"tmp#4##0" = inttoptr i64 %"tmp#3##0" to ptr
  store i64 %"#field##0", ptr %"tmp#4##0"
  ret i64 %"tmp#2##0"
}

define external fastcc i1 @"position.position.~=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#8##0" = inttoptr i64 %"#left##0" to ptr
  %"tmp#3##0" = load i64, ptr %"tmp#8##0"
  %"tmp#9##0" = add i64 %"#left##0", 8
  %"tmp#10##0" = inttoptr i64 %"tmp#9##0" to ptr
  %"tmp#4##0" = load i64, ptr %"tmp#10##0"
  %"tmp#11##0" = inttoptr i64 %"#right##0" to ptr
  %"tmp#5##0" = load i64, ptr %"tmp#11##0"
  %"tmp#12##0" = add i64 %"#right##0", 8
  %"tmp#13##0" = inttoptr i64 %"tmp#12##0" to ptr
  %"tmp#6##0" = load i64, ptr %"tmp#13##0"
  %"tmp#7##0" = icmp eq i64 %"tmp#3##0", %"tmp#5##0"
  br i1 %"tmp#7##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#0##0" = icmp eq i64 %"tmp#4##0", %"tmp#6##0"
  %"tmp#14##0" = xor i1 %"tmp#0##0", 1
  ret i1 %"tmp#14##0"
if.else.0:
  %"tmp#15##0" = xor i1 0, 1
  ret i1 %"tmp#15##0"
}
