Error detected during type checking of module(s) alias_recursion3, alias_recursion3.mynode
final-dump/alias_recursion3.wybe:12:5: Output parameter resutl1 not defined by proc foo
final-dump/alias_recursion3.wybe:15:17: Calling test proc alias_recursion3.mynode.next<0> in a normal (total) context
final-dump/alias_recursion3.wybe:16:13: Calling test proc alias_recursion3.mynode.next<1> in a normal (total) context
final-dump/alias_recursion3.wybe:16:28: Calling test proc alias_recursion3.mynode.next<0> in a normal (total) context
