======================================================================
AFTER EVERYTHING:
 Module assert_error
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : assert_error.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: assert_error.<0>
()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.control.assert<0>(0:wybe.bool, c"assert_error:3:2":wybe.c_string) #1 @assert_error:nn:nn
    foreign c {terminal,semipure} error_exit(c"assert_error:5:2":wybe.c_string, c"we should never get here":wybe.c_string) @assert_error:nn:nn

  LLVM code       :

; ModuleID = 'assert_error'


 


@assert_error.0 =    constant [?? x i8] c"assert_error:3:2\00"


@assert_error.1 =    constant [?? x i8] c"assert_error:5:2\00"


@assert_error.2 =    constant [?? x i8] c"we should never get here\00"


declare external ccc  void @error_exit(i64, i64)    


declare external fastcc  void @"wybe.control.assert<0>"(i1, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"assert_error.<0>"()    {
entry:
  tail call fastcc  void  @"wybe.control.assert<0>"(i1  0, i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @assert_error.0, i32 0, i32 0) to i64))  
  tail call ccc  void  @error_exit(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @assert_error.1, i32 0, i32 0) to i64), i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @assert_error.2, i32 0, i32 0) to i64))  
  ret void 
}
