======================================================================
AFTER EVERYTHING:
 Module bar
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : bar.<0>
  imports         : use numbers
                    use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: bar.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    numbers.factorial<0>(4:wybe.int, ?tmp#0##0:wybe.int) #0 @bar:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @int:nn:nn
    foreign c print_int(~tmp#0##0:wybe.int, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @io:nn:nn
    foreign c print_float(35.0:wybe.float, ~tmp#5##0:wybe.phantom, ?tmp#10##0:wybe.phantom) @float:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#10##0:wybe.phantom, ?tmp#11##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#11##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'bar'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_float(double)    


declare external ccc  void @print_int(i64)    


declare external fastcc  i64 @"numbers.factorial<0>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"bar.<0>"()    {
entry:
  %0 = tail call fastcc  i64  @"numbers.factorial<0>"(i64  4)  
  tail call ccc  void  @print_int(i64  %0)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  3.500000e1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
--------------------------------------------------
 Module numbers
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : numbers.<0>
                    numbers.factorial<0>
                    numbers.toCelsius<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: numbers.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.print<0>("Numbers has been initialised.":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#2##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn


proc factorial > public (1 calls)
0: numbers.factorial<0>
factorial(n##0:wybe.int, ?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_sle(n##0:wybe.int, 0:wybe.int, ?tmp#4##0:wybe.bool) @int:nn:nn
    case ~tmp#4##0:wybe.bool of
    0:
        foreign llvm sub(n##0:wybe.int, 1:wybe.int, ?tmp#3##0:wybe.int) @int:nn:nn
        numbers.factorial<0>(~tmp#3##0:wybe.int, ?tmp#2##0:wybe.int) #2 @numbers:nn:nn
        foreign llvm mul(~n##0:wybe.int, ~tmp#2##0:wybe.int, ?#result##0:wybe.int) @int:nn:nn

    1:
        foreign llvm move(1:wybe.int, ?#result##0:wybe.int) @numbers:nn:nn



proc toCelsius > public {inline} (0 calls)
0: numbers.toCelsius<0>
toCelsius(f##0:wybe.float, ?#result##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm fsub(~f##0:wybe.float, 32.0:wybe.float, ?tmp#1##0:wybe.float) @float:nn:nn
    foreign llvm fdiv(~tmp#1##0:wybe.float, 1.8:wybe.float, ?#result##0:wybe.float) @float:nn:nn

  LLVM code       :

; ModuleID = 'numbers'


 


@numbers.1 =    constant {i64, i64} { i64 29, i64 ptrtoint ([?? x i8]* @numbers.0 to i64) }


@numbers.0 =    constant [?? x i8] c"Numbers has been initialised.\00"


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"numbers.<0>"() alwaysinline   {
entry:
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @numbers.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  i64 @"numbers.factorial<0>"(i64  %"n##0")    {
entry:
  %0 = icmp sle i64 %"n##0", 0 
  br i1 %0, label %if.then, label %if.else 
if.then:
  ret i64 1 
if.else:
  %1 = sub   i64 %"n##0", 1 
  %2 = tail call fastcc  i64  @"numbers.factorial<0>"(i64  %1)  
  %3 = mul   i64 %"n##0", %2 
  ret i64 %3 
}


define external fastcc  double @"numbers.toCelsius<0>"(double  %"f##0") alwaysinline   {
entry:
  %0 = fsub double %"f##0", 3.200000e1 
  %1 = fdiv double %0, 1.800000e0 
  ret double %1 
}
