======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module bug_497
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : bug_497.<0>
  constants       : 0:: StructInfo {structSize = 16, structData = [FnPointerStructMember bug_497.#anon#1<1>,IntStructMember 3 8]}
  imports         : use logging
                    use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: bug_497.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    bug_497.call<0>(bug_497.#anon#1<1><3>:(wybe.int, ?wybe.bool), 2:wybe.int, ?tmp#0##0:wybe.bool) #0 @bug_497:nn:nn
    wybe.bool.print<0>(~tmp#0##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #4 @bug_497:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#8##0:wybe.phantom) @bug_497:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @bug_497:nn:nn
    foreign lpvm store(~%tmp#9##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @bug_497:nn:nn
    bug_497.proc<0>(3:wybe.int, ?tmp#5##0:wybe.bool) #2 @bug_497:nn:nn
    wybe.bool.print<0>(~tmp#5##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5 @bug_497:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#11##0:wybe.phantom) @bug_497:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#11##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @bug_497:nn:nn
    foreign lpvm store(~%tmp#12##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @bug_497:nn:nn


proc #anon#1 > {inline} (1 calls)
0: bug_497.#anon#1<0>
#anon#1(^p##0:wybe.int, anon#1#1##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.int.fmt<2>(p##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#2##0:wybe.string) #8 @bug_497:nn:nn
    wybe.int.fmt<2>(~anon#1#1##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#4##0:wybe.string) #9 @bug_497:nn:nn
    wybe.string.,,<0>(1155:wybe.string, ~tmp#4##0:wybe.string, ?tmp#3##0:wybe.string) #3 @bug_497:nn:nn
    wybe.string.,,<0>(~tmp#2##0:wybe.string, ~tmp#3##0:wybe.string, ?tmp#1##0:wybe.string) #4 @bug_497:nn:nn
    wybe.string.c_string<0>(~tmp#1##0:wybe.string, ?tmp#15##0:wybe.c_string) #10 @bug_497:nn:nn
    foreign c {impure} log_string(~tmp#15##0:wybe.c_string) @bug_497:nn:nn
    foreign c {impure} log_char(10:wybe.char) @bug_497:nn:nn
    foreign llvm icmp_eq(~p##0:wybe.int, 3:wybe.int, ?#success##0:wybe.bool) @bug_497:nn:nn
proc #anon#1 > {inline} (1 calls)
1: bug_497.#anon#1<1>
#anon#1(^p##0:wybe.int, anon#1#1##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.int.fmt<2>(^p##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#2##0:wybe.string) #1 @bug_497:nn:nn
    wybe.int.fmt<2>(~anon#1#1##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#3##0:wybe.string) #2 @bug_497:nn:nn
    wybe.string.,,<0>(1155:wybe.string, ~tmp#3##0:wybe.string, ?tmp#4##0:wybe.string) #3 @bug_497:nn:nn
    wybe.string.,,<0>(~tmp#2##0:wybe.string, ~tmp#4##0:wybe.string, ?tmp#5##0:wybe.string) #4 @bug_497:nn:nn
    wybe.string.c_string<0>(~tmp#5##0:wybe.string, ?tmp#6##0:wybe.c_string) #5 @bug_497:nn:nn
    foreign c {impure} log_string(~tmp#6##0:wybe.c_string) @bug_497:nn:nn
    foreign c {impure} log_char(10:wybe.char) @bug_497:nn:nn
    foreign llvm icmp_eq(~^p##0:wybe.int, 3:wybe.int, ?#success##0:wybe.bool) @bug_497:nn:nn


proc call > {noinline} (2 calls)
0: bug_497.call<0>
call(f##0:(X, ?wybe.bool) <{}; {}; {0}>, x##0:X <{}; {}; {1}>, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    ~f##0:(X, ?wybe.bool)(~x##0:X, ?#success##0:wybe.bool) #0 @bug_497:nn:nn


proc proc > {noinline} (1 calls)
0: bug_497.proc<0>
proc(p##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    bug_497.call<0>(bug_497.proc#anon#1<1><^p##0:wybe.int>:(wybe.int, ?wybe.bool), 2:wybe.int, ?#success##0:wybe.bool) #0 @bug_497:nn:nn


proc proc#anon#1 > {inline} (1 calls)
0: bug_497.proc#anon#1<0>
proc#anon#1(^p##0:wybe.int, anon#1#1##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.int.fmt<2>(p##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#1##0:wybe.string) #8 @bug_497:nn:nn
    wybe.int.fmt<2>(~anon#1#1##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#3##0:wybe.string) #9 @bug_497:nn:nn
    wybe.string.,,<0>(1155:wybe.string, ~tmp#3##0:wybe.string, ?tmp#2##0:wybe.string) #3 @bug_497:nn:nn
    wybe.string.,,<0>(~tmp#1##0:wybe.string, ~tmp#2##0:wybe.string, ?tmp#0##0:wybe.string) #4 @bug_497:nn:nn
    wybe.string.c_string<0>(~tmp#0##0:wybe.string, ?tmp#14##0:wybe.c_string) #10 @bug_497:nn:nn
    foreign c {impure} log_string(~tmp#14##0:wybe.c_string) @bug_497:nn:nn
    foreign c {impure} log_char(10:wybe.char) @bug_497:nn:nn
    foreign llvm icmp_eq(~p##0:wybe.int, 3:wybe.int, ?#success##0:wybe.bool) @bug_497:nn:nn
proc proc#anon#1 > {inline} (1 calls)
1: bug_497.proc#anon#1<1>
proc#anon#1(^p##0:wybe.int, anon#1#1##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.int.fmt<2>(^p##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#2##0:wybe.string) #1 @bug_497:nn:nn
    wybe.int.fmt<2>(~anon#1#1##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#3##0:wybe.string) #2 @bug_497:nn:nn
    wybe.string.,,<0>(1155:wybe.string, ~tmp#3##0:wybe.string, ?tmp#4##0:wybe.string) #3 @bug_497:nn:nn
    wybe.string.,,<0>(~tmp#2##0:wybe.string, ~tmp#4##0:wybe.string, ?tmp#5##0:wybe.string) #4 @bug_497:nn:nn
    wybe.string.c_string<0>(~tmp#5##0:wybe.string, ?tmp#6##0:wybe.c_string) #5 @bug_497:nn:nn
    foreign c {impure} log_string(~tmp#6##0:wybe.c_string) @bug_497:nn:nn
    foreign c {impure} log_char(10:wybe.char) @bug_497:nn:nn
    foreign llvm icmp_eq(~^p##0:wybe.int, 3:wybe.int, ?#success##0:wybe.bool) @bug_497:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'bug_497'

source_filename = "!ROOT!/final-dump/bug_497.wybe"
target triple    ????

@"bug_497#constant#0" = private unnamed_addr constant {ptr, i64} { ptr @"bug_497.#anon#1<1>", i64 3 }, align 8

declare external fastcc void @"wybe.bool.print<0>"(i1)
declare external fastcc i64 @"wybe.int.fmt<2>"(i64, i64, i8)
declare external fastcc i64 @"wybe.string.,,<0>"(i64, i64)
declare external fastcc i64 @"wybe.string.c_string<0>"(i64)
declare external ccc void @log_char(i8)
declare external ccc void @log_string(i64)
declare external ccc void @putchar(i8)
declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"bug_497.<0>"() {
  %"tmp#0##0" = tail call fastcc i1 @"bug_497.call<0>"(ptr @"bug_497#constant#0", i64 2)
  tail call fastcc void @"wybe.bool.print<0>"(i1 %"tmp#0##0")
  call ccc void @putchar(i8 10)
  %"tmp#5##0" = tail call fastcc i1 @"bug_497.proc<0>"(i64 3)
  tail call fastcc void @"wybe.bool.print<0>"(i1 %"tmp#5##0")
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc i1 @"bug_497.#anon#1<0>"(i64 %"p##0", i64 %"anon#1#1##0") {
  %"tmp#2##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"p##0", i64 0, i8 32)
  %"tmp#4##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"anon#1#1##0", i64 0, i8 32)
  %"tmp#3##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 1155, i64 %"tmp#4##0")
  %"tmp#1##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#2##0", i64 %"tmp#3##0")
  %"tmp#15##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"tmp#1##0")
  call ccc void @log_string(i64 %"tmp#15##0")
  call ccc void @log_char(i8 10)
  %"tmp#18##0" = icmp eq i64 %"p##0", 3
  ret i1 %"tmp#18##0"
}

define external fastcc i64 @"bug_497.#anon#1<1>"(ptr %"#env##0", i64 %"generic#anon#1#1##0") {
  %"tmp#7##0" = getelementptr inbounds {ptr, i64}, ptr %"#env##0", i64 0, i32 1
  %"p##0" = load i64, ptr %"tmp#7##0"
  %"tmp#2##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"p##0", i64 0, i8 32)
  %"tmp#3##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"generic#anon#1#1##0", i64 0, i8 32)
  %"tmp#4##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 1155, i64 %"tmp#3##0")
  %"tmp#5##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#2##0", i64 %"tmp#4##0")
  %"tmp#6##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"tmp#5##0")
  call ccc void @log_string(i64 %"tmp#6##0")
  call ccc void @log_char(i8 10)
  %"#success##0" = icmp eq i64 %"p##0", 3
  %"tmp#8##0" = zext i1 %"#success##0" to i64
  ret i64 %"tmp#8##0"
}

define external fastcc i1 @"bug_497.call<0>"(ptr %"f##0", i64 %"x##0") {
  %"tmp#1##0" = load ptr, ptr %"f##0"
  %"tmp#2##0" = tail call fastcc i1 %"tmp#1##0"(ptr %"f##0", i64 %"x##0")
  ret i1 %"tmp#2##0"
}

define external fastcc i1 @"bug_497.proc<0>"(i64 %"p##0") {
  %"tmp#7##0" = getelementptr inbounds {ptr, i64}, ptr null, i64 1
  %"tmp#8##0" = ptrtoint ptr %"tmp#7##0" to i32
  %"tmp#6##0" = call ccc ptr @wybe_malloc(i32 %"tmp#8##0")
  store ptr @"bug_497.proc#anon#1<1>", ptr %"tmp#6##0"
  %"tmp#9##0" = getelementptr inbounds {ptr, i64}, ptr %"tmp#6##0", i64 0, i32 1
  store i64 %"p##0", ptr %"tmp#9##0"
  %"tmp#10##0" = tail call fastcc i1 @"bug_497.call<0>"(ptr %"tmp#6##0", i64 2)
  ret i1 %"tmp#10##0"
}

define external fastcc i1 @"bug_497.proc#anon#1<0>"(i64 %"p##0", i64 %"anon#1#1##0") {
  %"tmp#1##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"p##0", i64 0, i8 32)
  %"tmp#3##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"anon#1#1##0", i64 0, i8 32)
  %"tmp#2##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 1155, i64 %"tmp#3##0")
  %"tmp#0##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#1##0", i64 %"tmp#2##0")
  %"tmp#14##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"tmp#0##0")
  call ccc void @log_string(i64 %"tmp#14##0")
  call ccc void @log_char(i8 10)
  %"tmp#17##0" = icmp eq i64 %"p##0", 3
  ret i1 %"tmp#17##0"
}

define external fastcc i64 @"bug_497.proc#anon#1<1>"(ptr %"#env##0", i64 %"generic#anon#1#1##0") {
  %"tmp#7##0" = getelementptr inbounds {ptr, i64}, ptr %"#env##0", i64 0, i32 1
  %"p##0" = load i64, ptr %"tmp#7##0"
  %"tmp#2##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"p##0", i64 0, i8 32)
  %"tmp#3##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"generic#anon#1#1##0", i64 0, i8 32)
  %"tmp#4##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 1155, i64 %"tmp#3##0")
  %"tmp#5##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#2##0", i64 %"tmp#4##0")
  %"tmp#6##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"tmp#5##0")
  call ccc void @log_string(i64 %"tmp#6##0")
  call ccc void @log_char(i8 10)
  %"#success##0" = icmp eq i64 %"p##0", 3
  %"tmp#8##0" = zext i1 %"#success##0" to i64
  ret i64 %"tmp#8##0"
}

--------------------------------------------------
 Module logging
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : logging.logmsg<0>
                    logging.logmsg<1>
                    logging.logmsg<2>
                    logging.logmsg<3>
                    logging.logmsg<4>
                    logging.logmsg<5>
                    logging.logmsg<6>
                    logging.lognl<0>
  constants       : 0:: CStringInfo {cstringChars = "true"}
                    1:: CStringInfo {cstringChars = "false"}
                    2:: ArrayInfo {arrayData = [PointerStructMember c"false",PointerStructMember c"true"]}
  imports         : use wybe
  resources       : 
  procs           : 

proc logmsg > public {inline,semipure} (0 calls)
0: logging.logmsg<0>
logmsg(x##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_int(~x##0:wybe.int) @logging:nn:nn
proc logmsg > public {inline,semipure} (0 calls)
1: logging.logmsg<1>
logmsg(x##0:wybe.count)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_count(~x##0:wybe.count) @logging:nn:nn
proc logmsg > public {inline,semipure} (0 calls)
2: logging.logmsg<2>
logmsg(x##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_float(~x##0:wybe.float) @logging:nn:nn
proc logmsg > public {inline,semipure} (1 calls)
3: logging.logmsg<3>
logmsg(x##0:wybe.char)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_char(~x##0:wybe.char) @logging:nn:nn
proc logmsg > public {inline,semipure} (0 calls)
4: logging.logmsg<4>
logmsg(x##0:wybe.string)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.c_string<0>(~x##0:wybe.string, ?tmp#0##0:wybe.c_string) #0 @logging:nn:nn
    foreign c {impure} log_string(~tmp#0##0:wybe.c_string) @logging:nn:nn
proc logmsg > public {inline,semipure} (3 calls)
5: logging.logmsg<5>
logmsg(x##0:wybe.c_string)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_string(~x##0:wybe.c_string) @logging:nn:nn
proc logmsg > public {semipure} (0 calls)
6: logging.logmsg<6>
logmsg(x##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    factored ~x##0:wybe.bool of
      ?tmp#4##0:wybe.c_string <- logging#constant#2[PointerStructMember c"false",PointerStructMember c"true"]
        foreign c {impure} log_string(~tmp#4##0:wybe.c_string) @logging:nn:nn


proc lognl > public {inline,semipure} (0 calls)
0: logging.lognl<0>
lognl()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c {impure} log_char(10:wybe.char) @logging:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'logging'

source_filename = "!ROOT!/../wybelibs/logging.o"
target triple    ????

@"logging#constant#0" = private unnamed_addr constant [ ?? x i8 ] c"true\00", align 8
@"logging#constant#1" = private unnamed_addr constant [ ?? x i8 ] c"false\00", align 8
@"logging#constant#2" = private unnamed_addr constant [ 2 x ptr ] [ptr @"logging#constant#1", ptr @"logging#constant#0"]

declare external fastcc i64 @"wybe.string.c_string<0>"(i64)
declare external ccc void @log_char(i8)
declare external ccc void @log_count(i64)
declare external ccc void @log_float(double)
declare external ccc void @log_int(i64)
declare external ccc void @log_string(i64)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"logging.logmsg<0>"(i64 %"x##0") {
  call ccc void @log_int(i64 %"x##0")
  ret void
}

define external fastcc void @"logging.logmsg<1>"(i64 %"x##0") {
  call ccc void @log_count(i64 %"x##0")
  ret void
}

define external fastcc void @"logging.logmsg<2>"(double %"x##0") {
  call ccc void @log_float(double %"x##0")
  ret void
}

define external fastcc void @"logging.logmsg<3>"(i8 %"x##0") {
  call ccc void @log_char(i8 %"x##0")
  ret void
}

define external fastcc void @"logging.logmsg<4>"(i64 %"x##0") {
  %"tmp#0##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"x##0")
  call ccc void @log_string(i64 %"tmp#0##0")
  ret void
}

define external fastcc void @"logging.logmsg<5>"(i64 %"x##0") {
  call ccc void @log_string(i64 %"x##0")
  ret void
}

define external fastcc void @"logging.logmsg<6>"(i1 %"x##0") {
  %"tmp#6##0" = zext i1 %"x##0" to i64
  %"tmp#5##0" = getelementptr inbounds [ 2 x i64 ], ptr @"logging#constant#2", i64 0, i64 %"tmp#6##0"
  %"tmp#4##0" = load i64, ptr %"tmp#5##0"
  call ccc void @log_string(i64 %"tmp#4##0")
  ret void
}

define external fastcc void @"logging.lognl<0>"() {
  call ccc void @log_char(i8 10)
  ret void
}
