======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module cond_expr_no_else
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : cond_expr_no_else.<0>
  constants       : 0:: CStringInfo {cstringChars = "5:int -> "}
                    1:: CStringInfo {cstringChars = "-5:int -> "}
                    2:: CStringInfo {cstringChars = "e is vowel number "}
                    3:: CStringInfo {cstringChars = "f is vowel number "}
                    4:: StructInfo {structSize = 16, structData = [IntStructMember 18 8,PointerStructMember c"f is vowel number "]}
                    5:: StructInfo {structSize = 16, structData = [IntStructMember 18 8,PointerStructMember c"e is vowel number "]}
                    6:: StructInfo {structSize = 16, structData = [IntStructMember 10 8,PointerStructMember c"-5:int -> "]}
                    7:: StructInfo {structSize = 16, structData = [IntStructMember 9 8,PointerStructMember c"5:int -> "]}
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: cond_expr_no_else.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    cond_expr_no_else.to_count<0>(5:wybe.int, ?tmp#3##0:wybe.count, ?tmp#23##0:wybe.bool) #0 @cond_expr_no_else:nn:nn
    case ~tmp#23##0:wybe.bool of
    0:
        cond_expr_no_else.#cont#1<0>(10:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2

    1:
        cond_expr_no_else.#cont#1<0>(~tmp#3##0:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1



proc #cont#1 > {semipure} (2 calls)
0: cond_expr_no_else.#cont#1<0>
#cont#1(tmp#2##0:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(8,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.count.fmt<2>(~tmp#2##0:wybe.count, 0:wybe.int, 32:wybe.char, ?tmp#1##0:wybe.string) #7 @cond_expr_no_else:nn:nn
    wybe.string.,,<0>("5:int -> ":wybe.string, ~tmp#1##0:wybe.string, ?tmp#0##0:wybe.string) #2 @cond_expr_no_else:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#0##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #8 @cond_expr_no_else:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#29##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#29##0:wybe.phantom, ?tmp#30##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign lpvm store(~%tmp#30##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @cond_expr_no_else:nn:nn
    cond_expr_no_else.to_count<0>(-5:wybe.int, ?tmp#7##0:wybe.count, ?tmp#22##0:wybe.bool) #4 @cond_expr_no_else:nn:nn
    case ~tmp#22##0:wybe.bool of
    0:
        cond_expr_no_else.#cont#2<0>(10:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6

    1:
        cond_expr_no_else.#cont#2<0>(~tmp#7##0:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5



proc #cont#2 > {semipure} (2 calls)
0: cond_expr_no_else.#cont#2<0>
#cont#2(tmp#6##0:wybe.count)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(8,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.count.fmt<2>(~tmp#6##0:wybe.count, 0:wybe.int, 32:wybe.char, ?tmp#5##0:wybe.string) #7 @cond_expr_no_else:nn:nn
    wybe.string.,,<0>("-5:int -> ":wybe.string, ~tmp#5##0:wybe.string, ?tmp#4##0:wybe.string) #2 @cond_expr_no_else:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#4##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #8 @cond_expr_no_else:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#28##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#28##0:wybe.phantom, ?tmp#29##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign lpvm store(~%tmp#29##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @cond_expr_no_else:nn:nn
    cond_expr_no_else.vowel_num<0>(101:wybe.char, ?tmp#11##0:wybe.int, ?tmp#21##0:wybe.bool) #4 @cond_expr_no_else:nn:nn
    case ~tmp#21##0:wybe.bool of
    0:
        cond_expr_no_else.#cont#3<0>(0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6

    1:
        cond_expr_no_else.#cont#3<0>(~tmp#11##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5



proc #cont#3 > {semipure} (2 calls)
0: cond_expr_no_else.#cont#3<0>
#cont#3(tmp#10##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(8,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.int.fmt<2>(~tmp#10##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#9##0:wybe.string) #7 @cond_expr_no_else:nn:nn
    wybe.string.,,<0>("e is vowel number ":wybe.string, ~tmp#9##0:wybe.string, ?tmp#8##0:wybe.string) #2 @cond_expr_no_else:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#8##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #8 @cond_expr_no_else:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#27##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#27##0:wybe.phantom, ?tmp#28##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign lpvm store(~%tmp#28##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @cond_expr_no_else:nn:nn
    cond_expr_no_else.vowel_num<0>(102:wybe.char, ?tmp#15##0:wybe.int, ?tmp#20##0:wybe.bool) #4 @cond_expr_no_else:nn:nn
    case ~tmp#20##0:wybe.bool of
    0:
        cond_expr_no_else.#cont#4<0>(0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6

    1:
        cond_expr_no_else.#cont#4<0>(~tmp#15##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5



proc #cont#4 > {semipure} (2 calls)
0: cond_expr_no_else.#cont#4<0>
#cont#4(tmp#14##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(5,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.int.fmt<2>(~tmp#14##0:wybe.int, 0:wybe.int, 32:wybe.char, ?tmp#13##0:wybe.string) #4 @cond_expr_no_else:nn:nn
    wybe.string.,,<0>("f is vowel number ":wybe.string, ~tmp#13##0:wybe.string, ?tmp#12##0:wybe.string) #2 @cond_expr_no_else:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#12##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #5 @cond_expr_no_else:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#26##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#26##0:wybe.phantom, ?tmp#27##0:wybe.phantom) @cond_expr_no_else:nn:nn
    foreign lpvm store(~%tmp#27##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @cond_expr_no_else:nn:nn


proc to_count > (6 calls)
0: cond_expr_no_else.to_count<0>
to_count(i##0:wybe.int, ?#result##0:wybe.count, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_sge(i##0:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.bool) @cond_expr_no_else:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:wybe.count, ?#result##0:wybe.count)

    1:
        foreign llvm move(~i##0:wybe.count, ?#result##0:wybe.count) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)



proc vowel_num > (6 calls)
0: cond_expr_no_else.vowel_num<0>
vowel_num(c##0:wybe.char, ?#result##0:wybe.int, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    case ~c##0:wybe.char of
    97:
        foreign llvm move(1:wybe.int, ?#result##0:wybe.int) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

    101:
        foreign llvm move(2:wybe.int, ?#result##0:wybe.int) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

    105:
        foreign llvm move(3:wybe.int, ?#result##0:wybe.int) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

    111:
        foreign llvm move(4:wybe.int, ?#result##0:wybe.int) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

    117:
        foreign llvm move(5:wybe.int, ?#result##0:wybe.int) @cond_expr_no_else:nn:nn
        foreign llvm move(1:wybe.bool, ?#success##0:wybe.bool)

    else:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)
        foreign llvm move(undef:wybe.int, ?#result##0:wybe.int)


  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'cond_expr_no_else'

source_filename = "!ROOT!/final-dump/cond_expr_no_else.wybe"
target triple    ????

@"cond_expr_no_else#constant#0" = private unnamed_addr constant [ ?? x i8 ] c"5:int -> \00", align 8
@"cond_expr_no_else#constant#1" = private unnamed_addr constant [ ?? x i8 ] c"-5:int -> \00", align 8
@"cond_expr_no_else#constant#2" = private unnamed_addr constant [ ?? x i8 ] c"e is vowel number \00", align 8
@"cond_expr_no_else#constant#3" = private unnamed_addr constant [ ?? x i8 ] c"f is vowel number \00", align 8
@"cond_expr_no_else#constant#4" = private unnamed_addr constant {i64, ptr} { i64 18, ptr @"cond_expr_no_else#constant#3" }, align 8
@"cond_expr_no_else#constant#5" = private unnamed_addr constant {i64, ptr} { i64 18, ptr @"cond_expr_no_else#constant#2" }, align 8
@"cond_expr_no_else#constant#6" = private unnamed_addr constant {i64, ptr} { i64 10, ptr @"cond_expr_no_else#constant#1" }, align 8
@"cond_expr_no_else#constant#7" = private unnamed_addr constant {i64, ptr} { i64 9, ptr @"cond_expr_no_else#constant#0" }, align 8

declare external fastcc i64 @"wybe.count.fmt<2>"(i64, i64, i8)
declare external fastcc i64 @"wybe.int.fmt<2>"(i64, i64, i8)
declare external fastcc i64 @"wybe.string.,,<0>"(i64, i64)
declare external fastcc void @"wybe.string.print<0>[410bae77d3]"(i64)
declare external ccc void @putchar(i8)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"cond_expr_no_else.<0>"() {
  %"tmp#24##0" = tail call fastcc {i64, i1} @"cond_expr_no_else.to_count<0>"(i64 5)
  %"tmp#3##0" = extractvalue {i64, i1}%"tmp#24##0", 0
  %"tmp#23##0" = extractvalue {i64, i1}%"tmp#24##0", 1
  br i1 %"tmp#23##0", label %if.then.0, label %if.else.0
if.then.0:
  tail call fastcc void @"cond_expr_no_else.#cont#1<0>"(i64 %"tmp#3##0")
  ret void
if.else.0:
  tail call fastcc void @"cond_expr_no_else.#cont#1<0>"(i64 10)
  ret void
}

define external fastcc void @"cond_expr_no_else.#cont#1<0>"(i64 %"tmp#2##0") {
  %"tmp#1##0" = tail call fastcc i64 @"wybe.count.fmt<2>"(i64 %"tmp#2##0", i64 0, i8 32)
  %"tmp#0##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"cond_expr_no_else#constant#7" to i64 ), i64 %"tmp#1##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#0##0")
  call ccc void @putchar(i8 10)
  %"tmp#31##0" = tail call fastcc {i64, i1} @"cond_expr_no_else.to_count<0>"(i64 -5)
  %"tmp#7##0" = extractvalue {i64, i1}%"tmp#31##0", 0
  %"tmp#22##0" = extractvalue {i64, i1}%"tmp#31##0", 1
  br i1 %"tmp#22##0", label %if.then.0, label %if.else.0
if.then.0:
  tail call fastcc void @"cond_expr_no_else.#cont#2<0>"(i64 %"tmp#7##0")
  ret void
if.else.0:
  tail call fastcc void @"cond_expr_no_else.#cont#2<0>"(i64 10)
  ret void
}

define external fastcc void @"cond_expr_no_else.#cont#2<0>"(i64 %"tmp#6##0") {
  %"tmp#5##0" = tail call fastcc i64 @"wybe.count.fmt<2>"(i64 %"tmp#6##0", i64 0, i8 32)
  %"tmp#4##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"cond_expr_no_else#constant#6" to i64 ), i64 %"tmp#5##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#4##0")
  call ccc void @putchar(i8 10)
  %"tmp#30##0" = tail call fastcc {i64, i1} @"cond_expr_no_else.vowel_num<0>"(i8 101)
  %"tmp#11##0" = extractvalue {i64, i1}%"tmp#30##0", 0
  %"tmp#21##0" = extractvalue {i64, i1}%"tmp#30##0", 1
  br i1 %"tmp#21##0", label %if.then.0, label %if.else.0
if.then.0:
  tail call fastcc void @"cond_expr_no_else.#cont#3<0>"(i64 %"tmp#11##0")
  ret void
if.else.0:
  tail call fastcc void @"cond_expr_no_else.#cont#3<0>"(i64 0)
  ret void
}

define external fastcc void @"cond_expr_no_else.#cont#3<0>"(i64 %"tmp#10##0") {
  %"tmp#9##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"tmp#10##0", i64 0, i8 32)
  %"tmp#8##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"cond_expr_no_else#constant#5" to i64 ), i64 %"tmp#9##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#8##0")
  call ccc void @putchar(i8 10)
  %"tmp#29##0" = tail call fastcc {i64, i1} @"cond_expr_no_else.vowel_num<0>"(i8 102)
  %"tmp#15##0" = extractvalue {i64, i1}%"tmp#29##0", 0
  %"tmp#20##0" = extractvalue {i64, i1}%"tmp#29##0", 1
  br i1 %"tmp#20##0", label %if.then.0, label %if.else.0
if.then.0:
  tail call fastcc void @"cond_expr_no_else.#cont#4<0>"(i64 %"tmp#15##0")
  ret void
if.else.0:
  tail call fastcc void @"cond_expr_no_else.#cont#4<0>"(i64 0)
  ret void
}

define external fastcc void @"cond_expr_no_else.#cont#4<0>"(i64 %"tmp#14##0") {
  %"tmp#13##0" = tail call fastcc i64 @"wybe.int.fmt<2>"(i64 %"tmp#14##0", i64 0, i8 32)
  %"tmp#12##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"cond_expr_no_else#constant#4" to i64 ), i64 %"tmp#13##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#12##0")
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc {i64, i1} @"cond_expr_no_else.to_count<0>"(i64 %"i##0") {
  %"tmp#1##0" = icmp sge i64 %"i##0", 0
  br i1 %"tmp#1##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#4##0" = insertvalue {i64, i1} undef, i64 %"i##0", 0
  %"tmp#5##0" = insertvalue {i64, i1} %"tmp#4##0", i1 1, 1
  ret {i64, i1} %"tmp#5##0"
if.else.0:
  %"tmp#6##0" = insertvalue {i64, i1} undef, i64 undef, 0
  %"tmp#7##0" = insertvalue {i64, i1} %"tmp#6##0", i1 0, 1
  ret {i64, i1} %"tmp#7##0"
}

define external fastcc {i64, i1} @"cond_expr_no_else.vowel_num<0>"(i8 %"c##0") {
  switch i8 %"c##0", label %default.switch.0 [
    i8 97, label %case.97.switch.0
    i8 101, label %case.101.switch.0
    i8 105, label %case.105.switch.0
    i8 111, label %case.111.switch.0
    i8 117, label %case.117.switch.0 ]
case.97.switch.0:
  %"tmp#24##0" = insertvalue {i64, i1} undef, i64 1, 0
  %"tmp#25##0" = insertvalue {i64, i1} %"tmp#24##0", i1 1, 1
  ret {i64, i1} %"tmp#25##0"
case.101.switch.0:
  %"tmp#26##0" = insertvalue {i64, i1} undef, i64 2, 0
  %"tmp#27##0" = insertvalue {i64, i1} %"tmp#26##0", i1 1, 1
  ret {i64, i1} %"tmp#27##0"
case.105.switch.0:
  %"tmp#28##0" = insertvalue {i64, i1} undef, i64 3, 0
  %"tmp#29##0" = insertvalue {i64, i1} %"tmp#28##0", i1 1, 1
  ret {i64, i1} %"tmp#29##0"
case.111.switch.0:
  %"tmp#30##0" = insertvalue {i64, i1} undef, i64 4, 0
  %"tmp#31##0" = insertvalue {i64, i1} %"tmp#30##0", i1 1, 1
  ret {i64, i1} %"tmp#31##0"
case.117.switch.0:
  %"tmp#32##0" = insertvalue {i64, i1} undef, i64 5, 0
  %"tmp#33##0" = insertvalue {i64, i1} %"tmp#32##0", i1 1, 1
  ret {i64, i1} %"tmp#33##0"
default.switch.0:
  %"tmp#34##0" = insertvalue {i64, i1} undef, i64 undef, 0
  %"tmp#35##0" = insertvalue {i64, i1} %"tmp#34##0", i1 0, 1
  ret {i64, i1} %"tmp#35##0"
}
