======================================================================
AFTER EVERYTHING:
 Module decimal
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : decimal.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public (0 calls)
0: decimal.<0>
(io##0:wybe.phantom, ?io##10:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_float(1.0e-2:wybe.float, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn
    foreign c print_int(255:wybe.int, ~#io##1:wybe.phantom, ?tmp#5##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#5##0:wybe.phantom, ?#io##2:wybe.phantom) @io:nn:nn
    foreign c print_int(42:wybe.int, ~#io##2:wybe.phantom, ?tmp#8##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?#io##3:wybe.phantom) @io:nn:nn
    foreign c print_int(63:wybe.int, ~#io##3:wybe.phantom, ?tmp#11##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#11##0:wybe.phantom, ?#io##4:wybe.phantom) @io:nn:nn
    foreign c print_float(1.0e100:wybe.float, ~#io##4:wybe.phantom, ?tmp#14##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#14##0:wybe.phantom, ?#io##5:wybe.phantom) @io:nn:nn
    foreign c print_float(100.001:wybe.float, ~#io##5:wybe.phantom, ?tmp#17##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#17##0:wybe.phantom, ?#io##6:wybe.phantom) @io:nn:nn
    foreign c print_float(50010.0:wybe.float, ~#io##6:wybe.phantom, ?tmp#20##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#20##0:wybe.phantom, ?#io##7:wybe.phantom) @io:nn:nn
    foreign c print_int(1000000000:wybe.int, ~#io##7:wybe.phantom, ?tmp#23##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#23##0:wybe.phantom, ?#io##8:wybe.phantom) @io:nn:nn
    foreign c print_float(5.0010000000000006e-14:wybe.float, ~#io##8:wybe.phantom, ?tmp#26##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#26##0:wybe.phantom, ?#io##9:wybe.phantom) @io:nn:nn
    foreign c print_float(-10.0:wybe.float, ~#io##9:wybe.phantom, ?tmp#29##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#29##0:wybe.phantom, ?#io##10:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'decimal'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_float(double)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"decimal.<0>"()    {
entry:
  tail call ccc  void  @print_float(double  1.000000e-2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  255)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  42)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  63)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  1.000000e100)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  1.000010e2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  5.001000e4)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  1000000000)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  5.001000e-14)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_float(double  -1.000000e1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
