======================================================================
AFTER EVERYTHING:
 Module early_exit
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : early_exit.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public {impure} (0 calls)
0: early_exit.<0>
(io##0:wybe.phantom, ?io##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string("should print this":wybe.string, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn
    foreign c {terminal,semipure} exit(1:wybe.int) @control:nn:nn

  LLVM code       :

; ModuleID = 'early_exit'


 


declare external ccc  void @exit(i64)    


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


@early_exit.1 =    constant [?? x i8] c"should print this\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"early_exit.<0>"()    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @early_exit.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @exit(i64  1)  
  ret void 
}
