======================================================================
AFTER EVERYTHING:
 Module early_exit2
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : early_exit2.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public (0 calls)
0: (io#0:wybe.phantom, ?io#1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string("should print this":wybe.string, ~#io#0:wybe.phantom, ?tmp$2#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$2#0:wybe.phantom, ?#io#1:wybe.phantom) @io:nn:nn
    foreign c {terminal,semipure} exit(1:wybe.int) @early_exit2:6:34


my_exit > {terminal,inline} (1 calls)
0: my_exit(code#0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c {terminal,semipure} exit(~code#0:wybe.int) @early_exit2:6:34

  LLVM code       :

; ModuleID = 'early_exit2'


 


declare external ccc  void @exit(i64)    


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


@early_exit2.1 =    constant [18 x i8] c"should print this\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"early_exit2.<0>"()    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([18 x i8], [18 x i8]* @early_exit2.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @exit(i64  1)  
  ret void 
}


define external fastcc  void @"early_exit2.my_exit<0>"(i64  %"code#0")    {
entry:
  tail call ccc  void  @exit(i64  %"code#0")  
  ret void 
}
