======================================================================
AFTER EVERYTHING:
 Module eof_comment
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : eof_comment.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: eof_comment.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.print<0>("Wominjeka!":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @eof_comment:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @eof_comment:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @eof_comment:nn:nn
    foreign lpvm store(~%tmp#2##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @eof_comment:nn:nn

  LLVM code       :

; ModuleID = 'eof_comment'


 


@eof_comment.1 =    constant {i64, i64} { i64 10, i64 ptrtoint ([?? x i8]* @eof_comment.0 to i64) }


@eof_comment.0 =    constant [?? x i8] c"Wominjeka!\00"


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"eof_comment.<0>"() alwaysinline   {
entry:
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @eof_comment.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
