======================================================================
AFTER EVERYTHING:
 Module exp_print
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : exp_print.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public (0 calls)
0: exp_print.<0>
(io#0:wybe.phantom, ?io#7:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string("print(x:raw_string) creates a newline already":wybe.raw_string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>("print(x:string) creates a newline already":wybe.string, ~#io#1:wybe.phantom, ?#io#2:wybe.phantom) #7 @io:nn:nn
    foreign c print_string("println(x:raw_string) generates an extra newline?":wybe.raw_string, ~#io#2:wybe.phantom, ?tmp$6#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$6#0:wybe.phantom, ?#io#3:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>("println(x:string) generates an extra newline?":wybe.string, ~#io#3:wybe.phantom, ?tmp$9#0:wybe.phantom) #8 @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$9#0:wybe.phantom, ?#io#4:wybe.phantom) @io:nn:nn
    foreign c putchar('c':wybe.char, ~#io#4:wybe.phantom, ?tmp$12#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$12#0:wybe.phantom, ?#io#5:wybe.phantom) @io:nn:nn
    foreign c print_int(1:wybe.int, ~#io#5:wybe.phantom, ?tmp$15#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$15#0:wybe.phantom, ?#io#6:wybe.phantom) @io:nn:nn
    foreign c print_int(1:wybe.int, ~#io#6:wybe.phantom, ?#io#7:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'exp_print'


 


declare external ccc  void @print_int(i64)    


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


declare external ccc  void @print_string(i64)    


@exp_print.9 =    constant {i64, i64} { i64 45, i64 ptrtoint ([?? x i8]* @exp_print.8 to i64) }


@exp_print.8 =    constant [?? x i8] c"println(x:string) generates an extra newline?\00"


@exp_print.6 =    constant [?? x i8] c"println(x:raw_string) generates an extra newline?\00"


@exp_print.4 =    constant {i64, i64} { i64 41, i64 ptrtoint ([?? x i8]* @exp_print.3 to i64) }


@exp_print.3 =    constant [?? x i8] c"print(x:string) creates a newline already\00"


@exp_print.1 =    constant [?? x i8] c"print(x:raw_string) creates a newline already\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"exp_print.<0>"()    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @exp_print.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  %5 = ptrtoint i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @exp_print.4, i32 0, i32 0) to i64 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  %5)  
  %7 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @exp_print.6, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %7)  
  tail call ccc  void  @putchar(i8  10)  
  %10 = ptrtoint i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @exp_print.9, i32 0, i32 0) to i64 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  %10)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @putchar(i8  99)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  1)  
  ret void 
}
