======================================================================
AFTER EVERYTHING:
 Module foreign_def_unordered
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : foreign_def_unordered.<0>
  imports         : use wybe
  resources       : a: fromList [(foreign_def_unordered.a,wybe.int @foreign_def_unordered:nn:nn)]
                    b: fromList [(foreign_def_unordered.b,wybe.int @foreign_def_unordered:nn:nn)]
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: foreign_def_unordered.<0>
()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc a_before_b_1 > {inline} (0 calls)
0: foreign_def_unordered.a_before_b_1<0>
a_before_b_1()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_before_b_1(~%a##0:wybe.int, ?%a##1:wybe.int, ~%b##0:wybe.int, ?%b##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_before_b_2 > {inline} (0 calls)
0: foreign_def_unordered.a_before_b_2<0>
a_before_b_2()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_before_b_2(~%a##0:wybe.int, ?%a##1:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_before_b_3 > {inline} (0 calls)
0: foreign_def_unordered.a_before_b_3<0>
a_before_b_3()<{<<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_before_b_3(?%a##0:wybe.int, ~tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_before_a_1 > {inline} (0 calls)
0: foreign_def_unordered.b_before_a_1<0>
b_before_a_1()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_before_a_1(~%b##0:wybe.int, ?%b##1:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_before_a_2 > {inline} (0 calls)
0: foreign_def_unordered.b_before_a_2<0>
b_before_a_2()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_before_a_2(?%b##0:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_before_a_3 > {inline} (0 calls)
0: foreign_def_unordered.b_before_a_3<0>
b_before_a_3()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []

  LLVM code       :

; ModuleID = 'foreign_def_unordered'


 


@"resource#foreign_def_unordered.a" =    global i64 undef


@"resource#foreign_def_unordered.b" =    global i64 undef


declare external ccc  {i64, i64} @b_before_a_2(i64)    


declare external ccc  {i64, i64} @b_before_a_1(i64, i64)    


declare external ccc  i64 @a_before_b_3(i64)    


declare external ccc  {i64, i64} @a_before_b_2(i64)    


declare external ccc  {i64, i64} @a_before_b_1(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"foreign_def_unordered.<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_before_b_1<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  {i64, i64}  @a_before_b_1(i64  %0, i64  %1)  
  %3 = extractvalue {i64, i64} %2, 0 
  %4 = extractvalue {i64, i64} %2, 1 
  store  i64 %3, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %4, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_before_b_2<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  {i64, i64}  @a_before_b_2(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %3, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_before_b_3<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = tail call ccc  i64  @a_before_b_3(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_before_a_1<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  {i64, i64}  @b_before_a_1(i64  %1, i64  %0)  
  %3 = extractvalue {i64, i64} %2, 0 
  %4 = extractvalue {i64, i64} %2, 1 
  store  i64 %4, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %3, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_before_a_2<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  {i64, i64}  @b_before_a_2(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %3, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_before_a_3<0>"() alwaysinline   {
entry:
  ret void 
}
