======================================================================
AFTER EVERYTHING:
 Module foreign_def_unordered
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : 
  imports         : use wybe
  resources       : a: fromList [(foreign_def_unordered.a,wybe.int @foreign_def_unordered:nn:nn)]
                    b: fromList [(foreign_def_unordered.b,wybe.int @foreign_def_unordered:nn:nn)]
  procs           : 

proc a_in_b_in > {inline} (0 calls)
0: foreign_def_unordered.a_in_b_in<0>
a_in_b_in()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc a_in_b_inout > {inline} (0 calls)
0: foreign_def_unordered.a_in_b_inout<0>
a_in_b_inout()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_in_b_inout(~tmp#0##0:wybe.int, ~%b##0:wybe.int, ?%b##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_in_b_out > {inline} (0 calls)
0: foreign_def_unordered.a_in_b_out<0>
a_in_b_out()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_in_b_out(~tmp#0##0:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_inout_b_in > {inline} (0 calls)
0: foreign_def_unordered.a_inout_b_in<0>
a_inout_b_in()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_inout_b_in(~%a##0:wybe.int, ?%a##1:wybe.int, ~tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_inout_b_inout > {inline} (0 calls)
0: foreign_def_unordered.a_inout_b_inout<0>
a_inout_b_inout()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_inout_b_inout(~%a##0:wybe.int, ?%a##1:wybe.int, ~%b##0:wybe.int, ?%b##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_inout_b_out > {inline} (0 calls)
0: foreign_def_unordered.a_inout_b_out<0>
a_inout_b_out()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_inout_b_out(~%a##0:wybe.int, ?%a##1:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_out_b_in > {inline} (0 calls)
0: foreign_def_unordered.a_out_b_in<0>
a_out_b_in()<{<<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_out_b_in(?%a##0:wybe.int, ~tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_out_b_inout > {inline} (0 calls)
0: foreign_def_unordered.a_out_b_inout<0>
a_out_b_inout()<{<<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c a_out_b_inout(?%a##0:wybe.int, ~%b##0:wybe.int, ?%b##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc a_out_b_out > {inline} (0 calls)
0: foreign_def_unordered.a_out_b_out<0>
a_out_b_out()<{}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c a_out_b_out(?%a##0:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_in_a_in > {inline} (0 calls)
0: foreign_def_unordered.b_in_a_in<0>
b_in_a_in()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc b_in_a_inout > {inline} (0 calls)
0: foreign_def_unordered.b_in_a_inout<0>
b_in_a_inout()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_in_a_inout(~tmp#0##0:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_in_a_out > {inline} (0 calls)
0: foreign_def_unordered.b_in_a_out<0>
b_in_a_out()<{<<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_in_a_out(~tmp#0##0:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_inout_a_in > {inline} (0 calls)
0: foreign_def_unordered.b_inout_a_in<0>
b_inout_a_in()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_inout_a_in(~%b##0:wybe.int, ?%b##1:wybe.int, ~tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_inout_a_inout > {inline} (0 calls)
0: foreign_def_unordered.b_inout_a_inout<0>
b_inout_a_inout()<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_inout_a_inout(~%b##0:wybe.int, ?%b##1:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_inout_a_out > {inline} (0 calls)
0: foreign_def_unordered.b_inout_a_out<0>
b_inout_a_out()<{<<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%b##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_inout_a_out(~%b##0:wybe.int, ?%b##1:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##1:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_out_a_in > {inline} (0 calls)
0: foreign_def_unordered.b_out_a_in<0>
b_out_a_in()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_out_a_in(?%b##0:wybe.int, ~tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_out_a_inout > {inline} (0 calls)
0: foreign_def_unordered.b_out_a_inout<0>
b_out_a_inout()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c b_out_a_inout(?%b##0:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc b_out_a_out > {inline} (0 calls)
0: foreign_def_unordered.b_out_a_out<0>
b_out_a_out()<{}; {<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign c b_out_a_out(?%b##0:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##0:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%b##0:wybe.int, <<foreign_def_unordered.b>>:wybe.int) @foreign_def_unordered:nn:nn


proc out_in > {inline} (0 calls)
0: foreign_def_unordered.out_in<0>
out_in()<{<<foreign_def_unordered.a>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c out_in(?%a##1:wybe.int, ~%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn


proc repeated > {inline} (0 calls)
0: foreign_def_unordered.repeated<0>
repeated(x##0:wybe.int)<{<<foreign_def_unordered.a>>, <<foreign_def_unordered.b>>}; {<<foreign_def_unordered.a>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<foreign_def_unordered.b>>:wybe.int, ?%tmp#0##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm load(<<foreign_def_unordered.a>>:wybe.int, ?%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign c repeated(~x##0:wybe.int, ~%a##0:wybe.int, ?%a##1:wybe.int, ~tmp#0##0:wybe.int, ~tmp#0##0:wybe.int, ~%a##0:wybe.int) @foreign_def_unordered:nn:nn
    foreign lpvm store(~%a##1:wybe.int, <<foreign_def_unordered.a>>:wybe.int) @foreign_def_unordered:nn:nn

  LLVM code       :

; ModuleID = 'foreign_def_unordered'


 


@"resource#foreign_def_unordered.a" =    global i64 undef


@"resource#foreign_def_unordered.b" =    global i64 undef


declare external ccc  i64 @repeated(i64, i64, i64, i64, i64)    


declare external ccc  i64 @out_in(i64)    


declare external ccc  {i64, i64} @b_out_a_out()    


declare external ccc  {i64, i64} @b_out_a_inout(i64)    


declare external ccc  i64 @b_out_a_in(i64)    


declare external ccc  {i64, i64} @b_inout_a_out(i64)    


declare external ccc  {i64, i64} @b_inout_a_inout(i64, i64)    


declare external ccc  i64 @b_inout_a_in(i64, i64)    


declare external ccc  i64 @b_in_a_out(i64)    


declare external ccc  i64 @b_in_a_inout(i64, i64)    


declare external ccc  {i64, i64} @a_out_b_out()    


declare external ccc  {i64, i64} @a_out_b_inout(i64)    


declare external ccc  i64 @a_out_b_in(i64)    


declare external ccc  {i64, i64} @a_inout_b_out(i64)    


declare external ccc  {i64, i64} @a_inout_b_inout(i64, i64)    


declare external ccc  i64 @a_inout_b_in(i64, i64)    


declare external ccc  i64 @a_in_b_out(i64)    


declare external ccc  i64 @a_in_b_inout(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"foreign_def_unordered.a_in_b_in<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_in_b_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  i64  @a_in_b_inout(i64  %0, i64  %1)  
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_in_b_out<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  i64  @a_in_b_out(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_inout_b_in<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %2 = tail call ccc  i64  @a_inout_b_in(i64  %1, i64  %0)  
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_inout_b_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  {i64, i64}  @a_inout_b_inout(i64  %0, i64  %1)  
  %3 = extractvalue {i64, i64} %2, 0 
  %4 = extractvalue {i64, i64} %2, 1 
  store  i64 %3, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %4, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_inout_b_out<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  {i64, i64}  @a_inout_b_out(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %3, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_out_b_in<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = tail call ccc  i64  @a_out_b_in(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_out_b_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = tail call ccc  {i64, i64}  @a_out_b_inout(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %3, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.a_out_b_out<0>"() alwaysinline   {
entry:
  %0 = tail call ccc  {i64, i64}  @a_out_b_out()  
  %1 = extractvalue {i64, i64} %0, 0 
  %2 = extractvalue {i64, i64} %0, 1 
  store  i64 %1, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_in_a_in<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_in_a_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %2 = tail call ccc  i64  @b_in_a_inout(i64  %0, i64  %1)  
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_in_a_out<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = tail call ccc  i64  @b_in_a_out(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_inout_a_in<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  i64  @b_inout_a_in(i64  %1, i64  %0)  
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_inout_a_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %2 = tail call ccc  {i64, i64}  @b_inout_a_inout(i64  %1, i64  %0)  
  %3 = extractvalue {i64, i64} %2, 0 
  %4 = extractvalue {i64, i64} %2, 1 
  store  i64 %4, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %3, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_inout_a_out<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = tail call ccc  {i64, i64}  @b_inout_a_out(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %3, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_out_a_in<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  i64  @b_out_a_in(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_out_a_inout<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  {i64, i64}  @b_out_a_inout(i64  %0)  
  %2 = extractvalue {i64, i64} %1, 0 
  %3 = extractvalue {i64, i64} %1, 1 
  store  i64 %3, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %2, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.b_out_a_out<0>"() alwaysinline   {
entry:
  %0 = tail call ccc  {i64, i64}  @b_out_a_out()  
  %1 = extractvalue {i64, i64} %0, 0 
  %2 = extractvalue {i64, i64} %0, 1 
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  store  i64 %1, i64* @"resource#foreign_def_unordered.b" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.out_in<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %1 = tail call ccc  i64  @out_in(i64  %0)  
  store  i64 %1, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}


define external fastcc  void @"foreign_def_unordered.repeated<0>"(i64  %"x##0") alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#foreign_def_unordered.b" 
  %1 = load  i64, i64* @"resource#foreign_def_unordered.a" 
  %2 = tail call ccc  i64  @repeated(i64  %"x##0", i64  %1, i64  %0, i64  %0, i64  %1)  
  store  i64 %2, i64* @"resource#foreign_def_unordered.a" 
  ret void 
}
