======================================================================
AFTER EVERYTHING:
 Module func_let
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : func_let.<0>
                    func_let.quad<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public {inline,impure} (0 calls) 
0: func_let.<0>
(*#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
  GlobalFlows: {<<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom, *#globals##0:wybe.phantom)
    foreign c print_int(40:wybe.int, ~%tmp#5##0:wybe.phantom, ?%tmp#6##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#6##0:wybe.phantom, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom)


quad > public {inline} (1 calls) 
0: func_let.quad<0>
quad(x##0:wybe.int, ?#result##0:wybe.int):
  GlobalFlows: {} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~x##0:wybe.int, ~x##0:wybe.int, ?tmp#0##0:wybe.int) @int:nn:nn
    foreign llvm add(~tmp#0##0:wybe.int, ~tmp#0##0:wybe.int, ?#result##0:wybe.int) @int:nn:nn

  LLVM code       :

; ModuleID = 'func_let'


 


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"func_let.<0>"()    {
entry:
  tail call ccc  void  @print_int(i64  40)  
  ret void 
}


define external fastcc  i64 @"func_let.quad<0>"(i64  %"x##0")    {
entry:
  %"1#tmp#0##0" = add   i64 %"x##0", %"x##0" 
  %"1##result##0" = add   i64 %"1#tmp#0##0", %"1#tmp#0##0" 
  ret i64 %"1##result##0" 
}
