======================================================================
AFTER EVERYTHING:
 Module func_where
  public submods  : 
  public types    : 
  public resources: 
  public procs    : func_where.quad<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

quad > public inline (0 calls)
0: quad(x#0:wybe.int, ?$#0:wybe.int):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm add(~x#0:wybe.int, ~x#0:wybe.int, ?tmp$0#0:wybe.int) @wybe:nn:nn
    foreign llvm add(~tmp$0#0:wybe.int, ~tmp$0#0:wybe.int, ?$#0:wybe.int) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'func_where'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  i64 @"func_where.quad<0>"(i64  %"x#0")    {
entry:
  %"tmp$0#0" = add   i64 %"x#0", %"x#0" 
  %"$#0" = add   i64 %"tmp$0#0", %"tmp$0#0" 
  ret i64 %"$#0" 
}
