======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module higher_order_anon
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : higher_order_anon.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: higher_order_anon.<0>
()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc #anon#1 > {inline} (1 calls)
0: higher_order_anon.#anon#1<0>
#anon#1(anon#1#1##0:wybe.int, ?anon#1#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#1#1##0:wybe.int, 1:wybe.int, ?anon#1#2##0:wybe.int) @higher_order_anon:nn:nn
proc #anon#1 > {inline} (1 calls)
1: higher_order_anon.#anon#1<1>
#anon#1(anon#1#1##0:wybe.int, ?anon#1#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#1#1##0:wybe.int, 1:wybe.int, ?anon#1#2##0:wybe.int) @higher_order_anon:nn:nn


proc #anon#2 > {inline} (1 calls)
0: higher_order_anon.#anon#2<0>
#anon#2(anon#2#1##0:wybe.int, ?anon#2#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#2#1##0:wybe.int, 1:wybe.int, ?anon#2#2##0:wybe.int) @higher_order_anon:nn:nn
proc #anon#2 > {inline} (1 calls)
1: higher_order_anon.#anon#2<1>
#anon#2(anon#2#1##0:wybe.int, ?anon#2#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#2#1##0:wybe.int, 1:wybe.int, ?anon#2#2##0:wybe.int) @higher_order_anon:nn:nn


proc #anon#3 > {inline} (1 calls)
0: higher_order_anon.#anon#3<0>
#anon#3([anon#3#1##0:20 <{}; {}; {0}>], anon#3#2##0:2 <{}; {}; {1}>, ?anon#3#3##0:2 <{}; {}; {1}>)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#3#2##0:2, ?anon#3#3##0:2) @higher_order_anon:nn:nn
proc #anon#3 > {inline} (1 calls)
1: higher_order_anon.#anon#3<1>
#anon#3(anon#3#1##0:20 <{}; {}; {0}>, anon#3#2##0:2 <{}; {}; {1}>, ?anon#3#3##0:2 <{}; {}; {1}>)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#3#2##0:2, ?anon#3#3##0:2) @higher_order_anon:nn:nn


proc #anon#4 > {inline} (1 calls)
0: higher_order_anon.#anon#4<0>
#anon#4([anon#4#1##0:20 <{}; {}; {0}>], anon#4#2##0:2 <{}; {}; {1}>, ?anon#4#3##0:2 <{}; {}; {1}>)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#4#2##0:2, ?anon#4#3##0:2) @higher_order_anon:nn:nn
proc #anon#4 > {inline} (1 calls)
1: higher_order_anon.#anon#4<1>
#anon#4(anon#4#1##0:20 <{}; {}; {0}>, anon#4#2##0:2 <{}; {}; {1}>, ?anon#4#3##0:2 <{}; {}; {1}>)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#4#2##0:2, ?anon#4#3##0:2) @higher_order_anon:nn:nn


proc #anon#5 > {inline} (1 calls)
0: higher_order_anon.#anon#5<0>
#anon#5(anon#5#1##0:(wybe.int, ?wybe.int), ?anon#5#2##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#5#1##0:(wybe.int, ?wybe.int), ?anon#5#2##0:(wybe.int, ?wybe.int)) @higher_order_anon:nn:nn
proc #anon#5 > {inline} (1 calls)
1: higher_order_anon.#anon#5<1>
#anon#5(anon#5#1##0:(wybe.int, ?wybe.int), ?anon#5#2##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#5#1##0:(wybe.int, ?wybe.int), ?anon#5#2##0:(wybe.int, ?wybe.int)) @higher_order_anon:nn:nn


proc #anon#6 > {inline} (1 calls)
0: higher_order_anon.#anon#6<0>
#anon#6(anon#6#1##0:(wybe.int, ?wybe.int), ?anon#6#2##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#6#1##0:(wybe.int, ?wybe.int), ?anon#6#2##0:(wybe.int, ?wybe.int)) @higher_order_anon:nn:nn
proc #anon#6 > {inline} (1 calls)
1: higher_order_anon.#anon#6<1>
#anon#6(anon#6#1##0:(wybe.int, ?wybe.int), ?anon#6#2##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~anon#6#1##0:(wybe.int, ?wybe.int), ?anon#6#2##0:(wybe.int, ?wybe.int)) @higher_order_anon:nn:nn


proc #anon#7 > {inline} (1 calls)
0: higher_order_anon.#anon#7<0>
#anon#7(^id##0:((wybe.int, ?wybe.int), ?(wybe.int, ?wybe.int)), ?anon#7#1##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    ~id##0:((wybe.int, ?wybe.int), ?(wybe.int, ?wybe.int))(higher_order_anon.#anon#7#anon#1<1><>:(wybe.int, ?wybe.int), ?anon#7#1##0:(wybe.int, ?wybe.int)) #0 @higher_order_anon:nn:nn
proc #anon#7 > {inline} (1 calls)
1: higher_order_anon.#anon#7<1>
#anon#7(^id##0:((wybe.int, ?wybe.int), ?(wybe.int, ?wybe.int)), ?anon#7#1##0:(wybe.int, ?wybe.int))<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    ~^id##0:((wybe.int, ?wybe.int), ?(wybe.int, ?wybe.int))(higher_order_anon.#anon#7#anon#1<1><>:(wybe.int, ?wybe.int), ?anon#7#1##0:(wybe.int, ?wybe.int)) #0 @higher_order_anon:nn:nn


proc #anon#7#anon#1 > {inline} (1 calls)
0: higher_order_anon.#anon#7#anon#1<0>
#anon#7#anon#1(anon#8#1##0:wybe.int, ?anon#8#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#8#1##0:wybe.int, 1:wybe.int, ?anon#8#2##0:wybe.int) @higher_order_anon:nn:nn
proc #anon#7#anon#1 > {inline} (1 calls)
1: higher_order_anon.#anon#7#anon#1<1>
#anon#7#anon#1(anon#8#1##0:wybe.int, ?anon#8#2##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~anon#8#1##0:wybe.int, 1:wybe.int, ?anon#8#2##0:wybe.int) @higher_order_anon:nn:nn


proc #anon#8 > {inline} (1 calls)
0: higher_order_anon.#anon#8<0>
#anon#8(anon#9#1##0:wybe.float, [anon#9#2##0:29 <{}; {}; {1}>], anon#9#3##0:wybe.float, ?anon#9#4##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm fadd(~anon#9#1##0:wybe.float, ~anon#9#3##0:wybe.float, ?anon#9#4##0:wybe.float) @higher_order_anon:nn:nn
proc #anon#8 > {inline} (1 calls)
1: higher_order_anon.#anon#8<1>
#anon#8(anon#9#1##0:wybe.float, anon#9#2##0:29 <{}; {}; {1}>, anon#9#3##0:wybe.float, ?anon#9#4##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm fadd(~anon#9#1##0:wybe.float, ~anon#9#3##0:wybe.float, ?anon#9#4##0:wybe.float) @higher_order_anon:nn:nn


proc #anon#9 > {inline} (1 calls)
0: higher_order_anon.#anon#9<0>
#anon#9(anon#10#1##0:wybe.float, [anon#10#2##0:29 <{}; {}; {1}>], anon#10#3##0:wybe.float, ?anon#10#4##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm fadd(~anon#10#1##0:wybe.float, ~anon#10#3##0:wybe.float, ?anon#10#4##0:wybe.float) @higher_order_anon:nn:nn
proc #anon#9 > {inline} (1 calls)
1: higher_order_anon.#anon#9<1>
#anon#9(anon#10#1##0:wybe.float, anon#10#2##0:29 <{}; {}; {1}>, anon#10#3##0:wybe.float, ?anon#10#4##0:wybe.float)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm fadd(~anon#10#1##0:wybe.float, ~anon#10#3##0:wybe.float, ?anon#10#4##0:wybe.float) @higher_order_anon:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'higher_order_anon'

source_filename = "!ROOT!/final-dump/higher_order_anon.wybe"
target triple    ????

@"closure#0" = private unnamed_addr constant {ptr} { ptr @"higher_order_anon.#anon#7#anon#1<1>" }, align 8

declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"higher_order_anon.<0>"() {
  ret void
}

define external fastcc i64 @"higher_order_anon.#anon#1<0>"(i64 %"anon#1#1##0") {
  %"tmp#8##0" = add i64 %"anon#1#1##0", 1
  ret i64 %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#1<1>"(i64 %"#env##0", i64 %"generic#anon#1#1##0") {
  %"anon#1#2##0" = add i64 %"generic#anon#1#1##0", 1
  ret i64 %"anon#1#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#2<0>"(i64 %"anon#2#1##0") {
  %"tmp#8##0" = add i64 %"anon#2#1##0", 1
  ret i64 %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#2<1>"(i64 %"#env##0", i64 %"generic#anon#2#1##0") {
  %"anon#2#2##0" = add i64 %"generic#anon#2#1##0", 1
  ret i64 %"anon#2#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#3<0>"(i64 %"anon#3#2##0") {
  ret i64 %"anon#3#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#3<1>"(i64 %"#env##0", i64 %"generic#anon#3#1##0", i64 %"generic#anon#3#2##0") {
  ret i64 %"generic#anon#3#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#4<0>"(i64 %"anon#4#2##0") {
  ret i64 %"anon#4#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#4<1>"(i64 %"#env##0", i64 %"generic#anon#4#1##0", i64 %"generic#anon#4#2##0") {
  ret i64 %"generic#anon#4#2##0"
}

define external fastcc i64 @"higher_order_anon.#anon#5<0>"(i64 %"anon#5#1##0") {
  ret i64 %"anon#5#1##0"
}

define external fastcc i64 @"higher_order_anon.#anon#5<1>"(i64 %"#env##0", i64 %"generic#anon#5#1##0") {
  %"anon#5#1##0" = bitcast i64 %"generic#anon#5#1##0" to i64
  %"tmp#1##0" = bitcast i64 %"anon#5#1##0" to i64
  ret i64 %"tmp#1##0"
}

define external fastcc i64 @"higher_order_anon.#anon#6<0>"(i64 %"anon#6#1##0") {
  ret i64 %"anon#6#1##0"
}

define external fastcc i64 @"higher_order_anon.#anon#6<1>"(i64 %"#env##0", i64 %"generic#anon#6#1##0") {
  %"anon#6#1##0" = bitcast i64 %"generic#anon#6#1##0" to i64
  %"tmp#1##0" = bitcast i64 %"anon#6#1##0" to i64
  ret i64 %"tmp#1##0"
}

define external fastcc i64 @"higher_order_anon.#anon#7<0>"(i64 %"id##0") {
  %"tmp#7##0" = inttoptr i64 %"id##0" to ptr
  %"tmp#6##0" = load ptr, ptr %"tmp#7##0"
  %"tmp#8##0" = tail call fastcc i64 %"tmp#6##0"(i64 %"id##0", ptr @"closure#0")
  ret i64 %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#7<1>"(i64 %"#env##0") {
  %"tmp#1##0" = add i64 %"#env##0", 8
  %"tmp#2##0" = inttoptr i64 %"tmp#1##0" to ptr
  %"generic#id##0" = load i64, ptr %"tmp#2##0"
  %"id##0" = bitcast i64 %"generic#id##0" to i64
  %"tmp#4##0" = inttoptr i64 %"id##0" to ptr
  %"tmp#3##0" = load ptr, ptr %"tmp#4##0"
  %"anon#7#1##0" = tail call fastcc i64 %"tmp#3##0"(i64 %"id##0", ptr @"closure#0")
  %"tmp#5##0" = bitcast i64 %"anon#7#1##0" to i64
  ret i64 %"tmp#5##0"
}

define external fastcc i64 @"higher_order_anon.#anon#7#anon#1<0>"(i64 %"anon#8#1##0") {
  %"tmp#8##0" = add i64 %"anon#8#1##0", 1
  ret i64 %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#7#anon#1<1>"(i64 %"#env##0", i64 %"generic#anon#8#1##0") {
  %"anon#8#2##0" = add i64 %"generic#anon#8#1##0", 1
  ret i64 %"anon#8#2##0"
}

define external fastcc double @"higher_order_anon.#anon#8<0>"(double %"anon#9#1##0", double %"anon#9#3##0") {
  %"tmp#8##0" = fadd double %"anon#9#1##0", %"anon#9#3##0"
  ret double %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#8<1>"(i64 %"#env##0", i64 %"generic#anon#9#1##0", i64 %"generic#anon#9#2##0", i64 %"generic#anon#9#3##0") {
  %"anon#9#1##0" = bitcast i64 %"generic#anon#9#1##0" to double
  %"anon#9#3##0" = bitcast i64 %"generic#anon#9#3##0" to double
  %"anon#9#4##0" = fadd double %"anon#9#1##0", %"anon#9#3##0"
  %"tmp#3##0" = bitcast double %"anon#9#4##0" to i64
  ret i64 %"tmp#3##0"
}

define external fastcc double @"higher_order_anon.#anon#9<0>"(double %"anon#10#1##0", double %"anon#10#3##0") {
  %"tmp#8##0" = fadd double %"anon#10#1##0", %"anon#10#3##0"
  ret double %"tmp#8##0"
}

define external fastcc i64 @"higher_order_anon.#anon#9<1>"(i64 %"#env##0", i64 %"generic#anon#10#1##0", i64 %"generic#anon#10#2##0", i64 %"generic#anon#10#3##0") {
  %"anon#10#1##0" = bitcast i64 %"generic#anon#10#1##0" to double
  %"anon#10#3##0" = bitcast i64 %"generic#anon#10#3##0" to double
  %"anon#10#4##0" = fadd double %"anon#10#1##0", %"anon#10#3##0"
  %"tmp#3##0" = bitcast double %"anon#10#4##0" to i64
  ret i64 %"tmp#3##0"
}
