======================================================================
AFTER EVERYTHING:
 Module import_in_sub_mod_lib
  public submods  : 
  public types    : 
  public resources: 
  public procs    : import_in_sub_mod_lib.foo<0>
  imports         : use wybe
  types           : 
  resources       : 
  procs           : 

foo > public inline (0 calls)
0: foo(v#0:wybe.int, io#0:wybe.phantom, ?io#1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_int(~v#0:wybe.int, ~#io#0:wybe.phantom, ?tmp$2#0:wybe.phantom) @wybe:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$2#0:wybe.phantom, ?#io#1:wybe.phantom) @wybe:nn:nn

  LLVM code       :

; ModuleID = 'import_in_sub_mod_lib'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"import_in_sub_mod_lib.foo<0>"(i64  %"v#0")    {
entry:
  tail call ccc  void  @print_int(i64  %"v#0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
