======================================================================
AFTER EVERYTHING:
 Module list_loop
  representation  : (not a type)
  public submods  : intlist -> list_loop.intlist
  public resources: 
  public procs    : list_loop.<0>
                    list_loop.intlist.=<0>
                    list_loop.intlist.cons<0>
                    list_loop.intlist.cons<1>
                    list_loop.intlist.head<0>
                    list_loop.intlist.head<1>
                    list_loop.intlist.nil<0>
                    list_loop.intlist.tail<0>
                    list_loop.intlist.tail<1>
                    list_loop.intlist.~=<0>
  imports         : public use list_loop.intlist
                    use wybe
  resources       : 
  submodules      : list_loop.intlist
  procs           : 

*main* > public (0 calls)
0: list_loop.<0>
(io#0:wybe.phantom, ?io#1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?tmp$8#0:list_loop.intlist)
    foreign lpvm mutate(~tmp$8#0:list_loop.intlist, ?tmp$9#0:list_loop.intlist, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 3:wybe.int)
    foreign lpvm mutate(~tmp$9#0:list_loop.intlist, ?tmp$10#0:list_loop.intlist, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:list_loop.intlist)
    foreign lpvm alloc(16:wybe.int, ?tmp$13#0:list_loop.intlist)
    foreign lpvm mutate(~tmp$13#0:list_loop.intlist, ?tmp$14#0:list_loop.intlist, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2:wybe.int)
    foreign lpvm mutate(~tmp$14#0:list_loop.intlist, ?tmp$15#0:list_loop.intlist, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, tmp$10#0:list_loop.intlist)
    foreign lpvm alloc(16:wybe.int, ?tmp$18#0:list_loop.intlist)
    foreign lpvm mutate(~tmp$18#0:list_loop.intlist, ?tmp$19#0:list_loop.intlist, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.int)
    foreign lpvm mutate(~tmp$19#0:list_loop.intlist, ?tmp$20#0:list_loop.intlist, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, tmp$15#0:list_loop.intlist)
    list_loop.gen$1<0>(~io#0:wybe.phantom, ~tmp$20#0:list_loop.intlist, ~tmp$20#0:list_loop.intlist, ~tmp$15#0:list_loop.intlist, ~tmp$10#0:list_loop.intlist, 0:list_loop.intlist, ~tmp$20#0:list_loop.intlist, ?io#1:wybe.phantom) #4 @list_loop:nn:nn


gen$1 > (2 calls)
0: list_loop.gen$1<0>
gen$1(io#0:wybe.phantom, l#0:list_loop.intlist, tmp$0#0:list_loop.intlist, tmp$1#0:list_loop.intlist, tmp$2#0:list_loop.intlist, tmp$3#0:list_loop.intlist, x#0:list_loop.intlist, ?io#1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne(l#0:wybe.int, 0:wybe.int, ?tmp$7#0:wybe.bool)
    case ~tmp$7#0:wybe.bool of
    0:
        foreign llvm move(~io#0:wybe.phantom, ?io#1:wybe.phantom)

    1:
        foreign lpvm access(l#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?h#0:wybe.int)
        foreign lpvm access(~l#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?l#1:list_loop.intlist)
        foreign c print_int(h#0:wybe.int, ~io#0:wybe.phantom, ?tmp$16#0:wybe.phantom) @io:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp$16#0:wybe.phantom, ?tmp$17#0:wybe.phantom) @io:nn:nn
        list_loop.gen$3<0>(~h#0:wybe.int, ~tmp$17#0:wybe.phantom, ~l#1:list_loop.intlist, ~x#0:list_loop.intlist, ~tmp$0#0:list_loop.intlist, ~tmp$1#0:list_loop.intlist, ~tmp$2#0:list_loop.intlist, ~tmp$3#0:list_loop.intlist, ~x#0:list_loop.intlist, ?io#1:wybe.phantom) #2 @list_loop:nn:nn



gen$2 > {inline} (1 calls)
0: list_loop.gen$2<0>
gen$2(h#0:wybe.int, io#0:wybe.phantom, l#0:list_loop.intlist, tmp$0#0:list_loop.intlist, tmp$1#0:list_loop.intlist, tmp$2#0:list_loop.intlist, tmp$3#0:list_loop.intlist, x#0:list_loop.intlist, ?io#2:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_int(h#0:wybe.int, ~#io#0:wybe.phantom, ?tmp$7#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$7#0:wybe.phantom, ?#io#1:wybe.phantom) @io:nn:nn
    list_loop.gen$3<0>(~h#0:wybe.int, ~io#1:wybe.phantom, ~l#0:list_loop.intlist, ~x#0:list_loop.intlist, ~tmp$0#0:list_loop.intlist, ~tmp$1#0:list_loop.intlist, ~tmp$2#0:list_loop.intlist, ~tmp$3#0:list_loop.intlist, ~x#0:list_loop.intlist, ?io#2:wybe.phantom) #1 @list_loop:nn:nn


gen$3 > (2 calls)
0: list_loop.gen$3<0>
gen$3(h#0:wybe.int, io#0:wybe.phantom, l#0:list_loop.intlist, l2#0:list_loop.intlist, tmp$0#0:list_loop.intlist, tmp$1#0:list_loop.intlist, tmp$2#0:list_loop.intlist, tmp$3#0:list_loop.intlist, x#0:list_loop.intlist, ?io#1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne(l2#0:wybe.int, 0:wybe.int, ?tmp$6#0:wybe.bool)
    case ~tmp$6#0:wybe.bool of
    0:
        list_loop.gen$1<0>(~io#0:wybe.phantom, ~l#0:list_loop.intlist, ~tmp$0#0:list_loop.intlist, ~tmp$1#0:list_loop.intlist, ~tmp$2#0:list_loop.intlist, ~tmp$3#0:list_loop.intlist, ~x#0:list_loop.intlist, ?io#1:wybe.phantom) #2 @list_loop:nn:nn

    1:
        foreign lpvm access(l2#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?h2#0:wybe.int)
        foreign lpvm access(~l2#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?l2#1:list_loop.intlist)
        foreign c print_string("    ":wybe.string, ~io#0:wybe.phantom, ?tmp$17#0:wybe.phantom) @io:nn:nn
        foreign c print_int(h#0:wybe.int, ~tmp$17#0:wybe.phantom, ?tmp$18#0:wybe.phantom) @io:nn:nn
        foreign c print_string(" ":wybe.string, ~tmp$18#0:wybe.phantom, ?tmp$19#0:wybe.phantom) @io:nn:nn
        foreign c print_int(~h2#0:wybe.int, ~tmp$19#0:wybe.phantom, ?tmp$20#0:wybe.phantom) @io:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp$20#0:wybe.phantom, ?tmp$21#0:wybe.phantom) @io:nn:nn
        list_loop.gen$3<0>(~h#0:wybe.int, ~tmp$21#0:wybe.phantom, ~l#0:list_loop.intlist, ~l2#1:list_loop.intlist, ~tmp$0#0:list_loop.intlist, ~tmp$1#0:list_loop.intlist, ~tmp$2#0:list_loop.intlist, ~tmp$3#0:list_loop.intlist, ~x#0:list_loop.intlist, ?io#1:wybe.phantom) #3 @list_loop:nn:nn



gen$4 > {inline} (1 calls)
0: list_loop.gen$4<0>
gen$4(h#0:wybe.int, h2#0:wybe.int, io#0:wybe.phantom, l#0:list_loop.intlist, l2#0:list_loop.intlist, tmp$0#0:list_loop.intlist, tmp$1#0:list_loop.intlist, tmp$2#0:list_loop.intlist, tmp$3#0:list_loop.intlist, x#0:list_loop.intlist, ?io#5:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string("    ":wybe.string, ~#io#0:wybe.phantom, ?#io#1:wybe.phantom) @io:nn:nn
    foreign c print_int(h#0:wybe.int, ~#io#1:wybe.phantom, ?#io#2:wybe.phantom) @io:nn:nn
    foreign c print_string(" ":wybe.string, ~#io#2:wybe.phantom, ?#io#3:wybe.phantom) @io:nn:nn
    foreign c print_int(~h2#0:wybe.int, ~#io#3:wybe.phantom, ?tmp$12#0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp$12#0:wybe.phantom, ?#io#4:wybe.phantom) @io:nn:nn
    list_loop.gen$3<0>(~h#0:wybe.int, ~io#4:wybe.phantom, ~l#0:list_loop.intlist, ~l2#0:list_loop.intlist, ~tmp$0#0:list_loop.intlist, ~tmp$1#0:list_loop.intlist, ~tmp$2#0:list_loop.intlist, ~tmp$3#0:list_loop.intlist, ~x#0:list_loop.intlist, ?io#5:wybe.phantom) #4 @list_loop:nn:nn

  LLVM code       :

; ModuleID = 'list_loop'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external ccc  void @print_string(i64)    


@list_loop.41 =    constant [?? x i8] c" \00"


@list_loop.39 =    constant [?? x i8] c"    \00"


@list_loop.45 =    constant [?? x i8] c" \00"


@list_loop.43 =    constant [?? x i8] c"    \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"list_loop.<0>"()    {
entry:
  %1 = trunc i64 16 to i32  
  %2 = tail call ccc  i8*  @wybe_malloc(i32  %1)  
  %3 = ptrtoint i8* %2 to i64 
  %4 = inttoptr i64 %3 to i64* 
  %5 = getelementptr  i64, i64* %4, i64 0 
  store  i64 3, i64* %5 
  %6 = add   i64 %3, 8 
  %7 = inttoptr i64 %6 to i64* 
  %8 = getelementptr  i64, i64* %7, i64 0 
  store  i64 0, i64* %8 
  %9 = trunc i64 16 to i32  
  %10 = tail call ccc  i8*  @wybe_malloc(i32  %9)  
  %11 = ptrtoint i8* %10 to i64 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  store  i64 2, i64* %13 
  %14 = add   i64 %11, 8 
  %15 = inttoptr i64 %14 to i64* 
  %16 = getelementptr  i64, i64* %15, i64 0 
  store  i64 %3, i64* %16 
  %17 = trunc i64 16 to i32  
  %18 = tail call ccc  i8*  @wybe_malloc(i32  %17)  
  %19 = ptrtoint i8* %18 to i64 
  %20 = inttoptr i64 %19 to i64* 
  %21 = getelementptr  i64, i64* %20, i64 0 
  store  i64 1, i64* %21 
  %22 = add   i64 %19, 8 
  %23 = inttoptr i64 %22 to i64* 
  %24 = getelementptr  i64, i64* %23, i64 0 
  store  i64 %11, i64* %24 
  tail call fastcc  void  @"list_loop.gen$1<0>"(i64  %19, i64  %19, i64  %11, i64  %3, i64  0, i64  %19)  
  ret void 
}


define external fastcc  void @"list_loop.gen$1<0>"(i64  %"l#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")    {
entry:
  %"1$tmp$7#0" = icmp ne i64 %"l#0", 0 
  br i1 %"1$tmp$7#0", label %if.then, label %if.else 
if.then:
  %25 = inttoptr i64 %"l#0" to i64* 
  %26 = getelementptr  i64, i64* %25, i64 0 
  %27 = load  i64, i64* %26 
  %28 = add   i64 %"l#0", 8 
  %29 = inttoptr i64 %28 to i64* 
  %30 = getelementptr  i64, i64* %29, i64 0 
  %31 = load  i64, i64* %30 
  tail call ccc  void  @print_int(i64  %27)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"list_loop.gen$3<0>"(i64  %27, i64  %31, i64  %"x#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")  
  ret void 
if.else:
  ret void 
}


define external fastcc  void @"list_loop.gen$2<0>"(i64  %"h#0", i64  %"l#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")    {
entry:
  tail call ccc  void  @print_int(i64  %"h#0")  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"list_loop.gen$3<0>"(i64  %"h#0", i64  %"l#0", i64  %"x#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")  
  ret void 
}


define external fastcc  void @"list_loop.gen$3<0>"(i64  %"h#0", i64  %"l#0", i64  %"l2#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")    {
entry:
  %"1$tmp$6#0" = icmp ne i64 %"l2#0", 0 
  br i1 %"1$tmp$6#0", label %if.then, label %if.else 
if.then:
  %32 = inttoptr i64 %"l2#0" to i64* 
  %33 = getelementptr  i64, i64* %32, i64 0 
  %34 = load  i64, i64* %33 
  %35 = add   i64 %"l2#0", 8 
  %36 = inttoptr i64 %35 to i64* 
  %37 = getelementptr  i64, i64* %36, i64 0 
  %38 = load  i64, i64* %37 
  %40 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @list_loop.39, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %40)  
  tail call ccc  void  @print_int(i64  %"h#0")  
  %42 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @list_loop.41, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %42)  
  tail call ccc  void  @print_int(i64  %34)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"list_loop.gen$3<0>"(i64  %"h#0", i64  %"l#0", i64  %38, i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")  
  ret void 
if.else:
  tail call fastcc  void  @"list_loop.gen$1<0>"(i64  %"l#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")  
  ret void 
}


define external fastcc  void @"list_loop.gen$4<0>"(i64  %"h#0", i64  %"h2#0", i64  %"l#0", i64  %"l2#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")    {
entry:
  %44 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @list_loop.43, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %44)  
  tail call ccc  void  @print_int(i64  %"h#0")  
  %46 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @list_loop.45, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %46)  
  tail call ccc  void  @print_int(i64  %"h2#0")  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"list_loop.gen$3<0>"(i64  %"h#0", i64  %"l#0", i64  %"l2#0", i64  %"tmp$0#0", i64  %"tmp$1#0", i64  %"tmp$2#0", i64  %"tmp$3#0", i64  %"x#0")  
  ret void 
}
--------------------------------------------------
 Module list_loop.intlist
  representation  : address
  public submods  : 
  public resources: 
  public procs    : list_loop.intlist.=<0>
                    list_loop.intlist.cons<0>
                    list_loop.intlist.cons<1>
                    list_loop.intlist.head<0>
                    list_loop.intlist.head<1>
                    list_loop.intlist.nil<0>
                    list_loop.intlist.tail<0>
                    list_loop.intlist.tail<1>
                    list_loop.intlist.~=<0>
  imports         : use list_loop
                    use wybe
  resources       : 
  procs           : 

= > public (2 calls)
0: list_loop.intlist.=<0>
=($left#0:list_loop.intlist, $right#0:list_loop.intlist, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($left#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm icmp_eq(~$left#0:list_loop.intlist, ~$right#0:list_loop.intlist, ?$$#0:wybe.bool)

    1:
        foreign lpvm access($left#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?$left$head#0:wybe.int)
        foreign lpvm access(~$left#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?$left$tail#0:list_loop.intlist)
        foreign llvm icmp_ne($right#0:wybe.int, 0:wybe.int, ?tmp$9#0:wybe.bool)
        case ~tmp$9#0:wybe.bool of
        0:
            foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

        1:
            foreign lpvm access($right#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?$right$head#0:wybe.int)
            foreign lpvm access(~$right#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?$right$tail#0:list_loop.intlist)
            foreign llvm icmp_eq(~$left$head#0:wybe.int, ~$right$head#0:wybe.int, ?tmp$4#0:wybe.bool) @int:nn:nn
            case ~tmp$4#0:wybe.bool of
            0:
                foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)

            1:
                list_loop.intlist.=<0>(~$left$tail#0:list_loop.intlist, ~$right$tail#0:list_loop.intlist, ?$$#0:wybe.bool) #3





cons > public {inline} (0 calls)
0: list_loop.intlist.cons<0>
cons(head#0:wybe.int, tail#0:list_loop.intlist, ?$#0:list_loop.intlist):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?$rec#0:list_loop.intlist)
    foreign lpvm mutate(~$rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~head#0:wybe.int)
    foreign lpvm mutate(~$rec#1:list_loop.intlist, ?$#0:list_loop.intlist, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tail#0:list_loop.intlist)
cons > public {inline} (12 calls)
1: list_loop.intlist.cons<1>
cons(?head#0:wybe.int, ?tail#0:list_loop.intlist, $#0:list_loop.intlist, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)
        foreign llvm move(undef:wybe.int, ?head#0:wybe.int)
        foreign llvm move(undef:list_loop.intlist, ?tail#0:list_loop.intlist)

    1:
        foreign lpvm access($#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?head#0:wybe.int)
        foreign lpvm access(~$#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tail#0:list_loop.intlist)
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)



head > public {inline} (0 calls)
0: list_loop.intlist.head<0>
head($rec#0:list_loop.intlist, ?$#0:wybe.int, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($rec#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)
        foreign llvm move(undef:wybe.int, ?$#0:wybe.int)

    1:
        foreign lpvm access(~$rec#0:list_loop.intlist, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?$#0:wybe.int)
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

head > public {inline} (0 calls)
1: list_loop.intlist.head<1>
head($rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist, $field#0:wybe.int, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($rec#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)
        foreign llvm move(~$rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist)

    1:
        foreign lpvm mutate(~$rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:wybe.int)
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)



nil > public {inline} (0 calls)
0: list_loop.intlist.nil<0>
nil(?$#0:list_loop.intlist):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm move(0:list_loop.intlist, ?$#0:list_loop.intlist)


tail > public {inline} (0 calls)
0: list_loop.intlist.tail<0>
tail($rec#0:list_loop.intlist, ?$#0:list_loop.intlist, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($rec#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)
        foreign llvm move(undef:list_loop.intlist, ?$#0:list_loop.intlist)

    1:
        foreign lpvm access(~$rec#0:list_loop.intlist, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?$#0:list_loop.intlist)
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)

tail > public {inline} (0 calls)
1: list_loop.intlist.tail<1>
tail($rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist, $field#0:list_loop.intlist, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    foreign llvm icmp_ne($rec#0:wybe.int, 0:wybe.int, ?tmp$0#0:wybe.bool)
    case ~tmp$0#0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?$$#0:wybe.bool)
        foreign llvm move(~$rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist)

    1:
        foreign lpvm {noalias} mutate(~$rec#0:list_loop.intlist, ?$rec#1:list_loop.intlist, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~$field#0:list_loop.intlist)
        foreign llvm move(1:wybe.bool, ?$$#0:wybe.bool)



~= > public {inline} (0 calls)
0: list_loop.intlist.~=<0>
~=($left#0:list_loop.intlist, $right#0:list_loop.intlist, ?$$#0:wybe.bool):
 AliasPairs: []
 InterestingCallProperties: []
    list_loop.intlist.=<0>(~$left#0:list_loop.intlist, ~$right#0:list_loop.intlist, ?tmp$0#0:wybe.bool) #0
    foreign llvm xor(~tmp$0#0:wybe.bool, 1:wybe.bool, ?$$#0:wybe.bool)

  LLVM code       :

; ModuleID = 'list_loop.intlist'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  i1 @"list_loop.intlist.=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$left#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %1 = inttoptr i64 %"$left#0" to i64* 
  %2 = getelementptr  i64, i64* %1, i64 0 
  %3 = load  i64, i64* %2 
  %4 = add   i64 %"$left#0", 8 
  %5 = inttoptr i64 %4 to i64* 
  %6 = getelementptr  i64, i64* %5, i64 0 
  %7 = load  i64, i64* %6 
  %"2$tmp$9#0" = icmp ne i64 %"$right#0", 0 
  br i1 %"2$tmp$9#0", label %if.then1, label %if.else1 
if.else:
  %"3$$$#0" = icmp eq i64 %"$left#0", %"$right#0" 
  ret i1 %"3$$$#0" 
if.then1:
  %8 = inttoptr i64 %"$right#0" to i64* 
  %9 = getelementptr  i64, i64* %8, i64 0 
  %10 = load  i64, i64* %9 
  %11 = add   i64 %"$right#0", 8 
  %12 = inttoptr i64 %11 to i64* 
  %13 = getelementptr  i64, i64* %12, i64 0 
  %14 = load  i64, i64* %13 
  %"4$tmp$4#0" = icmp eq i64 %3, %10 
  br i1 %"4$tmp$4#0", label %if.then2, label %if.else2 
if.else1:
  ret i1 0 
if.then2:
  %"6$$$#0" = tail call fastcc  i1  @"list_loop.intlist.=<0>"(i64  %7, i64  %14)  
  ret i1 %"6$$$#0" 
if.else2:
  ret i1 0 
}


define external fastcc  i64 @"list_loop.intlist.cons<0>"(i64  %"head#0", i64  %"tail#0")    {
entry:
  %15 = trunc i64 16 to i32  
  %16 = tail call ccc  i8*  @wybe_malloc(i32  %15)  
  %17 = ptrtoint i8* %16 to i64 
  %18 = inttoptr i64 %17 to i64* 
  %19 = getelementptr  i64, i64* %18, i64 0 
  store  i64 %"head#0", i64* %19 
  %20 = add   i64 %17, 8 
  %21 = inttoptr i64 %20 to i64* 
  %22 = getelementptr  i64, i64* %21, i64 0 
  store  i64 %"tail#0", i64* %22 
  ret i64 %17 
}


define external fastcc  {i64, i64, i1} @"list_loop.intlist.cons<1>"(i64  %"$#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %23 = inttoptr i64 %"$#0" to i64* 
  %24 = getelementptr  i64, i64* %23, i64 0 
  %25 = load  i64, i64* %24 
  %26 = add   i64 %"$#0", 8 
  %27 = inttoptr i64 %26 to i64* 
  %28 = getelementptr  i64, i64* %27, i64 0 
  %29 = load  i64, i64* %28 
  %30 = insertvalue {i64, i64, i1} undef, i64 %25, 0 
  %31 = insertvalue {i64, i64, i1} %30, i64 %29, 1 
  %32 = insertvalue {i64, i64, i1} %31, i1 1, 2 
  ret {i64, i64, i1} %32 
if.else:
  %33 = insertvalue {i64, i64, i1} undef, i64 undef, 0 
  %34 = insertvalue {i64, i64, i1} %33, i64 undef, 1 
  %35 = insertvalue {i64, i64, i1} %34, i1 0, 2 
  ret {i64, i64, i1} %35 
}


define external fastcc  {i64, i1} @"list_loop.intlist.head<0>"(i64  %"$rec#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$rec#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %36 = inttoptr i64 %"$rec#0" to i64* 
  %37 = getelementptr  i64, i64* %36, i64 0 
  %38 = load  i64, i64* %37 
  %39 = insertvalue {i64, i1} undef, i64 %38, 0 
  %40 = insertvalue {i64, i1} %39, i1 1, 1 
  ret {i64, i1} %40 
if.else:
  %41 = insertvalue {i64, i1} undef, i64 undef, 0 
  %42 = insertvalue {i64, i1} %41, i1 0, 1 
  ret {i64, i1} %42 
}


define external fastcc  {i64, i1} @"list_loop.intlist.head<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$rec#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %43 = trunc i64 16 to i32  
  %44 = tail call ccc  i8*  @wybe_malloc(i32  %43)  
  %45 = ptrtoint i8* %44 to i64 
  %46 = inttoptr i64 %45 to i8* 
  %47 = inttoptr i64 %"$rec#0" to i8* 
  %48 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %46, i8*  %47, i32  %48, i32  8, i1  0)  
  %49 = inttoptr i64 %45 to i64* 
  %50 = getelementptr  i64, i64* %49, i64 0 
  store  i64 %"$field#0", i64* %50 
  %51 = insertvalue {i64, i1} undef, i64 %45, 0 
  %52 = insertvalue {i64, i1} %51, i1 1, 1 
  ret {i64, i1} %52 
if.else:
  %53 = insertvalue {i64, i1} undef, i64 %"$rec#0", 0 
  %54 = insertvalue {i64, i1} %53, i1 0, 1 
  ret {i64, i1} %54 
}


define external fastcc  i64 @"list_loop.intlist.nil<0>"()    {
entry:
  ret i64 0 
}


define external fastcc  {i64, i1} @"list_loop.intlist.tail<0>"(i64  %"$rec#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$rec#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %55 = add   i64 %"$rec#0", 8 
  %56 = inttoptr i64 %55 to i64* 
  %57 = getelementptr  i64, i64* %56, i64 0 
  %58 = load  i64, i64* %57 
  %59 = insertvalue {i64, i1} undef, i64 %58, 0 
  %60 = insertvalue {i64, i1} %59, i1 1, 1 
  ret {i64, i1} %60 
if.else:
  %61 = insertvalue {i64, i1} undef, i64 undef, 0 
  %62 = insertvalue {i64, i1} %61, i1 0, 1 
  ret {i64, i1} %62 
}


define external fastcc  {i64, i1} @"list_loop.intlist.tail<1>"(i64  %"$rec#0", i64  %"$field#0")    {
entry:
  %"1$tmp$0#0" = icmp ne i64 %"$rec#0", 0 
  br i1 %"1$tmp$0#0", label %if.then, label %if.else 
if.then:
  %63 = trunc i64 16 to i32  
  %64 = tail call ccc  i8*  @wybe_malloc(i32  %63)  
  %65 = ptrtoint i8* %64 to i64 
  %66 = inttoptr i64 %65 to i8* 
  %67 = inttoptr i64 %"$rec#0" to i8* 
  %68 = trunc i64 16 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %66, i8*  %67, i32  %68, i32  8, i1  0)  
  %69 = add   i64 %65, 8 
  %70 = inttoptr i64 %69 to i64* 
  %71 = getelementptr  i64, i64* %70, i64 0 
  store  i64 %"$field#0", i64* %71 
  %72 = insertvalue {i64, i1} undef, i64 %65, 0 
  %73 = insertvalue {i64, i1} %72, i1 1, 1 
  ret {i64, i1} %73 
if.else:
  %74 = insertvalue {i64, i1} undef, i64 %"$rec#0", 0 
  %75 = insertvalue {i64, i1} %74, i1 0, 1 
  ret {i64, i1} %75 
}


define external fastcc  i1 @"list_loop.intlist.~=<0>"(i64  %"$left#0", i64  %"$right#0")    {
entry:
  %"1$tmp$0#0" = tail call fastcc  i1  @"list_loop.intlist.=<0>"(i64  %"$left#0", i64  %"$right#0")  
  %"1$$$#0" = xor i1 %"1$tmp$0#0", 1 
  ret i1 %"1$$$#0" 
}
