======================================================================
AFTER EVERYTHING:
 Module main_hello2
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : main_hello2.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public {impure} (0 calls) 
0: main_hello2.<0>
(*#globals##0:wybe.phantom, *?#globals##2:wybe.phantom):
  GlobalFlows: everything 
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.print_string<0>("hello, ":wybe.string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #2 @io:nn:nn
    wybe.string.print_string<0>("world!":wybe.string, ~*#globals##1:wybe.phantom, ?*tmp#4##0:wybe.phantom) #3 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom, *tmp#4##0:wybe.phantom)
    foreign c putchar('\n':wybe.char, ~%tmp#5##0:wybe.phantom, ?%tmp#6##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#6##0:wybe.phantom, ~*tmp#4##0:wybe.phantom, ?*#globals##2:wybe.phantom)

  LLVM code       :

; ModuleID = 'main_hello2'


 


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


@main_hello2.4 =    constant {i64, i64} { i64 6, i64 ptrtoint ([?? x i8]* @main_hello2.3 to i64) }


@main_hello2.3 =    constant [?? x i8] c"world!\00"


@main_hello2.2 =    constant {i64, i64} { i64 7, i64 ptrtoint ([?? x i8]* @main_hello2.1 to i64) }


@main_hello2.1 =    constant [?? x i8] c"hello, \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"main_hello2.<0>"()    {
entry:
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @main_hello2.2, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @main_hello2.4, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
