======================================================================
AFTER EVERYTHING:
 Module multi_out
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : multi_out.<0>
                    multi_out.onetwothree<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: multi_out.<0>
()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc onetwothree > public {inline} (1 calls)
0: multi_out.onetwothree<0>
onetwothree(?x##0:wybe.int, ?y##0:wybe.int, ?z##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(1:wybe.int, ?x##0:wybe.int) @multi_out:nn:nn
    foreign llvm move(2:wybe.int, ?y##0:wybe.int) @multi_out:nn:nn
    foreign llvm move(3:wybe.int, ?z##0:wybe.int) @multi_out:nn:nn

  LLVM code       :

; ModuleID = 'multi_out'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"multi_out.<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  {i64, i64, i64} @"multi_out.onetwothree<0>"() alwaysinline   {
entry:
  %0 = insertvalue {i64, i64, i64} undef, i64 1, 0 
  %1 = insertvalue {i64, i64, i64} %0, i64 2, 1 
  %2 = insertvalue {i64, i64, i64} %1, i64 3, 2 
  ret {i64, i64, i64} %2 
}
