======================================================================
AFTER EVERYTHING:
 Module proc_yorn
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : proc_yorn.<0>
                    proc_yorn.yorn<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {impure} (0 calls)
0: proc_yorn.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}>:
  AliasPairs: []
  InterestingCallProperties: []
    proc_yorn.gen#1<0>("Well, yes or no?":wybe.string, ?r##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #2 @proc_yorn:nn:nn
    wybe.io.print<5>(~r##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #3 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn


gen#1 > (2 calls)
0: proc_yorn.gen#1<0>
gen#1(prompt##0:wybe.string, ?result##1:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.print_string<0>(prompt##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #7 @io:nn:nn
    wybe.string.print_string<0>(" (y/n) ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #8 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#4##0:wybe.phantom) @io:nn:nn
    foreign c read_char(?response##0:wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn
    foreign llvm icmp_ne(response##0:wybe.char, 'y':wybe.char, ?tmp#7##0:wybe.bool) @char:nn:nn
    foreign llvm icmp_ne(response##0:wybe.char, 'Y':wybe.char, ?tmp#8##0:wybe.bool) @char:nn:nn
    foreign llvm and(~tmp#7##0:wybe.bool, ~tmp#8##0:wybe.bool, ?tmp#9##0:wybe.bool) @bool:nn:nn
    foreign llvm xor(~tmp#9##0:wybe.bool, 1:wybe.bool, ?tmp#0##0:wybe.bool) @bool:nn:nn
    proc_yorn.is_yes_or_no<0>(~response##0:wybe.char, ?tmp#1##0:wybe.bool) #4 @proc_yorn:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        wybe.string.print_string<0>("Please answer 'yes' or 'no'.":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #9 @io:nn:nn
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#11##0:wybe.phantom) @io:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#11##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @io:nn:nn
        foreign lpvm store(~%tmp#12##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn
        proc_yorn.gen#1<0>(~prompt##0:wybe.string, ?result##1:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #6 @proc_yorn:nn:nn

    1:
        foreign llvm move(~tmp#0##0:wybe.bool, ?result##1:wybe.bool)



is_yes > {inline} (4 calls)
0: proc_yorn.is_yes<0>
is_yes(ch##0:wybe.char, ?#result##0:wybe.bool)<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(ch##0:wybe.char, 'y':wybe.char, ?tmp#2##0:wybe.bool) @char:nn:nn
    foreign llvm icmp_ne(~ch##0:wybe.char, 'Y':wybe.char, ?tmp#3##0:wybe.bool) @char:nn:nn
    foreign llvm and(~tmp#2##0:wybe.bool, ~tmp#3##0:wybe.bool, ?tmp#1##0:wybe.bool) @bool:nn:nn
    foreign llvm xor(~tmp#1##0:wybe.bool, 1:wybe.bool, ?#result##0:wybe.bool) @bool:nn:nn


is_yes_or_no > (3 calls)
0: proc_yorn.is_yes_or_no<0>
is_yes_or_no(ch##0:wybe.char, ?#result##0:wybe.bool)<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(ch##0:wybe.char, 'y':wybe.char, ?tmp#6##0:wybe.bool) @char:nn:nn
    foreign llvm icmp_ne(ch##0:wybe.char, 'Y':wybe.char, ?tmp#7##0:wybe.bool) @char:nn:nn
    foreign llvm and(~tmp#6##0:wybe.bool, ~tmp#7##0:wybe.bool, ?tmp#8##0:wybe.bool) @bool:nn:nn
    foreign llvm xor(~tmp#8##0:wybe.bool, 1:wybe.bool, ?tmp#1##0:wybe.bool) @bool:nn:nn
    foreign llvm icmp_eq(ch##0:wybe.char, 'n':wybe.char, ?tmp#3##0:wybe.bool) @char:nn:nn
    foreign llvm icmp_eq(~ch##0:wybe.char, 'N':wybe.char, ?tmp#4##0:wybe.bool) @char:nn:nn
    foreign llvm or(~tmp#3##0:wybe.bool, ~tmp#4##0:wybe.bool, ?tmp#2##0:wybe.bool) @bool:nn:nn
    foreign llvm or(~tmp#1##0:wybe.bool, ~tmp#2##0:wybe.bool, ?#result##0:wybe.bool) @bool:nn:nn


yorn > public {inline} (1 calls)
0: proc_yorn.yorn<0>
yorn(prompt##0:wybe.string, ?result##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}>:
  AliasPairs: []
  InterestingCallProperties: []
    proc_yorn.gen#1<0>(~prompt##0:wybe.string, ?result##0:wybe.bool)<{<<wybe.io.io>>}; {<<wybe.io.io>>}> #0 @proc_yorn:nn:nn

  LLVM code       :

; ModuleID = 'proc_yorn'


 


@proc_yorn.4 =    constant {i64, i64} { i64 7, i64 ptrtoint ([?? x i8]* @proc_yorn.3 to i64) }


@proc_yorn.2 =    constant {i64, i64} { i64 16, i64 ptrtoint ([?? x i8]* @proc_yorn.1 to i64) }


@proc_yorn.6 =    constant {i64, i64} { i64 28, i64 ptrtoint ([?? x i8]* @proc_yorn.5 to i64) }


@proc_yorn.3 =    constant [?? x i8] c" (y/n) \00"


@proc_yorn.5 =    constant [?? x i8] c"Please answer 'yes' or 'no'.\00"


@proc_yorn.1 =    constant [?? x i8] c"Well, yes or no?\00"


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


declare external ccc  i8 @read_char()    


declare external fastcc  void @"wybe.io.print<5>"(i1)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"proc_yorn.<0>"()    {
entry:
  %"1#r##0" = tail call fastcc  i1  @"proc_yorn.gen#1<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @proc_yorn.2, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.io.print<5>"(i1  %"1#r##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  i1 @"proc_yorn.gen#1<0>"(i64  %"prompt##0")    {
entry:
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  %"prompt##0")  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @proc_yorn.4, i32 0, i32 0) to i64))  
  %"1#response##0" = tail call ccc  i8  @read_char()  
  %"1#tmp#7##0" = icmp ne i8 %"1#response##0", 121 
  %"1#tmp#8##0" = icmp ne i8 %"1#response##0", 89 
  %"1#tmp#9##0" = and i1 %"1#tmp#7##0", %"1#tmp#8##0" 
  %"1#tmp#0##0" = xor i1 %"1#tmp#9##0", 1 
  %"1#tmp#1##0" = tail call fastcc  i1  @"proc_yorn.is_yes_or_no<0>"(i8  %"1#response##0")  
  br i1 %"1#tmp#1##0", label %if.then, label %if.else 
if.then:
  ret i1 %"1#tmp#0##0" 
if.else:
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @proc_yorn.6, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  %"3#result##1" = tail call fastcc  i1  @"proc_yorn.gen#1<0>"(i64  %"prompt##0")  
  ret i1 %"3#result##1" 
}


define external fastcc  i1 @"proc_yorn.is_yes<0>"(i8  %"ch##0")    {
entry:
  %"1#tmp#2##0" = icmp ne i8 %"ch##0", 121 
  %"1#tmp#3##0" = icmp ne i8 %"ch##0", 89 
  %"1#tmp#1##0" = and i1 %"1#tmp#2##0", %"1#tmp#3##0" 
  %"1##result##0" = xor i1 %"1#tmp#1##0", 1 
  ret i1 %"1##result##0" 
}


define external fastcc  i1 @"proc_yorn.is_yes_or_no<0>"(i8  %"ch##0")    {
entry:
  %"1#tmp#6##0" = icmp ne i8 %"ch##0", 121 
  %"1#tmp#7##0" = icmp ne i8 %"ch##0", 89 
  %"1#tmp#8##0" = and i1 %"1#tmp#6##0", %"1#tmp#7##0" 
  %"1#tmp#1##0" = xor i1 %"1#tmp#8##0", 1 
  %"1#tmp#3##0" = icmp eq i8 %"ch##0", 110 
  %"1#tmp#4##0" = icmp eq i8 %"ch##0", 78 
  %"1#tmp#2##0" = or i1 %"1#tmp#3##0", %"1#tmp#4##0" 
  %"1##result##0" = or i1 %"1#tmp#1##0", %"1#tmp#2##0" 
  ret i1 %"1##result##0" 
}


define external fastcc  i1 @"proc_yorn.yorn<0>"(i64  %"prompt##0")    {
entry:
  %"1#result##0" = tail call fastcc  i1  @"proc_yorn.gen#1<0>"(i64  %"prompt##0")  
  ret i1 %"1#result##0" 
}
