======================================================================
AFTER EVERYTHING:
 Module proc_beer
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : proc_beer.<0>
                    proc_beer.beer99<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,impure} (0 calls)
0: proc_beer.<0>
(*#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
  GlobalFlows: {<<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    proc_beer.gen#1<0>(~*#globals##0:wybe.phantom, 99:wybe.int, ?*#globals##1:wybe.phantom) #1 @proc_beer:nn:nn


beer99 > public {inline} (1 calls)
0: proc_beer.beer99<0>
beer99(*#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
  GlobalFlows: {<<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    proc_beer.gen#1<0>(~*#globals##0:wybe.phantom, 99:wybe.int, ?#globals##1:wybe.phantom) #0 @proc_beer:nn:nn


gen#1 > (2 calls)
0: proc_beer.gen#1<0>
gen#1(*#globals##0:wybe.phantom, count##0:wybe.int, *?#globals##1:wybe.phantom):
  GlobalFlows: {<<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_sge(count##0:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.bool) @int:nn:nn
    case ~tmp#0##0:wybe.bool of
    0:
        foreign llvm move(~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom)

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom, ~*#globals##0:wybe.phantom, ?*tmp#6##0:wybe.phantom) @io:nn:nn
        foreign c print_int(count##0:wybe.int, ~tmp#5##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @io:nn:nn
        foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#7##0:wybe.phantom, ~*tmp#6##0:wybe.phantom, ?*tmp#8##0:wybe.phantom) @io:nn:nn
        wybe.string.print_string<0>(" bottles of beer on the wall":wybe.string, ~*tmp#8##0:wybe.phantom, ?*tmp#9##0:wybe.phantom) #2 @io:nn:nn
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#10##0:wybe.phantom, ~*tmp#9##0:wybe.phantom, ?*tmp#11##0:wybe.phantom) @io:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#10##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @io:nn:nn
        foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#12##0:wybe.phantom, ~*tmp#11##0:wybe.phantom, ?*tmp#13##0:wybe.phantom) @io:nn:nn
        foreign llvm sub(~count##0:wybe.int, 1:wybe.int, ?tmp#14##0:wybe.int) @int:nn:nn
        proc_beer.gen#1<0>(~*tmp#13##0:wybe.phantom, ~tmp#14##0:wybe.int, ?#globals##1:wybe.phantom) #3 @proc_beer:nn:nn



gen#2 > {inline} (1 calls)
0: proc_beer.gen#2<0>
gen#2(*#globals##0:wybe.phantom, count##0:wybe.int, *?#globals##3:wybe.phantom):
  GlobalFlows: {<<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#2##0:wybe.phantom, ~*#globals##0:wybe.phantom, ?*tmp#3##0:wybe.phantom) @io:nn:nn
    foreign c print_int(count##0:wybe.int, ~tmp#2##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#4##0:wybe.phantom, ~*tmp#3##0:wybe.phantom, ?*#globals##1:wybe.phantom) @io:nn:nn
    wybe.string.print_string<0>(" bottles of beer on the wall":wybe.string, ~*#globals##1:wybe.phantom, ?*tmp#7##0:wybe.phantom) #4 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#8##0:wybe.phantom, ~*tmp#7##0:wybe.phantom, ?*tmp#9##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#10##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#10##0:wybe.phantom, ~*tmp#9##0:wybe.phantom, ?*#globals##2:wybe.phantom) @io:nn:nn
    foreign llvm sub(~count##0:wybe.int, 1:wybe.int, ?count##1:wybe.int) @int:nn:nn
    proc_beer.gen#1<0>(~*#globals##2:wybe.phantom, ~count##1:wybe.int, ?#globals##3:wybe.phantom) #3 @proc_beer:nn:nn

  LLVM code       :

; ModuleID = 'proc_beer'


 


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


declare external ccc  void @print_int(i64)    


@proc_beer.2 =    constant {i64, i64} { i64 28, i64 ptrtoint ([?? x i8]* @proc_beer.1 to i64) }


@proc_beer.1 =    constant [?? x i8] c" bottles of beer on the wall\00"


@proc_beer.4 =    constant {i64, i64} { i64 28, i64 ptrtoint ([?? x i8]* @proc_beer.3 to i64) }


@proc_beer.3 =    constant [?? x i8] c" bottles of beer on the wall\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"proc_beer.<0>"()    {
entry:
  tail call fastcc  void  @"proc_beer.gen#1<0>"(i64  99)  
  ret void 
}


define external fastcc  void @"proc_beer.beer99<0>"()    {
entry:
  tail call fastcc  void  @"proc_beer.gen#1<0>"(i64  99)  
  ret void 
}


define external fastcc  void @"proc_beer.gen#1<0>"(i64  %"count##0")    {
entry:
  %"1#tmp#0##0" = icmp sge i64 %"count##0", 0 
  br i1 %"1#tmp#0##0", label %if.then, label %if.else 
if.then:
  tail call ccc  void  @print_int(i64  %"count##0")  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @proc_beer.2, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  %"2#tmp#14##0" = sub   i64 %"count##0", 1 
  tail call fastcc  void  @"proc_beer.gen#1<0>"(i64  %"2#tmp#14##0")  
  ret void 
if.else:
  ret void 
}


define external fastcc  void @"proc_beer.gen#2<0>"(i64  %"count##0")    {
entry:
  tail call ccc  void  @print_int(i64  %"count##0")  
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @proc_beer.4, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  %"1#count##1" = sub   i64 %"count##0", 1 
  tail call fastcc  void  @"proc_beer.gen#1<0>"(i64  %"1#count##1")  
  ret void 
}
