======================================================================
AFTER EVERYTHING:
 Module resource_tmp_vars
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : resource_tmp_vars.<0>
  imports         : use wybe
  resources       : counter: fromList [(resource_tmp_vars.counter,wybe.int = 0 @resource_tmp_vars:nn:nn @resource_tmp_vars:nn:nn)]
  procs           : 

module top-level code > public {semipure} (0 calls)
0: resource_tmp_vars.<0>
()<{<<wybe.io.io>>}; {<<resource_tmp_vars.counter>>, <<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm store(0:wybe.int, <<resource_tmp_vars.counter>>:wybe.int) @resource_tmp_vars:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom) @int:nn:nn
    foreign c print_int(1:wybe.int, ~tmp#5##0:wybe.phantom, ?tmp#6##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @io:nn:nn
    foreign c print_int(0:wybe.int, ~tmp#7##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#9##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn


proc #cont#1 > {inline} (1 calls)
0: resource_tmp_vars.#cont#1<0>
#cont#1([tmp#0##0:wybe.int], tmp#1##0:wybe.int)<{<<wybe.io.io>>}; {<<resource_tmp_vars.counter>>, <<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @int:nn:nn
    foreign c print_int(1:wybe.int, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(%tmp#1##0:wybe.int, <<resource_tmp_vars.counter>>:wybe.int) @resource_tmp_vars:nn:nn
    foreign c print_int(~tmp#1##0:wybe.int, ~tmp#5##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#9##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'resource_tmp_vars'


 


@"resource#resource_tmp_vars.counter" =    global i64 undef


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"resource_tmp_vars.<0>"()    {
entry:
  store  i64 0, i64* @"resource#resource_tmp_vars.counter" 
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  0)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"resource_tmp_vars.#cont#1<0>"(i64  %"tmp#1##0") alwaysinline   {
entry:
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 %"tmp#1##0", i64* @"resource#resource_tmp_vars.counter" 
  tail call ccc  void  @print_int(i64  %"tmp#1##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
