======================================================================
AFTER EVERYTHING:
 Module resource_tmp_vars
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : resource_tmp_vars.<0>
  imports         : use wybe
  resources       : counter: fromList [(resource_tmp_vars.counter,wybe.int = 0 @resource_tmp_vars:nn:nn @resource_tmp_vars:nn:nn)]
  procs           : 

*main* > public {impure} (0 calls) 
0: resource_tmp_vars.<0>
(*#globals##0:wybe.phantom, *?#globals##3:wybe.phantom):
  GlobalFlows: {<<resource_tmp_vars.counter>>::{FlowOut}, <<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom, ~*#globals##0:wybe.phantom, ?*tmp#6##0:wybe.phantom)
    foreign c print_int(1:wybe.int, ~%tmp#5##0:wybe.phantom, ?%tmp#7##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#7##0:wybe.phantom, ?%tmp#8##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<resource_tmp_vars.counter>>:wybe.int, 0:wybe.int, ~*tmp#6##0:wybe.phantom, ?*tmp#9##0:wybe.phantom)
    foreign c print_int(0:wybe.int, ~%tmp#8##0:wybe.phantom, ?%tmp#10##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#10##0:wybe.phantom, ?%tmp#11##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#11##0:wybe.phantom, ~*tmp#9##0:wybe.phantom, ?#globals##3:wybe.phantom)


gen#1 > {inline} (1 calls) 
0: resource_tmp_vars.gen#1<0>
gen#1(*#globals##0:wybe.phantom, tmp#0##0:wybe.int, ?#globals##6:wybe.phantom):
  GlobalFlows: {<<resource_tmp_vars.counter>>::{FlowOut}, <<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm move(~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom)
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom, ~*#globals##1:wybe.phantom, ?*#globals##3:wybe.phantom)
    foreign c print_int(1:wybe.int, ~%tmp#3##0:wybe.phantom, ?%tmp#5##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#5##0:wybe.phantom, ?%tmp#6##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<resource_tmp_vars.counter>>:wybe.int, %tmp#0##0:wybe.int, ~*#globals##3:wybe.phantom, ?*#globals##4:wybe.phantom)
    foreign c print_int(~%tmp#0##0:wybe.int, ~%tmp#6##0:wybe.phantom, ?%tmp#11##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#11##0:wybe.phantom, ?%tmp#12##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#12##0:wybe.phantom, ~*#globals##4:wybe.phantom, ?*#globals##6:wybe.phantom)

  LLVM code       :

; ModuleID = 'resource_tmp_vars'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


@"resource#resource_tmp_vars.counter" =    global i64 undef


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"resource_tmp_vars.<0>"()    {
entry:
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 0, i64* @"resource#resource_tmp_vars.counter" 
  tail call ccc  void  @print_int(i64  0)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"resource_tmp_vars.gen#1<0>"(i64  %"tmp#0##0")    {
entry:
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 %"tmp#0##0", i64* @"resource#resource_tmp_vars.counter" 
  tail call ccc  void  @print_int(i64  %"tmp#0##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
