======================================================================
AFTER EVERYTHING:
 Module specials_one_module
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials_one_module.<0>
                    specials_one_module.indirect_call_location<0>
                    specials_one_module.show_column<0>
                    specials_one_module.show_file<0>
                    specials_one_module.show_line<0>
                    specials_one_module.show_location<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: specials_one_module.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_string(c"specials_one_module":wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_int(27:wybe.int, ~tmp#3##0:wybe.phantom, ?tmp#6##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_int(2:wybe.int, ~tmp#7##0:wybe.phantom, ?tmp#10##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#10##0:wybe.phantom, ?tmp#11##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#11##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn
    specials_one_module.indirect_call_location<0>(c"specials_one_module:29:2":wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #4 @specials_one_module:nn:nn


proc indirect_call_location > public (1 calls)
0: specials_one_module.indirect_call_location<0>
indirect_call_location(%call_source_location##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_string(~call_source_location##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#2##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn
    wybe.string.print<0>(" (should be line 28)":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @specials_one_module:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#4##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn


proc show_column > public {inline} (1 calls)
0: specials_one_module.show_column<0>
show_column(%call_source_column_number##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_int(~call_source_column_number##0:wybe.int, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn


proc show_file > public {inline} (1 calls)
0: specials_one_module.show_file<0>
show_file(%call_source_file_name##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_string(~call_source_file_name##0:wybe.c_string, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn


proc show_line > public {inline} (1 calls)
0: specials_one_module.show_line<0>
show_line(%call_source_line_number##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c print_int(~call_source_line_number##0:wybe.int, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @specials_one_module:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @specials_one_module:nn:nn
    foreign lpvm store(~%tmp#3##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @specials_one_module:nn:nn


proc show_location > public {inline} (1 calls)
0: specials_one_module.show_location<0>
show_location(%call_source_location##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    specials_one_module.indirect_call_location<0>(~%call_source_location##0:wybe.c_string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #0 @specials_one_module:nn:nn

  LLVM code       :

; ModuleID = 'specials_one_module'


 


@specials_one_module.3 =    constant {i64, i64} { i64 20, i64 ptrtoint ([?? x i8]* @specials_one_module.2 to i64) }


@specials_one_module.2 =    constant [?? x i8] c" (should be line 28)\00"


@specials_one_module.0 =    constant [?? x i8] c"specials_one_module\00"


@specials_one_module.1 =    constant [?? x i8] c"specials_one_module:29:2\00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external ccc  void @print_string(i64)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"specials_one_module.<0>"()    {
entry:
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.0, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  27)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"specials_one_module.indirect_call_location<0>"(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.1, i32 0, i32 0) to i64))  
  ret void 
}


define external fastcc  void @"specials_one_module.indirect_call_location<0>"(i64  %"call_source_location##0")    {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_location##0")  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @specials_one_module.3, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_column<0>"(i64  %"call_source_column_number##0") alwaysinline   {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_column_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_file<0>"(i64  %"call_source_file_name##0") alwaysinline   {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_file_name##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_line<0>"(i64  %"call_source_line_number##0") alwaysinline   {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_line_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_location<0>"(i64  %"call_source_location##0") alwaysinline   {
entry:
  musttail call fastcc  void  @"specials_one_module.indirect_call_location<0>"(i64  %"call_source_location##0")  
  ret void 
}
