======================================================================
AFTER EVERYTHING:
 Module specials
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials.show_column<0>
                    specials.show_file<0>
                    specials.show_full_file<0>
                    specials.show_full_location<0>
                    specials.show_line<0>
                    specials.show_location<0>
  imports         : use wybe
  resources       : 
  procs           : 

show_column > public {inline} (0 calls) 
0: specials.show_column<0>
show_column(%call_source_column_number##0:wybe.int, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<0>(~call_source_column_number##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_file > public {inline} (0 calls) 
0: specials.show_file<0>
show_file(%call_source_file_name##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_file_name##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_full_file > public {inline} (0 calls) 
0: specials.show_full_file<0>
show_full_file(%call_source_file_full_name##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_file_full_name##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_full_location > public {inline} (0 calls) 
0: specials.show_full_location<0>
show_full_location(%call_source_full_location##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_full_location##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_line > public {inline} (0 calls) 
0: specials.show_line<0>
show_line(%call_source_line_number##0:wybe.int, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<0>(~call_source_line_number##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_location > public {inline} (0 calls) 
0: specials.show_location<0>
show_location(%call_source_location##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_location##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn

  LLVM code       :

; ModuleID = 'specials'


 


declare external fastcc  void @"wybe.io.println<0>"(i64)    


declare external fastcc  void @"wybe.io.println<4>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"specials.show_column<0>"(i64  %"call_source_column_number##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<0>"(i64  %"call_source_column_number##0")  
  ret void 
}


define external fastcc  void @"specials.show_file<0>"(i64  %"call_source_file_name##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_file_name##0")  
  ret void 
}


define external fastcc  void @"specials.show_full_file<0>"(i64  %"call_source_file_full_name##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_file_full_name##0")  
  ret void 
}


define external fastcc  void @"specials.show_full_location<0>"(i64  %"call_source_full_location##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_full_location##0")  
  ret void 
}


define external fastcc  void @"specials.show_line<0>"(i64  %"call_source_line_number##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<0>"(i64  %"call_source_line_number##0")  
  ret void 
}


define external fastcc  void @"specials.show_location<0>"(i64  %"call_source_location##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_location##0")  
  ret void 
}
