======================================================================
AFTER EVERYTHING:
 Module specials
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials.show_column<0>
                    specials.show_file<0>
                    specials.show_full_file<0>
                    specials.show_full_location<0>
                    specials.show_line<0>
                    specials.show_location<0>
  imports         : use wybe
  resources       : 
  procs           : 

show_column > public {inline} (0 calls) 
0: specials.show_column<0>
show_column(%call_source_column_number##0:wybe.int, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<0>(~call_source_column_number##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_file > public {inline} (0 calls) 
0: specials.show_file<0>
show_file(%call_source_file_name##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_file_name##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_full_file > public {inline} (0 calls) 
0: specials.show_full_file<0>
show_full_file(%call_source_file_full_name##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_file_full_name##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_full_location > public {inline} (0 calls) 
0: specials.show_full_location<0>
show_full_location(%call_source_full_location##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_full_location##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_line > public {inline} (0 calls) 
0: specials.show_line<0>
show_line(%call_source_line_number##0:wybe.int, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<0>(~call_source_line_number##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn


show_location > public {inline} (0 calls) 
0: specials.show_location<0>
show_location(%call_source_location##0:wybe.c_string, *#globals##0:wybe.phantom, *?#globals##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(~call_source_location##0:wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #0 @specials:nn:nn

  LLVM code       :

; ModuleID = 'specials'


 


declare external fastcc  void @"wybe.io.println<0>"(i64)    


declare external fastcc  void @"wybe.io.println<4>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"specials.show_column<0>"(i64  %"call_source_column_number##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<0>"(i64  %"call_source_column_number##0")  
  ret void 
}


define external fastcc  void @"specials.show_file<0>"(i64  %"call_source_file_name##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_file_name##0")  
  ret void 
}


define external fastcc  void @"specials.show_full_file<0>"(i64  %"call_source_file_full_name##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_file_full_name##0")  
  ret void 
}


define external fastcc  void @"specials.show_full_location<0>"(i64  %"call_source_full_location##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_full_location##0")  
  ret void 
}


define external fastcc  void @"specials.show_line<0>"(i64  %"call_source_line_number##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<0>"(i64  %"call_source_line_number##0")  
  ret void 
}


define external fastcc  void @"specials.show_location<0>"(i64  %"call_source_location##0")    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  %"call_source_location##0")  
  ret void 
}
--------------------------------------------------
 Module specials_use
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials_use.<0>
  imports         : use specials
                    use wybe
  resources       : 
  procs           : 

*main* > public {impure} (0 calls) 
0: specials_use.<0>
(*#globals##0:wybe.phantom, *?#globals##6:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    wybe.io.println<4>(c"specials_use":wybe.c_string, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom) #6 @specials:nn:nn
    wybe.io.println<4>(c"!ROOT!/final-dump/specials_use.wybe":wybe.c_string, ~*#globals##1:wybe.phantom, ?*#globals##2:wybe.phantom) #7 @specials:nn:nn
    wybe.io.println<0>(5:wybe.int, ~*#globals##2:wybe.phantom, ?*#globals##3:wybe.phantom) #8 @specials:nn:nn
    wybe.io.println<0>(2:wybe.int, ~*#globals##3:wybe.phantom, ?*#globals##4:wybe.phantom) #9 @specials:nn:nn
    wybe.io.println<4>(c"specials_use:7:2":wybe.c_string, ~*#globals##4:wybe.phantom, ?*#globals##5:wybe.phantom) #10 @specials:nn:nn
    wybe.io.println<4>(c"!ROOT!/final-dump/specials_use.wybe:8:2":wybe.c_string, ~*#globals##5:wybe.phantom, ?*#globals##6:wybe.phantom) #11 @specials:nn:nn

  LLVM code       :

; ModuleID = 'specials_use'


 


declare external fastcc  void @"wybe.io.println<4>"(i64)    


declare external fastcc  void @"wybe.io.println<0>"(i64)    


@specials_use.4 =    constant [?? x i8] c"!ROOT!/final-dump/specials_use.wybe:8:2\00"


@specials_use.3 =    constant [?? x i8] c"specials_use:7:2\00"


@specials_use.2 =    constant [?? x i8] c"!ROOT!/final-dump/specials_use.wybe\00"


@specials_use.1 =    constant [?? x i8] c"specials_use\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"specials_use.<0>"()    {
entry:
  tail call fastcc  void  @"wybe.io.println<4>"(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.1, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.io.println<4>"(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.2, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.io.println<0>"(i64  5)  
  tail call fastcc  void  @"wybe.io.println<0>"(i64  2)  
  tail call fastcc  void  @"wybe.io.println<4>"(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.3, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.io.println<4>"(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_use.4, i32 0, i32 0) to i64))  
  ret void 
}
