======================================================================
AFTER EVERYTHING:
 Module specials_one_module
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : specials_one_module.<0>
                    specials_one_module.indirect_call_location<0>
                    specials_one_module.show_column<0>
                    specials_one_module.show_file<0>
                    specials_one_module.show_line<0>
                    specials_one_module.show_location<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public {impure} (0 calls)
0: specials_one_module.<0>
(io##0:wybe.phantom, ?io##4:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string("specials_one_module":wybe.string, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn
    foreign c print_int(27:wybe.int, ~#io##1:wybe.phantom, ?tmp#5##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#5##0:wybe.phantom, ?#io##2:wybe.phantom) @io:nn:nn
    foreign c print_int(2:wybe.int, ~#io##2:wybe.phantom, ?tmp#8##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?#io##3:wybe.phantom) @io:nn:nn
    foreign c print_string("specials_one_module:29:2":wybe.string, ~#io##3:wybe.phantom, ?tmp#11##0:wybe.phantom) @io:nn:nn
    foreign c print_string(" (should be line 28)":wybe.string, ~tmp#11##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#12##0:wybe.phantom, ?#io##4:wybe.phantom) @io:nn:nn


indirect_call_location > public {inline} (1 calls)
0: specials_one_module.indirect_call_location<0>
indirect_call_location(call_source_location##0:wybe.string, io##0:wybe.phantom, ?io##2:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string(~call_source_location##0:wybe.string, ~#io##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn
    foreign c print_string(" (should be line 28)":wybe.string, ~#io##1:wybe.phantom, ?tmp#4##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?#io##2:wybe.phantom) @io:nn:nn


show_column > public {inline} (1 calls)
0: specials_one_module.show_column<0>
show_column(call_source_column_number##0:wybe.int, io##0:wybe.phantom, ?io##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_int(~call_source_column_number##0:wybe.int, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn


show_file > public {inline} (1 calls)
0: specials_one_module.show_file<0>
show_file(call_source_file_name##0:wybe.string, io##0:wybe.phantom, ?io##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string(~call_source_file_name##0:wybe.string, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn


show_line > public {inline} (1 calls)
0: specials_one_module.show_line<0>
show_line(call_source_line_number##0:wybe.int, io##0:wybe.phantom, ?io##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_int(~call_source_line_number##0:wybe.int, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#2##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn


show_location > public {inline} (1 calls)
0: specials_one_module.show_location<0>
show_location(call_source_location##0:wybe.string, io##0:wybe.phantom, ?io##1:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign c print_string(~#call_source_location##0:wybe.string, ~#io##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @io:nn:nn
    foreign c print_string(" (should be line 28)":wybe.string, ~tmp#2##0:wybe.phantom, ?tmp#3##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#3##0:wybe.phantom, ?#io##1:wybe.phantom) @io:nn:nn

  LLVM code       :

; ModuleID = 'specials_one_module'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external ccc  void @print_int(i64)    


@specials_one_module.5 =    constant [?? x i8] c" (should be line 28)\00"


@specials_one_module.3 =    constant [?? x i8] c"specials_one_module:29:2\00"


@specials_one_module.1 =    constant [?? x i8] c"specials_one_module\00"


@specials_one_module.7 =    constant [?? x i8] c" (should be line 28)\00"


@specials_one_module.9 =    constant [?? x i8] c" (should be line 28)\00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"specials_one_module.<0>"()    {
entry:
  %2 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.1, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %2)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  27)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_int(i64  2)  
  tail call ccc  void  @putchar(i8  10)  
  %4 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.3, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %4)  
  %6 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.5, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %6)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.indirect_call_location<0>"(i64  %"call_source_location##0")    {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_location##0")  
  %8 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.7, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %8)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_column<0>"(i64  %"call_source_column_number##0")    {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_column_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_file<0>"(i64  %"call_source_file_name##0")    {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_file_name##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_line<0>"(i64  %"call_source_line_number##0")    {
entry:
  tail call ccc  void  @print_int(i64  %"call_source_line_number##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"specials_one_module.show_location<0>"(i64  %"call_source_location##0")    {
entry:
  tail call ccc  void  @print_string(i64  %"call_source_location##0")  
  %10 = ptrtoint i8* getelementptr inbounds ([?? x i8], [?? x i8]* @specials_one_module.9, i32 0, i32 0) to i64 
  tail call ccc  void  @print_string(i64  %10)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
