======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module stack_alloc_reuse_escape
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : stack_alloc_reuse_escape.<0>
  constants       : 0:: ArrayInfo {arrayData = [IntStructMember (-1) 8,IntStructMember 1 8]}
  imports         : use stack_alloc_reuse_escape.cell
                    use wybe
  resources       : saved: fromList [(stack_alloc_reuse_escape.saved,stack_alloc_reuse_escape.cell = cell(0 @stack_alloc_reuse_escape:nn:nn, 0 @stack_alloc_reuse_escape:nn:nn) @stack_alloc_reuse_escape:nn:nn @stack_alloc_reuse_escape:nn:nn)]
  submodules      : stack_alloc_reuse_escape.cell
  procs           : 

module top-level code > public {semipure} (0 calls)
0: stack_alloc_reuse_escape.<0>
()<{<<wybe.io.io>>}; {<<stack_alloc_reuse_escape.saved>>, <<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    stack_alloc_reuse_escape.stash<0>(42:wybe.int)<{}; {<<stack_alloc_reuse_escape.saved>>}; {}> #0 @stack_alloc_reuse_escape:nn:nn
    stack_alloc_reuse_escape.clobber<0>(1000:wybe.int, ?junk##0:wybe.int) #1 @stack_alloc_reuse_escape:nn:nn
    foreign lpvm load(<<stack_alloc_reuse_escape.saved>>:stack_alloc_reuse_escape.cell, ?%saved##3:stack_alloc_reuse_escape.cell) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(saved##3:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#0##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign c print_int(~tmp#0##0:wybe.int, ~%tmp#6##0:wybe.phantom, ?%tmp#7##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#7##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~saved##3:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign c print_int(~tmp#1##0:wybe.int, ~tmp#8##0:wybe.phantom, ?%tmp#12##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#12##0:wybe.phantom, ?tmp#13##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign c print_int(~junk##0:wybe.int, ~tmp#13##0:wybe.phantom, ?%tmp#16##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign c putchar(10:wybe.char, ~tmp#16##0:wybe.phantom, ?tmp#17##0:wybe.phantom) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm store(~%tmp#17##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @stack_alloc_reuse_escape:nn:nn


proc clobber > {noinline} (1 calls)
0: stack_alloc_reuse_escape.clobber<0>
clobber(n##0:wybe.int, ?out##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(1,(stack_alloc_reuse_escape.clobber#cont#1<0>,fromList [NonAliasedParamCond 1 []]))]
    foreign llvm icmp_sge(n##0:wybe.int, 1:wybe.int, ?tmp#7##0:wybe.bool) @stack_alloc_reuse_escape:nn:nn
    factored ~tmp#7##0:wybe.bool of
      ?tmp#11##0:wybe.int <- stack_alloc_reuse_escape#constant#0[IntStructMember (-1) 8,IntStructMember 1 8]
        wybe.range.construct<0>(1:wybe.int, ~tmp#11##0:wybe.int, ~n##0:wybe.int, ?tmp#1##0:wybe.range) #3 @stack_alloc_reuse_escape:nn:nn
        stack_alloc_reuse_escape.clobber#cont#1<0>[6dacb8fd25](0:wybe.int, ~tmp#1##0:wybe.range, ?out##0:wybe.int) #1 @stack_alloc_reuse_escape:nn:nn


proc clobber#cont#1 > (2 calls)
0: stack_alloc_reuse_escape.clobber#cont#1<0>
clobber#cont#1(acc##0:wybe.int, tmp#0##0:wybe.range, ?out##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: [InterestingUnaliased 1]
  MultiSpeczDepInfo: [(0,(wybe.range.[|]<0>,fromList [NonAliasedParamCond 2 [1]])),(2,(stack_alloc_reuse_escape.clobber#cont#1<0>,fromList [NonAliasedParamCond 1 []]))]
    wybe.range.[|]<0>(?i##0:wybe.int, ?tmp#0##1:wybe.range, ~tmp#0##0:wybe.range, ?tmp#4##0:wybe.bool) #0 @stack_alloc_reuse_escape:nn:nn
    case ~tmp#4##0:wybe.bool of
    0:
        foreign llvm move(~acc##0:wybe.int, ?out##0:wybe.int) @stack_alloc_reuse_escape:nn:nn

    1:
        foreign llvm add(~acc##0:wybe.int, ~i##0:wybe.int, ?tmp#2##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
        stack_alloc_reuse_escape.clobber#cont#1<0>[6dacb8fd25](~tmp#2##0:wybe.int, ~tmp#0##1:wybe.range, ?out##0:wybe.int) #2 @stack_alloc_reuse_escape:nn:nn

 [6dacb8fd25] [NonAliasedParam 1] :
    wybe.range.[|]<0>[785a827a1b](?i##0:wybe.int, ?tmp#0##1:wybe.range, ~tmp#0##0:wybe.range, ?tmp#4##0:wybe.bool) #0 @stack_alloc_reuse_escape:nn:nn
    case ~tmp#4##0:wybe.bool of
    0:
        foreign llvm move(~acc##0:wybe.int, ?out##0:wybe.int) @stack_alloc_reuse_escape:nn:nn

    1:
        foreign llvm add(~acc##0:wybe.int, ~i##0:wybe.int, ?tmp#2##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
        stack_alloc_reuse_escape.clobber#cont#1<0>[6dacb8fd25](~tmp#2##0:wybe.int, ~tmp#0##1:wybe.range, ?out##0:wybe.int) #2 @stack_alloc_reuse_escape:nn:nn



proc stash > {noinline} (1 calls)
0: stack_alloc_reuse_escape.stash<0>
stash(x##0:wybe.int)<{}; {<<stack_alloc_reuse_escape.saved>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm {stack} alloc(16:wybe.int, ?tmp#5##0:stack_alloc_reuse_escape.cell) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~tmp#5##0:stack_alloc_reuse_escape.cell, ?tmp#6##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, x##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~tmp#6##0:stack_alloc_reuse_escape.cell, ?tmp#7##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, x##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~tmp#7##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#1##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#11##0:stack_alloc_reuse_escape.cell) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~tmp#11##0:stack_alloc_reuse_escape.cell, ?tmp#12##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#1##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~tmp#12##0:stack_alloc_reuse_escape.cell, ?tmp#13##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~x##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm store(~tmp#13##0:stack_alloc_reuse_escape.cell, <<stack_alloc_reuse_escape.saved>>:stack_alloc_reuse_escape.cell) @stack_alloc_reuse_escape:nn:nn

  LLVM code       :

;; FILE GENERATED BY wybemk XXX
; ModuleID = 'stack_alloc_reuse_escape'

source_filename = "!ROOT!/final-dump/stack_alloc_reuse_escape.wybe"
target triple   = ????

@"stack_alloc_reuse_escape#constant#0" = private unnamed_addr constant [ 2 x i64 ] [i64 -1, i64 1]

declare external fastcc {i64, i64, i1} @"wybe#.range#.[|]<0>"(i64)
declare external fastcc {i64, i64, i1} @"wybe#.range#.[|]<0>[785a827a1b]"(i64)
declare external fastcc i64 @"wybe#.range#.construct<0>"(i64, i64, i64)
declare external ccc void @print_int(i64)
declare external ccc void @putchar(i8)
declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
@"resource#stack_alloc_reuse_escape.saved" = global i64 undef

define external fastcc void @"stack_alloc_reuse_escape#.<0>"() {
  tail call fastcc void @"stack_alloc_reuse_escape#.stash<0>"(i64 42)
  %"junk##0" = tail call fastcc i64 @"stack_alloc_reuse_escape#.clobber<0>"(i64 1000)
  %"saved##3" = load i64, ptr @"resource#stack_alloc_reuse_escape.saved"
  %"tmp#18##0" = inttoptr i64 %"saved##3" to ptr
  %"tmp#0##0" = load i64, ptr %"tmp#18##0"
  call ccc void @print_int(i64 %"tmp#0##0")
  call ccc void @putchar(i8 10)
  %"tmp#19##0" = add i64 %"saved##3", 8
  %"tmp#20##0" = inttoptr i64 %"tmp#19##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#20##0"
  call ccc void @print_int(i64 %"tmp#1##0")
  call ccc void @putchar(i8 10)
  call ccc void @print_int(i64 %"junk##0")
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc i64 @"stack_alloc_reuse_escape#.clobber<0>"(i64 %"n##0") {
  %"tmp#7##0" = icmp sge i64 %"n##0", 1
  %"tmp#13##0" = zext i1 %"tmp#7##0" to i64
  %"tmp#12##0" = getelementptr inbounds [ 2 x i64 ], ptr @"stack_alloc_reuse_escape#constant#0", i64 0, i64 %"tmp#13##0"
  %"tmp#11##0" = load i64, ptr %"tmp#12##0"
  %"tmp#1##0" = tail call fastcc i64 @"wybe#.range#.construct<0>"(i64 1, i64 %"tmp#11##0", i64 %"n##0")
  %"tmp#14##0" = tail call fastcc i64 @"stack_alloc_reuse_escape#.clobber#cont#1<0>[6dacb8fd25]"(i64 0, i64 %"tmp#1##0")
  ret i64 %"tmp#14##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.clobber#cont#1<0>"(i64 %"acc##0", i64 %"tmp#0##0") {
  %"tmp#7##0" = tail call fastcc {i64, i64, i1} @"wybe#.range#.[|]<0>"(i64 %"tmp#0##0")
  %"i##0" = extractvalue {i64, i64, i1}%"tmp#7##0", 0
  %"tmp#0##1" = extractvalue {i64, i64, i1}%"tmp#7##0", 1
  %"tmp#4##0" = extractvalue {i64, i64, i1}%"tmp#7##0", 2
  br i1 %"tmp#4##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#2##0" = add i64 %"acc##0", %"i##0"
  %"tmp#8##0" = tail call fastcc i64 @"stack_alloc_reuse_escape#.clobber#cont#1<0>[6dacb8fd25]"(i64 %"tmp#2##0", i64 %"tmp#0##1")
  ret i64 %"tmp#8##0"
if.else.0:
  ret i64 %"acc##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.clobber#cont#1<0>[6dacb8fd25]"(i64 %"acc##0", i64 %"tmp#0##0") {
  %"tmp#7##0" = tail call fastcc {i64, i64, i1} @"wybe#.range#.[|]<0>[785a827a1b]"(i64 %"tmp#0##0")
  %"i##0" = extractvalue {i64, i64, i1}%"tmp#7##0", 0
  %"tmp#0##1" = extractvalue {i64, i64, i1}%"tmp#7##0", 1
  %"tmp#4##0" = extractvalue {i64, i64, i1}%"tmp#7##0", 2
  br i1 %"tmp#4##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#2##0" = add i64 %"acc##0", %"i##0"
  %"tmp#8##0" = tail call fastcc i64 @"stack_alloc_reuse_escape#.clobber#cont#1<0>[6dacb8fd25]"(i64 %"tmp#2##0", i64 %"tmp#0##1")
  ret i64 %"tmp#8##0"
if.else.0:
  ret i64 %"acc##0"
}

define external fastcc void @"stack_alloc_reuse_escape#.stash<0>"(i64 %"x##0") {
  %"tmp#14##0" = alloca i8, i64 16, align 8
  %"tmp#5##0" = ptrtoint ptr %"tmp#14##0" to i64
  %"tmp#15##0" = inttoptr i64 %"tmp#5##0" to ptr
  store i64 %"x##0", ptr %"tmp#15##0"
  %"tmp#16##0" = add i64 %"tmp#5##0", 8
  %"tmp#17##0" = inttoptr i64 %"tmp#16##0" to ptr
  store i64 %"x##0", ptr %"tmp#17##0"
  %"tmp#18##0" = inttoptr i64 %"tmp#5##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#18##0"
  %"tmp#19##0" = call ccc ptr @wybe_malloc(i32 16)
  %"tmp#11##0" = ptrtoint ptr %"tmp#19##0" to i64
  %"tmp#20##0" = inttoptr i64 %"tmp#11##0" to ptr
  store i64 %"tmp#1##0", ptr %"tmp#20##0"
  %"tmp#21##0" = add i64 %"tmp#11##0", 8
  %"tmp#22##0" = inttoptr i64 %"tmp#21##0" to ptr
  store i64 %"x##0", ptr %"tmp#22##0"
  store i64 %"tmp#11##0", ptr @"resource#stack_alloc_reuse_escape.saved"
  ret void
}

--------------------------------------------------
 Module stack_alloc_reuse_escape.cell
  representation  : pointer
  public submods  : 
  public resources: 
  public procs    : stack_alloc_reuse_escape.cell.=<0>
                    stack_alloc_reuse_escape.cell.a<0>
                    stack_alloc_reuse_escape.cell.a<1>
                    stack_alloc_reuse_escape.cell.b<0>
                    stack_alloc_reuse_escape.cell.b<1>
                    stack_alloc_reuse_escape.cell.cell<0>
                    stack_alloc_reuse_escape.cell.cell<1>
                    stack_alloc_reuse_escape.cell.~=<0>
  constants       : 
  imports         : use stack_alloc_reuse_escape
                    use wybe
  resources       : 
  procs           : 

proc = > public {inline} (1 calls)
0: stack_alloc_reuse_escape.cell.=<0>
=(#left##0:stack_alloc_reuse_escape.cell, #right##0:stack_alloc_reuse_escape.cell, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#left##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#a##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~#left##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#left#b##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(#right##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#a##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~#right##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#right#b##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign llvm icmp_eq(~#left#a##0:wybe.int, ~#right#a##0:wybe.int, ?tmp#1##0:wybe.bool) @int:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~#left#b##0:wybe.int, ~#right#b##0:wybe.int, ?#success##0:wybe.bool) @int:nn:nn



proc a > public {inline} (0 calls)
0: stack_alloc_reuse_escape.cell.a<0>
a(#rec##0:stack_alloc_reuse_escape.cell, ?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
proc a > public {inline} (0 calls)
1: stack_alloc_reuse_escape.cell.a<1>
a(#rec##0:stack_alloc_reuse_escape.cell, ?#rec##1:stack_alloc_reuse_escape.cell, #field##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:stack_alloc_reuse_escape.cell, ?#rec##1:stack_alloc_reuse_escape.cell, 0:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int) @stack_alloc_reuse_escape:nn:nn


proc b > public {inline} (0 calls)
0: stack_alloc_reuse_escape.cell.b<0>
b(#rec##0:stack_alloc_reuse_escape.cell, ?#result##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?#result##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
proc b > public {inline} (0 calls)
1: stack_alloc_reuse_escape.cell.b<1>
b(#rec##0:stack_alloc_reuse_escape.cell, ?#rec##1:stack_alloc_reuse_escape.cell, #field##0:wybe.int)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm {noalias} mutate(~#rec##0:stack_alloc_reuse_escape.cell, ?#rec##1:stack_alloc_reuse_escape.cell, 8:wybe.int, 0:wybe.int, 16:wybe.int, 0:wybe.int, ~#field##0:wybe.int) @stack_alloc_reuse_escape:nn:nn


proc cell > public {inline} (0 calls)
0: stack_alloc_reuse_escape.cell.cell<0>
cell(a##0:wybe.int, b##0:wybe.int, ?#result##0:stack_alloc_reuse_escape.cell)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?#rec##0:stack_alloc_reuse_escape.cell) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~#rec##0:stack_alloc_reuse_escape.cell, ?#rec##1:stack_alloc_reuse_escape.cell, 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~a##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm mutate(~#rec##1:stack_alloc_reuse_escape.cell, ?#result##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~b##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
proc cell > public {inline} (6 calls)
1: stack_alloc_reuse_escape.cell.cell<1>
cell(?a##0:wybe.int, ?b##0:wybe.int, #result##0:stack_alloc_reuse_escape.cell)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#result##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?a##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~#result##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?b##0:wybe.int) @stack_alloc_reuse_escape:nn:nn


proc ~= > public {inline} (0 calls)
0: stack_alloc_reuse_escape.cell.~=<0>
~=(#left##0:stack_alloc_reuse_escape.cell, #right##0:stack_alloc_reuse_escape.cell, ?#success##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#left##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#3##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~#left##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#4##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(#right##0:stack_alloc_reuse_escape.cell, 0:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#5##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign lpvm access(~#right##0:stack_alloc_reuse_escape.cell, 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#6##0:wybe.int) @stack_alloc_reuse_escape:nn:nn
    foreign llvm icmp_eq(~tmp#3##0:wybe.int, ~tmp#5##0:wybe.int, ?tmp#7##0:wybe.bool) @int:nn:nn
    case ~tmp#7##0:wybe.bool of
    0:
        foreign llvm move(0:wybe.bool, ?tmp#0##0:wybe.bool)
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)

    1:
        foreign llvm icmp_eq(~tmp#4##0:wybe.int, ~tmp#6##0:wybe.int, ?tmp#0##0:wybe.bool) @int:nn:nn
        foreign llvm xor(~tmp#0##0:wybe.bool, 1:wybe.bool, ?#success##0:wybe.bool)


  LLVM code       :

;; FILE GENERATED BY wybemk XXX
; ModuleID = 'stack_alloc_reuse_escape.cell'

source_filename = "!ROOT!/final-dump/stack_alloc_reuse_escape.wybe"
target triple   = ????


declare external ccc ptr @wybe_malloc(i32)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc i1 @"stack_alloc_reuse_escape#.cell#.=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#9##0" = inttoptr i64 %"#left##0" to ptr
  %"#left#a##0" = load i64, ptr %"tmp#9##0"
  %"tmp#10##0" = add i64 %"#left##0", 8
  %"tmp#11##0" = inttoptr i64 %"tmp#10##0" to ptr
  %"#left#b##0" = load i64, ptr %"tmp#11##0"
  %"tmp#12##0" = inttoptr i64 %"#right##0" to ptr
  %"#right#a##0" = load i64, ptr %"tmp#12##0"
  %"tmp#13##0" = add i64 %"#right##0", 8
  %"tmp#14##0" = inttoptr i64 %"tmp#13##0" to ptr
  %"#right#b##0" = load i64, ptr %"tmp#14##0"
  %"tmp#1##0" = icmp eq i64 %"#left#a##0", %"#right#a##0"
  br i1 %"tmp#1##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#15##0" = icmp eq i64 %"#left#b##0", %"#right#b##0"
  ret i1 %"tmp#15##0"
if.else.0:
  ret i1 0
}

define external fastcc i64 @"stack_alloc_reuse_escape#.cell#.a<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = inttoptr i64 %"#rec##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#0##0"
  ret i64 %"tmp#1##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.cell#.a<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = call ccc ptr @wybe_malloc(i32 16)
  %"tmp#1##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#2##0" = add i64 %"tmp#1##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  %"tmp#4##0" = add i64 %"#rec##0", 8
  %"tmp#5##0" = inttoptr i64 %"tmp#4##0" to ptr
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#3##0", ptr %"tmp#5##0", i64 8, i1 0)
  %"tmp#6##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#7##0" = inttoptr i64 %"tmp#6##0" to ptr
  store i64 %"#field##0", ptr %"tmp#7##0"
  ret i64 %"tmp#6##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.cell#.b<0>"(i64 %"#rec##0") {
  %"tmp#0##0" = add i64 %"#rec##0", 8
  %"tmp#1##0" = inttoptr i64 %"tmp#0##0" to ptr
  %"tmp#2##0" = load i64, ptr %"tmp#1##0"
  ret i64 %"tmp#2##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.cell#.b<1>"(i64 %"#rec##0", i64 %"#field##0") {
  %"tmp#0##0" = call ccc ptr @wybe_malloc(i32 16)
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  call ccc void @llvm.memcpy.p0.p0.i64(ptr %"tmp#0##0", ptr %"tmp#1##0", i64 8, i1 0)
  %"tmp#2##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#3##0" = add i64 %"tmp#2##0", 8
  %"tmp#4##0" = inttoptr i64 %"tmp#3##0" to ptr
  store i64 %"#field##0", ptr %"tmp#4##0"
  ret i64 %"tmp#2##0"
}

define external fastcc i64 @"stack_alloc_reuse_escape#.cell#.cell<0>"(i64 %"a##0", i64 %"b##0") {
  %"tmp#0##0" = call ccc ptr @wybe_malloc(i32 16)
  %"#rec##0" = ptrtoint ptr %"tmp#0##0" to i64
  %"tmp#1##0" = inttoptr i64 %"#rec##0" to ptr
  store i64 %"a##0", ptr %"tmp#1##0"
  %"tmp#2##0" = add i64 %"#rec##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  store i64 %"b##0", ptr %"tmp#3##0"
  ret i64 %"#rec##0"
}

define external fastcc {i64, i64} @"stack_alloc_reuse_escape#.cell#.cell<1>"(i64 %"#result##0") {
  %"tmp#0##0" = inttoptr i64 %"#result##0" to ptr
  %"tmp#1##0" = load i64, ptr %"tmp#0##0"
  %"tmp#2##0" = add i64 %"#result##0", 8
  %"tmp#3##0" = inttoptr i64 %"tmp#2##0" to ptr
  %"tmp#4##0" = load i64, ptr %"tmp#3##0"
  %"tmp#5##0" = insertvalue {i64, i64} undef, i64 %"tmp#1##0", 0
  %"tmp#6##0" = insertvalue {i64, i64} %"tmp#5##0", i64 %"tmp#4##0", 1
  ret {i64, i64} %"tmp#6##0"
}

define external fastcc i1 @"stack_alloc_reuse_escape#.cell#.~=<0>"(i64 %"#left##0", i64 %"#right##0") {
  %"tmp#8##0" = inttoptr i64 %"#left##0" to ptr
  %"tmp#3##0" = load i64, ptr %"tmp#8##0"
  %"tmp#9##0" = add i64 %"#left##0", 8
  %"tmp#10##0" = inttoptr i64 %"tmp#9##0" to ptr
  %"tmp#4##0" = load i64, ptr %"tmp#10##0"
  %"tmp#11##0" = inttoptr i64 %"#right##0" to ptr
  %"tmp#5##0" = load i64, ptr %"tmp#11##0"
  %"tmp#12##0" = add i64 %"#right##0", 8
  %"tmp#13##0" = inttoptr i64 %"tmp#12##0" to ptr
  %"tmp#6##0" = load i64, ptr %"tmp#13##0"
  %"tmp#7##0" = icmp eq i64 %"tmp#3##0", %"tmp#5##0"
  br i1 %"tmp#7##0", label %if.then.0, label %if.else.0
if.then.0:
  %"tmp#0##0" = icmp eq i64 %"tmp#4##0", %"tmp#6##0"
  %"tmp#14##0" = xor i1 %"tmp#0##0", 1
  ret i1 %"tmp#14##0"
if.else.0:
  %"tmp#15##0" = xor i1 0, 1
  ret i1 %"tmp#15##0"
}
