======================================================================
AFTER EVERYTHING:
 Module stmt_nop
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : stmt_nop.<0>
  imports         : use wybe
  resources       : 
  procs           : 

*main* > public {inline} (0 calls)
0: (io#0:wybe.phantom, [?io#0:wybe.phantom]):
 AliasPairs: []
 InterestingCallProperties: []

  LLVM code       :

; ModuleID = 'stmt_nop'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"stmt_nop.<0>"()    {
entry:
  ret void 
}
