======================================================================
AFTER EVERYTHING:
 Module string
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : string.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: string.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(65,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(68,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(70,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(72,(string.print_loop#cont#1<0>,fromList [NonAliasedParamCond 0 []]))]
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#33##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"TESTING CONSTRUCTION":wybe.c_string, ~tmp#33##0:wybe.phantom, ?tmp#34##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#34##0:wybe.phantom, ?tmp#35##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#35##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #62 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#37##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#37##0:wybe.phantom, ?tmp#38##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#38##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("a":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #63 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#40##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#40##0:wybe.phantom, ?tmp#41##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#41##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("abc":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #64 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#43##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#43##0:wybe.phantom, ?tmp#44##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#44##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, "abc":wybe.string, ?tmp#0##0:wybe.string) #4 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#0##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #65 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#46##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#46##0:wybe.phantom, ?tmp#47##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#47##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    foreign llvm shl('a':wybe.string, 2:wybe.string, ?tmp#106##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#106##0:wybe.string, 1024:wybe.string, ?tmp#107##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#107##0:wybe.string, 3:wybe.string, ?tmp#1##0:wybe.string) @string:nn:nn
    wybe.string.print<0>(tmp#1##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #66 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#52##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#52##0:wybe.phantom, ?tmp#53##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#53##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.range.construct<0>(1:wybe.int, 3:wybe.int, 100:wybe.int, ?tmp#3##0:wybe.range) #67 @string:nn:nn
    wybe.string.[]<1>("abcdefghi":wybe.string, tmp#3##0:wybe.range, ?tmp#2##0:wybe.string) #9 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#2##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #68 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#58##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#58##0:wybe.phantom, ?tmp#59##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#59##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.[]<1>("abcdefghi":wybe.string, ~tmp#3##0:wybe.range, ?tmp#5##0:wybe.string) #12 @string:nn:nn
    wybe.range...<0>(1:wybe.int, 3:wybe.int, ?tmp#7##0:wybe.range) #13 @string:nn:nn
    wybe.string.[]<1>(~tmp#5##0:wybe.string, ~tmp#7##0:wybe.range, ?tmp#4##0:wybe.string) #14 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#4##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #70 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#64##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#64##0:wybe.phantom, ?tmp#65##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING CONVERSION TO c_string":wybe.c_string, ~tmp#65##0:wybe.phantom, ?tmp#68##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#68##0:wybe.phantom, ?tmp#69##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#69##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    foreign llvm shl('d':wybe.string, 2:wybe.string, ?tmp#71##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#71##0:wybe.string, 1024:wybe.string, ?tmp#72##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#72##0:wybe.string, 3:wybe.string, ?tmp#10##0:wybe.string) @string:nn:nn
    wybe.range...<0>(1:wybe.int, 2:wybe.int, ?tmp#12##0:wybe.range) #18 @string:nn:nn
    wybe.string.[]<1>("efg":wybe.string, ~tmp#12##0:wybe.range, ?tmp#11##0:wybe.string) #19 @string:nn:nn
    wybe.string.,,<0>(~tmp#10##0:wybe.string, ~tmp#11##0:wybe.string, ?tmp#9##0:wybe.string) #20 @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, ~tmp#9##0:wybe.string, ?tmp#8##0:wybe.string) #21 @string:nn:nn
    wybe.string.c_string<0>(tmp#8##0:wybe.string, ?r##0:wybe.c_string) #22 @string:nn:nn
    wybe.string.print<0>(~tmp#8##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #23 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#74##0:wybe.phantom) @string:nn:nn
    foreign c putchar(' ':wybe.char, ~tmp#74##0:wybe.phantom, ?tmp#75##0:wybe.phantom) @string:nn:nn
    foreign c print_string(~r##0:wybe.c_string, ~tmp#75##0:wybe.phantom, ?tmp#78##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#78##0:wybe.phantom, ?tmp#79##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING LOOPS":wybe.c_string, ~tmp#79##0:wybe.phantom, ?tmp#82##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#82##0:wybe.phantom, ?tmp#83##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#83##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    string.print_loop#cont#1<0>("abc":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #71 @string:nn:nn
    wybe.range.irange<0>(10:wybe.int, -1:wybe.int, 1:wybe.int, ?tmp#14##0:wybe.range) #28 @string:nn:nn
    wybe.string.[]<1>("abcdefghijkl":wybe.string, ~tmp#14##0:wybe.range, ?tmp#13##0:wybe.string) #29 @string:nn:nn
    string.print_loop#cont#1<0>[410bae77d3](~tmp#13##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #72 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#87##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING INDEXING":wybe.c_string, ~tmp#87##0:wybe.phantom, ?tmp#88##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#88##0:wybe.phantom, ?tmp#89##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#89##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    string.test_index<0>("abc":wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #32 @string:nn:nn
    string.test_index<0>("abc":wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #33 @string:nn:nn
    string.test_index<0>("abcdefghijklmnopqrstuvwxyz":wybe.string, 25:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #34 @string:nn:nn
    wybe.string.,,<0>("ab":wybe.string, "cd":wybe.string, ?tmp#15##0:wybe.string) #35 @string:nn:nn
    string.test_index<0>(~tmp#15##0:wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #36 @string:nn:nn
    wybe.string.,,<0>("ab":wybe.string, "cd":wybe.string, ?tmp#16##0:wybe.string) #37 @string:nn:nn
    string.test_index<0>(~tmp#16##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #38 @string:nn:nn
    string.test_index<0>(tmp#1##0:wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #40 @string:nn:nn
    wybe.range.construct<0>(0:wybe.int, 2:wybe.int, 10:wybe.int, ?tmp#19##0:wybe.range) #73 @string:nn:nn
    wybe.string.[]<1>("abcdefgh":wybe.string, tmp#19##0:wybe.range, ?tmp#18##0:wybe.string) #42 @string:nn:nn
    string.test_index<0>(~tmp#18##0:wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #43 @string:nn:nn
    string.test_index<0>("abc":wybe.string, 3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #44 @string:nn:nn
    string.test_index<0>(tmp#1##0:wybe.string, 3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #46 @string:nn:nn
    string.test_index<0>("abc":wybe.string, -3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #47 @string:nn:nn
    wybe.string.[]<1>("abc":wybe.string, ~tmp#19##0:wybe.range, ?tmp#21##0:wybe.string) #49 @string:nn:nn
    string.test_index<0>(~tmp#21##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #50 @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, tmp#1##0:wybe.string, ?tmp#23##0:wybe.string) #52 @string:nn:nn
    string.test_index<0>(~tmp#23##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #53 @string:nn:nn
    foreign llvm shl('b':wybe.string, 2:wybe.string, ?tmp#109##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#109##0:wybe.string, 1024:wybe.string, ?tmp#110##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#110##0:wybe.string, 3:wybe.string, ?tmp#29##0:wybe.string) @string:nn:nn
    foreign llvm shl('c':wybe.string, 2:wybe.string, ?tmp#112##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#112##0:wybe.string, 1024:wybe.string, ?tmp#113##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#113##0:wybe.string, 3:wybe.string, ?tmp#30##0:wybe.string) @string:nn:nn
    wybe.string.,,<0>(~tmp#29##0:wybe.string, ~tmp#30##0:wybe.string, ?tmp#28##0:wybe.string) #57 @string:nn:nn
    wybe.string.,,<0>(~tmp#1##0:wybe.string, ~tmp#28##0:wybe.string, ?tmp#26##0:wybe.string) #58 @string:nn:nn
    wybe.range...<0>(0:wybe.int, 2:wybe.int, ?tmp#31##0:wybe.range) #59 @string:nn:nn
    wybe.string.[]<1>(~tmp#26##0:wybe.string, ~tmp#31##0:wybe.range, ?tmp#25##0:wybe.string) #60 @string:nn:nn
    string.test_index<0>(~tmp#25##0:wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #61 @string:nn:nn


proc print_loop > {inline} (2 calls)
0: string.print_loop<0>
print_loop(s##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    string.print_loop#cont#1<0>(~s##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #0 @string:nn:nn


proc print_loop#cont#1 > (2 calls)
0: string.print_loop#cont#1<0>[410bae77d3]
print_loop#cont#1(tmp#0##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: [InterestingUnaliased 0]
  MultiSpeczDepInfo: [(0,(wybe.string.[|]<0>,fromList [NonAliasedParamCond 2 [0]])),(2,(string.print_loop#cont#1<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.string.[|]<0>(?c##0:wybe.char, ?tmp#0##1:wybe.string, ~tmp#0##0:wybe.string, ?tmp#2##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#4##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~c##0:wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
        string.print_loop#cont#1<0>[410bae77d3](~tmp#0##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @string:nn:nn

 [410bae77d3] [NonAliasedParam 0] :
    wybe.string.[|]<0>[785a827a1b](?c##0:wybe.char, ?tmp#0##1:wybe.string, ~tmp#0##0:wybe.string, ?tmp#2##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#4##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~c##0:wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
        string.print_loop#cont#1<0>[410bae77d3](~tmp#0##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @string:nn:nn



proc test_index > (13 calls)
0: string.test_index<0>
test_index(s##0:wybe.string, i##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.[]<0>(~s##0:wybe.string, ~i##0:wybe.int, ?tmp#0##0:wybe.char, ?tmp#1##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c print_string(c"OUT OF RANGE":wybe.c_string, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#7##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~tmp#0##0:wybe.char, ~tmp#7##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#9##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn


  LLVM code       :

; ModuleID = 'string'


 


@string.2 =    constant {i64, i64} { i64 0, i64 ptrtoint ([?? x i8]* @string.1 to i64) }


@string.4 =    constant {i64, i64} { i64 1, i64 ptrtoint ([?? x i8]* @string.3 to i64) }


@string.19 =    constant {i64, i64} { i64 2, i64 ptrtoint ([?? x i8]* @string.18 to i64) }


@string.21 =    constant {i64, i64} { i64 2, i64 ptrtoint ([?? x i8]* @string.20 to i64) }


@string.11 =    constant {i64, i64} { i64 3, i64 ptrtoint ([?? x i8]* @string.10 to i64) }


@string.6 =    constant {i64, i64} { i64 3, i64 ptrtoint ([?? x i8]* @string.5 to i64) }


@string.23 =    constant {i64, i64} { i64 8, i64 ptrtoint ([?? x i8]* @string.22 to i64) }


@string.8 =    constant {i64, i64} { i64 9, i64 ptrtoint ([?? x i8]* @string.7 to i64) }


@string.14 =    constant {i64, i64} { i64 12, i64 ptrtoint ([?? x i8]* @string.13 to i64) }


@string.17 =    constant {i64, i64} { i64 26, i64 ptrtoint ([?? x i8]* @string.16 to i64) }


@string.1 =    constant [?? x i8] c"\00"


@string.9 =    constant [?? x i8] c"\0aTESTING CONVERSION TO c_string\00"


@string.15 =    constant [?? x i8] c"\0aTESTING INDEXING\00"


@string.12 =    constant [?? x i8] c"\0aTESTING LOOPS\00"


@string.24 =    constant [?? x i8] c"OUT OF RANGE\00"


@string.0 =    constant [?? x i8] c"TESTING CONSTRUCTION\00"


@string.3 =    constant [?? x i8] c"a\00"


@string.18 =    constant [?? x i8] c"ab\00"


@string.5 =    constant [?? x i8] c"abc\00"


@string.22 =    constant [?? x i8] c"abcdefgh\00"


@string.7 =    constant [?? x i8] c"abcdefghi\00"


@string.13 =    constant [?? x i8] c"abcdefghijkl\00"


@string.16 =    constant [?? x i8] c"abcdefghijklmnopqrstuvwxyz\00"


@string.20 =    constant [?? x i8] c"cd\00"


@string.10 =    constant [?? x i8] c"efg\00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_string(i64)    


declare external fastcc  {i8, i1} @"wybe.string.[]<0>"(i64, i64)    


declare external fastcc  {i8, i64, i1} @"wybe.string.[|]<0>[785a827a1b]"(i64)    


declare external fastcc  {i8, i64, i1} @"wybe.string.[|]<0>"(i64)    


declare external fastcc  i64 @"wybe.string.[]<1>"(i64, i64)    


declare external fastcc  i64 @"wybe.range...<0>"(i64, i64)    


declare external fastcc  i64 @"wybe.string.,,<0>"(i64, i64)    


declare external fastcc  i64 @"wybe.range.construct<0>"(i64, i64, i64)    


declare external fastcc  i64 @"wybe.range.irange<0>"(i64, i64, i64)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external fastcc  i64 @"wybe.string.c_string<0>"(i64)    


declare external fastcc  void @"wybe.string.print<0>[410bae77d3]"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"string.<0>"()    {
entry:
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @string.0, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.2, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.4, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  %0 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"wybe.string.print<0>[410bae77d3]"(i64  %0)  
  tail call ccc  void  @putchar(i8  10)  
  %1 = shl   i64 97, 2 
  %2 = or i64 %1, 1024 
  %3 = or i64 %2, 3 
  tail call fastcc  void  @"wybe.string.print<0>"(i64  %3)  
  tail call ccc  void  @putchar(i8  10)  
  %4 = tail call fastcc  i64  @"wybe.range.construct<0>"(i64  1, i64  3, i64  100)  
  %5 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.8, i32 0, i32 0) to i64), i64  %4)  
  tail call fastcc  void  @"wybe.string.print<0>[410bae77d3]"(i64  %5)  
  tail call ccc  void  @putchar(i8  10)  
  %6 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.8, i32 0, i32 0) to i64), i64  %4)  
  %7 = tail call fastcc  i64  @"wybe.range...<0>"(i64  1, i64  3)  
  %8 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  %6, i64  %7)  
  tail call fastcc  void  @"wybe.string.print<0>[410bae77d3]"(i64  %8)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @string.9, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  %9 = shl   i64 100, 2 
  %10 = or i64 %9, 1024 
  %11 = or i64 %10, 3 
  %12 = tail call fastcc  i64  @"wybe.range...<0>"(i64  1, i64  2)  
  %13 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.11, i32 0, i32 0) to i64), i64  %12)  
  %14 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  %11, i64  %13)  
  %15 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  %14)  
  %16 = tail call fastcc  i64  @"wybe.string.c_string<0>"(i64  %15)  
  tail call fastcc  void  @"wybe.string.print<0>"(i64  %15)  
  tail call ccc  void  @putchar(i8  32)  
  tail call ccc  void  @print_string(i64  %16)  
  tail call ccc  void  @putchar(i8  10)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @string.12, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"string.print_loop#cont#1<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64))  
  %17 = tail call fastcc  i64  @"wybe.range.irange<0>"(i64  10, i64  -1, i64  1)  
  %18 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.14, i32 0, i32 0) to i64), i64  %17)  
  tail call fastcc  void  @"string.print_loop#cont#1<0>[410bae77d3]"(i64  %18)  
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @string.15, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  tail call fastcc  void  @"string.test_index<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  0)  
  tail call fastcc  void  @"string.test_index<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  1)  
  tail call fastcc  void  @"string.test_index<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.17, i32 0, i32 0) to i64), i64  25)  
  %19 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.19, i32 0, i32 0) to i64), i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.21, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"string.test_index<0>"(i64  %19, i64  1)  
  %20 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.19, i32 0, i32 0) to i64), i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.21, i32 0, i32 0) to i64))  
  tail call fastcc  void  @"string.test_index<0>"(i64  %20, i64  2)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %3, i64  0)  
  %21 = tail call fastcc  i64  @"wybe.range.construct<0>"(i64  0, i64  2, i64  10)  
  %22 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.23, i32 0, i32 0) to i64), i64  %21)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %22, i64  0)  
  tail call fastcc  void  @"string.test_index<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  3)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %3, i64  3)  
  tail call fastcc  void  @"string.test_index<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  -3)  
  %23 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  %21)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %23, i64  2)  
  %24 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @string.6, i32 0, i32 0) to i64), i64  %3)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %24, i64  2)  
  %25 = shl   i64 98, 2 
  %26 = or i64 %25, 1024 
  %27 = or i64 %26, 3 
  %28 = shl   i64 99, 2 
  %29 = or i64 %28, 1024 
  %30 = or i64 %29, 3 
  %31 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  %27, i64  %30)  
  %32 = tail call fastcc  i64  @"wybe.string.,,<0>"(i64  %3, i64  %31)  
  %33 = tail call fastcc  i64  @"wybe.range...<0>"(i64  0, i64  2)  
  %34 = tail call fastcc  i64  @"wybe.string.[]<1>"(i64  %32, i64  %33)  
  tail call fastcc  void  @"string.test_index<0>"(i64  %34, i64  1)  
  ret void 
}


define external fastcc  void @"string.print_loop<0>"(i64  %"s##0") alwaysinline   {
entry:
  musttail call fastcc  void  @"string.print_loop#cont#1<0>"(i64  %"s##0")  
  ret void 
}


define external fastcc  void @"string.print_loop#cont#1<0>"(i64  %"tmp#0##0")    {
entry:
  %0 = tail call fastcc  {i8, i64, i1}  @"wybe.string.[|]<0>"(i64  %"tmp#0##0")  
  %1 = extractvalue {i8, i64, i1} %0, 0 
  %2 = extractvalue {i8, i64, i1} %0, 1 
  %3 = extractvalue {i8, i64, i1} %0, 2 
  br i1 %3, label %if.then, label %if.else 
if.then:
  tail call ccc  void  @putchar(i8  %1)  
  musttail call fastcc  void  @"string.print_loop#cont#1<0>[410bae77d3]"(i64  %2)  
  ret void 
if.else:
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"string.print_loop#cont#1<0>[410bae77d3]"(i64  %"tmp#0##0")    {
entry:
  %0 = tail call fastcc  {i8, i64, i1}  @"wybe.string.[|]<0>[785a827a1b]"(i64  %"tmp#0##0")  
  %1 = extractvalue {i8, i64, i1} %0, 0 
  %2 = extractvalue {i8, i64, i1} %0, 1 
  %3 = extractvalue {i8, i64, i1} %0, 2 
  br i1 %3, label %if.then, label %if.else 
if.then:
  tail call ccc  void  @putchar(i8  %1)  
  musttail call fastcc  void  @"string.print_loop#cont#1<0>[410bae77d3]"(i64  %2)  
  ret void 
if.else:
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"string.test_index<0>"(i64  %"s##0", i64  %"i##0")    {
entry:
  %0 = tail call fastcc  {i8, i1}  @"wybe.string.[]<0>"(i64  %"s##0", i64  %"i##0")  
  %1 = extractvalue {i8, i1} %0, 0 
  %2 = extractvalue {i8, i1} %0, 1 
  br i1 %2, label %if.then, label %if.else 
if.then:
  tail call ccc  void  @putchar(i8  %1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
if.else:
  tail call ccc  void  @print_string(i64  ptrtoint (i8* getelementptr inbounds ([?? x i8], [?? x i8]* @string.24, i32 0, i32 0) to i64))  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
