======================================================================
AFTER EVERYTHING:


--------------------------------------------------
 Module string
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : string.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {semipure} (0 calls)
0: string.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
  MultiSpeczDepInfo: [(65,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(68,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(70,(wybe.string.print<0>,fromList [NonAliasedParamCond 0 []])),(72,(string.print_loop#cont#1<0>,fromList [NonAliasedParamCond 0 []]))]
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#33##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"TESTING CONSTRUCTION":wybe.c_string, ~tmp#33##0:wybe.phantom, ?tmp#34##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#34##0:wybe.phantom, ?tmp#35##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#35##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #62 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#37##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#37##0:wybe.phantom, ?tmp#38##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#38##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("a":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #63 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#40##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#40##0:wybe.phantom, ?tmp#41##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#41##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.print<0>("abc":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #64 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#43##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#43##0:wybe.phantom, ?tmp#44##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#44##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, "abc":wybe.string, ?tmp#0##0:wybe.string) #4 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#0##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #65 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#46##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#46##0:wybe.phantom, ?tmp#47##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#47##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    foreign lpvm cast('a':wybe.char, ?tmp#111##0:wybe.string) @string:nn:nn
    foreign llvm shl(~tmp#111##0:wybe.string, 2:wybe.string, ?tmp#112##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#112##0:wybe.string, 1024:wybe.string, ?tmp#113##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#113##0:wybe.string, 3:wybe.string, ?tmp#1##0:wybe.string) @string:nn:nn
    wybe.string.print<0>(tmp#1##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #66 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#53##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#53##0:wybe.phantom, ?tmp#54##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#54##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.range.construct<0>(1:wybe.int, 3:wybe.int, 100:wybe.int, ?tmp#3##0:wybe.range) #67 @string:nn:nn
    wybe.string.[]<1>("abcdefghi":wybe.string, tmp#3##0:wybe.range, ?tmp#2##0:wybe.string) #9 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#2##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #68 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#59##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#59##0:wybe.phantom, ?tmp#60##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#60##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    wybe.string.[]<1>("abcdefghi":wybe.string, ~tmp#3##0:wybe.range, ?tmp#5##0:wybe.string) #12 @string:nn:nn
    wybe.range...<0>(1:wybe.int, 3:wybe.int, ?tmp#7##0:wybe.range) #13 @string:nn:nn
    wybe.string.[]<1>(~tmp#5##0:wybe.string, ~tmp#7##0:wybe.range, ?tmp#4##0:wybe.string) #14 @string:nn:nn
    wybe.string.print<0>[410bae77d3](~tmp#4##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #70 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#65##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#65##0:wybe.phantom, ?tmp#66##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING CONVERSION TO c_string":wybe.c_string, ~tmp#66##0:wybe.phantom, ?tmp#69##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#69##0:wybe.phantom, ?tmp#70##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#70##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    foreign lpvm cast('d':wybe.char, ?tmp#72##0:wybe.string) @string:nn:nn
    foreign llvm shl(~tmp#72##0:wybe.string, 2:wybe.string, ?tmp#73##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#73##0:wybe.string, 1024:wybe.string, ?tmp#74##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#74##0:wybe.string, 3:wybe.string, ?tmp#10##0:wybe.string) @string:nn:nn
    wybe.range...<0>(1:wybe.int, 2:wybe.int, ?tmp#12##0:wybe.range) #18 @string:nn:nn
    wybe.string.[]<1>("efg":wybe.string, ~tmp#12##0:wybe.range, ?tmp#11##0:wybe.string) #19 @string:nn:nn
    wybe.string.,,<0>(~tmp#10##0:wybe.string, ~tmp#11##0:wybe.string, ?tmp#9##0:wybe.string) #20 @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, ~tmp#9##0:wybe.string, ?tmp#8##0:wybe.string) #21 @string:nn:nn
    wybe.string.c_string<0>(tmp#8##0:wybe.string, ?r##0:wybe.c_string) #22 @string:nn:nn
    wybe.string.print<0>(~tmp#8##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #23 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#76##0:wybe.phantom) @string:nn:nn
    foreign c putchar(' ':wybe.char, ~tmp#76##0:wybe.phantom, ?tmp#77##0:wybe.phantom) @string:nn:nn
    foreign c print_string(~r##0:wybe.c_string, ~tmp#77##0:wybe.phantom, ?tmp#80##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#80##0:wybe.phantom, ?tmp#81##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING LOOPS":wybe.c_string, ~tmp#81##0:wybe.phantom, ?tmp#84##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#84##0:wybe.phantom, ?tmp#85##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#85##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    string.print_loop#cont#1<0>("abc":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #71 @string:nn:nn
    wybe.range.irange<0>(10:wybe.int, -1:wybe.int, 1:wybe.int, ?tmp#14##0:wybe.range) #28 @string:nn:nn
    wybe.string.[]<1>("abcdefghijkl":wybe.string, ~tmp#14##0:wybe.range, ?tmp#13##0:wybe.string) #29 @string:nn:nn
    string.print_loop#cont#1<0>[410bae77d3](~tmp#13##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #72 @string:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#89##0:wybe.phantom) @string:nn:nn
    foreign c print_string(c"\nTESTING INDEXING":wybe.c_string, ~tmp#89##0:wybe.phantom, ?tmp#90##0:wybe.phantom) @string:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#90##0:wybe.phantom, ?tmp#91##0:wybe.phantom) @string:nn:nn
    foreign lpvm store(~%tmp#91##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
    string.test_index<0>("abc":wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #32 @string:nn:nn
    string.test_index<0>("abc":wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #33 @string:nn:nn
    string.test_index<0>("abcdefghijklmnopqrstuvwxyz":wybe.string, 25:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #34 @string:nn:nn
    wybe.string.,,<0>("ab":wybe.string, "cd":wybe.string, ?tmp#15##0:wybe.string) #35 @string:nn:nn
    string.test_index<0>(~tmp#15##0:wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #36 @string:nn:nn
    wybe.string.,,<0>("ab":wybe.string, "cd":wybe.string, ?tmp#16##0:wybe.string) #37 @string:nn:nn
    string.test_index<0>(~tmp#16##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #38 @string:nn:nn
    string.test_index<0>(tmp#1##0:wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #40 @string:nn:nn
    wybe.range.construct<0>(0:wybe.int, 2:wybe.int, 10:wybe.int, ?tmp#19##0:wybe.range) #73 @string:nn:nn
    wybe.string.[]<1>("abcdefgh":wybe.string, tmp#19##0:wybe.range, ?tmp#18##0:wybe.string) #42 @string:nn:nn
    string.test_index<0>(~tmp#18##0:wybe.string, 0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #43 @string:nn:nn
    string.test_index<0>("abc":wybe.string, 3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #44 @string:nn:nn
    string.test_index<0>(tmp#1##0:wybe.string, 3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #46 @string:nn:nn
    string.test_index<0>("abc":wybe.string, -3:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #47 @string:nn:nn
    wybe.string.[]<1>("abc":wybe.string, ~tmp#19##0:wybe.range, ?tmp#21##0:wybe.string) #49 @string:nn:nn
    string.test_index<0>(~tmp#21##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #50 @string:nn:nn
    wybe.string.,,<0>("abc":wybe.string, tmp#1##0:wybe.string, ?tmp#23##0:wybe.string) #52 @string:nn:nn
    string.test_index<0>(~tmp#23##0:wybe.string, 2:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #53 @string:nn:nn
    foreign lpvm cast('b':wybe.char, ?tmp#115##0:wybe.string) @string:nn:nn
    foreign llvm shl(~tmp#115##0:wybe.string, 2:wybe.string, ?tmp#116##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#116##0:wybe.string, 1024:wybe.string, ?tmp#117##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#117##0:wybe.string, 3:wybe.string, ?tmp#29##0:wybe.string) @string:nn:nn
    foreign lpvm cast('c':wybe.char, ?tmp#119##0:wybe.string) @string:nn:nn
    foreign llvm shl(~tmp#119##0:wybe.string, 2:wybe.string, ?tmp#120##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#120##0:wybe.string, 1024:wybe.string, ?tmp#121##0:wybe.string) @string:nn:nn
    foreign llvm or(~tmp#121##0:wybe.string, 3:wybe.string, ?tmp#30##0:wybe.string) @string:nn:nn
    wybe.string.,,<0>(~tmp#29##0:wybe.string, ~tmp#30##0:wybe.string, ?tmp#28##0:wybe.string) #57 @string:nn:nn
    wybe.string.,,<0>(~tmp#1##0:wybe.string, ~tmp#28##0:wybe.string, ?tmp#26##0:wybe.string) #58 @string:nn:nn
    wybe.range...<0>(0:wybe.int, 2:wybe.int, ?tmp#31##0:wybe.range) #59 @string:nn:nn
    wybe.string.[]<1>(~tmp#26##0:wybe.string, ~tmp#31##0:wybe.range, ?tmp#25##0:wybe.string) #60 @string:nn:nn
    string.test_index<0>(~tmp#25##0:wybe.string, 1:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #61 @string:nn:nn


proc print_loop > {inline} (2 calls)
0: string.print_loop<0>
print_loop(s##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    string.print_loop#cont#1<0>(~s##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #0 @string:nn:nn


proc print_loop#cont#1 > (2 calls)
0: string.print_loop#cont#1<0>
print_loop#cont#1(tmp#0##0:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: [InterestingUnaliased 0]
  MultiSpeczDepInfo: [(0,(wybe.string.[|]<0>,fromList [NonAliasedParamCond 2 [0]])),(2,(string.print_loop#cont#1<0>,fromList [NonAliasedParamCond 0 []]))]
    wybe.string.[|]<0>(?c##0:wybe.char, ?tmp#0##1:wybe.string, ~tmp#0##0:wybe.string, ?tmp#2##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#4##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~c##0:wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
        string.print_loop#cont#1<0>[410bae77d3](~tmp#0##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @string:nn:nn

 [410bae77d3] [NonAliasedParam 0] :
    wybe.string.[|]<0>[785a827a1b](?c##0:wybe.char, ?tmp#0##1:wybe.string, ~tmp#0##0:wybe.string, ?tmp#2##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#2##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#4##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#6##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~c##0:wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn
        string.print_loop#cont#1<0>[410bae77d3](~tmp#0##1:wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @string:nn:nn



proc test_index > (13 calls)
0: string.test_index<0>
test_index(s##0:wybe.string, i##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.string.[]<0>(~s##0:wybe.string, ~i##0:wybe.int, ?tmp#0##0:wybe.char, ?tmp#1##0:wybe.bool) #0 @string:nn:nn
    case ~tmp#1##0:wybe.bool of
    0:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#3##0:wybe.phantom) @string:nn:nn
        foreign c print_string(c"OUT OF RANGE":wybe.c_string, ~tmp#3##0:wybe.phantom, ?tmp#4##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#4##0:wybe.phantom, ?tmp#5##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#5##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn

    1:
        foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#7##0:wybe.phantom) @string:nn:nn
        foreign c putchar(~tmp#0##0:wybe.char, ~tmp#7##0:wybe.phantom, ?tmp#8##0:wybe.phantom) @string:nn:nn
        foreign c putchar('\n':wybe.char, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @string:nn:nn
        foreign lpvm store(~%tmp#9##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @string:nn:nn


  LLVM code       :

;; FILE GENERATED BY wybemk 0.2 -- see https://github.com/pschachte/wybe
; ModuleID = 'string'

source_filename = "!ROOT!/final-dump/string.wybe"
target triple    ????

@"cstring#0" = private unnamed_addr constant [ 1 x i8 ] c"\00", align 8
@"cstring#1" = private unnamed_addr constant [ 32 x i8 ] c"\0ATESTING CONVERSION TO c_string\00", align 8
@"cstring#2" = private unnamed_addr constant [ 18 x i8 ] c"\0ATESTING INDEXING\00", align 8
@"cstring#3" = private unnamed_addr constant [ 15 x i8 ] c"\0ATESTING LOOPS\00", align 8
@"cstring#4" = private unnamed_addr constant [ 13 x i8 ] c"OUT OF RANGE\00", align 8
@"cstring#5" = private unnamed_addr constant [ 21 x i8 ] c"TESTING CONSTRUCTION\00", align 8
@"cstring#6" = private unnamed_addr constant [ 2 x i8 ] c"a\00", align 8
@"cstring#7" = private unnamed_addr constant [ 3 x i8 ] c"ab\00", align 8
@"cstring#8" = private unnamed_addr constant [ 4 x i8 ] c"abc\00", align 8
@"cstring#9" = private unnamed_addr constant [ 9 x i8 ] c"abcdefgh\00", align 8
@"cstring#10" = private unnamed_addr constant [ 10 x i8 ] c"abcdefghi\00", align 8
@"cstring#11" = private unnamed_addr constant [ 13 x i8 ] c"abcdefghijkl\00", align 8
@"cstring#12" = private unnamed_addr constant [ 27 x i8 ] c"abcdefghijklmnopqrstuvwxyz\00", align 8
@"cstring#13" = private unnamed_addr constant [ 3 x i8 ] c"cd\00", align 8
@"cstring#14" = private unnamed_addr constant [ 4 x i8 ] c"efg\00", align 8
@"string#15" = private unnamed_addr constant {i64, i64} { i64 0, i64 ptrtoint( ptr @"cstring#0" to i64 ) }, align 8
@"string#16" = private unnamed_addr constant {i64, i64} { i64 1, i64 ptrtoint( ptr @"cstring#6" to i64 ) }, align 8
@"string#17" = private unnamed_addr constant {i64, i64} { i64 2, i64 ptrtoint( ptr @"cstring#7" to i64 ) }, align 8
@"string#18" = private unnamed_addr constant {i64, i64} { i64 3, i64 ptrtoint( ptr @"cstring#8" to i64 ) }, align 8
@"string#19" = private unnamed_addr constant {i64, i64} { i64 8, i64 ptrtoint( ptr @"cstring#9" to i64 ) }, align 8
@"string#20" = private unnamed_addr constant {i64, i64} { i64 9, i64 ptrtoint( ptr @"cstring#10" to i64 ) }, align 8
@"string#21" = private unnamed_addr constant {i64, i64} { i64 12, i64 ptrtoint( ptr @"cstring#11" to i64 ) }, align 8
@"string#22" = private unnamed_addr constant {i64, i64} { i64 26, i64 ptrtoint( ptr @"cstring#12" to i64 ) }, align 8
@"string#23" = private unnamed_addr constant {i64, i64} { i64 2, i64 ptrtoint( ptr @"cstring#13" to i64 ) }, align 8
@"string#24" = private unnamed_addr constant {i64, i64} { i64 3, i64 ptrtoint( ptr @"cstring#14" to i64 ) }, align 8

declare external ccc void @print_string(i64)
declare external ccc void @putchar(i8)
declare external fastcc i64 @"wybe.range...<0>"(i64, i64)
declare external fastcc i64 @"wybe.range.construct<0>"(i64, i64, i64)
declare external fastcc i64 @"wybe.range.irange<0>"(i64, i64, i64)
declare external fastcc i64 @"wybe.string.,,<0>"(i64, i64)
declare external fastcc {i8, i1} @"wybe.string.[]<0>"(i64, i64)
declare external fastcc i64 @"wybe.string.[]<1>"(i64, i64)
declare external fastcc {i8, i64, i1} @"wybe.string.[|]<0>"(i64)
declare external fastcc {i8, i64, i1} @"wybe.string.[|]<0>[785a827a1b]"(i64)
declare external fastcc i64 @"wybe.string.c_string<0>"(i64)
declare external fastcc void @"wybe.string.print<0>"(i64)
declare external fastcc void @"wybe.string.print<0>[410bae77d3]"(i64)
declare external ccc void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)

define external fastcc void @"string.<0>"() {
  call ccc void @print_string(i64 ptrtoint( ptr @"cstring#5" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#15" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#16" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"wybe.string.print<0>"(i64 ptrtoint( ptr @"string#18" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#0##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 ptrtoint( ptr @"string#18" to i64 ))
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#0##0")
  call ccc void @putchar(i8 10)
  %"tmp#111##0" = zext i8 97 to i64
  %"tmp#112##0" = shl i64 %"tmp#111##0", 2
  %"tmp#113##0" = or i64 %"tmp#112##0", 1024
  %"tmp#1##0" = or i64 %"tmp#113##0", 3
  tail call fastcc void @"wybe.string.print<0>"(i64 %"tmp#1##0")
  call ccc void @putchar(i8 10)
  %"tmp#3##0" = tail call fastcc i64 @"wybe.range.construct<0>"(i64 1, i64 3, i64 100)
  %"tmp#2##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#20" to i64 ), i64 %"tmp#3##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#2##0")
  call ccc void @putchar(i8 10)
  %"tmp#5##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#20" to i64 ), i64 %"tmp#3##0")
  %"tmp#7##0" = tail call fastcc i64 @"wybe.range...<0>"(i64 1, i64 3)
  %"tmp#4##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 %"tmp#5##0", i64 %"tmp#7##0")
  tail call fastcc void @"wybe.string.print<0>[410bae77d3]"(i64 %"tmp#4##0")
  call ccc void @putchar(i8 10)
  call ccc void @print_string(i64 ptrtoint( ptr @"cstring#1" to i64 ))
  call ccc void @putchar(i8 10)
  %"tmp#72##0" = zext i8 100 to i64
  %"tmp#73##0" = shl i64 %"tmp#72##0", 2
  %"tmp#74##0" = or i64 %"tmp#73##0", 1024
  %"tmp#10##0" = or i64 %"tmp#74##0", 3
  %"tmp#12##0" = tail call fastcc i64 @"wybe.range...<0>"(i64 1, i64 2)
  %"tmp#11##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#24" to i64 ), i64 %"tmp#12##0")
  %"tmp#9##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#10##0", i64 %"tmp#11##0")
  %"tmp#8##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 %"tmp#9##0")
  %"r##0" = tail call fastcc i64 @"wybe.string.c_string<0>"(i64 %"tmp#8##0")
  tail call fastcc void @"wybe.string.print<0>"(i64 %"tmp#8##0")
  call ccc void @putchar(i8 32)
  call ccc void @print_string(i64 %"r##0")
  call ccc void @putchar(i8 10)
  call ccc void @print_string(i64 ptrtoint( ptr @"cstring#3" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"string.print_loop#cont#1<0>"(i64 ptrtoint( ptr @"string#18" to i64 ))
  %"tmp#14##0" = tail call fastcc i64 @"wybe.range.irange<0>"(i64 10, i64 -1, i64 1)
  %"tmp#13##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#21" to i64 ), i64 %"tmp#14##0")
  tail call fastcc void @"string.print_loop#cont#1<0>[410bae77d3]"(i64 %"tmp#13##0")
  call ccc void @print_string(i64 ptrtoint( ptr @"cstring#2" to i64 ))
  call ccc void @putchar(i8 10)
  tail call fastcc void @"string.test_index<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 0)
  tail call fastcc void @"string.test_index<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 1)
  tail call fastcc void @"string.test_index<0>"(i64 ptrtoint( ptr @"string#22" to i64 ), i64 25)
  %"tmp#15##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"string#17" to i64 ), i64 ptrtoint( ptr @"string#23" to i64 ))
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#15##0", i64 1)
  %"tmp#16##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"string#17" to i64 ), i64 ptrtoint( ptr @"string#23" to i64 ))
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#16##0", i64 2)
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#1##0", i64 0)
  %"tmp#19##0" = tail call fastcc i64 @"wybe.range.construct<0>"(i64 0, i64 2, i64 10)
  %"tmp#18##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#19" to i64 ), i64 %"tmp#19##0")
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#18##0", i64 0)
  tail call fastcc void @"string.test_index<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 3)
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#1##0", i64 3)
  tail call fastcc void @"string.test_index<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 -3)
  %"tmp#21##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 %"tmp#19##0")
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#21##0", i64 2)
  %"tmp#23##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 ptrtoint( ptr @"string#18" to i64 ), i64 %"tmp#1##0")
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#23##0", i64 2)
  %"tmp#115##0" = zext i8 98 to i64
  %"tmp#116##0" = shl i64 %"tmp#115##0", 2
  %"tmp#117##0" = or i64 %"tmp#116##0", 1024
  %"tmp#29##0" = or i64 %"tmp#117##0", 3
  %"tmp#119##0" = zext i8 99 to i64
  %"tmp#120##0" = shl i64 %"tmp#119##0", 2
  %"tmp#121##0" = or i64 %"tmp#120##0", 1024
  %"tmp#30##0" = or i64 %"tmp#121##0", 3
  %"tmp#28##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#29##0", i64 %"tmp#30##0")
  %"tmp#26##0" = tail call fastcc i64 @"wybe.string.,,<0>"(i64 %"tmp#1##0", i64 %"tmp#28##0")
  %"tmp#31##0" = tail call fastcc i64 @"wybe.range...<0>"(i64 0, i64 2)
  %"tmp#25##0" = tail call fastcc i64 @"wybe.string.[]<1>"(i64 %"tmp#26##0", i64 %"tmp#31##0")
  tail call fastcc void @"string.test_index<0>"(i64 %"tmp#25##0", i64 1)
  ret void
}

define external fastcc void @"string.print_loop<0>"(i64 %"s##0") {
  tail call fastcc void @"string.print_loop#cont#1<0>"(i64 %"s##0")
  ret void
}

define external fastcc void @"string.print_loop#cont#1<0>"(i64 %"tmp#0##0") {
  %"tmp#8##0" = tail call fastcc {i8, i64, i1} @"wybe.string.[|]<0>"(i64 %"tmp#0##0")
  %"c##0" = extractvalue {i8, i64, i1}%"tmp#8##0", 0
  %"tmp#0##1" = extractvalue {i8, i64, i1}%"tmp#8##0", 1
  %"tmp#2##0" = extractvalue {i8, i64, i1}%"tmp#8##0", 2
  br i1 %"tmp#2##0", label %if.then.0, label %if.else.0
if.then.0:
  call ccc void @putchar(i8 %"c##0")
  tail call fastcc void @"string.print_loop#cont#1<0>[410bae77d3]"(i64 %"tmp#0##1")
  ret void
if.else.0:
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc void @"string.print_loop#cont#1<0>[410bae77d3]"(i64 %"tmp#0##0") {
  %"tmp#8##0" = tail call fastcc {i8, i64, i1} @"wybe.string.[|]<0>[785a827a1b]"(i64 %"tmp#0##0")
  %"c##0" = extractvalue {i8, i64, i1}%"tmp#8##0", 0
  %"tmp#0##1" = extractvalue {i8, i64, i1}%"tmp#8##0", 1
  %"tmp#2##0" = extractvalue {i8, i64, i1}%"tmp#8##0", 2
  br i1 %"tmp#2##0", label %if.then.0, label %if.else.0
if.then.0:
  call ccc void @putchar(i8 %"c##0")
  tail call fastcc void @"string.print_loop#cont#1<0>[410bae77d3]"(i64 %"tmp#0##1")
  ret void
if.else.0:
  call ccc void @putchar(i8 10)
  ret void
}

define external fastcc void @"string.test_index<0>"(i64 %"s##0", i64 %"i##0") {
  %"tmp#10##0" = tail call fastcc {i8, i1} @"wybe.string.[]<0>"(i64 %"s##0", i64 %"i##0")
  %"tmp#0##0" = extractvalue {i8, i1}%"tmp#10##0", 0
  %"tmp#1##0" = extractvalue {i8, i1}%"tmp#10##0", 1
  br i1 %"tmp#1##0", label %if.then.0, label %if.else.0
if.then.0:
  call ccc void @putchar(i8 %"tmp#0##0")
  call ccc void @putchar(i8 10)
  ret void
if.else.0:
  call ccc void @print_string(i64 ptrtoint( ptr @"cstring#4" to i64 ))
  call ccc void @putchar(i8 10)
  ret void
}
