======================================================================
AFTER EVERYTHING:
 Module tcmc_mutate_struct_directly
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : tcmc_mutate_struct_directly.<0>
                    tcmc_mutate_struct_directly.appendstuff<0>
  imports         : use tcmc_mutate_struct_directly.combined
                    use wybe
  resources       : 
  submodules      : tcmc_mutate_struct_directly.combined
  procs           : 

module top-level code > public {impure} (0 calls)
0: tcmc_mutate_struct_directly.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?tmp#15##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#15##0:wybe.list(T), ?tmp#16##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 3:T) @list:nn:nn
    foreign lpvm mutate(~tmp#16##0:wybe.list(T), ?tmp#2##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:wybe.list(T)) @list:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#19##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#19##0:wybe.list(T), ?tmp#20##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2:T) @list:nn:nn
    foreign lpvm mutate(~tmp#20##0:wybe.list(T), ?tmp#1##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#2##0:wybe.list(T)) @list:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#23##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#23##0:wybe.list(T), ?tmp#24##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:T) @list:nn:nn
    foreign lpvm mutate(~tmp#24##0:wybe.list(T), ?tmp#0##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#1##0:wybe.list(T)) @list:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#27##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#27##0:wybe.list(T), ?tmp#28##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 6:T) @list:nn:nn
    foreign lpvm mutate(~tmp#28##0:wybe.list(T), ?tmp#6##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:wybe.list(T)) @list:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#31##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#31##0:wybe.list(T), ?tmp#32##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 5:T) @list:nn:nn
    foreign lpvm mutate(~tmp#32##0:wybe.list(T), ?tmp#5##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#6##0:wybe.list(T)) @list:nn:nn
    foreign lpvm alloc(16:wybe.int, ?tmp#35##0:wybe.list(T)) @list:nn:nn
    foreign lpvm mutate(~tmp#35##0:wybe.list(T), ?tmp#36##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 4:T) @list:nn:nn
    foreign lpvm mutate(~tmp#36##0:wybe.list(T), ?tmp#4##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#5##0:wybe.list(T)) @list:nn:nn
    tcmc_mutate_struct_directly.appendstuff<0>(~tmp#0##0:wybe.list(wybe.int), ~tmp#4##0:wybe.list(wybe.int), ?l2##0:tcmc_mutate_struct_directly.combined(wybe.int)) #8 @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm access(l2##0:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 24:wybe.int, 0:wybe.int, ?tmp#8##0:wybe.int) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#39##0:wybe.phantom) @int:nn:nn
    foreign c print_int(~tmp#8##0:wybe.int, ~tmp#39##0:wybe.phantom, ?tmp#40##0:wybe.phantom) @int:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#40##0:wybe.phantom, ?tmp#41##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#41##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn
    foreign lpvm access(l2##0:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 24:wybe.int, 0:wybe.int, ?tmp#10##0:wybe.list(wybe.int)) @tcmc_mutate_struct_directly:nn:nn
    wybe.list.print<0>(tcmc_mutate_struct_directly.gen#1<0><>:{resource}(T), ~tmp#10##0:wybe.list(T))<Everything; Everything> #15 @list:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#45##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#45##0:wybe.phantom, ?tmp#46##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#46##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn
    foreign lpvm access(~l2##0:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 24:wybe.int, 0:wybe.int, ?tmp#12##0:wybe.list(wybe.int)) @tcmc_mutate_struct_directly:nn:nn
    wybe.list.print<0>(tcmc_mutate_struct_directly.gen#1<0><>:{resource}(T), ~tmp#12##0:wybe.list(T))<Everything; Everything> #16 @list:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#50##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#50##0:wybe.phantom, ?tmp#51##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(~%tmp#51##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @io:nn:nn


appendstuff > public (1 calls)
0: tcmc_mutate_struct_directly.appendstuff<0>
appendstuff(l##0:wybe.list(wybe.int), l2##0:wybe.list(wybe.int), ?result##0:tcmc_mutate_struct_directly.combined(wybe.int))<{}; {}>:
  AliasPairs: [(l##0,l2##0),(l##0,result##0),(l2##0,result##0)]
  InterestingCallProperties: []
    wybe.list.length1<0>(l##0:wybe.list(T), 0:wybe.int, ?tmp#3##0:wybe.int) #6 @list:nn:nn
    wybe.list.length1<0>(l2##0:wybe.list(T), 0:wybe.int, ?tmp#4##0:wybe.int) #7 @list:nn:nn
    foreign llvm add(~tmp#3##0:wybe.int, ~tmp#4##0:wybe.int, ?tmp#2##0:wybe.int) @int:nn:nn
    foreign lpvm alloc(24:wybe.int, ?tmp#13##0:tcmc_mutate_struct_directly.combined(T)) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~tmp#13##0:tcmc_mutate_struct_directly.combined(T), ?tmp#14##0:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~tmp#2##0:T) @tcmc_mutate_struct_directly:nn:nn
    wybe.list.,,<0>(l2##0:wybe.list(wybe.int), l##0:wybe.list(wybe.int), outByReference tmp#1##0:wybe.list(wybe.int)) #1 @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~tmp#14##0:tcmc_mutate_struct_directly.combined(T), ?tmp#15##0:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~takeReference tmp#1##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
    wybe.list.,,<0>(~l##0:wybe.list(wybe.int), ~l2##0:wybe.list(wybe.int), outByReference tmp#0##0:wybe.list(wybe.int)) #0 @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~tmp#15##0:tcmc_mutate_struct_directly.combined(T), ?result##0:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~takeReference tmp#0##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn


gen#1 > {inline} (2 calls)
0: tcmc_mutate_struct_directly.gen#1<0>
gen#1(x##0:wybe.int)<{<<wybe.io.io>>}; {<<wybe.io.io>>}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#1##0:wybe.phantom) @int:nn:nn
    foreign c print_int(~x##0:wybe.int, ~tmp#1##0:wybe.phantom, ?tmp#2##0:wybe.phantom) @int:nn:nn
    foreign lpvm store(~%tmp#2##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @int:nn:nn

  LLVM code       :

; ModuleID = 'tcmc_mutate_struct_directly'


 


@tcmc_mutate_struct_directly.0 =    constant [1 x i64] [i64 ptrtoint (void (i64, i64)* @"tcmc_mutate_struct_directly.gen#1<0>" to i64)]


declare external ccc  void @print_int(i64)    


declare external fastcc  void @"wybe.list.,,<0>"(i64, i64, i64*)    


declare external fastcc  i64 @"wybe.list.length1<0>"(i64, i64)    


declare external ccc  void @putchar(i8)    


declare external fastcc  void @"wybe.list.print<0>"(i64, i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"tcmc_mutate_struct_directly.<0>"()    {
entry:
  %0 = trunc i64 16 to i32  
  %1 = tail call ccc  i8*  @wybe_malloc(i32  %0)  
  %2 = ptrtoint i8* %1 to i64 
  %3 = inttoptr i64 %2 to i64* 
  store  i64 3, i64* %3 
  %4 = add   i64 %2, 8 
  %5 = inttoptr i64 %4 to i64* 
  store  i64 0, i64* %5 
  %6 = trunc i64 16 to i32  
  %7 = tail call ccc  i8*  @wybe_malloc(i32  %6)  
  %8 = ptrtoint i8* %7 to i64 
  %9 = inttoptr i64 %8 to i64* 
  store  i64 2, i64* %9 
  %10 = add   i64 %8, 8 
  %11 = inttoptr i64 %10 to i64* 
  store  i64 %2, i64* %11 
  %12 = trunc i64 16 to i32  
  %13 = tail call ccc  i8*  @wybe_malloc(i32  %12)  
  %14 = ptrtoint i8* %13 to i64 
  %15 = inttoptr i64 %14 to i64* 
  store  i64 1, i64* %15 
  %16 = add   i64 %14, 8 
  %17 = inttoptr i64 %16 to i64* 
  store  i64 %8, i64* %17 
  %18 = trunc i64 16 to i32  
  %19 = tail call ccc  i8*  @wybe_malloc(i32  %18)  
  %20 = ptrtoint i8* %19 to i64 
  %21 = inttoptr i64 %20 to i64* 
  store  i64 6, i64* %21 
  %22 = add   i64 %20, 8 
  %23 = inttoptr i64 %22 to i64* 
  store  i64 0, i64* %23 
  %24 = trunc i64 16 to i32  
  %25 = tail call ccc  i8*  @wybe_malloc(i32  %24)  
  %26 = ptrtoint i8* %25 to i64 
  %27 = inttoptr i64 %26 to i64* 
  store  i64 5, i64* %27 
  %28 = add   i64 %26, 8 
  %29 = inttoptr i64 %28 to i64* 
  store  i64 %20, i64* %29 
  %30 = trunc i64 16 to i32  
  %31 = tail call ccc  i8*  @wybe_malloc(i32  %30)  
  %32 = ptrtoint i8* %31 to i64 
  %33 = inttoptr i64 %32 to i64* 
  store  i64 4, i64* %33 
  %34 = add   i64 %32, 8 
  %35 = inttoptr i64 %34 to i64* 
  store  i64 %26, i64* %35 
  %36 = tail call fastcc  i64  @"tcmc_mutate_struct_directly.appendstuff<0>"(i64  %14, i64  %32)  
  %37 = inttoptr i64 %36 to i64* 
  %38 = load  i64, i64* %37 
  tail call ccc  void  @print_int(i64  %38)  
  tail call ccc  void  @putchar(i8  10)  
  %39 = add   i64 %36, 8 
  %40 = inttoptr i64 %39 to i64* 
  %41 = load  i64, i64* %40 
  tail call fastcc  void  @"wybe.list.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ([1 x i64], [1 x i64]* @tcmc_mutate_struct_directly.0, i32 0, i32 0) to i64), i64  %41)  
  tail call ccc  void  @putchar(i8  10)  
  %42 = add   i64 %36, 16 
  %43 = inttoptr i64 %42 to i64* 
  %44 = load  i64, i64* %43 
  tail call fastcc  void  @"wybe.list.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ([1 x i64], [1 x i64]* @tcmc_mutate_struct_directly.0, i32 0, i32 0) to i64), i64  %44)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.appendstuff<0>"(i64  %"l##0", i64  %"l2##0")    {
entry:
  %0 = tail call fastcc  i64  @"wybe.list.length1<0>"(i64  %"l##0", i64  0)  
  %1 = tail call fastcc  i64  @"wybe.list.length1<0>"(i64  %"l2##0", i64  0)  
  %2 = add   i64 %0, %1 
  %3 = trunc i64 24 to i32  
  %4 = tail call ccc  i8*  @wybe_malloc(i32  %3)  
  %5 = ptrtoint i8* %4 to i64 
  %6 = inttoptr i64 %5 to i64* 
  store  i64 %2, i64* %6 
  %7 = add   i64 %5, 16 
  %8 = inttoptr i64 %7 to i64* 
  tail call fastcc  void  @"wybe.list.,,<0>"(i64  %"l2##0", i64  %"l##0", i64*  %8)  
  %9 = load  i64, i64* %8 
  %10 = add   i64 %5, 8 
  %11 = inttoptr i64 %10 to i64* 
  tail call fastcc  void  @"wybe.list.,,<0>"(i64  %"l##0", i64  %"l2##0", i64*  %11)  
  ret i64 %5 
}


define external fastcc  void @"tcmc_mutate_struct_directly.gen#1<0>"(i64  %"#env##0", i64  %"x##0")    {
entry:
  tail call ccc  void  @print_int(i64  %"x##0")  
  ret void 
}
--------------------------------------------------
 Module tcmc_mutate_struct_directly.combined(T)
  representation  : address
  public submods  : 
  public resources: 
  public procs    : tcmc_mutate_struct_directly.combined.combined<0>
                    tcmc_mutate_struct_directly.combined.combined<1>
                    tcmc_mutate_struct_directly.combined.x<0>
                    tcmc_mutate_struct_directly.combined.x<1>
                    tcmc_mutate_struct_directly.combined.y<0>
                    tcmc_mutate_struct_directly.combined.y<1>
                    tcmc_mutate_struct_directly.combined.z<0>
                    tcmc_mutate_struct_directly.combined.z<1>
  imports         : use tcmc_mutate_struct_directly
                    use wybe
  resources       : 
  procs           : 

combined > public {inline} (0 calls)
0: tcmc_mutate_struct_directly.combined.combined<0>
combined(x##0:T, y##0:wybe.list(T), z##0:wybe.list(T), ?#result##0:tcmc_mutate_struct_directly.combined(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(24:wybe.int, ?#rec##0:tcmc_mutate_struct_directly.combined(T)) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~x##0:T) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~#rec##1:tcmc_mutate_struct_directly.combined(T), ?#rec##2:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~y##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm mutate(~#rec##2:tcmc_mutate_struct_directly.combined(T), ?#result##0:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 1:wybe.int, 24:wybe.int, 0:wybe.int, ~z##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
combined > public {inline} (0 calls)
1: tcmc_mutate_struct_directly.combined.combined<1>
combined(?x##0:T, ?y##0:wybe.list(T), ?z##0:wybe.list(T), #result##0:tcmc_mutate_struct_directly.combined(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(#result##0:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 24:wybe.int, 0:wybe.int, ?x##0:T) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm access(#result##0:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 24:wybe.int, 0:wybe.int, ?y##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
    foreign lpvm access(~#result##0:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 24:wybe.int, 0:wybe.int, ?z##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn


x > public {inline} (0 calls)
0: tcmc_mutate_struct_directly.combined.x<0>
x(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#result##0:T)<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:T) @tcmc_mutate_struct_directly:nn:nn
x > public {inline} (0 calls)
1: tcmc_mutate_struct_directly.combined.x<1>
x(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), #field##0:T)<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm mutate(~#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), 0:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:T) @tcmc_mutate_struct_directly:nn:nn


y > public {inline} (0 calls)
0: tcmc_mutate_struct_directly.combined.y<0>
y(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#result##0:wybe.list(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
y > public {inline} (0 calls)
1: tcmc_mutate_struct_directly.combined.y<1>
y(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), #field##0:wybe.list(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm mutate(~#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), 8:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn


z > public {inline} (0 calls)
0: tcmc_mutate_struct_directly.combined.z<0>
z(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#result##0:wybe.list(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm access(~#rec##0:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 24:wybe.int, 0:wybe.int, ?#result##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn
z > public {inline} (0 calls)
1: tcmc_mutate_struct_directly.combined.z<1>
z(#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), #field##0:wybe.list(T))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm mutate(~#rec##0:tcmc_mutate_struct_directly.combined(T), ?#rec##1:tcmc_mutate_struct_directly.combined(T), 16:wybe.int, 0:wybe.int, 24:wybe.int, 0:wybe.int, ~#field##0:wybe.list(T)) @tcmc_mutate_struct_directly:nn:nn

  LLVM code       :

; ModuleID = 'tcmc_mutate_struct_directly.combined'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.combined<0>"(i64  %"x##0", i64  %"y##0", i64  %"z##0")    {
entry:
  %0 = trunc i64 24 to i32  
  %1 = tail call ccc  i8*  @wybe_malloc(i32  %0)  
  %2 = ptrtoint i8* %1 to i64 
  %3 = inttoptr i64 %2 to i64* 
  store  i64 %"x##0", i64* %3 
  %4 = add   i64 %2, 8 
  %5 = inttoptr i64 %4 to i64* 
  store  i64 %"y##0", i64* %5 
  %6 = add   i64 %2, 16 
  %7 = inttoptr i64 %6 to i64* 
  store  i64 %"z##0", i64* %7 
  ret i64 %2 
}


define external fastcc  {i64, i64, i64} @"tcmc_mutate_struct_directly.combined.combined<1>"(i64  %"#result##0")    {
entry:
  %0 = inttoptr i64 %"#result##0" to i64* 
  %1 = load  i64, i64* %0 
  %2 = add   i64 %"#result##0", 8 
  %3 = inttoptr i64 %2 to i64* 
  %4 = load  i64, i64* %3 
  %5 = add   i64 %"#result##0", 16 
  %6 = inttoptr i64 %5 to i64* 
  %7 = load  i64, i64* %6 
  %8 = insertvalue {i64, i64, i64} undef, i64 %1, 0 
  %9 = insertvalue {i64, i64, i64} %8, i64 %4, 1 
  %10 = insertvalue {i64, i64, i64} %9, i64 %7, 2 
  ret {i64, i64, i64} %10 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.x<0>"(i64  %"#rec##0")    {
entry:
  %0 = inttoptr i64 %"#rec##0" to i64* 
  %1 = load  i64, i64* %0 
  ret i64 %1 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.x<1>"(i64  %"#rec##0", i64  %"#field##0")    {
entry:
  %0 = trunc i64 24 to i32  
  %1 = tail call ccc  i8*  @wybe_malloc(i32  %0)  
  %2 = ptrtoint i8* %1 to i64 
  %3 = inttoptr i64 %2 to i8* 
  %4 = inttoptr i64 %"#rec##0" to i8* 
  %5 = trunc i64 24 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %3, i8*  %4, i32  %5, i1  0)  
  %6 = inttoptr i64 %2 to i64* 
  store  i64 %"#field##0", i64* %6 
  ret i64 %2 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.y<0>"(i64  %"#rec##0")    {
entry:
  %0 = add   i64 %"#rec##0", 8 
  %1 = inttoptr i64 %0 to i64* 
  %2 = load  i64, i64* %1 
  ret i64 %2 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.y<1>"(i64  %"#rec##0", i64  %"#field##0")    {
entry:
  %0 = trunc i64 24 to i32  
  %1 = tail call ccc  i8*  @wybe_malloc(i32  %0)  
  %2 = ptrtoint i8* %1 to i64 
  %3 = inttoptr i64 %2 to i8* 
  %4 = inttoptr i64 %"#rec##0" to i8* 
  %5 = trunc i64 24 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %3, i8*  %4, i32  %5, i1  0)  
  %6 = add   i64 %2, 8 
  %7 = inttoptr i64 %6 to i64* 
  store  i64 %"#field##0", i64* %7 
  ret i64 %2 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.z<0>"(i64  %"#rec##0")    {
entry:
  %0 = add   i64 %"#rec##0", 16 
  %1 = inttoptr i64 %0 to i64* 
  %2 = load  i64, i64* %1 
  ret i64 %2 
}


define external fastcc  i64 @"tcmc_mutate_struct_directly.combined.z<1>"(i64  %"#rec##0", i64  %"#field##0")    {
entry:
  %0 = trunc i64 24 to i32  
  %1 = tail call ccc  i8*  @wybe_malloc(i32  %0)  
  %2 = ptrtoint i8* %1 to i64 
  %3 = inttoptr i64 %2 to i8* 
  %4 = inttoptr i64 %"#rec##0" to i8* 
  %5 = trunc i64 24 to i32  
  tail call ccc  void  @llvm.memcpy.p0i8.p0i8.i32(i8*  %3, i8*  %4, i32  %5, i1  0)  
  %6 = add   i64 %2, 16 
  %7 = inttoptr i64 %6 to i64* 
  store  i64 %"#field##0", i64* %7 
  ret i64 %2 
}
