======================================================================
AFTER EVERYTHING:
 Module top_level_use
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : top_level_use.<0>
  imports         : use wybe
  resources       : res: fromList [(top_level_use.res,wybe.int = 0 @top_level_use:nn:nn @top_level_use:nn:nn)]
  procs           : 

*main* > public {impure} (0 calls) 
0: top_level_use.<0>
(*#globals##0:wybe.phantom, *?#globals##4:wybe.phantom):
 AliasPairs: []
 InterestingCallProperties: []
    foreign lpvm store(<<top_level_use.res>>:wybe.int, 0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom)
    foreign lpvm load(<<top_level_use.res>>:wybe.int, ?%tmp#0##0:wybe.int, *#globals##1:wybe.phantom)
    foreign lpvm store(<<top_level_use.res>>:wybe.int, 0:wybe.int, ~*#globals##1:wybe.phantom, ?*#globals##2:wybe.phantom)
    foreign lpvm load(<<top_level_use.res>>:wybe.int, ?%res##2:wybe.int, *#globals##2:wybe.phantom)
    wybe.io.println<0>(~%res##2:wybe.int, ~*#globals##2:wybe.phantom, ?*#globals##3:wybe.phantom) #0 @top_level_use:nn:nn
    foreign lpvm store(<<top_level_use.res>>:wybe.int, ~%tmp#0##0:wybe.int, ~*#globals##3:wybe.phantom, ?*#globals##4:wybe.phantom)

  LLVM code       :

; ModuleID = 'top_level_use'


 


declare external fastcc  void @"wybe.io.println<0>"(i64)    


@"resource#top_level_use.res" =    global i64 undef


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i32, i1)    


define external fastcc  void @"top_level_use.<0>"()    {
entry:
  store  i64 0, i64* @"resource#top_level_use.res" 
  %1 = load  i64, i64* @"resource#top_level_use.res" 
  store  i64 0, i64* @"resource#top_level_use.res" 
  %2 = load  i64, i64* @"resource#top_level_use.res" 
  tail call fastcc  void  @"wybe.io.println<0>"(i64  %2)  
  store  i64 %1, i64* @"resource#top_level_use.res" 
  ret void 
}
