======================================================================
AFTER EVERYTHING:
 Module unbranch_bug
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : unbranch_bug.<0>
  imports         : use wybe
  resources       : 
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: unbranch_bug.<0>
()<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    unbranch_bug.#cont#3<0>(0:wybe.list(5))<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @unbranch_bug:nn:nn


proc #cont#1 > {inline} (1 calls)
0: unbranch_bug.#cont#1<0>
#cont#1()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc #cont#2 > {inline} (1 calls)
0: unbranch_bug.#cont#2<0>
#cont#2()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []


proc #cont#3 > (2 calls)
0: unbranch_bug.#cont#3<0>
#cont#3(tmp#0##0:wybe.list(5) <{}; {}; {0}>)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm icmp_ne(tmp#0##0:wybe.int, 0:wybe.int, ?tmp#6##0:wybe.bool)
    case ~tmp#6##0:wybe.bool of
    0:

    1:
        foreign lpvm access(~tmp#0##0:wybe.list(T), 8:wybe.int, 16:wybe.int, 0:wybe.int, ?tmp#0##1:wybe.list(5)) @list:nn:nn
        unbranch_bug.#cont#3<0>(~tmp#0##1:wybe.list(5))<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @unbranch_bug:nn:nn


  LLVM code       :

; ModuleID = 'unbranch_bug'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"unbranch_bug.<0>"() alwaysinline   {
entry:
  tail call fastcc  void  @"unbranch_bug.#cont#3<0>"(i64  0)  
  ret void 
}


define external fastcc  void @"unbranch_bug.#cont#1<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  void @"unbranch_bug.#cont#2<0>"() alwaysinline   {
entry:
  ret void 
}


define external fastcc  void @"unbranch_bug.#cont#3<0>"(i64  %"tmp#0##0")    {
entry:
  %0 = icmp ne i64 %"tmp#0##0", 0 
  br i1 %0, label %if.then, label %if.else 
if.then:
  %1 = add   i64 %"tmp#0##0", 8 
  %2 = inttoptr i64 %1 to i64* 
  %3 = load  i64, i64* %2 
  musttail call fastcc  void  @"unbranch_bug.#cont#3<0>"(i64  %3)  
  ret void 
if.else:
  ret void 
}
