======================================================================
AFTER EVERYTHING:
 Module unneeded
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : 
  imports         : use wybe
  resources       : 
  procs           : 

proc unneeded > {inline} (0 calls)
0: unneeded.unneeded<0>
unneeded(x##0:wybe.int, [y##0:wybe.int], ?z##0:wybe.int, q##0:wybe.int, [?q##0:wybe.int])<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign llvm add(~x##0:wybe.int, 1:wybe.int, ?z##0:wybe.int) @int:nn:nn

  LLVM code       :

; ModuleID = 'unneeded'


 


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  i64 @"unneeded.unneeded<0>"(i64  %"x##0", i64  %"q##0") alwaysinline   {
entry:
  %0 = add   i64 %"x##0", 1 
  ret i64 %0 
}
