======================================================================
AFTER EVERYTHING:
 Module use_resource
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : use_resource.<0>
  imports         : use wybe
  resources       : count: fromList [(use_resource.count,wybe.int = 0 @use_resource:nn:nn @use_resource:nn:nn)]
  procs           : 

module top-level code > public {impure} (0 calls) 
0: use_resource.<0>
(*#globals##0:wybe.phantom, *?#globals##2:wybe.phantom):
  GlobalFlows: {<<use_resource.count>>::{FlowOut}, <<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm store(<<use_resource.count>>:wybe.int, 4:wybe.int, ~*#globals##0:wybe.phantom, ?*tmp#7##0:wybe.phantom)
    wybe.string.print_string<0>("Inner count (4): ":wybe.string, ~*tmp#7##0:wybe.phantom, ?*tmp#8##0:wybe.phantom) #1 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#9##0:wybe.phantom, ~*tmp#8##0:wybe.phantom, ?*tmp#10##0:wybe.phantom)
    foreign c print_int(4:wybe.int, ~%tmp#9##0:wybe.phantom, ?%tmp#11##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#11##0:wybe.phantom, ?%tmp#12##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#12##0:wybe.phantom, ~*tmp#10##0:wybe.phantom, ?*tmp#13##0:wybe.phantom)
    foreign lpvm store(<<use_resource.count>>:wybe.int, 1:wybe.int, ~*tmp#13##0:wybe.phantom, ?*tmp#14##0:wybe.phantom)
    wybe.string.print_string<0>("Outer count (1): ":wybe.string, ~*tmp#14##0:wybe.phantom, ?*tmp#15##0:wybe.phantom) #2 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#16##0:wybe.phantom, ~*tmp#15##0:wybe.phantom, ?*tmp#17##0:wybe.phantom)
    foreign c print_int(1:wybe.int, ~%tmp#16##0:wybe.phantom, ?%tmp#18##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#18##0:wybe.phantom, ?%tmp#19##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#19##0:wybe.phantom, ~*tmp#17##0:wybe.phantom, ?*#globals##2:wybe.phantom)


inc_count > {inline} (4 calls) 
0: use_resource.inc_count<0>
inc_count(*#globals##0:wybe.phantom, *?#globals##2:wybe.phantom):
  GlobalFlows: {<<use_resource.count>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<use_resource.count>>:wybe.int, ?%count##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##1:wybe.phantom)
    foreign llvm add(~%count##0:wybe.int, 1:wybe.int, ?tmp#0##0:wybe.int) @int:nn:nn
    foreign lpvm store(<<use_resource.count>>:wybe.int, ~tmp#0##0:wybe.int, ~*#globals##1:wybe.phantom, ?*#globals##2:wybe.phantom)


use_test > {inline} (1 calls) 
0: use_resource.use_test<0>
use_test(*#globals##0:wybe.phantom, *?#globals##12:wybe.phantom):
  GlobalFlows: {<<use_resource.count>>::{FlowIn, FlowOut}, <<wybe.io.io>>::{FlowIn, FlowOut}} 
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<use_resource.count>>:wybe.int, ?%tmp#2##0:wybe.int, ~*#globals##0:wybe.phantom, ?*#globals##4:wybe.phantom)
    foreign llvm add(~%tmp#2##0:wybe.int, 1:wybe.int, ?tmp#4##0:wybe.int) @int:nn:nn
    foreign llvm add(tmp#4##0:wybe.int, 1:wybe.int, ?tmp#8##0:wybe.int) @int:nn:nn
    foreign llvm add(~tmp#8##0:wybe.int, 1:wybe.int, ?tmp#12##0:wybe.int) @int:nn:nn
    foreign llvm add(~tmp#12##0:wybe.int, 1:wybe.int, ?tmp#16##0:wybe.int) @int:nn:nn
    foreign lpvm store(<<use_resource.count>>:wybe.int, tmp#16##0:wybe.int, ~*#globals##4:wybe.phantom, ?*#globals##5:wybe.phantom)
    wybe.string.print_string<0>("Inner count (4): ":wybe.string, ~*#globals##5:wybe.phantom, ?*#globals##6:wybe.phantom) #8 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#21##0:wybe.phantom, ~*#globals##6:wybe.phantom, ?*tmp#22##0:wybe.phantom)
    foreign c print_int(~tmp#16##0:wybe.int, ~%tmp#21##0:wybe.phantom, ?%tmp#23##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#23##0:wybe.phantom, ?%tmp#24##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#24##0:wybe.phantom, ~*tmp#22##0:wybe.phantom, ?*#globals##8:wybe.phantom)
    foreign lpvm store(<<use_resource.count>>:wybe.int, tmp#4##0:wybe.int, ~*#globals##8:wybe.phantom, ?*#globals##9:wybe.phantom)
    wybe.string.print_string<0>("Outer count (1): ":wybe.string, ~*#globals##9:wybe.phantom, ?*#globals##10:wybe.phantom) #9 @io:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#29##0:wybe.phantom, ~*#globals##10:wybe.phantom, ?*tmp#30##0:wybe.phantom)
    foreign c print_int(~tmp#4##0:wybe.int, ~%tmp#29##0:wybe.phantom, ?%tmp#31##0:wybe.phantom) @io:nn:nn
    foreign c putchar('\n':wybe.char, ~%tmp#31##0:wybe.phantom, ?%tmp#32##0:wybe.phantom) @io:nn:nn
    foreign lpvm store(<<wybe.io.io>>:wybe.phantom, ~%tmp#32##0:wybe.phantom, ~*tmp#30##0:wybe.phantom, ?*#globals##12:wybe.phantom)

  LLVM code       :

; ModuleID = 'use_resource'


 


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external fastcc  void @"wybe.string.print_string<0>"(i64)    


@use_resource.4 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.3 to i64) }


@use_resource.3 =    constant [?? x i8] c"Outer count (1): \00"


@use_resource.2 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.1 to i64) }


@use_resource.1 =    constant [?? x i8] c"Inner count (4): \00"


@"resource#use_resource.count" =    global i64 undef


@use_resource.10 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.9 to i64) }


@use_resource.9 =    constant [?? x i8] c"Outer count (1): \00"


@use_resource.8 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.7 to i64) }


@use_resource.7 =    constant [?? x i8] c"Inner count (4): \00"


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"use_resource.<0>"()    {
entry:
  store  i64 4, i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.2, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  4)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 1, i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.4, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"use_resource.inc_count<0>"()    {
entry:
  %5 = load  i64, i64* @"resource#use_resource.count" 
  %"1#tmp#0##0" = add   i64 %5, 1 
  store  i64 %"1#tmp#0##0", i64* @"resource#use_resource.count" 
  ret void 
}


define external fastcc  void @"use_resource.use_test<0>"()    {
entry:
  %6 = load  i64, i64* @"resource#use_resource.count" 
  %"1#tmp#4##0" = add   i64 %6, 1 
  %"1#tmp#8##0" = add   i64 %"1#tmp#4##0", 1 
  %"1#tmp#12##0" = add   i64 %"1#tmp#8##0", 1 
  %"1#tmp#16##0" = add   i64 %"1#tmp#12##0", 1 
  store  i64 %"1#tmp#16##0", i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.8, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %"1#tmp#16##0")  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 %"1#tmp#4##0", i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print_string<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.10, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %"1#tmp#4##0")  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
