======================================================================
AFTER EVERYTHING:
 Module use_resource
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : use_resource.<0>
  imports         : use wybe
  resources       : count: fromList [(use_resource.count,wybe.int = 0 @use_resource:nn:nn @use_resource:nn:nn)]
  procs           : 

module top-level code > public {semipure} (0 calls)
0: use_resource.<0>
()<{<<use_resource.count>>, <<wybe.io.io>>}; {<<use_resource.count>>, <<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<use_resource.count>>:wybe.int, ?%tmp#0##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#0##0:wybe.int, 1:wybe.int, ?tmp#1##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(tmp#1##0:wybe.int, 1:wybe.int, ?tmp#2##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#2##0:wybe.int, 1:wybe.int, ?tmp#3##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#3##0:wybe.int, 1:wybe.int, ?tmp#4##0:wybe.int) @use_resource:nn:nn
    wybe.string.print<0>("Inner count (4): ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #1 @use_resource:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#5##0:wybe.phantom) @use_resource:nn:nn
    foreign c print_int(~tmp#4##0:wybe.int, ~tmp#5##0:wybe.phantom, ?tmp#6##0:wybe.phantom) @use_resource:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#6##0:wybe.phantom, ?tmp#7##0:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(~%tmp#7##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(tmp#1##0:wybe.int, <<use_resource.count>>:wybe.int) @use_resource:nn:nn
    wybe.string.print<0>("Outer count (1): ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #2 @use_resource:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#8##0:wybe.phantom) @use_resource:nn:nn
    foreign c print_int(~tmp#1##0:wybe.int, ~tmp#8##0:wybe.phantom, ?tmp#9##0:wybe.phantom) @use_resource:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#9##0:wybe.phantom, ?tmp#10##0:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(~%tmp#10##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @use_resource:nn:nn


proc inc_count > {inline} (4 calls)
0: use_resource.inc_count<0>
inc_count()<{<<use_resource.count>>}; {<<use_resource.count>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<use_resource.count>>:wybe.int, ?%count##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~count##0:wybe.int, 1:wybe.int, ?tmp#0##0:wybe.int) @use_resource:nn:nn
    foreign lpvm store(~tmp#0##0:wybe.int, <<use_resource.count>>:wybe.int) @use_resource:nn:nn


proc use_test > {inline} (1 calls)
0: use_resource.use_test<0>
use_test()<{<<use_resource.count>>, <<wybe.io.io>>}; {<<use_resource.count>>, <<wybe.io.io>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm load(<<use_resource.count>>:wybe.int, ?%tmp#2##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#2##0:wybe.int, 1:wybe.int, ?tmp#3##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(tmp#3##0:wybe.int, 1:wybe.int, ?tmp#5##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#5##0:wybe.int, 1:wybe.int, ?tmp#7##0:wybe.int) @use_resource:nn:nn
    foreign llvm add(~tmp#7##0:wybe.int, 1:wybe.int, ?tmp#9##0:wybe.int) @use_resource:nn:nn
    wybe.string.print<0>("Inner count (4): ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #4 @use_resource:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#11##0:wybe.phantom) @use_resource:nn:nn
    foreign c print_int(~tmp#9##0:wybe.int, ~tmp#11##0:wybe.phantom, ?tmp#12##0:wybe.phantom) @use_resource:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#12##0:wybe.phantom, ?tmp#13##0:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(~%tmp#13##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(tmp#3##0:wybe.int, <<use_resource.count>>:wybe.int) @use_resource:nn:nn
    wybe.string.print<0>("Outer count (1): ":wybe.string)<{<<wybe.io.io>>}; {<<wybe.io.io>>}; {}> #6 @use_resource:nn:nn
    foreign lpvm load(<<wybe.io.io>>:wybe.phantom, ?%tmp#15##0:wybe.phantom) @use_resource:nn:nn
    foreign c print_int(~tmp#3##0:wybe.int, ~tmp#15##0:wybe.phantom, ?tmp#16##0:wybe.phantom) @use_resource:nn:nn
    foreign c putchar('\n':wybe.char, ~tmp#16##0:wybe.phantom, ?tmp#17##0:wybe.phantom) @use_resource:nn:nn
    foreign lpvm store(~%tmp#17##0:wybe.phantom, <<wybe.io.io>>:wybe.phantom) @use_resource:nn:nn

  LLVM code       :

; ModuleID = 'use_resource'


 


@"resource#use_resource.count" =    global i64 undef


@use_resource.1 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.0 to i64) }


@use_resource.3 =    constant {i64, i64} { i64 17, i64 ptrtoint ([?? x i8]* @use_resource.2 to i64) }


@use_resource.0 =    constant [?? x i8] c"Inner count (4): \00"


@use_resource.2 =    constant [?? x i8] c"Outer count (1): \00"


declare external ccc  void @putchar(i8)    


declare external ccc  void @print_int(i64)    


declare external fastcc  void @"wybe.string.print<0>"(i64)    


declare external ccc  i8* @wybe_malloc(i32)    


declare external ccc  void @llvm.memcpy.p0i8.p0i8.i32(i8*, i8*, i32, i1)    


define external fastcc  void @"use_resource.<0>"()    {
entry:
  %0 = load  i64, i64* @"resource#use_resource.count" 
  %1 = add   i64 %0, 1 
  %2 = add   i64 %1, 1 
  %3 = add   i64 %2, 1 
  %4 = add   i64 %3, 1 
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %4)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 %1, i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.3, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}


define external fastcc  void @"use_resource.inc_count<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#use_resource.count" 
  %1 = add   i64 %0, 1 
  store  i64 %1, i64* @"resource#use_resource.count" 
  ret void 
}


define external fastcc  void @"use_resource.use_test<0>"() alwaysinline   {
entry:
  %0 = load  i64, i64* @"resource#use_resource.count" 
  %1 = add   i64 %0, 1 
  %2 = add   i64 %1, 1 
  %3 = add   i64 %2, 1 
  %4 = add   i64 %3, 1 
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.1, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %4)  
  tail call ccc  void  @putchar(i8  10)  
  store  i64 %1, i64* @"resource#use_resource.count" 
  tail call fastcc  void  @"wybe.string.print<0>"(i64  ptrtoint (i64* getelementptr inbounds ({i64, i64}, {i64, i64}* @use_resource.3, i32 0, i32 0) to i64))  
  tail call ccc  void  @print_int(i64  %1)  
  tail call ccc  void  @putchar(i8  10)  
  ret void 
}
