/* File     : c_config.c
 * Author   : Peter Schachte
 * Purpose  : Determine configuration for Wybe -> C interface
 * Copyright: (c) 2024 Peter Schachte.  All rights reserved.
 * License  : Licensed under terms of the MIT license.  See the file
 *          : LICENSE in the root directory of this project.
 *
 *  Generate Haskell source code defining Wybe interpretation of standard
 *  C types.
 * 
 * NB:  This code assumes a byte-addressed architecture.
 **/

#include <stdio.h>

int main() {
    int i;
    float f;
    double d;
    char c;
    void *p;
    printf("-- AUTOMATICALLY GENERATED BY c_config.c\n-- DO NOT EDIT!\n\n");
    printf("-- Purpose : Relate C types to Wybe types for foreign interface\n\n");
    printf("module CConfig (cTypeRepresentation, cPointerSize) where\n");
    printf("\nimport AST (TypeRepresentation(..))\n");
    printf("import Config (byteBits)\n\n");
    printf("cTypeRepresentation :: String -> Maybe TypeRepresentation\n");
    printf("cTypeRepresentation \"int\" = Just $ Signed $ byteBits*%lu\n", sizeof(i));
    printf("cTypeRepresentation \"float\" = Just $ Floating $ byteBits*%lu\n", sizeof(f));
    printf("cTypeRepresentation \"double\" = Just $ Floating $ byteBits*%lu\n", sizeof(d));
    printf("cTypeRepresentation \"char\" = Just $ Bits $ byteBits*%lu\n", sizeof(c));
    printf("cTypeRepresentation \"pointer\" = Just CPointer\n");
    printf("cTypeRepresentation \"void\" = Just $ Bits 0\n");
    printf("cTypeRepresentation \"intrinsic_bool\" = Just $ Bits 1\n");
    printf("cTypeRepresentation other = Nothing\n\n");
    printf("cPointerSize :: Int\n");
    printf("cPointerSize = byteBits*%lu\n", sizeof(p));
    return 0;
}