/* File     : c_config.c
 * Author   : Peter Schachte
 * Purpose  : Determine configuration for Wybe -> C interface
 * Copyright: (c) 2018-2019 Ting Lu.  All rights reserved.
 * License  : Licensed under terms of the MIT license.  See the file
 *          : LICENSE in the root directory of this project.
 *
 *  Generate Haskell source code defining Wybe interpretation of standard
 *  C types.
 **/

#include <stdio.h>

int main() {
    int i;
    float f;
    double d;
    char c;
    void *p;
    printf("-- AUTOMATICALLY GENERATED BY c_config.c\n-- DO NOT EDIT!\n\n");
    printf("module CConfig (cTypeRepresentation) where\n");
    printf("\nimport AST (TypeRepresentation(..))\n\n");
    printf("cTypeRepresentation :: String -> Maybe TypeRepresentation\n");
    printf("cTypeRepresentation \"int\" = Just $ Signed %lu\n", 8*sizeof(i));
    printf("cTypeRepresentation \"float\" = Just $ Floating %lu\n", 8*sizeof(f));
    printf("cTypeRepresentation \"double\" = Just $ Floating %lu\n", 8*sizeof(d));
    printf("cTypeRepresentation \"char\" = Just $ Bits %lu\n", 8*sizeof(c));
    printf("cTypeRepresentation \"pointer\" = Just $ Bits %lu\n", 8*sizeof(p));
    printf("cTypeRepresentation other = Nothing\n");
    return 0;
}